### ISSUE TITLE
Implement Ben's original model in the current workflow

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#10]
Everything is in the title.

**Comment by fso42** [comment]
I can offer to try to integrate my existing code in here. However I won't have the time to completely rewrite it to code languages used in current worklfow. If that's acceptable? (@fmaussion)

**Comment by fmaussion** [comment]
Hi Felix, it would be great to have your help with it. In all cases the integration into the new workflow will require some changes to the original model, so that I think that it would be good to have it in pure python at first. We can discuss this in more detail soon.

Both OGGM V1 and V2 **will** require rewriting in a compiled language soon or late, that's for sure

**Comment by fso42** [comment]
Ok, so my code is python for controlling/steering, and the main part in fortran... I don't have the time to rewrite it to pure python (apart from it not making sense computational time wise), but if someone wants to do it, feel free to use my code as blueprint...

**Comment by fmaussion** [comment]
I agree. A possible roadmap could look like:

1. I take care of the I/O for it to fit into the actual OGGM workflow: I am thinking about topo I/O for example (since z_max and z_terminus should be in line with OGGM V2)  

2. What about climate related stuff? Computation of mu*, t* and stuffs should also be in line with OGGM V2, but I guess that OGGR is already doing this in Fortran?

3. Maybe the most computational intensive part is the iterative search for a starting glacier? We could easily wrap your Fortran code in a python call.

How did you parallelize OGGR? OGGM follows a naive multiprocessing, in which a job is to compute a task on one single glacier, so that several glaciers can be computed in parallel on different processors.

**Comment by fso42** [comment]
I parallelized OGGR via OpenMP.
Strategy is the same as OGGM: computing single glaciers in parallel...

**Comment by fmaussion** [comment]
I'm pushing up this issue here, as I think there are a couple of things we can learn about Ben's model if we had it in the OGGM codebase. Basically I think that a python implementation would be very easy to do in two steps:
- we need a new preprocessing task which gets the parameters the models need to run (super easy: hmin, hmax, area...)
- we need to make a model class similar to the flowline's one (i.e. with run_until methods) but based on the equations in Ben's paper.

**Comment by fmaussion** [comment]
Closing this issue as being "too general" -> yes this should happen, and will happen one day
