### ISSUE TITLE
tests runtime

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1063]
On my new env with py3.8 and all packages at latest, running the tests in simplest mode (`pytest .`) takes 12 mins on my relatively powerful laptop:

```bash
(py3) mowglie@flappi-top:~/Documents/git/oggm-timo$ pytest .
====================================================== test session starts ======================================================
platform linux -- Python 3.8.5, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
Matplotlib: 3.3.2
Freetype: 2.6.1
rootdir: /home/mowglie/disk/Dropbox/HomeDocs/git/oggm-timo, configfile: pytest.ini
plugins: mpl-0.122
collected 316 items                                                                                                             

oggm/tests/test_benchmarks.py .......                                                                                     [  2%]
oggm/tests/test_graphics.py ...................X                                                                          [  8%]
oggm/tests/test_minimal.py ...                                                                                            [  9%]
oggm/tests/test_models.py ..........................sss.......ssss..s.ss..ssssss..sss                                     [ 28%]
oggm/tests/test_numerics.py .sssssssssss.ssss...s..ss.s                                                                   [ 36%]
oggm/tests/test_prepro.py .................s........................s................s....s............                   [ 61%]
oggm/tests/test_shop.py .......                                                                                           [ 63%]
oggm/tests/test_utils.py ....................................................ss.ss..sssss.ssssss..sss...s.ss.ss.ss..      [ 92%]
oggm/tests/test_vascaling.py ...................                                                                          [ 98%]
oggm/tests/test_workflow.py ssssss                                                                                        [100%]

======================================================= warnings summary ========================================================
(skipped)
============================== 242 passed, 73 skipped, 1 xpassed, 9 warnings in 718.15s (0:11:58) ===============================
```

This is too long, and I wonder if there is still some performance issue hidden somewhere: @matthiasdusch @TimoRoth , could you run the tests on latest master (after https://github.com/OGGM/oggm/pull/1062 is merged) in your non-modified envs and let me know how long it takes? Maybe I'm confused but in my memories this should take about 6 minutes, not 12.

**Comment by fmaussion** [comment]
OK so I tried some recent envs and itls always so slow. 

So I guess:
- the number of tests blew up too much
- oggm possibly got slower with certain changes in the numerics
- I hope that I didn't miss a large performance drop recently
- we need better benchmarks

**Comment by TimoRoth** [comment]
12 minutes really does not strike me as unusually slow.
Are you sure it got significantly slower?

**Comment by fmaussion** [comment]
> Are you sure it got significantly slower?

No I'm not - I didn't check for a long time. But last time I updated the docs (probably a couple of years ago) it was 3 minutes!!!

I would rather have this reduced to about 3-5 minutes. This is unfortunately not an easy endeavour:
- simplify tests and remove the many (many) redundant ones
- make some of them in the --slow category
