### ISSUE TITLE
filter_inversion_output still far from satisfying

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1083]
I qualitatively tested the new approach implemented in https://github.com/OGGM/oggm/pull/1045 on a couple of valley glaciers

It turns out to be a real embarrassment on other glaciers, as reported by @drounce  

![image](https://user-images.githubusercontent.com/10050469/97077883-95d00a00-15e7-11eb-955e-c475d0c60ba4.png)

This needs a fix ASAP.

@matthiasdusch sorry for that -> did you see anything weird in your profiles as well?

**Comment by matthiasdusch** [comment]
something like this?

![grafik](https://user-images.githubusercontent.com/37663627/97326737-992bf580-1874-11eb-8844-76c4d1ee269f.png)

(without looking into the issue)

**Comment by fmaussion** [comment]
Your profile looks pretty!! It seems to work well in the Alps but I need to find out what's going on in the many examples @drounce pointed out
