### ISSUE TITLE
The error of 'tasks.glacier_masks'

### ISSUE THREAD

**Issue by zxl951128** [OGGM/oggm#1095]
I run 1.3.1 version OGGM by default valut, and found a problem:
At the function 'workflow.init_glacier_regions', the parameter 'prepro_base_url' defalut value is the 1.1 version results, the link is https://cluster.klima.uni-bremen.de/~fmaussion/gdirs/oggm_v1.1/. After I run the task 'tasks.glacier_masks', it happen the following screenshot's problem.
![Snipaste_2020-11-16_17-28-43](https://user-images.githubusercontent.com/17431648/99246764-cac72980-2840-11eb-8ac7-373f91d67697.png)
And I check the data download from the above the link, in the file named 'gridded_data.nc', it does not have 'topo valid mask' data.
I also check the 1.3.1 version code of 'tasks.glacier_masks', and think may the error from this part:
![Snipaste_2020-11-16_19-24-24](https://user-images.githubusercontent.com/17431648/99247161-85572c00-2841-11eb-8a6b-6c4af29f9a65.png)
If I download the data from the link, it will not run the function 'process_dem' which can make the 'topo valid mask'. And the data actually does not have the 'topo valid mask',so the error happen.

**Comment by fmaussion** [comment]
Thanks for the report! Can you update to latest master and see if the error happens again? I am in the process of creating a new release of OGGM soon.

Installation instructions for the "dev" version: https://docs.oggm.org/en/latest/installing-oggm.html#install-oggm-itself

**Comment by zxl951128** [comment]
> Thanks for the report! Can you update to latest master and see if the error happens again? I am in the process of creating a new release of OGGM soon.
> 
> Installation instructions for the "dev" version: https://docs.oggm.org/en/latest/installing-oggm.html#install-oggm-itself

I check the code from the DOCUMENTS. The version of Latest, Stable and 1.3.1, the code of the 'tasks.glacier_masks' part that I mention is the same. The code from website is not same the GitHub? I run my code on Stable version, I will try the Latest version later.

**Comment by zxl951128** [comment]
> Thanks for the report! Can you update to latest master and see if the error happens again? I am in the process of creating a new release of OGGM soon.
> 
> Installation instructions for the "dev" version: https://docs.oggm.org/en/latest/installing-oggm.html#install-oggm-itself

I try the 'dev' version, 1.3.2.dev118+gf71fe7d, and error happens again but not the same one. The screenshot shows that 
![Snipaste_2020-11-16_21-42-58](https://user-images.githubusercontent.com/17431648/99259282-ba20ae80-2854-11eb-9413-a14ba743b4c3.png)
The glacier RGI ID is RGI60-15.07605. After some paths setting and initialize, I just run 'workflow.init_glacier_regions'. And error still happens on 'tasks.glacier_masks'.

**Comment by fmaussion** [comment]
Can you please post the full code that produces the error? 

Are you trying to run one of the tutorial notebooks? Does your code run on MyBinder or does it also crashes there? (link to MyBinder explanations: https://docs.oggm.org/en/latest/installing-oggm.html

**Comment by fmaussion** [comment]
Ups sorry I meant Cloud explanations: https://docs.oggm.org/en/latest/cloud.html

**Comment by zxl951128** [comment]
> Can you please post the full code that produces the error?
> 
> Are you trying to run one of the tutorial notebooks? Does your code run on MyBinder or does it also crashes there? (link to MyBinder explanations: https://docs.oggm.org/en/latest/cloud.html )

Yes, the following is the code:

import oggm
from oggm import cfg, utils, workflow, tasks

cfg.initialize()
cfg.PATHS['working_dir'] = utils.gettempdir(dirname='OGGM-GettingStarted', reset=True)
cfg.PARAMS['use_multiprocessing'] = True

rgi_ids = ['RGI60-15.07605']
gdirs = workflow.init_glacier_regions(rgidf = rgi_ids, from_prepro_level = 3, prepro_border = 10)
gdir = gdirs[0]

# First error from 'tasks.glacier_masks'
tasks.glacier_masks(gdir)
# Second error from 'workflow.gis_prepro_tasks'
workflow.gis_prepro_tasks(gdir)

I try it on MyBinder and it also crashes. Bur it is okey for version 1.1.2.

**Comment by fmaussion** [comment]
Thanks for the report! I can reproduce this. A few comments:

1. the task ` workflow.init_glacier_regions` is replaced by `init_glacier_directories`, if you can you should switch to this new task instead (but this won't solve the problem)

2. you are trying to recompute glacier masks based on glacier directories which are already at level 3 (i.e. which should already have a pre-computed mask, flowlines, etc.). Why are you trying to go back from there and re-run the tasks?

3. this problem will be solved soon, when the new glacier directories are available. I will document and release them this week.

4. that being said, I can still solve this problem in OGGM I think, I'll have a look.

**Comment by fmaussion** [comment]
(if you want to know why the problem arises: in the process of changing `init_glacier_regions` to `init_glacier_directories` I changed how the DEM data is processed, and since you are starting from pre-processed directories, they do not contain these new data)

**Comment by zxl951128** [comment]
> Thanks for the report! I can reproduce this. A few comments:
> 
> 1. the task ` workflow.init_glacier_regions` is replaced by `init_glacier_directories`, if you can you should switch to this new task instead (but this won't solve the problem)
> 2. you are trying to recompute glacier masks based on glacier directories which are already at level 3 (i.e. which should already have a pre-computed mask, flowlines, etc.). Why are you trying to go back from there and re-run the tasks?
> 3. this problem will be solved soon, when the new glacier directories are available. I will document and release them this week.
> 4. that being said, I can still solve this problem in OGGM I think, I'll have a look.

For No.1, I will update my code that use `init_glacier_directories`.
Oh! For No.2, I think I know my problem. I misunderstand the meaning of 'Processing levels', for level 3, I should not run the re-run the tasks. I will change my level to 1 or 2.
Thanks a lot for answering!

**Comment by fmaussion** [comment]
@zxl951128 This code works:

```python
import oggm
from oggm import cfg, utils, workflow, tasks
from oggm.core import gis

cfg.initialize()
cfg.PATHS['working_dir'] = utils.gettempdir(dirname='OGGM-GettingStarted', reset=True)
cfg.PARAMS['use_multiprocessing'] = True

rgi_ids = ['RGI60-15.07605']
gdirs = workflow.init_glacier_directories(rgidf = rgi_ids, from_prepro_level=1, prepro_border = 10)
gdir = gdirs[0]


gis.process_dem(gdir)
tasks.glacier_masks(gdir) #first error
```

**Comment by zxl951128** [comment]
> @zxl951128 This code works:
> 
> ```python
> import oggm
> from oggm import cfg, utils, workflow, tasks
> from oggm.core import gis
> 
> cfg.initialize()
> cfg.PATHS['working_dir'] = utils.gettempdir(dirname='OGGM-GettingStarted', reset=True)
> cfg.PARAMS['use_multiprocessing'] = True
> 
> rgi_ids = ['RGI60-15.07605']
> gdirs = workflow.init_glacier_directories(rgidf = rgi_ids, from_prepro_level=1, prepro_border = 10)
> gdir = gdirs[0]
> 
> 
> gis.process_dem(gdir)
> tasks.glacier_masks(gdir) #first error
> ```

Yes, I change the level to 2 or 1, it works. So, maybe at the part of `tasks.glacier_masks`, the red box part shows the warning like 'You have download pre-run data, Do not need to run currently task'

**Comment by fmaussion** [comment]
yes good idea, I'll try to do that when time permits
