### ISSUE TITLE
More information on model output files (netCDF)

### ISSUE THREAD

**Issue by WFurian** [OGGM/oggm#1096]
Hi everyone!
I wonder if there is a part in the OGGM documentation with more details on the model output files for each glacier (`model_run_2000.nc`)? For example, I do not fully understand the three dimensions of each flowline group. I know that `time` represents the passing years and I think `x` somehow indicates the length of the flowline. But what does `c` stand for?
```
     3 dimensions:
        x  Size:18
        c  Size:2
        time  Size:201
            _FillValue: NaN
```
Is there a more detailed explanation of the variables, coordinates and dimensions and how they are depending on one another? I'm trying to export the extent of a glacier at a given year to use for further analyses in, e.g., QGIS or R.

**Comment by fmaussion** [comment]
Thanks for the report.

These files are meant to be read with a `FileModel`, which reads these files and then behaves quite like a regular OGGM flowline model: https://github.com/OGGM/oggm/blob/f71fe7da16c0079e481278d427c0efcdb59bafd7/oggm/core/flowline.py#L1676 

It is poorly documented indeed, and for some reason which I have yet to understand, quite slow to use. (but still faster than running the model I think). Feedback / improvements welcome!

**Comment by WFurian** [comment]
Thanks for the swift reply!
I've tried opening the whole netCDF file as well as files containing only single flowlines as you suggested:
```
from oggm.core.flowline import FileModel
ds2000 = utils.compile_run_output(gdirs, filesuffix='_2000')
ds2000_new = FileModel(ds2000)
```
```
path = "/home/wilhelm/OGGM/OGGM-GettingStarted/per_glacier/RGI60-14/RGI60-14.00/RGI60-14.00005/"
results = xr.open_dataset(path + 'model_run_2000.nc', group='fl_0')
results_new = FileModel(results)
```
However, each time I get an `AttributeError: 'Dataset' object has no attribute 'tell'`. 
```
Traceback (most recent call last):
  File "/home/wilhelm/miniconda3/envs/oggm_env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-77-9add9769cbc1>", line 1, in <module>
    ds2000_new = FileModel(results_0)
  File "/home/wilhelm/miniconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/core/flowline.py", line 1415, in __init__
    self.fls = glacier_from_netcdf(path)
  File "/home/wilhelm/miniconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/core/flowline.py", line 1539, in glacier_from_netcdf
    with xr.open_dataset(path) as ds:
  File "/home/wilhelm/miniconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/api.py", line 536, in open_dataset
    engine = _get_engine_from_magic_number(filename_or_obj)
  File "/home/wilhelm/miniconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/api.py", line 115, in _get_engine_from_magic_number
    if filename_or_obj.tell() != 0:
  File "/home/wilhelm/miniconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/core/common.py", line 232, in __getattr__
    raise AttributeError(
AttributeError: 'Dataset' object has no attribute 'tell'
```

**Comment by fmaussion** [comment]
The compiled run output should be straitghforward to understand and open with any program?

The FileModel should be used as such:

```python
path = "/home/wilhelm/OGGM/OGGM-GettingStarted/per_glacier/RGI60-14/RGI60-14.00/RGI60-14.00005/"
fpath = path + 'model_run_2000.nc'
model = FileModel(fpath)
```

Or rather (because in OGGM we never use absolute paths):

```python
model = FileModel(gdir.get_filepath('model_run', filesuffix='_2000'))
```
Or, even better:

```python
with FileModel(gdir.get_filepath('model_run', filesuffix='_2000')) as model:
    code...
```

This new object then behaves like a `FlowlineModel`, e.g.:

```python
with FileModel(gdir.get_filepath('model_run', filesuffix='_2000')) as fmodel:
    fmodel.unt_until(2018)
    # diagnostic variable
    print(fmod.area_km2)
    # Flowlines and their geometry
    print(fmod.fls)
    # Selected diagnostic timeseries
    vol = model.volume_km3_ts()
    area = model.area_km2_ts()
```

**Comment by fmaussion** [comment]
Just to clarify: for each glacier, OGGM output simple, diagnostic variable such as volume, area, length, etc in a NetCDF file which can be then compiled with other glaciers thanks to the easy structure (2D data: (time, rgi_id))

The full glacier geometry over time is stored in the  `'model_run'` file, which should not be opened by anything else than OGGM. These files are optimized for disk space and contain the minimal info that OGGM needs to re-construct the flowlines geometries.

Depending on your use case and if you have something specific in mind, you have two possibilities:
- use the file model to retrieve glacier geometries from the run
- output the things you need during the model run *yourself*

The latter is probably a bit faster in the end, but only if you know what you want to output and want to output it for all glaciers.

**Comment by WFurian** [comment]
Thank you for the clarification, this works great, at least for values like length and volume. However, I'm not sure how to access or export the geometries, more specifically the contents of `fmod.fls`. I can see where Python stores it (e.g., `oggm.core.flowline.MixedBedFlowline at 0x7fb68cd5e070`), but how would I retrieve the geometries to work with in ArcGIS, for example?

**Comment by fmaussion** [comment]
You'd have to do your own cuisine.  `fls` is a list of [oggm.core.flowline.Flowline](https://github.com/OGGM/oggm/blob/f71fe7da16c0079e481278d427c0efcdb59bafd7/oggm/core/flowline.py#L46) objects. They have location, widths, thickness, etc. as attributes.

You can have a look at `oggm.graphics` where we use all these attributes to make plots on maps, etc. [write_centerlines_to_shape](https://github.com/OGGM/oggm/blob/e20e673a0e50151f5a195ba29e1890d8447fd3e7/oggm/utils/_workflow.py#L533) is also a good starting point.

**Comment by WFurian** [comment]
Okay, I will look into this. Thanks for the starting point!

**Comment by fmaussion** [comment]
See also: https://github.com/OGGM/oggm/issues/1192
