### ISSUE TITLE
Extract coordinates of the centerlines in UTM 33 N 

### ISSUE THREAD

**Issue by Colinebouch** [OGGM/oggm#1105]
Hello, 

I am having a problem related to the x and y coordinates of the centerline on Svalbard glaciers returned from `tasks.initialize_flowlines(gdir)`,`tasks.compute_downstream_line(gdir)`. My goal is to extract these coordinates for each glaciers in Svalbard in UTM 33N.  From the file `centerlines.pk`, I can extract the index of the grid of the centerline and from `gridded_data.nc`, I could find the UTM 33N coordinates with the indexes. This is working. However,  it seems like all of the coordinates are relative to some central origin as opposed to being relative to the original glacier. Therefore, when I plot all the center lines, they are all aligned in the middle of the dems. 

I have then try to plot the different dem produced by oggm routine (i.e. Tunabreen and Postbreen), where these 2 dems should have some glaciers in common. The 2 dems are shifted and don't overlap as they should (the glaciers present in the both dem.tif are not at the same place) --> files: `/tmp/OGGM/Docs_GlacierDir/per_glacier/RGI60-07/RGI60-07.01/'glacier_name'/dem.tif`

I am quite out of idea now but I really need to retrieve these coordinates. Are you aware of any methods/issues to extract the coordinates from the centerline code of OGGM for many glaciers?

Best and Thanks!

Coline

**Comment by fmaussion** [comment]
Hi Coline,

the function `utils.write_centerlines_to_shape` should do what you want: 

https://github.com/OGGM/oggm/blob/e20e673a0e50151f5a195ba29e1890d8447fd3e7/oggm/utils/_workflow.py#L533-560

Currently it writes the shapefile in lon/lat WGS84, but it should be quite easy to add an option for that (contribution welcome!) or just use any GIS to reproject afterwards.

**Comment by Colinebouch** [comment]
Hello, 
Thank you very much for your quick answer, that was very helpful !! I have then modify the function to extract UTM coordinates on the centerlines and I store them into a pd.DataFrame. My goal was to extract values from netcdf that are on glaciers centerlines (thickness, bed elevation). As a second step, I am doing the same thing for runoff and SMB. When everything will be working, I am thinking about cleaning up all my codes and then we can discuss how can I contribute to OGGM with the new codes/functions I have developed :) Thank you anyway for the answer and the great work on that database!!

**Comment by fmaussion** [comment]
I think we can close this now - the function now writes all kinds of outputs in lon lat, I guess it'll be easier for users to just extract in another CRS outside of OGGM?

See also: https://docs.oggm.org/en/stable/assets.html 

Feel free to re-open if you disagree.
