### ISSUE TITLE
utils.get_cmip5_file() don't work anymore

### ISSUE THREAD

**Issue by Keeptg** [OGGM/oggm#1107]
The [utils.get_cmip5_file()](https://github.com/OGGM/oggm/blob/e20e673a0e50151f5a195ba29e1890d8447fd3e7/oggm/utils/_downloads.py#L2313) function seems not work anymore. I guess it is because the  dataset can't be accessed by the default link.

**Comment by fmaussion** [comment]
Thanks for the report! I forgot that this function existed. 

In my code I use `file_downloader` with the following url: https://cluster.klima.uni-bremen.de/~oggm/cmip5-ng/

**Comment by fmaussion** [comment]
(we should either delete the function or update it)
