### ISSUE TITLE
Checksum file should not be checked for without internet

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1110]
https://github.com/OGGM/oggm/blob/master/oggm/utils/_downloads.py#L213 

This is raised even when `has_internet` is set to False - this should not happen.

**Comment by fmaussion** [comment]
@TimoRoth if you have some time maybe?

**Comment by TimoRoth** [comment]
Not 100% sure what you mean.
The code reads to me that in case of no internet, if the checksum file already exists, it'll print a warning and then move on, and use the existing checksums, if any. If none exist, it will move on without verifying.

**Comment by fmaussion** [comment]
yes ok - a warning might be confusing for users since they don't expect to go online (and hence verify any file anyway)

So I'd be for not raising is `has_internet` is false

**Comment by TimoRoth** [comment]
With raising you mean don't print the warning?
Cause the function should not be raising an error, it should be returning an empty (or a non-verified) set of verification data.
