### ISSUE TITLE
Ice thickness inversion error: "KeyError: 'is_trapezoid'"

### ISSUE THREAD

**Issue by mplauch** [OGGM/oggm#1112]
I'm trying to run the ice thickness inversion example on the Jupyter binder (inversion.ipynb) and I get a KeyError for the 'is_trapezoid' class, specifically line 509 of inversion.py, is_trap = cl['is_trapezoid']. I get the same error when I run on my system on a different glacier, hence why I used the example but then I ended up with the same error!

Any help is appreciated I'm fairly new at this and just trying to go through the examples and figure out how things work, 

Thanks

When I run the inversion.ipynb code I get this output: 

2020-12-10 22:33:50: oggm.cfg: Reading default parameters from the OGGM `params.cfg` configuration file.
2020-12-10 22:33:50: oggm.cfg: Multiprocessing switched OFF according to the ENV variable OGGM_USE_MULTIPROCESSING
2020-12-10 22:33:50: oggm.cfg: Multiprocessing: using slurm allocated processors (N=1)
100% of 400.3 MiB |######################| Elapsed Time: 0:00:24 Time:  0:00:24
2020-12-10 22:34:28: oggm.workflow: init_glacier_directories from prepro level 3 on 35 glaciers.
2020-12-10 22:34:28: oggm.workflow: Execute entity task gdir_from_prepro on 35 glaciers
100% of  42.9 MiB |######################| Elapsed Time: 0:00:03 Time:  0:00:03
2020-12-10 22:34:33: oggm.workflow: Execute entity task mass_conservation_inversion on 35 glaciers
2020-12-10 22:34:33: oggm.core.inversion: KeyError occurred during task mass_conservation_inversion on RGI60-11.03208: 'is_trapezoid'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-a33dd0c12e57> in <module>
     45     # Without sliding
     46     suf = '_{:03d}_without_fs'.format(int(f * 10))
---> 47     workflow.execute_entity_task(tasks.mass_conservation_inversion, gdirs,
     48                                  glen_a=glen_a*f, fs=0)
     49     workflow.execute_entity_task(tasks.filter_inversion_output, gdirs)

/srv/conda/envs/notebook/lib/python3.8/site-packages/oggm/workflow.py in execute_entity_task(task, gdirs, **kwargs)
    142         out = mppool.map(pc, gdirs, chunksize=1)
    143     else:
--> 144         out = [pc(gdir) for gdir in gdirs]
    145 
    146     return out

/srv/conda/envs/notebook/lib/python3.8/site-packages/oggm/workflow.py in <listcomp>(.0)
    142         out = mppool.map(pc, gdirs, chunksize=1)
    143     else:
--> 144         out = [pc(gdir) for gdir in gdirs]
    145 
    146     return out

/srv/conda/envs/notebook/lib/python3.8/site-packages/oggm/workflow.py in __call__(self, arg)
     88             return call_func(gdir, **gdir_kwargs)
     89         else:
---> 90             return call_func(gdir, **self.out_kwargs)
     91 
     92 

/srv/conda/envs/notebook/lib/python3.8/site-packages/oggm/utils/_workflow.py in _entity_task(gdir, reset, print_log, **kwargs)
    475                     signal.alarm(cfg.PARAMS['task_timeout'])
    476                 ex_t = time.time()
--> 477                 out = task_func(gdir, **kwargs)
    478                 ex_t = time.time() - ex_t
    479                 if cfg.PARAMS['task_timeout'] > 0:

/srv/conda/envs/notebook/lib/python3.8/site-packages/oggm/core/inversion.py in mass_conservation_inversion(gdir, glen_a, fs, write, filesuffix, water_level, t_lambda)
    507 
    508         # Now recompute thickness where parabola is too flat
--> 509         is_trap = cl['is_trapezoid']
    510         if cl['invert_with_trapezoid']:
    511             min_shape = cfg.PARAMS['mixed_min_shape']

KeyError: 'is_trapezoid'

**Comment by fmaussion** [comment]
Yes OK, this is a mismatch between the relatively old preprocessed directories and recent updates in OGGM.

The fix is easy though. Just add this line below the `init_glacier_directories` line:

```python
gdirs = workflow.init_glacier_directories(rgidf, from_prepro_level=3, prepro_border=10)

# This is new
workflow.execute_entity_task(tasks.prepare_for_inversion, gdirs)
```

I've updated the online notebooks as well: https://github.com/OGGM/oggm-edu-notebooks/pull/37

**Comment by mplauch** [comment]
Thanks so much for the fast reply and fix!
