### ISSUE TITLE
Add utility function to convert NetCDF `gridded_data` files to Geotiff

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1116]
This would be useful for users keen to work with tiffs

**Comment by fmaussion** [comment]
Awesome, thanks! A few suggestions:

```
@entity_task(log)
def gridded_data_var_to_geotiff(gdir, varname, filename=None):
    """Writes a NetCDF variable to a georeferenced geotiff file. 
 
    The geotiff file will be written in the gdir directory.

    Parameters
    ----------
    gdir : :py:class:`oggm.GlacierDirectory`
        where to write the data
    varname : str
        variable name in gridded_data.nc
    fname : str
        output file name (should end with `tif`), default is `varname.tif`
    """
```

We want this to be an `entity_task` so that it can be parallelized.

Entity tasks should always write in the current glacier directory, which is why I suggest to not write elsewhere. If people want it elsewhere than can move it afterwards.

Unlike most entity task, you can't use the `gdir.get_filepath` mechanism, because we don't know the name of the output in advance, but you can simply use `os.path.join` with `gdir.dir` attribute.

I think that `gis.py` is a good place yes!

**Comment by Keeptg** [comment]
I've finished the function, how can I submit the code to OGGM?

**Comment by Keeptg** [comment]
> I've finished the function, how can I submit the code to OGGM?

Find the method in [OGGM's website](https://docs.oggm.org/en/latest/contributing.html). Will try to submit the code.
