### ISSUE TITLE
change process_cmip5_data name and other CMIP related functions

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1126]

**Comment by Keeptg** [comment]
I'd like to have a try with this job. What you means here is that those functions should also support CMIP6 as well and with a more appropriate name?

**Comment by fmaussion** [comment]
The function is already able to process CMIP6 data, so the first step is to change the name (remove the 5) but keep the old function with a deprecation warning.

Regarding the other functions, I thought about a way to manipulate the list of files a bit more easily - I think it's better if I take care of this because I have no clear view yet of how this should look like.

**Comment by fmaussion** [comment]
Partly addressed in #1141
