### ISSUE TITLE
init_glacier_directories

### ISSUE THREAD

**Issue by haris021** [OGGM/oggm#1128]
I have been trying to run the the tutorial code on my system externally on linux, Python 3.8. However i have  been facing an issue on preprocessing step on initializing glacier directories. It returns an error that  Oggm.workflow does not have the attribute "init_glacier_directories".

**Comment by fmaussion** [comment]
Thanks for the report. This feature has been added relatively recently and is only available when installing the latest OGGM (development version): https://docs.oggm.org/en/latest/installing-oggm.html#install-oggm-itself   

I'd recommend to install latest OGGM until we do a new release, hopefully in the next weeks or so.

**Comment by haris021** [comment]
Thank you very much. I re-installed the dev version, the code is now working fine
