### ISSUE TITLE
Exporting Thickness Info from Tutorial

### ISSUE THREAD

**Issue by mplauch** [OGGM/oggm#1136]
Sorry if this is answered somewhere in the documentation, I have tried to read as much as I could in regards to the model run outputs but can't seem to figure out how to get the thickness maps that some people seem to have (like in this issue [https://github.com/OGGM/oggm/issues/714]). 

I'm looking specifically at the maps from the "getting_started.py" from the Jupyter binder plotted with:

`f, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(14, 6))
graphics.plot_modeloutput_map(gdir, filesuffix='_2000', modelyr=0, ax=ax1, vmax=350)
graphics.plot_modeloutput_map(gdir, filesuffix='_2000', modelyr=50, ax=ax2, vmax=350)
graphics.plot_modeloutput_map(gdir, filesuffix='_2000', modelyr=150, ax=ax3, vmax=350)
plt.tight_layout();`

![Screenshot 2021-01-13 162836](https://user-images.githubusercontent.com/75814335/104528619-a11a4c80-55bc-11eb-9327-d0e5bbc87f7b.jpg)

I've tried to go through the graphics.py file and see how it plots the modeloutput but I seem to be at an impass on how to extract it. The netcdf file only seems to have volume, area, elavation, etc and not thickness distributions (also I think I need the squeezed flowlines or distribute thickness data).

Any help or guidance is appreciated and again sorry if this is a dumb question!

Thanks

Max

**Comment by fmaussion** [comment]
HI @mplauch , thanks for the question and sorry for the late reply.

Did you have a look at the [OGGM flowlines: where are they?](https://github.com/OGGM/oggm-edu-notebooks/blob/master/oggm-tuto/where-are-the-flowlines.ipynb) tutorial?

**Comment by mplauch** [comment]
Thanks for the reply (and sorry for the terrible questions)! I did go through that tutorial and can get the thickness along the individual flowlines and how to plot them with your built in graphics (but I can't seem to find the thickness in the model run .nc file). Is outputting all the individual flowlines and then somehow merging them in an external program (a separate python code or arcmap or something) the best idea?

Thanks,

Max

**Comment by fmaussion** [comment]
> but I can't seem to find the thickness in the model run .nc file

Which file? Maybe this issue here is helping as well: https://github.com/OGGM/oggm/issues/1096

> Is outputting all the individual flowlines and then somehow merging them in an external program (a separate python code or arcmap or something) the best idea?

Perhaps if you told us what _exactly_ it is what you want to do, we might provide better answers ;-)

**Comment by mplauch** [comment]
Thanks again! Yes I should be a lot more specific for sure! I am trying to use OGGM to help in the creation of a glacial loading model since the Little Ice Age for some western Canadian glaciers to then model the effects of glacial isostatic adjustment. I saw that OGGM can run historic glacier evolutions with different climate models. I know it won't be the most accurate but prior to an OGGM derived model I was projecting modern melt rates back to LIA and applying it to current ice thicknesses (or at least the output of the composite glacial thickness database from Farinotti) so it will be an improvement!
At the moment I am just running it on Klinaklini Glacier to test things out (code attached, mostly just from the "getting started" tutorial). Ideally I would like my code to output the glacier thickness data from various time-steps (either as shp or just some readable grid file in arcmap) so I can then amalgamate them for my study area, average the thicknesses over larger grid sizes (ex. 10 km, 20 km) and finally create a historic ice loading file with the ice thickness changes in each (larger) pixel over the different time-steps. I figured a good place to start was finding where the plotted info (from graphics.plot_modeloutput_map) was stored and the best way to output them. I actually think I figured out the storage part using:

```
from oggm.core.flowline import FileModel
from oggm.core import flowline

for gdir in gdirs:
    fmod = flowline.FileModel(gdir.get_filepath('model_run', filesuffix='_Klinaklini_test'))
    fmod.run_until(1871)
    tasks.distribute_thickness_interp(gdir)
fmod.fls
```

where the flowlines are in fmod.fls. I am now thinking maybe the best thing to do is run them through **tasks.distribute_thickness_interp**. Is there a way to run the **distribute_thickness_interp** with the model output flowlines? Or is there a different approach I should be taking?

Thanks again for all the help and sorry if this is too much to ask!

Max

Code:

```
#Python Imports
import time
import logging
import os

# Libs
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr

# Locals
import oggm.cfg as cfg
from oggm import tasks, utils, workflow
from oggm.workflow import execute_entity_task
from oggm.utils import get_demo_file
from oggm import graphics

# Module logger
log = logging.getLogger(__name__)

# For timing the run
start = time.time()

# Initialize OGGM and set up the default run parameters
cfg.initialize()

cfg.PATHS['working_dir'] = utils.gettempdir(dirname='OGGM-GettingStarted', reset=True)
cfg.PATHS['working_dir']

# Use multiprocessing?
cfg.PARAMS['use_multiprocessing'] = True

# How many grid points around the glacier?
# Make it large if you expect your glaciers to grow large
cfg.PARAMS['border'] = 160

# Go - initialize glacier directories
gdirs = workflow.init_glacier_directories(['RGI60-02.05157'], from_prepro_level=3)

# This is new
workflow.execute_entity_task(tasks.prepare_for_inversion, gdirs)

list_talks = [
        tasks.compute_centerlines,
        tasks.initialize_flowlines,
        tasks.compute_downstream_line,
        ]
for task in list_talks:
    # The order matters!
    workflow.execute_entity_task(task, gdirs)
    
list_talks = [
    tasks.catchment_area,
    tasks.catchment_width_geom,
    tasks.catchment_width_correction,
    tasks.compute_downstream_bedshape
    ]
for task in list_talks:
    workflow.execute_entity_task(task, gdirs)

# Computing ice thickness inversion
list_talks = [
#        tasks.prepare_for_inversion,  # This is a preprocessing task
        tasks.mass_conservation_inversion,  # This does the actual job
        tasks.filter_inversion_output  # This smoothes the thicknesses at the tongue a little
        ]
for task in list_talks:
    workflow.execute_entity_task(task, gdirs)
    
# Additional climate file (CESM)
cfg.PATHS['cesm_temp_file'] = get_demo_file('cesm.TREFHT.160001-200512'
                                            '.selection.nc')
cfg.PATHS['cesm_precc_file'] = get_demo_file('cesm.PRECC.160001-200512'
                                             '.selection.nc')
cfg.PATHS['cesm_precl_file'] = get_demo_file('cesm.PRECL.160001-200512'
                                             '.selection.nc')
execute_entity_task(tasks.process_cesm_data, gdirs)

# Convert the flowlines to a "glacier" for the ice dynamics module
workflow.execute_entity_task(tasks.init_present_time_glacier, gdirs);

cfg.PARAMS['use_inversion_flowlines'] = True

execute_entity_task(tasks.run_from_climate_data, gdirs,
        climate_filename='gcm_data',
        ys=1871, ye=2000,
        output_filesuffix='_Klinaklini_test')

# Compile output
log.info('Compiling output')
utils.compile_glacier_statistics(gdirs)
ds1 = utils.compile_run_output(gdirs, input_filesuffix='_Klinaklini_test')

#Plot thickness over timesteps
f1, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(14, 6))
graphics.plot_modeloutput_map(gdirs, filesuffix='_Klinaklini_test', modelyr=1871, ax=ax1, vmax=350)
graphics.plot_modeloutput_map(gdirs, filesuffix='_Klinaklini_test', modelyr=1950, ax=ax2, vmax=350)
graphics.plot_modeloutput_map(gdirs, filesuffix='_Klinaklini_test', modelyr=2000, ax=ax3, vmax=350)
plt.tight_layout();
```

**Comment by fmaussion** [comment]
Thanks for the information! 

The `distribute_thickness_*` functions will not help you, as they only work for inversion flowlines (i.e. they need to know where the RGI outlines are in order to build a mask where to interpolate the thicknesses to). Once you are in the "flowline world", glaciers are only a list of flowlines, each with grid points containing widths, thickness information, etc. 

OGGM provides you some tools to read and plot these flowlines, but anything beyond that you'll have to do yourself. The [OGGM flowlines: where are they?](https://github.com/OGGM/oggm-edu-notebooks/blob/master/oggm-tuto/where-are-the-flowlines.ipynb) tutorial was written for people like you who would like to output more specific things out of the model run. @WFurian also has such a use case.

I would be in favor of adding such output tools into the main OGGM codebase, as long as they are optional: the main reason for not outputting "everything" at run time is that it takes a lot of disk space, and for some applications (read: global stuff), it isn't needed. If you or @WFurian feel like opening a pull-request, it is very welcome ;-)

**Comment by mplauch** [comment]
Thanks again for the reply and help! I will do my best to find a way to do it!

Max

**Comment by fmaussion** [comment]
See also: https://github.com/OGGM/oggm/issues/1192
