### ISSUE TITLE
 Pytest returns many errors with the salem.

### ISSUE THREAD

**Issue by FANSCRAZY** [OGGM/oggm#1138]
Those are the errors return when I run the pytest :

================================================================================== short test summary info ==================================================================================FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_benchmarks.py::TestSouthGlacier::test_inversion - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_benchmarks.py::TestSouthGlacier::test_inversion_attributes - pyproj.exceptions.CRSError: Invalid CRS input: <sa...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_benchmarks.py::TestSouthGlacier::test_mb - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_benchmarks.py::TestSouthGlacier::test_optimize_inversion - pyproj.exceptions.CRSError: Invalid CRS input: <sale...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_benchmarks.py::TestSouthGlacier::test_workflow - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_benchmarks.py::TestCoxeGlacier::test_run - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_benchmarks.py::TestCoxeGlacier::test_set_width - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_centerlines - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_raster - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_flowlines - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_downstream - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_width - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_width_corrected - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_inversion - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_multiple_inversion - IndexError: list index out of range
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_modelsection - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_modelsection_withtrib - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_modeloutput_map - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_multiple_models - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_thick_alt - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_thick_interp - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_catch_areas - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_chhota_shigri - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_ice_cap - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_coxe - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_prepro.py::TestGIS::test_divides_as_glaciers - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_prepro.py::TestGeometry::test_geom_width - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_prepro.py::TestClimate::test_automated_workflow - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_prepro.py::TestFilterNegFlux::test_filter - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_prepro.py::TestCoxeCalvingInvert::test_inversion_with_calving - pyproj.exceptions.CRSError: Invalid CRS input: ...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_prepro.py::TestGrindelInvert::test_intersections - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_prepro.py::TestGCMClimate::test_process_cmip5 - AttributeError: 'numpy.datetime64' object has no attribute 'year'
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_prepro.py::TestGCMClimate::test_process_cmip5_scale - AttributeError: 'numpy.datetime64' object has no attribut...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestWorkflowTools::test_glacier_characs - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_corrupted_file - RuntimeError: Could not find file at https://cluster...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_start_from_demo - RuntimeError: Could not find file at https://cluste...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_start_from_level_1 - RuntimeError: Could not find file at https://clu...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_start_from_level_1_str - RuntimeError: Could not find file at https:/...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_start_from_level_2 - RuntimeError: Could not find file at https://clu...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_start_from_level_3 - RuntimeError: Could not find file at https://clu...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_start_from_level_4 - RuntimeError: Could not find file at https://clu...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestPreproCLI::test_full_run - IndexError: list index out of range
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestBenchmarkCLI::test_full_run - IndexError: list index out of range
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_vascaling.py::TestVAScalingModel::test_annual_climate - pyproj.exceptions.CRSError: Invalid CRS input: <salem.G...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_vascaling.py::TestVAScalingModel::test_annual_mb - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_vascaling.py::TestVAScalingModel::test_local_t_star - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_vascaling.py::TestVAScalingModel::test_monthly_climate - pyproj.exceptions.CRSError: Invalid CRS input: <salem....FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_vascaling.py::TestVAScalingModel::test_monthly_specific_mb - pyproj.exceptions.CRSError: Invalid CRS input: <sa...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_vascaling.py::TestVAScalingModel::test_reset - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_vascaling.py::TestVAScalingModel::test_run_until_and_store - pyproj.exceptions.CRSError: Invalid CRS input: <sa...FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_vascaling.py::TestVAScalingModel::test_specific_mb - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_vascaling.py::TestVAScalingModel::test_step - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_vascaling.py::TestVAScalingModel::test_time_scales - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_vascaling.py::TestVAScalingModel::test_yearly_mb_temp_prcp - pyproj.exceptions.CRSError: Invalid CRS input: <sa...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestInitPresentDayFlowline::test_init_present_time_glacier - pyproj.exceptions.CRSError: Invalid CRS ...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestInitPresentDayFlowline::test_present_time_glacier_massbalance - pyproj.exceptions.CRSError: Inval...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_past_mb_model - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_glacierwide_mb_model[PastMassBalance] - pyproj.exceptions.CRSError: Inval...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_glacierwide_mb_model[ConstantMassBalance] - pyproj.exceptions.CRSError: I...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_glacierwide_mb_model[RandomMassBalance] - pyproj.exceptions.CRSError: Inv...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_constant_mb_model - pyproj.exceptions.CRSError: Invalid CRS input: <salem...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_random_mb - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_random_mb_unique - pyproj.exceptions.CRSError: Invalid CRS input: <salem....ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_uncertain_mb - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_mb_performance - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_constant_bed] - pyproj.exceptions.CRSError: Invalid CRS input:...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_width_bed] - pyproj.exceptions.CRSError: Invalid CRS input: <s...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_noisy_bed] - pyproj.exceptions.CRSError: Invalid CRS input: <s...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_bumpy_bed] - pyproj.exceptions.CRSError: Invalid CRS input: <s...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_parabolic_bed] - pyproj.exceptions.CRSError: Invalid CRS input...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_trapezoidal_bed] - pyproj.exceptions.CRSError: Invalid CRS inp...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_mixed_bed] - pyproj.exceptions.CRSError: Invalid CRS input: <s...ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_model_to_file - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_gdir_copy - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_hef - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestHEF::test_start_from_spinup - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestHEF::test_start_from_spinup_min_ys - pyproj.exceptions.CRSError: Invalid CRS input: <salem.Grid>
====================================================== 54 failed, 138 passed, 69 skipped, 211 warnings, 23 errors in 356.64s (0:05:56) ======================================================

This is the conda list:

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
affine                    2.3.0                      py_0    conda-forge
argon2-cffi               20.1.0           py38h25fe258_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
blosc                     1.20.1               he1b5a44_0    conda-forge
bokeh                     2.2.3            py38h578d9bd_0    conda-forge
boost-cpp                 1.74.0               h9359b55_0    conda-forge
brotli                    1.0.9                he1b5a44_3    conda-forge
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.16.0            h3fc0475_1005    conda-forge
cartopy                   0.18.0           py38hc1e57b6_5    conda-forge
certifi                   2020.12.5        py38h578d9bd_0    conda-forge
cffi                      1.14.4           py38ha312104_0    conda-forge
cfitsio                   3.470                h2e3daa1_7    conda-forge
cftime                    1.3.0            py38h0b5ebd8_0    conda-forge
chardet                   4.0.0            py38h578d9bd_0    conda-forge
charls                    2.1.0                he1b5a44_2    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
cryptography              3.2.1            py38h7699a38_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py38h348cfbe_1    conda-forge
cytoolz                   0.11.0           py38h25fe258_1    conda-forge
dask                      2020.12.0          pyhd8ed1ab_0    conda-forge
dask-core                 2020.12.0          pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
distributed               2020.12.0        py38h578d9bd_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
fiona                     1.8.18           py38h37fbd03_0    conda-forge
fontconfig                2.13.1            h7e3eb15_1002    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
freexl                    1.0.5             h516909a_1002    conda-forge
fsspec                    0.8.5              pyhd8ed1ab_0    conda-forge
gdal                      3.1.4            py38h9edfc58_0    conda-forge
geopandas                 0.8.1                      py_0    conda-forge
geos                      3.8.1                he1b5a44_0    conda-forge
geotiff                   1.6.0                h5d11630_3    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.66.3               h58526e2_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.6          nompi_h7c3c948_1111    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2020.5.30        py38h36e1e94_1    conda-forge
imageio                   2.9.0                      py_0    conda-forge
importlib-metadata        3.3.0            py38h578d9bd_2    conda-forge
importlib_metadata        3.3.0                hd8ed1ab_2    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipykernel                 5.4.2            py38h81c977d_0    conda-forge
ipython                   7.19.0           py38h81c977d_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
jedi                      0.17.2           py38h578d9bd_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json-c                    0.13.1            hbfbb72e_1002    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.7.0            py38h578d9bd_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jxrlib                    1.1                  h516909a_2    conda-forge
kealib                    1.4.13               h33137a7_1    conda-forge
kiwisolver                1.3.1            py38h82cb98a_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7
libaec                    1.0.4                he1b5a44_1    conda-forge
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libclang                  10.0.1          default_hde54327_1    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdap4                   3.20.6               h1d1bd15_1    conda-forge
libedit                   3.1.20191231         h14c3975_1
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libgdal                   3.1.4                h670eac6_0    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libglib                   2.66.3               hbe7bbb4_0    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h74f7ee3_1012    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h255efa7_3    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libspatialite             5.0.0                h4dde289_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h4f3a223_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
libzopfli                 1.0.3                he1b5a44_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                1.1.1            py38h8df0ef7_2    conda-forge
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py38h5c7f4ab_1    conda-forge
mistune                   0.8.4           py38h25fe258_1002    conda-forge
mock                      4.0.3            py38h578d9bd_0    conda-forge
more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
motionless                1.3.2                      py_5    oggm
msgpack-python            1.0.0            py38h82cb98a_2    conda-forge
munch                     2.5.0                      py_0    conda-forge
mysql-common              8.0.21                        2    conda-forge
mysql-libs                8.0.21               hf3661c5_2    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py38h578d9bd_3    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
ncurses                   6.2                  he6710b0_1
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.4           nompi_py38hec8b9af_103    conda-forge
networkx                  2.5                        py_0    conda-forge
notebook                  6.1.5            py38h578d9bd_0    conda-forge
nspr                      4.29                 he1b5a44_1    conda-forge
nss                       3.59                 h2c00c37_0    conda-forge
numexpr                   2.7.1            py38hc5bc63f_3    conda-forge
numpy                     1.19.4           py38hf0fd68c_1    conda-forge
oggm                      1.3.1                      py_7    oggm
oggm-deps                 100                          21    oggm
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pandas                    1.1.4            py38h0ef3d22_0    conda-forge
pandoc                    2.11.3.1             h7f98852_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py38h70fbd49_0    conda-forge
pip                       20.3.3           py38h06a4308_0
pixman                    0.38.0            h516909a_1003    conda-forge
pluggy                    0.13.1           py38h924ce5b_3    conda-forge
poppler                   0.89.0               h4190859_1    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 hc2f5b80_3    conda-forge
progressbar2              3.53.1             pyh9f0ad1d_0    conda-forge
proj                      7.1.1                h966b41f_3    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
prompt_toolkit            3.0.8                hd8ed1ab_0    conda-forge
psutil                    5.7.3            py38h8df0ef7_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38h56787f0_3    conda-forge
pyqt                      5.12.3           py38ha8c2ead_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.17.3           py38h25fe258_1    conda-forge
pyshp                     2.1.2              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
pytables                  3.6.1            py38hf9f05d5_3    conda-forge
pytest                    6.2.1            py38h578d9bd_0    conda-forge
pytest-mpl                0.123.0.202009251653            py_0    oggm
python                    3.8.3           cpython_he5300dc_0    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-utils              2.4.0                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py38hab2c0dc_3    conda-forge
pyyaml                    5.3.1            py38h8df0ef7_1    conda-forge
pyzmq                     20.0.0           py38h1d1b12f_1    conda-forge
qt                        5.12.9               h1f2b2cb_0    conda-forge
qtconsole                 5.0.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
rasterio                  1.1.8            py38h37fbd03_0    conda-forge
readline                  8.0                  h7b6447c_0
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rtree                     0.9.5            py38h02d302b_0    conda-forge
salem                     0.3.0.202008202149            py_0    oggm
scikit-image              0.17.2           py38h0ef3d22_4    conda-forge
scipy                     1.5.3            py38h828c644_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                51.0.0           py38h06a4308_2
setuptools-scm            5.0.1              pyhd3deb0d_0    conda-forge
setuptools_scm            5.0.1                hd8ed1ab_0    conda-forge
setuptools_scm_git_archive 1.1                        py_0    conda-forge
shapely                   1.7.1            py38hc7361b7_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.33.0               h62c20be_0
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.1            py38h32f6830_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tifffile                  2020.12.8          pyhd8ed1ab_0    conda-forge
tiledb                    2.1.3                h17508cd_0    conda-forge
tk                        8.6.10               hbc83047_0
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h25fe258_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzcode                    2020a                h516909a_0    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1            py38h578d9bd_4    conda-forge
xarray                    0.16.2             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                hfe33f54_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.3                h58526e2_3    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.5                h6597ccf_2    conda-forge

There is a such error example:

2020-12-23T04:45:11; catchment_intersections; CRSError; Invalid CRS input: <salem.Grid>
  proj: +datum=WGS84 +k=0.9996 +lat_0=0 +lon_0=10.7584 +no_defs+proj=tmerc +units=m +x_0=0 +y_0=0
  pixel_ref: center
  origin: upper-left
  (nx, ny): (199, 154)
  (dx, dy): (50.0, -50.0)
  (x0, y0): (-4517.129122282515, 5187040.526772606)

**Comment by fmaussion** [comment]
Thanks for the report. It looks like many things in your environment are broken. Have you tried the troubleshooting section in the installation docs?

https://docs.oggm.org/en/latest/installing-oggm.html#installation-troubleshooting

**Comment by FANSCRAZY** [comment]
thank you a lot. I have already solve the problem with your help
