### ISSUE TITLE
Wrong equation for trapezoidal width in documentation

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/oggm#1139]
I think the equation for w in the documentation website for the trapezoidal bed shape is not correct with the explanation that λ=1 equals a 45° wall angle ([https://docs.oggm.org/en/latest/ice-dynamics.html#trapezoidal](https://docs.oggm.org/en/latest/ice-dynamics.html#trapezoidal)).

To make it clear here a sketch with a 45° wall angle:
![IMG_20210119_175647](https://user-images.githubusercontent.com/50843444/105067498-091ad800-5a80-11eb-8649-16f4f25c1354.jpg)

The formula for w should be `w = w0 + 2 λ h` or the description below the figure should state λ=1 equals an 22.5° wall angle.
I think the first option should be preferred to be consistent with the definition `λ=tan(α)`.

I hope I have not misunderstood anything.

**Comment by fmaussion** [comment]
Thanks for the report! 

`w = w0 + λ h` originates from [Oerlemans 97](https://doi.org/10.3189/S0260305500012489) and it is [how it's written in the code](https://github.com/OGGM/oggm/blob/master/oggm/core/flowline.py#L348), so I think we can't change this anymore at this point...

That being said, I agree that the documentation is not correct. First, I've always seen the angle as defined from the horizontal, i.e. a rectangular bed has lambda = 0 and angle = 90° (this should be clearer from the docs), and with this I come to that tan(α) = 2 /  λ:

![IMG_20210120_102852(1)](https://user-images.githubusercontent.com/10050469/105155296-b6d2c900-5b0a-11eb-9e07-496189459de2.jpg)

So λ = 1 -> 63°, and to obtain a 45° angle we need λ = 2. Thanks a lot for this!
