### ISSUE TITLE
Some errors occured when run the testing code: pytest --pyargs oggm.

### ISSUE THREAD

**Issue by zhaocaicai252** [OGGM/oggm#1140]
Mr. Developer, when I run `pytest --pyargs oggm` under the oggm_env, I encountered a problem. The report is as follows: 
[report(pytest --pyargs oggm).txt](https://github.com/OGGM/oggm/files/5841441/report.pytest.--pyargs.oggm.txt).  I find errors occurred at every step. Details as follows: `CRSError occurred during task catchment_intersections on RGI50-11.00897: Invalid CRS input: <salem.Grid>`. 
Attached conda list：[conda list.txt](https://github.com/OGGM/oggm/files/5842736/conda.list.txt).

**Comment by fmaussion** [comment]
Thanks for the report. It looks like some things in your environment are broken. Have you tried the troubleshooting section in the installation docs?

https://docs.oggm.org/en/latest/installing-oggm.html#installation-troubleshooting

**Comment by zhaocaicai252** [comment]
> Thanks for the report. It looks like some things in your environment are broken. Have you tried the troubleshooting section in the installation docs?
> 
> https://docs.oggm.org/en/latest/installing-oggm.html#installation-troubleshooting

Thank you very much, Mr. Developer! The model test ran successfully!
