### ISSUE TITLE
Run_from_climate_data in reverse (start with present time glacier and model back in time)? 

### ISSUE THREAD

**Issue by mplauch** [OGGM/oggm#1144]
I noticed that the example given for running a [past climate run](https://docs.oggm.org/en/latest/run_examples/run_with_spinup.html) takes the present day glacier information (such as volume) as the glacier information for whatever the ```ys``` year is set to in ```run_from_climate_data```. I am wondering if there is a built in way to start the run at the present time (or at least the more recent time like 2000) with the present glacier stats and model it backwards to the earlier date (such as 1801 as in the example). I know extent changes may not be modeled accurately but I am just looking for rough volume/thickness changes to improve on previous work (extrapolating modern melt rates as constant for the past 200 years). I could just be interpreting everything wrong but knowing that would be useful too! Is this "fixed" by using the spinups to simulate growth and try to get a reasonable modern endpoint?

Examples of the output from the past climate run (1801-2001) and from a test run (2000-2001) that I wanted to check starting volumes:

**Starting volume for 1801-2000 run:** 
```
array([[8.63237511e+08],
       [8.55782719e+08],
       [8.41470266e+08],...
```

**Volume for 2000-2001 run:** 
```
array([[8.63237511e+08],
       [8.67439081e+08]])
```

**Code:**
```
# Python imports
import time
import logging

# Libs
import matplotlib.pyplot as plt

# Locals
import oggm.cfg as cfg
from oggm import tasks, utils, workflow
from oggm.workflow import execute_entity_task
from oggm.utils import get_demo_file

# Module logger
log = logging.getLogger(__name__)

# For timing the run
start = time.time()

# Initialize OGGM and set up the default run parameters
cfg.initialize()

# Local working directory (where OGGM will write its output)
WORKING_DIR = utils.gettempdir('OGGM_spinup_run')
utils.mkdir(WORKING_DIR, reset=True)
cfg.PATHS['working_dir'] = WORKING_DIR

# Use multiprocessing?
cfg.PARAMS['use_multiprocessing'] = True

# How many grid points around the glacier?
# Make it large if you expect your glaciers to grow large
cfg.PARAMS['border'] = 80

# Go - initialize glacier directories
gdirs = workflow.init_glacier_directories(['RGI60-11.00897'],
                                          from_prepro_level=4)

# Additional climate file (CESM)
cfg.PATHS['cesm_temp_file'] = get_demo_file('cesm.TREFHT.160001-200512'
                                            '.selection.nc')
cfg.PATHS['cesm_precc_file'] = get_demo_file('cesm.PRECC.160001-200512'
                                             '.selection.nc')
cfg.PATHS['cesm_precl_file'] = get_demo_file('cesm.PRECL.160001-200512'
                                             '.selection.nc')
execute_entity_task(tasks.process_cesm_data, gdirs)

# Run the last 200 years with the default starting point (current glacier)
# and CESM data as input
execute_entity_task(tasks.run_from_climate_data, gdirs,
                    climate_filename='gcm_data',
                    ys=1801, ye=2000,
                    output_filesuffix='historic_test')

# Compile output
log.info('Compiling output')
utils.compile_glacier_statistics(gdirs)
ds1 = utils.compile_run_output(gdirs, input_filesuffix='historic_test')

#Try just 1 year to check starting volume
execute_entity_task(tasks.run_from_climate_data, gdirs,
                    climate_filename='gcm_data',
                    ys=2000, ye=2001,
                    output_filesuffix='present_test')

# Compile output
log.info('Compiling output')
utils.compile_glacier_statistics(gdirs)
ds2 = utils.compile_run_output(gdirs, input_filesuffix='present_test')

# Log
m, s = divmod(time.time() - start, 60)
h, m = divmod(m, 60)
log.info('OGGM is done! Time needed: %d:%02d:%02d' % (h, m, s))
```

Thank you,

Max

**Comment by anoukvlug** [comment]
@mplauch, by default `run_from_climate_data` indeed uses glaciers states that are based on present day, but you can use other initial states that are based on a spin-up or another simulation too (see [this example ](https://docs.oggm.org/en/latest/run_examples/run_with_spinup.html)or the documentation of the [function](https://github.com/OGGM/oggm/blob/0802c100761c8d6d2cf0cfc35f1c02659acf53bd/oggm/core/flowline.py#L2362)). There is no build in way to run OGGM backwards. The reason for that has to do with the physics in the model (running the model backwards would make it unstable).  

@juliaeis, @fmaussion could one of you address the last question of this issue?

**Comment by fmaussion** [comment]
Yes, unfortunately, models of ice flow cannot be run backwards (this is mathematically impossible). You may want to have a look at [Eis et al., 2019](https://doi.org/10.5194/tc-13-3317-2019) for some explanations and ideas to circumvent the issue, + a new paper bei @juliaeis to be published soon I hope ;-)

**Comment by mplauch** [comment]
Thank you both for your replies! Yes I have seen that paper and [This one](https://tc.copernicus.org/articles/14/3135/2020/) that I will look at and likely try to use for this. Thanks for the help!

Max
