### ISSUE TITLE
should we switch off multiprocessing per default?

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1173]
I think it would make more sense for entry users to not to have to fight with this. Advanced users will then switch it on.

It will mean that plenty of scripts that are running around on cluster will need an update... I.e. everybody will have to revisit ther scripts and add `cfg.PARAMS['use_multiprocessing'] = True` everywhere...

Thoughts? 

cc @anoukvlug @drounce @TimoRoth @Keeptg

**Comment by drounce** [comment]
As a user that changes this, I do think that this would make more sense as it comes as a bit of a surprise that it's automatically trying to parallelize things for you, but I don't know the specifics and how much this will affect OGGM's scripts.

**Comment by anoukvlug** [comment]
If it generates problems for first time users, than I'm definitely in favour of changing this. I think it would be good to document the option of multi processing in the documentation than. (I don't think I knew what parallelizing was when I started using OGGM and I'm maybe not be the only one.)

**Comment by TimoRoth** [comment]
It will make OGGM run tremendously slower though, not sure if that's a good idea, since a lot of people will never switch it on, then then waste time and/or resources chugging along on one CPU of a 64 core system.

**Comment by drounce** [comment]
I'd argue though that if they're working on a 64-core system, then they should be aware enough to know they need to figure out how the multiprocessing works.  In this case, this is as simple as switching it on, which is great.  However, a user trying to run OGGM for the first time is likely trying to test it out on just a few glaciers so they can learn the program.  They are also likely to expect that they're running things on a single cpu if I had to guess.  Just my two cents.

**Comment by Keeptg** [comment]
This change might be more friendly for entry user and is acceptable for me. I still remembered that OGGM take all of my 8 CPU cores and made the computer quite slow when the first time I run the example code on OGGM's web.

**Comment by fmaussion** [comment]
Yes I agree , I'll switch it off. The chance that a user runs on a 63 core machine without thinking about mp is much lower than the chance that a user gets discouraged because of problems on a local machine which are hard to debug, despite of using only one glacier.

**Comment by TimoRoth** [comment]
We could also just simply count the glaciers, and if it's less than a 
sensible threshold, skip multiprocessing.
The overhead it adds might not even make it worth it.

**Comment by drounce** [comment]
That is what I do for PyGEM as well (not like that matters, but in case you're interested in seeing it): https://github.com/drounce/PyGEM/blob/master/run_simulation_woggm.py#L1757-L1761
