### ISSUE TITLE
Question about the border keyword in run_prepro_levels()

### ISSUE THREAD

**Issue by anoukvlug** [OGGM/oggm#1177]
Earlier today I had an easy to be solved error in my run. Still I am wondering, should a little piece (~2 lines) in the OGGM code be added here or should I adjust my expectations with regards to the `cfg.PARAMS` settings (or both)? 

I put `cfg.PARAMS['border'] = 80` and later used the `run_prepro_levels(...)` function without using the border keyword and got the following error:

```
Traceback (most recent call last):
  File "prepro_files_incl_run.py", line 75, in <module>
    run_prepro_levels(rgi_version=rgi_version, rgi_reg=rgi_reg,
  File "/usr/local/pyenv/versions/3.8.7/lib/python3.8/site-packages/oggm/cli/prepro_levels.py", line 210, in run_prepro_levels
    'b_{:03d}'.format(border))
TypeError: unsupported format string passed to NoneType.__format__
```

I was expecting the function to read the border value from the `cfg.PARAMS`, unless specified otherwise. 

With the function containing something like: 

```
if border == None:
	border = cfg.PARAMS['border']
```

**Comment by fmaussion** [comment]
As always, code producing the error would be nice ;-) 

This works as expected for me: 

```
# Where to fetch the pre-processed directories
cfg.PARAMS['border'] = 160
gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=3)
```

Are you on latest OGGM?

**Comment by anoukvlug** [comment]
I'm on oggm_20210130.sif. Sorry for not including the code, here it is: 

```
# Python imports
import os, shutil, string

# Libs
import geopandas as gpd
import numpy as np

# Locals
import oggm.cfg as cfg
from oggm import utils, workflow, tasks
from oggm import GlacierDirectory
from oggm.workflow import execute_entity_task
from oggm.cli.prepro_levels import run_prepro_levels
from sandbox.paleo import process_cesm_ensemble
from sandbox import paleo
from sandbox.paleo import run_with_chosen_geom
from sandbox.paleo import compile_run_output_fixed_geom

from oggm.utils._workflow import include_patterns

import glob

import warnings

# For timing the run
import time
start = time.time()

PREPRO = True
RUN_ENS_CLIM = True
RUN_SQUEEZED_DYNAMIC = True
TGW_excl = True
# Initialize OGGM and set up the default run parameters
cfg.initialize()

# OGGM params
cfg.PARAMS['border'] = 80
cfg.PARAMS['climate_qc_months'] = 0
#cfg.PARAMS['prcp_scaling_factor'] = 1.8
cfg.add_to_basenames(basename='climatology', filename='climatology.nc', docstr='climatology can be used to save for'
                                                                               'instance the ensemble mean climatology'
                                                                               'of the CESM-LME.')
# Make it robust
cfg.PARAMS['continue_on_error'] = True

#rgi_reg = '03'  # CAA - North
rgi_version = '62'

# Local working directory (where OGGM will work)
WORKING_DIR = os.environ["WORKDIR"]
utils.mkdir(WORKING_DIR)
cfg.PATHS['working_dir'] = WORKING_DIR

JOBID =os.environ["JOBID"]

print('JOBID=', JOBID)

#for rgi_reg in [1,2,3,4]:
rgi_reg = str(JOBID).zfill(2)

# CESM files
CESM_DIR = '/home/users/avlug/cesm_data'
CESM_FILE = os.path.join(CESM_DIR, '{}.{}.085001-200512.nc')
CESM_FILE_1850 = os.path.join(CESM_DIR, '{}.{}.185001-200512.nc')

if PREPRO:
    run_prepro_levels(rgi_version=rgi_version, rgi_reg=rgi_reg,
                          elev_bands=True, working_dir=cfg.PATHS['working_dir'], max_level=3)

```

**Comment by fmaussion** [comment]
Ah ok. `run_prepro_levels` was never meant to be used that way. It was meant to be used as a command line interface only. For example, it re-initializes everything here: https://github.com/OGGM/oggm/blob/master/oggm/cli/prepro_levels.py#L179 

The pattern to pass specific params to it is to give it a parameter file to start from, but, one could actually allow to pass a dict of params instead. 

But, out of curiosity, why do you want to run this in the first place? What do you need that's not available in the existing directories?

**Comment by anoukvlug** [comment]
Thanks for your explanation. I think what I need might already be in the new directories by now. The reason I was playing around with this, is related to the chat we had on January 20th. I wanted to look a little more into why the difference is so big between my old runs and the once I did with the ERA pre-processed directories (that includes the climate_qc_months = 3 and match_regional_geodetic_mb).
