### ISSUE TITLE
Some errors in using the .yml file to install the environment

### ISSUE THREAD

**Issue by zhaocaicai252** [OGGM/oggm#1207]
Mr. Developer, according to your guidance, I successfully installed and ran the oggm model: see #1140 for details. But when I used the same method to install the model again after changing the computer, the following error occurred.This is a screenshot of the error report.
> 
![error](https://user-images.githubusercontent.com/75459436/109416683-b4616a00-79fa-11eb-9cdf-46d82cbaef98.png)

**Comment by TimoRoth** [comment]
That is an issue with your Internet connection, not the environment.yml. It's unable to reach GitHub.

**Comment by zhaocaicai252** [comment]
> That is an issue with your Internet connection, not the environment.yml. It's unable to reach GitHub.

I installed the environment after trying again. thank you very much!
