### ISSUE TITLE
More information about ice thickness at glacier front in OGGM output files?

### ISSUE THREAD

**Issue by WFurian** [OGGM/oggm#1212]
I'm interested in the morphology of the glaciers modelled by OGGM. At the moment, the OGGM output files contain, i.a., information about the length of the glacier so it is possible to somewhat estimate the retreat of the glacier over time by shortening the flowline. However, as there is no information about the glacier thickness in the normal output file the user cannot approximate the shape of the glacier. They do not know if the, say, last 100m of the glacier front are 5cm or 50m thick. 

So, I was wondering if there could be a possibility to add some information about the morphology of the glacier front to the OGGM output files.   
I am only familiar with the one version of the flowline calculation, but maybe it would be possible to add some more columns to the netCDF - containing the ice thickness value for the next 3-5 points upstream from the glacier front for each timestep? Thus, the user would be able to better estimate the position of the glacier front, the coupling with potential proglacial lakes etc.

**Comment by fmaussion** [comment]
Added in https://github.com/OGGM/oggm/pull/1230
