### ISSUE TITLE
Mass Balance Calibration

### ISSUE THREAD

**Issue by Igsnrr20192019** [OGGM/oggm#1214]
I am interested to calibrate some of glaciers and I have literature mass balance data for them that is just for 3 year, I am confused the area mention in RGI shapefile for that specific glacier is much higher (311) than the the area mention in that paper(228), my question is can I use that 3 year mass balance data to calibrate the glacier and please if anyone have did this on any reference glacier please guide me how to add that glacier into OGGM base directory so that if I apply other modules on that glacier  it can use calibrated value of mass balance parameters not the OGGM default parameters. Thanks

**Comment by fmaussion** [comment]
Hi. Thanks for your interest in OGGM!

Your questions are too vague to be answered directly, but maybe you will learn from our tutorials? 

https://oggm.org/tutorials 

Let us know what you tried and didn't work for you.

**Comment by fmaussion** [comment]
Closing this, feel free to re-open or join our slack
