### ISSUE TITLE
inconsistency in hydrodate <-> calendaryear definition for hydro_month = 1

### ISSUE THREAD

**Issue by lilianschuster** [OGGM/oggm#1218]
I encountered a new inconsistency about the hydrodate <-> calendaryear conversion:
as far as I understood from the discussions together with @fmaussion , we define now that if hydro_month =1, then calendar year corresponds to hydro year. Therefore, I commited some changes in #1142 but apparently I missed the hydrodate, calendaryear conversion functions:
at the moment they output :
`hydrodate_to_calendardate(2020, 1, start_month = 1)` : -> 2019, 1

`calendardate_to_hydrodate(2020, 1, start_month = 1)` : -> 2021, 1

But to be consistent, I believe the output for both should be **2020, 1**!

Please confirm if I understood this right, then I can prepare a pull request where the functions are changed and check if the tests work, and do a new search for hidden functions that still use the old convention

**Comment by fmaussion** [comment]
Yes I agree! Nice catch thanks
