### ISSUE TITLE
Add my own gcm data

### ISSUE THREAD

**Issue by yangmin27** [OGGM/oggm#1221]
I want choose another gcm data for the future run, how can I do it?

**Comment by anoukvlug** [comment]
@yangmin27, you can use the `process_gcm_data` function to pre-process your GCM data. It might be helpful to have a look at the `process_cesm_data` and `process_cmip_data` functions as an inspiration on how to prepare your data, so it can be fed to the `process_gcm_data` function.

The following notebook might be useful for you once have pre-processed your gcm data:
https://oggm.org/tutorials/notebooks/run_with_gcm.html 

Does this answer your question?
