### ISSUE TITLE
process gcm data

### ISSUE THREAD

**Issue by yangmin27** [OGGM/oggm#1223]
bp = "/.../pr_Amon_MPI-ESM-LR_{}_r1i1p1_200601-210012.nc"
bt = "/.../tas_Amon_MPI-ESM-LR_{}_r1i1p1_200601-210012.nc"
for rcp in ['rcp26', 'rcp45', 'rcp85']:
    ft = bt.format(rcp)
    fp = bp.format(rcp)
    # bias correct them
    workflow.execute_entity_task(gcm_climate.process_cmip5_data, gdirs, 
                                 filesuffix='_MPI-ESM-LR_{}'.format(rcp),  # recognize the climate file for later
                                 fpath_temp=ft,  # temperature projections
                                 fpath_precip=fp,  # precip projections
                                 )

when I run this, I got this error： 
oggm.core.gcm_climate: StopIteration occurred during task process_gcm_data_MPI-ESM-LR_rcp26 on RGI6.####,
and I changed the process_cmip5_data function, the last : source = 'CESM'  to source = ''

**Comment by anoukvlug** [comment]
Is that the complete error message you got? 

I noticed a couple of things in your message:
1. I think you cannot use the function without giving a source for the data. However I don't think including the data source, will solve your issue though.
2. It seems like your climate files don't cover the reference period (1961-1990 CE) that is being used by default when applying the anomaly method. Without your files covering the reference period (the default one or the one you choose) the data cannot be pre-processed. 
3. It is better to use the `process_cmip_data` instead of `process_cmip5_data` in the future. `process_cmip5_data` is the old name of the function.

**Comment by yangmin27** [comment]
Thank you. I installed the new version of OGGM. now, I met new problem, I followed the steps of  <Run OGGM with GCM data.py> (https://oggm.org/tutorials/notebooks/run_with_gcm.html) . I got this error: 
 bp = 'https://cluster.klima.uni-bremen.de/~oggm/cmip5-ng/pr/pr_mon_CCSM4_{}_r1i1p1_g025.nc'
   ...: bt = 'https://cluster.klima.uni-bremen.de/~oggm/cmip5-ng/tas/tas_mon_CCSM4_{}_r1i1p1_g025.nc'
   ...: for rcp in ['rcp26', 'rcp45', 'rcp60', 'rcp85']:
   ...:     # Download the files
   ...:     ft = utils.file_downloader(bt.format(rcp))
   ...:     fp = utils.file_downloader(bp.format(rcp))
   ...:     # bias correct them
   ...:     workflow.execute_entity_task(gcm_climate.process_cmip_data, gdirs,
   ...:                                  filesuffix='_CCSM4_{}'.format(rcp),  # recognize the climate file for later
   ...:                                  fpath_temp=ft,  # temperature projections
   ...:                                  fpath_precip=fp,  # precip projections
   ...:                                  )
   ...:
2021-03-18 23:49:58: oggm.workflow: Execute entity task process_cmip_data on 2 glaciers
2021-03-18 23:49:58: oggm.shop.gcm_climate: TypeError occurred during task process_cmip_data_CCSM4_rcp26 on RGI60-13.45334: open_dataset() got an unexpected keyword argument 'use_cftime'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-4949d15a5785> in <module>
      9                                  filesuffix='_CCSM4_{}'.format(rcp),  # recognize the climate file for later
     10                                  fpath_temp=ft,  # temperature projections
---> 11                                  fpath_precip=fp,  # precip projections
     12                                  )
     13

~/oggm/oggm/workflow.py in execute_entity_task(task, gdirs, **kwargs)
    159                          '%d glaciers with multiprocessing turned off. OGGM '
    160                          'will run faster with multiprocessing turned on.', ng)
--> 161         out = [pc(gdir) for gdir in gdirs]
    162
    163     return out

~/oggm/oggm/workflow.py in <listcomp>(.0)
    159                          '%d glaciers with multiprocessing turned off. OGGM '
    160                          'will run faster with multiprocessing turned on.', ng)
--> 161         out = [pc(gdir) for gdir in gdirs]
    162
    163     return out

~/oggm/oggm/workflow.py in __call__(self, arg)
     98             return call_func(gdir, **gdir_kwargs)
     99         else:
--> 100             return call_func(gdir, **self.out_kwargs)
    101
    102

~/oggm/oggm/utils/_workflow.py in _entity_task(gdir, reset, print_log, return_value, continue_on_error, add_to_log_file, **kwargs)
    487                     signal.alarm(cfg.PARAMS['task_timeout'])
    488                 ex_t = time.time()
--> 489                 out = task_func(gdir, **kwargs)
    490                 ex_t = time.time() - ex_t
    491                 if cfg.PARAMS['task_timeout'] > 0:

~/oggm/oggm/shop/gcm_climate.py in process_cmip_data(gdir, filesuffix, fpath_temp, fpath_precip, **kwargs)
    307
    308     # Read the GCM files
--> 309     with xr.open_dataset(fpath_temp, use_cftime=True) as tempds, \
    310             xr.open_dataset(fpath_precip, use_cftime=True) as precipds:
    311

TypeError: open_dataset() got an unexpected keyword argument 'use_cftime'

**Comment by fmaussion** [comment]
> TypeError: open_dataset() got an unexpected keyword argument 'use_cftime'

you also need to update the xarray package

**Comment by yangmin27** [comment]
I update ~ now same error... I am using python3.6.10~ before update oggm, it can work...

**Comment by yangmin27** [comment]
I installed whole enviroment, not it is working~~~

**Comment by fmaussion** [comment]
> not it is working

Do you mean *now* it is working? If yes feel free to close the issue.

**Comment by yangmin27** [comment]
oh, it is working,  now, when I do the next step of Projection runs, it throw me this error:
FileNotFoundError: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-15/RGI60-15.03/RGI60-15.03473/model_geometry_historical.nc'
so, how can I get this file? model_geometry_historical.nc
