### ISSUE TITLE
How to generate this model_geometry_historical.nc file?

### ISSUE THREAD

**Issue by yangmin27** [OGGM/oggm#1228]
Following the steps of  < run with gcm> when I run 
for rcp in ['rcp26', 'rcp45', 'rcp60', 'rcp85']:
    rid = '_CCSM4_{}'.format(rcp)
    workflow.execute_entity_task(tasks.run_from_climate_data, gdirs, ys=2020, 
                                 climate_filename='gcm_data',  # use gcm_data, not climate_historical
                                 climate_input_filesuffix=rid,  # use the chosen scenario
                                 init_model_filesuffix='_historical',  # this is important! Start from 2020 glacier
                                 output_filesuffix=rid,  # recognize the run for later
                                )
It throw me this error:
FileNotFoundError: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-15/RGI60-15.03/RGI60-15.03473/model_geometry_historical.nc'
so how I prepare this file? or how to generate this historical file?

**Comment by fmaussion** [comment]
This looks like a bug in OGGM itself on master - thanks for the report, I'll investigate.

In the meantime, it is safer to install the latest **stable** version of OGGM, with: `pip install oggm==v1.4.0`

**Comment by yangmin27** [comment]
oh oh . then I will wait... please tell me after this issue solved~~

**Comment by fmaussion** [comment]
The stable version is very recent and works fine, you should try it.

**Comment by yangmin27** [comment]
Now working well ~~~thank you so much ~~

**Comment by fmaussion** [comment]
For the record, this problem is solved on master since https://github.com/OGGM/oggm/commit/25970a944e2f47ac834b5c099b94f82f0a9cc826, but hasn't landed on jupyterhub yet (reason unknown)
