### ISSUE TITLE
The .pkl file question

### ISSUE THREAD

**Issue by FANSCRAZY** [OGGM/oggm#1235]
when I run out the oggm,the result .pkl file I can not read it in a right way ,need your help.

**Comment by fmaussion** [comment]
Unfortunately your question is not specific enough for us to help you. Please check "[How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)" and similar online guides to help you formulate the question more precisely.

**Comment by FANSCRAZY** [comment]
This is the error when I want to read the packle file I meet

**Comment by FANSCRAZY** [comment]
![Uploading QQ图片20210402211936.png…]()

**Comment by FANSCRAZY** [comment]
>>>import pickle
>>> F=open(r'C:\Users\31007\inversion_flowlines.pkl','rb')
>>> data=pickle.load(F)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.UnpicklingError: invalid load key, '\x1f'.

when I wanna read the packle file ,this error will happen. I can not solve this problem for a long time

**Comment by fmaussion** [comment]
It looks like you are trying to read an OGGM pickle file on windows, possibly in an environment without OGGM installed (OGGM does not work on windows). If you want to read OGGM pickle files, make sure that OGGM is installed properly.

Now, the question is: why do you want to read this pickle file? This is an internal file used by OGGM, and it should not be read outside of OGGM. If you need access to specific variables, you should store them in a machine readable format from within the OGGM workflow (see for example  https://github.com/OGGM/oggm/issues/1105)

Note also that the OGGM centerlines are already available for download here: https://docs.oggm.org/en/stable/assets.html

**Comment by FANSCRAZY** [comment]
It look like I read this file in a wrong way. thank you for your help

**Comment by fmaussion** [comment]
This is how OGGM reads them: https://github.com/OGGM/oggm/blob/4cfcddd00629a9e0ca1d8c6eabf23d1435f86762/oggm/utils/_workflow.py#L2524
