### ISSUE TITLE
`simple_glacier_mask()` will make the `graphics.plot_distributed_thickness()` invalid

### ISSUE THREAD

**Issue by Keeptg** [OGGM/oggm#1238]
I tried use the elev_bands flowline simulating the ice thickness, and I found the `graphics.plot_distributed_thickness()` function is invalid. The reason is `simple_glacier_mask()` function don't create the geometry.pkl file which will be created in `glacier_mask()`.

I think this can be fixed by create a geometry.pkl file in `simple_glacier_mask()` funciton like what `glacier_mask()` did, but only `polygon_pix` key included. If you think this method is feasible, I'd like to submit a PR to do this.

This problem also made me thinking maybe there should be a parameter, like `cfg.PARAMS['flowline_type']`, which can tell OGGM which flowline type he (OGGM is a boy, right? ; ) ) is working on. This might be useful to reminder users that some functions (like  "extracting the realistic flowline", "plot catchment/centerlines" and maybe some others) are invalid under the elev_bands flowline. What do you think about this?

**Comment by fmaussion** [comment]
> I think this can be fixed by create a geometry.pkl file in simple_glacier_mask() funciton like what glacier_mask() did, but only polygon_pix key included. If you think this method is feasible, I'd like to submit a PR to do this.

Thanks! It is not trivial to compute `polygon_pix` out of the `simple_glacier_mask` output (`polygon_pix`  is necessary to compute the OGGM masks, i.e. it's not just a side product). 

I think that it would be much simpler to tell the plots to use the glacier shapefiles for the plot (`gdir.read_shapefile('outlines')`) when `geometry.pkl` is not there.

> This problem also made me thinking maybe there should be a parameter, like cfg.PARAMS['flowline_type']

`gdir.get_diagnostics()['flowline_type']`, can be of `'elevation_band'` or `'centerlines'` ;-)

**Comment by Keeptg** [comment]
> `gdir.get_diagnostics()['flowline_type']`, can be of 'elevation_band' or 'centerlines'
Good to know this!

> I think that it would be much simpler to tell the plots to use the glacier shapefiles for the plot (`gdir.read_shapefile('outlines')`) when `geometry.pkl` is not there.
Agree! I'll try to submit a PR
