### ISSUE TITLE
Better timeout?

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1244]
Currently we use `signal.alarm`

https://github.com/OGGM/oggm/blob/a8b792263b640aeab86900c5169b9b1255526010/oggm/utils/_workflow.py#L486-L495

@TimoRoth I remember you mentioned that you would recommend something else?

**Comment by TimoRoth** [comment]
I looked into that, but any other Python-Written timeout would not be able to interrupt any stuck tasks.
It would always rely on the task cooperating.
