### ISSUE TITLE
Using my own inventory on OGGM

### ISSUE THREAD

**Issue by thierrydemierre** [OGGM/oggm#1250]
Hello!
I don't have much experiment on Python code and I've got some basic questions about the code. 
First of all, I will explain you briefly what I want to do. I want to compute centerlines, catchments, mass balance and ELA based on a glacier inventory (shapefiles) I've produced on ArcGIS for multiple glaciers around the world. In order to compute it I've taken your example code and I tried to modify it in order to use my own glacier inventory... But i didn't got much success.
I was able to upload my shapefile on OGGM and to plot it. As I saw on the tutorial "use_your_own_inventory", it seems that you always need a part of the RGI. My idea was to use my inventory and to modify it in order to seem like the RGI. Is it possible or does I always need information from the glacier based on RGI?
In your example I was able to define "gdirs" but when I begin to execute tasks I get some errors. Here, below is the beginning of the error I got.
2021-05-17 12:52:14: oggm.workflow: Execute entity task define_glacier_region on 1 glaciers
2021-05-17 12:52:16: oggm.core.gis: HttpDownloadError occurred during task define_glacier_region on RGI60-18.02397: (401, 'https://e4ftl01.cr.usgs.gov/MEASURES/NASADEM_HGT.001/2000.02.11/NASADEM_HGT_s44e170.zip')
---------------------------------------------------------------------------
HttpDownloadError                         Traceback (most recent call last)
<ipython-input-24-4a9d0f6f0aa9> in <module>
      1 # Executing some tasks
----> 2 workflow.execute_entity_task(tasks.define_glacier_region, gdirs);
      3 workflow.execute_entity_task(tasks.glacier_masks, gdirs);
      4 workflow.execute_entity_task(tasks.compute_centerlines, gdirs);
      5 workflow.execute_entity_task(tasks.initialize_flowlines, gdirs);

I think the problem is mainly my shapefiles properties but I don't really know how to change it. If you could give me an example or some ideas to resolve it, it would be awesome.

I've got another basic question concerning the mass balance. In your example you use hydrological data from uni Bremen. In order to compute mass balance for glaciers all around the world, Does I have to use specific hydrological dataset for every region? and how could I import it?

I hope it was clear enough so you can give me some help. 
Thanks a lot !

**Comment by fmaussion** [comment]
Thanks! The error message seems related to  https://github.com/OGGM/oggm/pull/1243 

Can you use `SRTM` instead? See https://oggm.org/tutorials/stable/notebooks/dem_sources.html#choose-a-dem-source-e-g-srtm for how to do that and report back

**Comment by fmaussion** [comment]
Regarding your question on mass-balance: please see https://docs.oggm.org/en/stable/mass-balance.html as well as the mass-balance calibration notebook: https://oggm.org/tutorials/stable/notebooks/massbalance_calibration.html 

For more usage questions feel free to use our slack as well!

**Comment by fmaussion** [comment]
Closing for lack of response - feel free to reopen if needed!
