### ISSUE TITLE
how to change parameters if the modeled mass balance has much difference with wgms data 

### ISSUE THREAD

**Issue by yangmin27** [OGGM/oggm#1253]

**Comment by yangmin27** [comment]
hello, professor, what I mean is, when I use workflow in OGGM to calculate mass balance, when this glacier is a reference glacier, then we can compare the wgms data with modeled mb. for my case, it has big difference, so what I can do? can I change some parameters to test? or ? any suggestions?

**Comment by lilianschuster** [comment]
Hi, 
In the default calibration scheme, the annual WGMS data (so: `gdir.get_ref_mb_data()`) should normally match quite well the modeled mass balance, as this is the data that was used to calibrate the model (see: https://docs.oggm.org/en/stable/mass-balance.html). Which pre-processed glacier directory did you use (see https://docs.oggm.org/en/stable/input-data.html#pre-processed-directories for more infos) ? If you changed something from the "default" workflow, it is possible that you have to recalibrate the mass-balance model or you might need to check that your settings are right. In the *climate* part of the *getting started tutorial* it is explained how to do this: https://oggm.org/tutorials/stable/notebooks/getting_started.html#climate-tasks. The details on the massbalance-calibration are explained here: https://oggm.org/tutorials/stable/notebooks/massbalance_calibration.html. 
I hope this helps a bit!

**Comment by fmaussion** [comment]
Closing for lack of response: please reopen with more information if needed!
