### ISSUE TITLE
When is the glacier velociety graph calculated using the "its_live" data in "oggm_shop"?

### ISSUE THREAD

**Issue by muzi2021** [OGGM/oggm#1254]
I want to know how to view the data year of the glacier velocity map extracted with the "its_live" data in "oggm_shop". Is it possible to extract the glacier velocity field of “its_live” data from 1985 to 2018 in any year？Thank you very much!

**Comment by fmaussion** [comment]
Thanks for your interest! 

We download directly from the ITS_LIVE servers, so all documentation about this dataset has to be searched for on their website: https://its-live.jpl.nasa.gov/

The link we are using is hard-coded here: https://github.com/OGGM/oggm/blob/4e50ae494ad1069a9edd0175800c39781e5b834f/oggm/shop/its_live.py#L20

**Comment by muzi2021** [comment]
Thank you for your reply，I know the ‘its_live’ website, and I also downloaded some of the data. I mean what year is the glacier velocity field calculated by "oggm_shop"? I  did not find the year that quoted the "its_live" data in the code.

**Comment by fmaussion** [comment]
Ah yes sorry this should be better documented: we use the 120m composite: 

https://github.com/OGGM/oggm/blob/4e50ae494ad1069a9edd0175800c39781e5b834f/oggm/shop/its_live.py#L28

(filename `G0120_0000`)

It should be quite easy to add more options to that in order to download more data.

**Comment by muzi2021** [comment]
Thank you, I will look at the documentation of "its_live" again. If the code can be updated, it would be better to choose the year of downloading the data.

**Comment by fmaussion** [comment]
We "reverse engineered" the links from here: 

https://its-live.jpl.nasa.gov/#data 

Examples: 

Composites 120 m:
https://its-live-data.jpl.nasa.gov.s3.amazonaws.com/velocity_mosaic/landsat/v00.0/static/cog/ALA_G0120_0000_vx.tif

Year 2017:
https://its-live-data.jpl.nasa.gov.s3.amazonaws.com/velocity_mosaic/landsat/v00.0/annual/cog/ALA_G0240_2017_vx.tif

**Comment by fmaussion** [comment]
It should be relatively to add this as a keyword to the OGGM functions. Contributions welcome!

**Comment by muzi2021** [comment]
I found it in the documentation. The 120m resolution data is a multi-year average from 1985 to 2018.

**Comment by fmaussion** [comment]
Info added to the docs and the tutorials.
