### ISSUE TITLE
Result output.

### ISSUE THREAD

**Issue by muzi2021** [OGGM/oggm#1255]
Can the ice thickness distribution results simulated by oggm be exported to raster format data？

**Comment by fmaussion** [comment]
Yes! See here: https://oggm.org/tutorials/stable/notebooks/inversion.html#distributed-ice-thickness

**Comment by muzi2021** [comment]
Can this result be opened in ArcGIS or Qgis？

**Comment by fmaussion** [comment]
It is a netCDF file, which has the same projection as the DEM geotiff file, so I can imagine that it is possible somehow... But I'm not an expert in this.

**Comment by Keeptg** [comment]
> 
> 
> Can the ice thickness distribution results simulated by oggm be exported to raster format data？

Maybe `tasks.gridded_data_var_to_geotiff()` is what you want!

**Comment by Keeptg** [comment]
You can use `tasks.gridded_data_var_to_geotiff(gdir, 'distributed_ice_thickness')` to save the inverse ice thickness in the `glacier directory` with the `geotiff` format. The path of `glacier directory` can be checked using `gdir.dir()`.

**Comment by fmaussion** [comment]
@Keeptg would you like to add a mention of this tool in the tutorial?

**Comment by muzi2021** [comment]
I think it is very practical to export the centerline. It is a great idea. It would be even better if you can add a tutorial.

**Comment by fmaussion** [comment]
@Keeptg for the geotiff just mention it here:  https://oggm.org/tutorials/stable/notebooks/inversion.html#distributed-ice-thickness 

For the centerlines, the data is available [here](https://docs.oggm.org/en/stable/assets.html) and the documentation of the function available [here](https://docs.oggm.org/en/stable/generated/oggm.global_tasks.write_centerlines_to_shape.html#oggm.global_tasks.write_centerlines_to_shape)

**Comment by fmaussion** [comment]
Has been added to the tutorials on master, will be part of the next release: https://oggm.org/tutorials/master/notebooks/inversion.html#distributed-ice-thickness
