### ISSUE TITLE
Add mean ice velocity to glacier statistics

### ISSUE THREAD

**Issue by Keeptg** [OGGM/oggm#1256]
I think maybe add the mean ice velocity and the avilabel ice velocity glacier area (in percent) to `glacier_statistics()` wil be useful.
Will glad to submit a PR!

**Comment by fmaussion** [comment]
Do you mean of the ITS_LIVE velocities? I think this is going a bit too far for OGGM itself in terms of functionality.

However, what I think would be good is to allow users to define an arbitrary function to be run by `compile_glacier_statistics` that would allow the user to add any variable they want to the output! This would be quite elegant...

**Comment by Keeptg** [comment]
> Do you mean of the ITS_LIVE velocities? I think this is going a bit too far for OGGM itself in terms of functionality.

Yes, I means ITS_LIVE velocities. What I thought at the beginning is statistics the mean ice velocity if the `obs_icevel_x` and `obs_icevel_y` variables is writen in `gridded_data.nc` files.

> what I think would be good is to allow users to define an arbitrary function

Do you means add a key argument like `statis_func` to pass in custom-defined function in `compile_glacier_statistics`?

**Comment by fmaussion** [comment]
> Do you means add a key argument like statis_func to pass in custom-defined function in compile_glacier_statistics?

Yes, maybe rather `apply_func`, which accepts a gdir and dict as input and simply fills the dict with any data (only scalar data though)
