### ISSUE TITLE
Feedback on installation instructions

### ISSUE THREAD

**Issue by matthewhoffman** [OGGM/oggm#1261]
I have been working on trying to install OGGM to our institutional cluster.  The OGGM docs are fantastic and make this easy to try.  I followed the conda instructions (https://docs.oggm.org/en/stable/installing-oggm.html#install-with-conda-all-platforms), but when I attempted the second install command (conda install -c conda-forge pytest ipython jupyter), conda got very stuck on dependency issues and I ended up killing it after a few hours.  However, the `environment.yml` file included in the troubleshooting section (https://docs.oggm.org/en/stable/installing-oggm.html#installation-troubleshooting) worked very cleanly and only took a couple minutes.  That seems like a preferable way to set up the conda environment.

After that, when I ran `pytest --pyargs oggm`, I got errors in the colorspace package:
```
========================================================================= ERRORS =========================================================================
________________________________________________________ ERROR collecting tests/test_graphics.py _________________________________________________________
/usr/projects/climate/mhoffman/miniconda3/envs/oggm_env2/lib/python3.8/site-packages/oggm/tests/test_graphics.py:18: in <module>
    from oggm import graphics
/usr/projects/climate/mhoffman/miniconda3/envs/oggm_env2/lib/python3.8/site-packages/oggm/graphics.py:55: in <module>
    set_oggm_cmaps()
/usr/projects/climate/mhoffman/miniconda3/envs/oggm_env2/lib/python3.8/site-packages/oggm/graphics.py:47: in set_oggm_cmaps
    tcmap = sequential_hcl("Blue-Yellow", rev=True).cmap(cm_divs)
/usr/projects/climate/mhoffman/miniconda3/envs/oggm_env2/lib/python3.8/site-packages/colorspace/palettes.py:1498: in __init__
    defaultpalettes = hclpalettes().get_palettes("Sequential")
/usr/projects/climate/mhoffman/miniconda3/envs/oggm_env2/lib/python3.8/site-packages/colorspace/palettes.py:376: in __init__
    raise ValueError("No palette config files found ({:s}.".format(self.__class__.__name__))
E   ValueError: No palette config files found (hclpalettes.
________________________________________________________ ERROR collecting tests/test_workflow.py _________________________________________________________
/usr/projects/climate/mhoffman/miniconda3/envs/oggm_env2/lib/python3.8/site-packages/oggm/tests/test_workflow.py:11: in <module>
    from oggm import graphics
/usr/projects/climate/mhoffman/miniconda3/envs/oggm_env2/lib/python3.8/site-packages/oggm/graphics.py:55: in <module>
    set_oggm_cmaps()
/usr/projects/climate/mhoffman/miniconda3/envs/oggm_env2/lib/python3.8/site-packages/oggm/graphics.py:47: in set_oggm_cmaps
    tcmap = sequential_hcl("Blue-Yellow", rev=True).cmap(cm_divs)
/usr/projects/climate/mhoffman/miniconda3/envs/oggm_env2/lib/python3.8/site-packages/colorspace/palettes.py:1498: in __init__
    defaultpalettes = hclpalettes().get_palettes("Sequential")
/usr/projects/climate/mhoffman/miniconda3/envs/oggm_env2/lib/python3.8/site-packages/colorspace/palettes.py:376: in __init__
    raise ValueError("No palette config files found ({:s}.".format(self.__class__.__name__))
E   ValueError: No palette config files found (hclpalettes.
```
I looked into these errors, and it looks like the head of the colorspace repo is broken (the required palconfig/*.conf files have been renamed).  I manually checked out the previous commit of the colorspace package (https://github.com/retostauffer/python-colorspace/commit/da56c170fbaa8a6ca27f9483954ac3e2f51af617), and then pytest was able to run without that error.  

I can't say how general my experience is, but I thought I would report my issues in case it is helpful.

**Comment by fmaussion** [comment]
Thanks for the feedback! And sorry for the late reply. I'm not sure about the colorspace package, I never had any issues with installing from latest master. But probably it's worth questioning if we really want to keep this (optional) dependency.

Regarding the installation: @TimoRoth what do you think about that? It seems that most people are landing on the troubleshooting part and therefore aren't using the oggm conda channels. Would it be easier for you to maintain some recipes in conda-forge for salem and all those that are not yet in conda and scrap the `oggm-deps` package?

**Comment by TimoRoth** [comment]
The oggm-deps package is the correct way to setup the environment though. All the environment snapshows are built from it.
Conda being a constantly broken mess does not help. They regularily remove old package versions, so providing an environment file will for one be constantly outdated, with potential security implications (OGGM connects to a ton of servers and downloads stuff after all) and on the other hand will require even more constant maintenance to keep it up to date.

There already is an attempt at auto-generating environment files over at https://github.com/OGGM/OGGM-dependency-list, but most of the time building those is failing, since Conda broke something again.

The simplified environment file listed in that article is pratically identical to what oggm-deps is, just not in package form. So I don't understand what the issue with oggm-deps is.
