### ISSUE TITLE
jupyter run error

### ISSUE THREAD

**Issue by muzi2021** [OGGM/oggm#1262]
When I use jupyter notebook to run ‘OGGM-inversion’, this error always occurs. Is it because of the OGGM version?
![1](https://user-images.githubusercontent.com/77234985/122178654-58432880-ceb9-11eb-84c7-a8c2f382ac15.JPG)
![2](https://user-images.githubusercontent.com/77234985/122178667-5c6f4600-ceb9-11eb-831e-25612b6f636f.JPG)

**Comment by fmaussion** [comment]
Can you try to delete the `.oggm` folder in your home folder and try to run the tests as explained in the docs?

**Comment by fmaussion** [comment]
Closing for lack of answer - reopen with more info if this still occurs!
