### ISSUE TITLE
Error after installation of OGGM - NameError: name 'salem' is not defined

### ISSUE THREAD

**Issue by kimcholi** [OGGM/oggm#1263]
After trying several times to install and deinstall OGGM following the instructions from the OGGM website (https://docs.oggm.org/en/stable/installing-oggm.html#install-with-conda-all-platforms), I still have problems with it. 

I am using Anaconda on my MacBook. The first problem, which occurs, is that when I try to launch Jupyter in Anaconda it does not work, therefore I have to launch it from the terminal each time. 

The second and more serious problem is that when I tried the Getting Started Tutorial provided on the website of OGGM (https://oggm.org/tutorials/stable/notebooks/getting_started.html), each time I used the command `gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=3, prepro_border=80)`, the following error occured: `NameError: name 'salem' is not defined`. I tried to import salem in order to solve this error, but then it told me `ModuleNotFoundError: No module named 'descartes'`. 

I am using a MacBook Air from Mid 2013.

[Getting Started.pdf](https://github.com/OGGM/oggm/files/6661434/Getting.Started.pdf)

Did anyone have the same problem and know how to solve it? Thanks :)

**Comment by lilianschuster** [comment]
Hi,
- I always start jupyter notebook/lab from the terminal, so never tried it via Anaconda Navigator, so there I can't help you. Maybe this helps: https://stackoverflow.com/questions/52300930/jupyter-notebook-not-launching-from-anaconda-navigator
- It looks like you have not installed **descartes** ?! Does `import descartes` work? If not, install it via `conda install -c conda-forge descartes` in your oggm environment and then try again to run the tutorial in that environment! 
I hope it works then!

**Comment by kimcholi** [comment]
> Hi,
> 
> * I always start jupyter notebook/lab from the terminal, so never tried it via Anaconda Navigator, so there I can't help you. Maybe this helps: https://stackoverflow.com/questions/52300930/jupyter-notebook-not-launching-from-anaconda-navigator
> * It looks like you have not installed **descartes** ?! Does `import descartes` work? If not, install it via `conda install -c conda-forge descartes` in your oggm environment and then try again to run the tutorial in that environment!
>   I hope it works then!

Thank you very much! With import `descartes` it didn't work before but with `conda install -c conda-forge descartes` it worked for now.
