### ISSUE TITLE
ValueError: model_geometry not in cfg.BASENAMES.

### ISSUE THREAD

**Issue by kimcholi** [OGGM/oggm#1265]
Hello everyone,
I'm just doing the Plotting the OGGM surface mass-balance tutorial from the OGGM website. In the last step to compute the retrospective MB from model output the following error came up: *ValueError: model_geometry not in cfg.BASENAMES.* Does someone know what could solve this problem?

[Plotting the OGGM surface mass-balance.pdf](https://github.com/OGGM/oggm/files/6699833/Plotting.the.OGGM.surface.mass-balance.pdf)

**Comment by Hamid-mojtabavi** [comment]
Hi kimcholi,

Have you tried it at Jupyterlab? I suggest to restart kernel, re-run whole notebook again!

Cheers,
Hamid

**Comment by kimcholi** [comment]
Hey,

I'm using Jupyter notebook. I restarted the kernel and run the notebook again. Unfortunately it did not work. But thanks :)

**Comment by Hamid-mojtabavi** [comment]
Please try this:

if not 'model_geometry' in cfg.BASENAMES:
            cfg.BASENAMES['model_geometry'] = ('model_geometry.nc', 'model output')

before this line: dyn_mod = flowline.FileModel(gdir.get_filepath('model_geometry'))

**Comment by kimcholi** [comment]
Unfortunately it didn't work. Then this error came:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/file_manager.py in _acquire_with_cache_info(self, needs_lock)
    198             try:
--> 199                 file = self._cache[self._key]
    200             except KeyError:

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/lru_cache.py in __getitem__(self, key)
     52         with self._lock:
---> 53             value = self._cache[key]
     54             self._cache.move_to_end(key)

KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/var/folders/zs/tcdjybhx73b4pz6v76tpbpnr0000gn/T/OGGM/OGGM-ref-mb/per_glacier/RGI60-11/RGI60-11.00/RGI60-11.00897/model_geometry.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-19-86b588e0dd23> in <module>
      6     cfg.BASENAMES['model_geometry'] = ('model_geometry.nc', 'model output')
      7 
----> 8 dyn_mod = flowline.FileModel(gdir.get_filepath('model_geometry'))
      9 # Get the calibrated mass-balance model
     10 mbmod = massbalance.MultipleFlowlineMassBalance(gdir)

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/core/flowline.py in __init__(self, path)
   1687         """
   1688 
-> 1689         self.fls = glacier_from_netcdf(path)
   1690         dss = []
   1691         for flid, fl in enumerate(self.fls):

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/core/flowline.py in glacier_from_netcdf(path)
   1836     """Instanciates a list of flowlines from an xarray Dataset."""
   1837 
-> 1838     with xr.open_dataset(path) as ds:
   1839         fls = []
   1840         for flid in ds['flowlines'].values:

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/api.py in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, backend_kwargs, *args, **kwargs)
    494 
    495     overwrite_encoded_chunks = kwargs.pop("overwrite_encoded_chunks", None)
--> 496     backend_ds = backend.open_dataset(
    497         filename_or_obj,
    498         drop_variables=drop_variables,

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/netCDF4_.py in open_dataset(self, filename_or_obj, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta, group, mode, format, clobber, diskless, persist, lock, autoclose)
    547 
    548         filename_or_obj = _normalize_path(filename_or_obj)
--> 549         store = NetCDF4DataStore.open(
    550             filename_or_obj,
    551             mode=mode,

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/netCDF4_.py in open(cls, filename, mode, format, group, clobber, diskless, persist, lock, lock_maker, autoclose)
    378             netCDF4.Dataset, filename, mode=mode, kwargs=kwargs
    379         )
--> 380         return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
    381 
    382     def _acquire(self, needs_lock=True):

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/netCDF4_.py in __init__(self, manager, group, mode, lock, autoclose)
    326         self._group = group
    327         self._mode = mode
--> 328         self.format = self.ds.data_model
    329         self._filename = self.ds.filepath()
    330         self.is_remote = is_remote_uri(self._filename)

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/netCDF4_.py in ds(self)
    387     @property
    388     def ds(self):
--> 389         return self._acquire()
    390 
    391     def open_store_variable(self, name, var):

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/netCDF4_.py in _acquire(self, needs_lock)
    381 
    382     def _acquire(self, needs_lock=True):
--> 383         with self._manager.acquire_context(needs_lock) as root:
    384             ds = _nc4_require_group(root, self._group, self._mode)
    385         return ds

/opt/anaconda3/envs/oggm_env/lib/python3.8/contextlib.py in __enter__(self)
    111         del self.args, self.kwds, self.func
    112         try:
--> 113             return next(self.gen)
    114         except StopIteration:
    115             raise RuntimeError("generator didn't yield") from None

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/file_manager.py in acquire_context(self, needs_lock)
    185     def acquire_context(self, needs_lock=True):
    186         """Context manager for acquiring a file."""
--> 187         file, cached = self._acquire_with_cache_info(needs_lock)
    188         try:
    189             yield file

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/file_manager.py in _acquire_with_cache_info(self, needs_lock)
    203                     kwargs = kwargs.copy()
    204                     kwargs["mode"] = self._mode
--> 205                 file = self._opener(*self._args, **kwargs)
    206                 if self._mode == "w":
    207                     # ensure file doesn't get overriden when opened again

src/netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

src/netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

FileNotFoundError: [Errno 2] No such file or directory: b'/var/folders/zs/tcdjybhx73b4pz6v76tpbpnr0000gn/T/OGGM/OGGM-ref-mb/per_glacier/RGI60-11/RGI60-11.00/RGI60-11.00897/model_geometry.nc'

**Comment by Hamid-mojtabavi** [comment]
Please update OGGM to 1.5 (new version)

**Comment by kimcholi** [comment]
It should already be the latest version

**Comment by kimcholi** [comment]
Thanks!
