### ISSUE TITLE
FAILED tests/test_utils.py::TestPreproCLI::test_start_from_prepro - RuntimeError: Found no valid glaciers!

### ISSUE THREAD

**Issue by kimcholi** [OGGM/oggm#1268]
After being new to OGGM and running the tutorials and getting some errors, I run the command `pytest --pyargs oggm`. The following error came up `FAILED tests/test_utils.py::TestPreproCLI::test_start_from_prepro - RuntimeError: Found no valid glaciers!`. Is this a major issue or does this not affect the usage of OGGM? Up to now I haven't had any problems with the `prepro`command. 

Thank you!

**Comment by fmaussion** [comment]
Closing this for now for lack of information - please reopen if the problem persists!
