### ISSUE TITLE
requests.exceptions.Connection Error when downloading the glacier directory

### ISSUE THREAD

**Issue by Ruitangtang** [OGGM/oggm#1271]
Hi, 
      I got a requests.exceptions.Connection Error as following when downloading the glacier directory through workflow.init_glacier_directories. 
       
      It seems the downloading exceeded the max retries, so the max limitation is? or it is caused by another reason. Any suggestions or advice to fix this? 
     
      Thank you very much

     Ruitang

Error:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cluster.klima.uni-bremen.de', port=443): Max retries exceeded with url: /~oggm/gdirs/oggm_v1.4/L1-L2_files/elev_bands/RGI62/b_040/L2/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f001a1794f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by Keeptg** [comment]
Hi, it's seems like a internet connection problem. I'd like to suggest you to make sure you can connect the OGGM servers first! You can paste the link: `https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.4/L1-L2_files/elev_bands/RGI62/b_040/L2/` in your internet explorer to check if you can access the data or not.

**Comment by Ruitangtang** [comment]
Hi, thanks for your reply.  Yeap, the link works well and  I can download data directly, but always killed in a loop.

**Comment by Keeptg** [comment]
Well, it's strange! The other thing I'd like to conform from you is that you did run OGGM in a linux OS environment, right?

**Comment by Ruitangtang** [comment]
Yeap, in Ubuntu.

**Comment by Ruitangtang** [comment]
Actually, I used PyGEM, but that part (glacier directory) seems compatible with OGGM.

**Comment by fmaussion** [comment]
Can you confirm that this still occurs? Are you maybe in a supercomputer environment where internet is not available? I can't see a reason why this would happen if your internet works properly.

**Comment by Ruitangtang** [comment]
Yes, it happened again when using another glacier list (86 glaciers). It's just weird. It works well when I run the second time for the same list.  Additionally, it's always good with the small list (6 glaciers I tried).

**Comment by fmaussion** [comment]
Closing this for now - I think this is related to your internet connection, not OGGM. 

If the problem persists, please reopen and send info about your laptop and setup.

**Comment by Nicole1150** [comment]
I had the same problem, please how did you solve it

**Comment by anoukvlug** [comment]
I had the same issue earlier today. Running the script again solved the issue in my case. I guess there might be something going on with the connection today, as I normally never encounter this issue.

**Comment by Nicole1150** [comment]
> I had the same issue earlier today. Running the script again solved the issue in my case. I guess there might be something going on with the connection today, as I normally never encounter this issue.

I tried all day and still couldn't solved the error.

**Comment by anoukvlug** [comment]
I'm very sorry to hear that! Seems to be a server problem on our end. We hope it will be solved soon.
