### ISSUE TITLE
salem can't be installed when installing oggm？

### ISSUE THREAD

**Issue by pxr1997** [OGGM/oggm#1273]
**Firstly, when I use ''pytest --pyargs oggm'' to check oggm's installation, it shows**

(oggm_env) pxr@LAPTOP-NLU90O0E:~$ pytest --pyargs oggm
================================================= test session starts ==================================================
platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
Matplotlib: 3.4.2
Freetype: 2.10.4
rootdir: /home/pxr
plugins: mpl-0.123
collected 3 items / 8 skipped

anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_minimal.py ...                               [100%]

============================================= 3 passed, 8 skipped in 6.69s =============================================

**Secondly, I meet the same problem, and use ''print(oggm.utils.show_versions())'' to find out the problem,it shows as follews:**

In [2]: print(oggm.utils.show_versions())
# OGGM environment:
## System info:
    python: 3.8.10.final.0
    python-bits: 64
    OS: Linux
    OS-release: 5.4.72-microsoft-standard-WSL2
    machine: x86_64
    processor: x86_64
## Packages info:
    oggm: 1.5.1.dev9+g42ded70
    numpy: 1.21.1
    scipy: 1.7.1
    pandas: 1.3.1
    geopandas: 0.9.0
    netCDF4: 1.5.7
    matplotlib: 3.4.2
    rasterio: 1.2.6
    fiona: 1.8.20
    pyproj: 3.1.0
    shapely: 1.7.1
    xarray: 0.19.0
    dask: 2021.07.2
    salem: None
    OGGM git identifier: 8150016b2e8c2983c01655fd2163346033b3a461
**It shows  salem is None, then I use '' pip install -- upgrade salem'', or ''pip install git+https://github.com/fmaussion/salem.git'' , it can work, but ''print(oggm.utils.show_versions())''  also shows: salem: None!  However, ''conda list'' show it already be installed.
Then when I use ''pytest --pyargs oggm'', the result is same as before.**

(oggm_env) pxr@LAPTOP-NLU90O0E:~$ conda list
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
rtree                     0.9.7            py38h02d302b_2    conda-forge
**salem                     0.3.4-1-gd3f2e5e          pypi_0    pypi**
scikit-image              0.18.2           py38h1abd341_0    conda-forge
scipy                     1.7.1            py38h56a6a73_0    conda-forge
send2trash                1.7.1              pyhd8ed1ab_0    conda-forge

**Comment by TimoRoth** [comment]
Can you manually import salem when running a python shell?
Are you absolutely sure pytest and the python you invoke come from the same environment you installed your packages in?

**Comment by pxr1997** [comment]
**thanks for your help! when I ''import salem'', it surely doesn't work.  I do  ''conda install -c conda-forge descartes'' according to its hints. I want to install dev version, again i do ''import oggm '' and  ''print(oggm.utils.show_versions())'' it shows as follows:**
# OGGM environment:
## System info:
    python: 3.8.10.final.0
    python-bits: 64
    OS: Linux
    OS-release: 5.4.72-microsoft-standard-WSL2
    machine: x86_64
    processor: x86_64
## Packages info:
    oggm: 1.5.1.dev9+g42ded70
    numpy: 1.21.1
    scipy: 1.7.1
    pandas: 1.3.1
    geopandas: 0.9.0
    netCDF4: 1.5.7
    matplotlib: 3.4.2
    rasterio: 1.2.6
    fiona: 1.8.20
    pyproj: 3.1.0
    shapely: 1.7.1
    xarray: 0.19.0
    dask: 2021.07.2
    salem: 0.3.4
    OGGM git identifier: 8150016b2e8c2983c01655fd2163346033b3a461

**I notcie salem:0.3.4, but I see other's is 0.3.4.1-, does it result to bad effect?  when I run ''pytest'', it shows as follows:**
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestWorkflowTools::test_demo_glacier_id - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestWorkflowTools::test_download_ref_tstars - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestWorkflowTools::test_glacier_characs - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestWorkflowTools::test_leclercq_data - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromTar::test_to_and_from_tar_string - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_corrupted_file - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_start_from_level_1 - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_start_from_level_1_str - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_start_from_level_2 - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_start_from_level_3 - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestStartFromOnlinePrepro::test_start_from_level_4 - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestPreproCLI::test_source_run - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestPreproCLI::test_start_from_prepro - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_alaska - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_arcticdem - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_aster - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_aw3d30 - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_copdem - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_dem3 - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_dl_verify - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_gimp - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_github_no_internet - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_mapzen - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_nasadem - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_ramp - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_rema - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_rgi - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_rgi_intersects - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_srtm - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_tandem - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_tandem_invalid - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_asterzone - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_copdemzone - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_dem3_viewpano_zone - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_download_demo_files - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_file_extractor - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_find_dem_zone - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_is_dem_source_available - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_lrufilecache - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_lruhandler - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_mapzen_zone - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_nasazone - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_srtmzone - tables.exceptions.HDF5ExtError: HDF5 error back trace
FAILED anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_utils.py::TestDataFiles::test_tandemzone - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestInitPresentDayFlowline::test_init_present_time_glacier - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestInitPresentDayFlowline::test_present_time_glacier_massbalance - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestInitFlowlineOtherGlacier::test_define_divides - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_past_mb_model - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_repr - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_prcp_fac_temp_bias_update - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_glacierwide_mb_model[PastMassBalance] - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_glacierwide_mb_model[ConstantMassBalance] - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_glacierwide_mb_model[RandomMassBalance] - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_constant_mb_model - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_random_mb - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_random_mb_unique - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_uncertain_mb - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestMassBalanceModels::test_mb_performance - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_constant_bed] - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_width_bed] - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_noisy_bed] - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_bumpy_bed] - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_parabolic_bed] - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_trapezoidal_bed] - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_flowline_to_dataset[dummy_mixed_bed] - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_model_to_file - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_gdir_copy - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIO::test_hef - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIdealisedInversion::test_inversion_rectangular - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIdealisedInversion::test_inversion_trapeze - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIdealisedInversion::test_inversion_parabolic - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIdealisedInversion::test_inversion_parabolic_sf_adhikari - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIdealisedInversion::test_inversion_parabolic_sf_huss - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIdealisedInversion::test_inversion_noisy - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIdealisedInversion::test_inversion_tributary - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIdealisedInversion::test_inversion_non_equilibrium - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestIdealisedInversion::test_inversion_and_run - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestHEF::test_start_from_spinup - tables.exceptions.HDF5ExtError: HDF5 error back trace
ERROR anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/tests/test_models.py::TestHEF::test_start_from_spinup_minmax_ys - tables.exceptions.HDF5ExtError: HDF5 error back trace
======================================================================= 144 failed, 23 passed, 130 skipped, 3 warnings, 35 errors in 50.88s =======================================================================

it mostly reminder ''hdf5ExError''? how to cope with it? thanks
