### ISSUE TITLE
Monthly Mass Balance - Error with fl_id

### ISSUE THREAD

**Issue by kimcholi** [OGGM/oggm#1277]
Hello there,
I am currently trying to plot the monthly mass balance of certain glaciers on OGGM. My first issue is that I do not 100% understand what the parameter fl_id means. If anyone could explain it to me, that would be amazing. Thank you!

This is the code I wrote:

`#Locals`
`#import the necessary libs`
`import matplotlib.pyplot as plt`
`import pandas as pd`
`import xarray as xr`
`import numpy as np`

`import os`
`import netCDF4`
`import logging`

`import oggm`
`from oggm import cfg, utils, workflow, tasks, graphics`
`from oggm.core import massbalance, flowline`
`from oggm.workflow import execute_entity_task`

`cfg.initialize(logging_level='WARNING')`
`cfg.PARAMS['use_multiprocessing'] = True`

`WORKING_DIR = '/Volumes/ExFAT/SMB'`
`cfg.PATHS['working_dir'] = WORKING_DIR`
`cfg.PARAMS['border']=80`

`# Initialize glacier directories`
`gdir=workflow.init_glacier_directories(['RGI60-17.14203'], from_prepro_level=3) [0]`
`tasks.init_present_time_glacier(gdir)`

`# Get the calibrated mass-balance model - the default is to use OGGM's "PastMassBalanceModel"`
`mbmod = massbalance.MultipleFlowlineMassBalance(gdir) #MultipleFlowlineMassBalance model`

`# Compute the specific MB for this glacier for a run of x year`
`fls_month = gdir.read_pickle('model_flowlines')`
`height = 4449`
`years_month = 1995`
`mb_month = mbmod.get_monthly_mb(heights=height, year=years_month, fl_id=fls_month.index) #heights required !`

`plt.plot(years_month, mb_month);`
`plt.ylabel('Specific MB (mm w.e.)'); #mm water equivalent`
`plt.xlabel('Year');`

Unfortunately I get the following error notification: 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-33-c665e94f130d> in <module>
     10 height = 4449
     11 years_month = 1995
---> 12 mb_month = mbmod.get_monthly_mb(heights=height, year=years_month, fl_id=fls_month.index) #heights required !
     13 
     14 plt.plot(years_month, mb_month);

/opt/anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/core/massbalance.py in get_monthly_mb(self, heights, year, fl_id, **kwargs)
   1180                              'MultipleFlowlineMassBalance!')
   1181 
-> 1182         return self.flowline_mb_models[fl_id].get_monthly_mb(heights,
   1183                                                              year=year,
   1184                                                              **kwargs)

TypeError: list indices must be integers or slices, not builtin_function_or_method
```

I have tried to use `mb_month = mbmod.get_monthly_mb(heights=height, year=years_month, fl_id=None)`. The error for this was: ValueError: `fl_id is required for MultipleFlowlineMassBalance!`

And I have also already tried to use `mb_month = mbmod.get_monthly_mb(heights=height, year=years_month, fl_id=True)`. The error notification this time was: ValueError: `TypeError: object of type 'int' has no len()`

Last but not least I tried: `mb_month = mbmod.get_monthly_mb(heights=height, year=years_month, fl_id=fls_month)`. This time the error notification stated : `TypeError: list indices must be integers or slices, not list`.

I would appreciate it very much if someone could help me out with this one. Thank you very much!

I hope you all are having a wonderful weekend! :)

**Comment by fmaussion** [comment]
Thanks for the question. `fl_id` is required for the `MultipleFlowlineMassBalance` model when using the preprocessed directories with multiple flowlines. It's an integer between `0` and `len(fls_month)-1` indicating which flowline to look at.

The reason is that for multiple flowlines (one of the two ways to represent glaciers in OGGM), each flowline has its own calibrated parameters. 

If you tell us more about what you'd like to do we might provide more support about the best strategy to reach your goal.

**Comment by kimcholi** [comment]
Thank you for explaining `fl_id` to me. 

With this code I am trying to plot the monthly mass balance of different glaciers with seasonal data. Getting the annual mass balance and plotting it worked fine but now I am trying to do it monthly. But unfortunately it didn't work the way I hoped it would. 

I hope this information might help you in order to provide me some advice on how to plot the monthly mass balance of specific glaciers. 

Have a good week! Thank you :)

**Comment by kimcholi** [comment]
This is the whole code I wrote for the annual and monthly mass balance plotting:

```
#Locals
#import the necessary libs
import matplotlib.pyplot as plt
import pandas as pd
import xarray as xr
import numpy as np
import os
import netCDF4
import logging
import oggm
from oggm import cfg, utils, workflow, tasks, graphics
from oggm.core import massbalance, flowline
from oggm.workflow import execute_entity_task
cfg.initialize(logging_level='WARNING')
cfg.PARAMS['use_multiprocessing'] = True
WORKING_DIR = '/Volumes/ExFAT/SMB'
cfg.PATHS['working_dir'] = WORKING_DIR
cfg.PARAMS['border']=80
# Initialize glacier directories
gdir=workflow.init_glacier_directories(['RGI60-17.14203'], from_prepro_level=3) [0]
tasks.init_present_time_glacier(gdir)
# Get the calibrated mass-balance model - the default is to use OGGM's "PastMassBalanceModel"
mbmod = massbalance.MultipleFlowlineMassBalance(gdir) #MultipleFlowlineMassBalance model
# Compute the specific MB for this glacier for a run of x year
fls = gdir.read_pickle('model_flowlines')
years = np.arange(1990, 1992)
mb_ts = mbmod.get_specific_mb(fls=fls, year=years)
plt.plot(years, mb_ts);
plt.ylabel('Specific MB (mm w.e.)'); #mm water equivalent
plt.xlabel('Year');
# Plot the measured data
# Get the reference mass-balance from the WGMS
ref_df = gdir.get_ref_mb_data(1999,2000) #choose length of time
# Get OGGM MB at the same dates
ref_df['OGGM'] = mbmod.get_specific_mb(fls=fls, year=ref_df.index.values)
# Plot
plt.plot(ref_df.index, ref_df.OGGM, label='OGGM'); #modelled data
plt.plot(ref_df.index, ref_df.ANNUAL_BALANCE, label='WGMS'); #measured data
plt.ylabel('Specific MB (mm w.e.)'); plt.legend();
plt.xlabel('Year');
# Initialize glacier directories
gdir=workflow.init_glacier_directories(['RGI60-17.14203'], from_prepro_level=3) [0]
tasks.init_present_time_glacier(gdir)
# Get the calibrated mass-balance model - the default is to use OGGM's "PastMassBalanceModel"
mbmod = massbalance.MultipleFlowlineMassBalance(gdir) #MultipleFlowlineMassBalance model
# Compute the specific MB for this glacier for a run of x year
fls = gdir.read_pickle('model_flowlines')
height = 4449
years = np.arange(1991.1, 1991.2)
mb_ts = mbmod.get_monthly_mb(heights=height, year=years, fl_id=fls) #heights required !
plt.plot(years, mb_ts);
plt.ylabel('Specific MB (mm w.e.)'); #mm water equivalent
plt.xlabel('Year')
```

**Comment by Keeptg** [comment]
It seems that you'd like to get the annual and monthly average mass balance over a glacier. For the annual mass balance, as you already know, the `mbmod.get_specific_mb()` function work well. While for the monthly average mass balance, it seems there is not a function like `mbmod.get_specific_mb()` done. In fact, there was already a [`monthly_step`](https://github.com/OGGM/oggm/blob/94bd76b4015f2a86d292562e9e24939210eec63a/oggm/core/massbalance.py#L1367) argument provided, but it was not finished yet.

In your code, the function `mbmod.get_monthly_mb()` will return a mass balance profile instead of a average mass balance values. To make this function work successfully, a list instead a number should be passed to `heights` argument, for example setting `height=range(4440, 4449)`. Besides, the `fl_id` argument in this function should be set as a integer (`fl_id=0` will get the longest flowline).

**Comment by kimcholi** [comment]
Thank you for your help. It solved previous error! :)

Now I tried to plot the monthly mass balance but unfortunately it is not working. 

With the following code: 
```
# Initialize glacier directories
gdir=workflow.init_glacier_directories(['RGI60-17.14203'], from_prepro_level=3) [0]
tasks.init_present_time_glacier(gdir)

# Get the calibrated mass-balance model - the default is to use OGGM's "PastMassBalanceModel"
mbmod = massbalance.MultipleFlowlineMassBalance(gdir) #MultipleFlowlineMassBalance model

# Compute the specific MB for this glacier for a run of x year
#fls_month = gdir.read_pickle('model_flowlines')
height = np.arange(4440,4449)
years_month = 1994
fl_id_month=0
mb_month = mbmod.get_monthly_mb(heights=height, year=years_month, fl_id=fl_id_month) #heights required !

print(years_month)
print(mb_month)

plt.plot(years_month, mb_month)
plt.ylabel('Specific MB (mm w.e.)') #mm water equivalent
plt.xlabel('Year')
```
The output is: 
```
1994
[8.75128256e-08 8.75128256e-08 8.75128256e-08 8.75128256e-08
 8.75128256e-08 8.75128256e-08 8.75128256e-08 8.75128256e-08
 8.75128256e-08]
```
I get the `ValueError: x and y must have the same first dimenstion, but have shapes (1,) and (9,). 

Then I changed the code to: 
```
# Initialize glacier directories
gdir=workflow.init_glacier_directories(['RGI60-17.14203'], from_prepro_level=3) [0]
tasks.init_present_time_glacier(gdir)

# Get the calibrated mass-balance model - the default is to use OGGM's "PastMassBalanceModel"
mbmod = massbalance.MultipleFlowlineMassBalance(gdir) #MultipleFlowlineMassBalance model

# Compute the specific MB for this glacier for a run of x year
#fls_month = gdir.read_pickle('model_flowlines')
height = np.arange(4440,4449)
years_month = 1994
fl_id_month=0
mb_month = mbmod.get_monthly_mb(heights=height, year=years_month, fl_id=fl_id_month) #heights required !

print(years_month)
print(mb_month)

x=years_month
y=np.array([mb_month])
plt.plot(x, y)
plt.ylabel('Specific MB (mm w.e.)') #mm water equivalent
plt.xlabel('Year')
```

There is luckily no error coming up. But the plot is empty since there is no graph and the labelling of the x axis shows 1900 to 2100 instead of 1994. 

I'm fairly new to OGGM and plotting with python. I would appreciate if anyone can further help me! And already thank you for the given advices :)
