### ISSUE TITLE
Global Tasks

### ISSUE THREAD

**Issue by MBeedle** [OGGM/oggm#1300]
Hi, OGGM Team:

I'm new to OGGM and am finding your tutorials super helpful. I am struggling, however, with moving from entity tasks (as in your tutorials) to global tasks. In particular, I want to model glacier recession and hydrologic impacts to 2100 for all glaciers in sub-drainages of interest (groupings of ~10 to 100 individual glaciers). 

Would you help me (or guide me to the resources) on how to compile and plot data for more than one glacier? It might be helpful to other new users to have an example of how to do this in a tutorial, or at the end of one of your existing tutorials. 

Here is what I'm working with for 21 glaciers in a small watershed using your 'OGGM With GCM Data' tutorial as a template. At the final step I can output individual plots for each of the 21 glaciers but want to do this for the 21 glaciers as a whole.

Your help is much appreciated! Sorry for what is most likely an issue my novice Python abilities.

from oggm import cfg, utils
cfg.initialize(logging_level='WARNING')

cfg.PARAMS['use_multiprocessing'] = True

cfg.PARAMS['continue_on_error']

cfg.PARAMS['border']

cfg.PARAMS['has_internet']

import os
from oggm import workflow, tasks

cfg.PATHS['working_dir'] = utils.gettempdir(dirname='Surprise_Creek', reset=True)
cfg.PATHS['working_dir']

rgi_ids = ['RGI60-01.04449', 'RGI60-01.04463', 'RGI60-01.04458', 'RGI60-01.04486', 'RGI60-01.04451', 'RGI60-01.04437','RGI60-01.04440', 
           'RGI60-01.04471', 'RGI60-01.04448', 'RGI60-01.04428', 'RGI60-01.04453', 'RGI60-01.04802', 'RGI60-01.04491', 'RGI60-01.04474',
           'RGI60-01.04494', 'RGI60-01.04782', 'RGI60-01.04795', 'RGI60-01.04814', 'RGI60-01.04417', 'RGI60-01.04412', 'RGI60-01.04409']  
# All RGI glaciers in Surprise Cr. watershed

# Libs
import xarray as xr
import matplotlib.pyplot as plt

# Locals
import oggm.cfg as cfg
from oggm import utils, workflow, tasks
from oggm.core import gcm_climate

# Go - get the pre-processed glacier directories
gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=5)

ds = utils.compile_run_output(gdirs, input_filesuffix='_historical')
ds.volume.plot(hue='rgi_id');

gdirs[0].rgi_date

ds.time[-1]

workflow.execute_entity_task(tasks.run_from_climate_data, gdirs, 
                             output_filesuffix='_my_spinup',  # to use the files as input later on
                            );
ds = utils.compile_run_output(gdirs, input_filesuffix='_my_spinup')
ds.volume.plot(hue='rgi_id');

ds.length.plot(hue='rgi_id');

bp = 'https://cluster.klima.uni-bremen.de/~oggm/cmip5-ng/pr/pr_mon_CCSM4_{}_r1i1p1_g025.nc'
bt = 'https://cluster.klima.uni-bremen.de/~oggm/cmip5-ng/tas/tas_mon_CCSM4_{}_r1i1p1_g025.nc'
for rcp in ['rcp26', 'rcp45', 'rcp60', 'rcp85']:
    # Download the files
    ft = utils.file_downloader(bt.format(rcp))
    fp = utils.file_downloader(bp.format(rcp))
    # bias correct them
    workflow.execute_entity_task(gcm_climate.process_cmip_data, gdirs, 
                                 filesuffix='_CCSM4_{}'.format(rcp),  # recognize the climate file for later
                                 fpath_temp=ft,  # temperature projections
                                 fpath_precip=fp,  # precip projections
                                 );

for rcp in ['rcp26', 'rcp45', 'rcp60', 'rcp85']:
    rid = '_CCSM4_{}'.format(rcp)
    workflow.execute_entity_task(tasks.run_from_climate_data, gdirs, ys=2020, 
                                 climate_filename='gcm_data',  # use gcm_data, not climate_historical
                                 climate_input_filesuffix=rid,  # use the chosen scenario
                                 init_model_filesuffix='_historical',  # this is important! Start from 2020 glacier
                                 output_filesuffix=rid,  # recognize the run for later
                                );

f, (ax1) = plt.subplots(1, figsize=(8, 4))
for rcp in ['rcp26', 'rcp45', 'rcp60', 'rcp85']:
    rid = '_CCSM4_{}'.format(rcp)
    ds = utils.compile_run_output(gdirs, input_filesuffix=rid)
    ds.isel(rgi_id=0).volume.plot(ax=ax1, label=rcp); plt.legend();

**Comment by nchampollion** [comment]
Hi, you an use numpy (python module) to calculate the mean or the sum of all your glacier outputs, i.e. your _ds_ data (volume, are, length) that you calculated using compile_run_output in order to plot them later on:
    - https://numpy.org/doc/stable/reference/generated/numpy.sum.html
    - https://numpy.org/doc/stable/reference/generated/numpy.mean.html
  
Hope that helps !

**Comment by fmaussion** [comment]
@MBeedle thanks for reaching out.

When we work with many glaciers we usually write the output to a netcdf file with `compile_run_output`. In the script we get the resulting xarray dataset out of it:

`ds = utils.compile_run_output(gdirs, input_filesuffix=rid)`

But as a user you can also write the file to the path that suits you ([path](https://docs.oggm.org/en/stable/generated/oggm.global_tasks.compile_run_output.html#oggm.global_tasks.compile_run_output) kw argument).

Xarray datasets are very powerful tools to aggregate the outputs, for example to compute sums or other things.

**Comment by MBeedle** [comment]
Thanks for your help. My struggle is with plotting the compiled volume change data for my group of glaciers. This returns a plot for one of the 21 glaciers in a particular subdrainage:

f, (ax1) = plt.subplots(1, figsize=(8, 4))
for rcp in ['rcp26', 'rcp45', 'rcp60', 'rcp85']:
rid = 'CCSM4{}'.format(rcp)
ds = utils.compile_run_output(gdirs, input_filesuffix=rid)
ds.isel(rgi_id=0).volume.plot(ax=ax1, label=rcp); plt.legend();

I want a similar plot but for volume change of all 21 glaciers combined. I know that ds.isel(rgi_id=0) is selecting the first of the 21 glaciers. Will you help with plotting the summed volume change?

**Comment by pat-schmitt** [comment]
Hi @MBeedle ,
if you want to plot the complete volume change you can use `ds.sum('rgi_id').volume.plot(ax=ax1);`
