### ISSUE TITLE
There is something wrong when I install oggm by the environment.yml file .

### ISSUE THREAD

**Issue by FANSCRAZY** [OGGM/oggm#1305]
Yestoday when I try to re-install  the oggm by the environment.yml file,there are always 3 pakages  went wrong . 
the error I put on the following. if can , I hope you can giave me a new environment.yml file to install the oggm correctly!

_Preparing transaction: done
Verifying transaction: done
Executing transaction: - Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

done
Installing pip dependencies: | Ran pip subprocess with arguments:
['/home/caixingran/anaconda3/envs/oggm_env/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/caixingran/condaenv.jhzpkwhm.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/fmaussion/salem.git (from -r /home/caixingran/condaenv.jhzpkwhm.requirements.txt (line 4))
  Cloning https://github.com/fmaussion/salem.git to /tmp/pip-req-build-w5_dmag5
  Resolved https://github.com/fmaussion/salem.git to commit 8374b91d2bdcc44866e458c6a53530c4251b9600
Collecting git+https://github.com/OGGM/pytest-mpl (from -r /home/caixingran/condaenv.jhzpkwhm.requirements.txt (line 5))
  Cloning https://github.com/OGGM/pytest-mpl to /tmp/pip-req-build-ivlrikt4

Pip subprocess error:
  Running command git clone -q https://github.com/fmaussion/salem.git /tmp/pip-req-build-w5_dmag5
  Running command git clone -q https://github.com/OGGM/pytest-mpl /tmp/pip-req-build-ivlrikt4
  fatal: unable to access 'https://github.com/OGGM/pytest-mpl/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
WARNING: Discarding git+https://github.com/OGGM/pytest-mpl. Command errored out with exit status 128: git clone -q https://github.com/OGGM/pytest-mpl /tmp/pip-req-build-ivlrikt4 Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q https://github.com/OGGM/pytest-mpl /tmp/pip-req-build-ivlrikt4 Check the logs for full command output.

failed

CondaEnvException: Pip failed_

**Comment by TimoRoth** [comment]
That's either an issue with your system, in that it's not properly able 
to initiate a TLS connection to Github, or Github had a temporary hickup 
and things just work again by now.
