### ISSUE TITLE
ELA diagnostics

### ISSUE THREAD

**Issue by anoukvlug** [OGGM/oggm#1328]
I like to have the ELA as an output in OGGM. However with PR #1145 it got removed, because it was not a real output of the simulation. The suggestion was to bring it back to OGGM in a different format. e.g. a variable that can separately be computed.

Hereby I would like to start that conversation again :)  

(I wouldn't mind making a PR to solve this issue.)

**Comment by anoukvlug** [comment]
I have now a function that roughly does what you suggested. I could make a PR of it. However I'm not sure what would be the most logical place to put it... Does anyone have a suggestion?

**Comment by fmaussion** [comment]
I think `utils._workflow` would be best. Thanks!

**Comment by anoukvlug** [comment]
Thanks for the suggestion :)

**Comment by anoukvlug** [comment]
`global_tasks.compile_ela` has been implemented (see PR #1333). Therefore this issue can be closed.
