### ISSUE TITLE
Add rioxarray as dependency

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1334]
xarray's `open_rasterio` is deprecated in favor of https://github.com/corteva/rioxarray :

```
 oggm/tests/test_shop.py::Test_bedtopo::test_add_consensus
  /tmp/oggm_git/oggm/tests/test_shop.py:555: DeprecationWarning: open_rasterio is Deprecated in favor of rioxarray. For information about transitioning, see: https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html
    with xr.open_rasterio(gdir.get_filepath('consensus')) as ds:
```

We use open_rasterio in the tests and the documentation / tutorials. rioxarray is a useful package and is pure python, it should be added to our dependencies. Once this is done I'll update the docs. A long list of TODOs:

- [x] Docker builds 
- [ ] r2d 
- [x] tutorials builds
- [ ] oggm-edu-notebook builds 
- [ ] something I forgot?

cc @TimoRoth

**Comment by TimoRoth** [comment]
I tried adding it, and it exploded quite horribly.
Will have to wait until https://github.com/pydata/xarray/issues/5944 is resolved and a fix released.
