### ISSUE TITLE
PyTables release problem

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1336]
see https://github.com/PyTables/PyTables/issues/826 

As of https://github.com/OGGM/oggm/pull/1335 , pytables is now the largest contributor of deprecation warnings in the test suite - it's probably worth investigating if we can:
- use another package / format (unlikely without breaking stuff)
- build it ourselves in the images

cc @TimoRoth

**Comment by TimoRoth** [comment]
On 08.11.2021 17:06, Fabien Maussion wrote:
> see PyTables/PyTables#826 <https://github.com/PyTables/PyTables/issues/826>
> 
> As of #1335 <https://github.com/OGGM/oggm/pull/1335> , pytables is now 
> the largest contributor of deprecation warnings in the test suite - it's 
> probably worth investigating if we can:
> 
>   * use another package / format (unlikely without breaking stuff)
>   * build it ourselves in the images
> 
> cc @TimoRoth <https://github.com/TimoRoth>

The docker images already build everything internally.
Use of wheels is explicitly disabled.

If I understand that issue right, I'd just have to point it to git 
master for pytables?

**Comment by fmaussion** [comment]
> If I understand that issue right, I'd just have to point it to git master for pytables?

Yes

**Comment by TimoRoth** [comment]
On 08.11.2021 18:09, Fabien Maussion wrote:
>     If I understand that issue right, I'd just have to point it to git
>     master for pytables?
> 
> Yes

Just did that change.
New images with that are building.
