### ISSUE TITLE
Stopping criterion causes FloatingPointError 

### ISSUE THREAD

**Issue by juliaeis** [OGGM/oggm#1344]
Hey, 
I used the new stopping criterion for an equilibrium run and want to use the output as new initial state for the next run by setting the `init_model_filesuffix`  in `tasks.run_random_climate`. 
As the FileModel contains Nan's after the criterion is satisfied, I get an FloatingPointError (NaN in numerical solution, at year: 0.0) as the model state at the last year is Nan. I can't really use the `init_model_yr` option, because it is a different year for each run and glacier. 

I see 2 possible options to solve this issue (I can do this, but would like to have your opinion first @fmaussion) : 
i) we replace the in the FileModel class `self.last_yr = float(ds.time[-1])` by
   `self.last_yr = float(ds.ts_section.dropna(dim='time').time[-1])`
ii) we add in `fowline_model_run()` the option that `init_model_yr` can also be a str (e.g. 'no_nan') and then set init_model_yr to the last entry without Nan's. 

Do you have any preference ?

**Comment by fmaussion** [comment]
Also relevant for @Holmgren825
