### ISSUE TITLE
How to get the original data of the result (not the finished graph)？

### ISSUE THREAD

**Issue by zhaocaicai252** [OGGM/oggm#1355]
Hello, Mr. Developer, how can I get the output data of some modules in the OGGM?
Taking [Ice thickness inversion](https://oggm.org/tutorials/stable/notebooks/inversion.html) as an example, what do I need to do to obtain raster data of the glacier thickness distribution as shown in the figure below?
![inversion_36_0](https://user-images.githubusercontent.com/75459436/147870226-08cba507-584e-45a1-bdec-044fc6ff0607.png)

**Comment by Keeptg** [comment]
Hello! Most of the available raster data are saved in the `gridded_data.nc` file in the glacier directory. The glacier directory path can be get with `gdir.dir`. Also, you can use `gdir.get_filepath('gridded_data')` to get the path of `gridded_data.nc` file directly. 

OGGM also provides a function to write the raster data in `geotiff` format. See the function[ `tasks.gridded_data_var_to_geotiff()`](https://github.com/OGGM/oggm/blob/61ee1fbcf1848816d9e8c1cc87ef4d3f0ede2285/oggm/core/gis.py#L1512) and the [tutorial](https://oggm.org/tutorials/stable/notebooks/inversion.html) for more details.

**Comment by zhaocaicai252** [comment]
Thank you very much for your prompt reply, I will try it later. And happy new year!

**Comment by zhaocaicai252** [comment]
Thank you very much for your prompt reply, I will try it later. And happy new year!

> Hello, glad to see the first question in 2022!
> 
> Most of the available raster data are saved in the `gridded_data.nc` file in the glacier directory. The glacier directory path can be gotten with `gdir.dir`. Also, you can use `gdir.get_filepath('gridded_data')` to get the path of `gridded_data.nc` file directly.
> 
> OGGM also provides a function to write the raster data in `geotiff` format. See the function[ `tasks.gridded_data_var_to_geotiff()`](https://github.com/OGGM/oggm/blob/61ee1fbcf1848816d9e8c1cc87ef4d3f0ede2285/oggm/core/gis.py#L1512) and the [tutorial](https://oggm.org/tutorials/stable/notebooks/inversion.html) (next line of the picture you shown here in the tutoral) for more details.
