### ISSUE TITLE
COPDEM90 and COPDEM30

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1362]
For RGI7 I think we really need to support COPDEM30 (I think that the idea will be to use it for all glaciers with a spatial resolution < 90 m). At the same time, we need to rename COPDEM to COPDEM90.

I just had a look today at the download instructions, etc, and needless to say it's a bit of a maze for me.

@matthiasdusch I would completely understand if you can't or don't want to do it, but would you be interested in having a look at that?

related: https://github.com/OGGM/oggm/issues/1074

**Comment by matthiasdusch** [comment]
It is a maze! But since I made it through it once, I am happy to try again ;-)
