### ISSUE TITLE
Use pooch to download stuff?

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1365]
https://www.fatiando.org/pooch/latest/about.html

**Comment by TimoRoth** [comment]
Hmm, I'm not sure.
It sounds like we have by now replicated all the primary features it has.
Switching to it now would for one come with massive code changes, probably resulting in a simplification, but:

We'd need to move the list of file hashes into the OGGM codebase. If some of the files then randomly changes hash (has happened multiple times already, where some archives got re-packed without changing the data), you need to update oggm to make it work again.

It also does not at all use the same cache structure we do. So we'd either need to kill the cache for all old OGGM versions, making them hard to impossible to use on the Cluster. Or we'd need to duplicate the entire cache in both formats, doubling storage use.

Would have been nice if we'd have used it from the beginning for sure.

**Comment by fmaussion** [comment]
Yes I agree - they are around since 2020 only though, so no regrets ;-)
