### ISSUE TITLE
Use pandas to handle gdirs instead of lists

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#137]
I see myself very often selecting glacier directories from the list, e.g.:

```
[gd for gd in gdirs if 'Columbia' in gd.name]
```

All these operations would be much easier if we had a Series (or even a Dataframe) of glacier directories.

**Comment by shreab373** [comment]
hello, i'm new could you guide me as to what exactly needs to be done here? thanks.

**Comment by fmaussion** [comment]
Dear @shreab373 , thanks for your interest in OGGM!

If I am allowed to ask: are you a climate scientist or a glaciologist? Let me know if I'm mistaken here, but unless you plan to use OGGM for your own work it's probably not worth to spend your time on it. OGGM probably isn't the most suitable project for a general open-source contribution since it has a specialized audience.

**Comment by shreab373** [comment]
@fmaussion haha, thank you for letting me knows so soon, i was hunting for issue like most new contributors do!
