### ISSUE TITLE
About the DEM in inversion

### ISSUE THREAD

**Issue by muzi2021** [OGGM/oggm#1371]
How can I know which DEM is used in the ice thickness inversion?
 
![image](https://user-images.githubusercontent.com/77234985/152816981-4717235a-c050-4b76-b0bd-805454234e3a.png)

**Comment by anoukvlug** [comment]
You can find the source of the DEM in the `diagnostics.json` file in the folder of the respective glacier. Does that answer your question @muzi2021 ?

**Comment by fmaussion** [comment]
Feel free to reopen id your question is still valid
