### ISSUE TITLE
Better document API on init_glacier_directories

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1387]
See slack thread with Jordi

**Comment by fmaussion** [comment]
Also better document GlacierDirectory API for our Julia users (@JordiBolibar  :wink: )

**Comment by fmaussion** [comment]
Addressed in https://github.com/OGGM/oggm/pull/1396 

altogehter API doc could need some love

**Comment by JordiBolibar** [comment]
Great, thanks so much!
