### ISSUE TITLE
run_dynamic_spinup do not take some cfg flags into account

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/oggm#1388]
I just realized (thanks to @minallah) that the `run_dynamic_spinup` function takes certain cfg flags not into account. In particular this are `cfg.PARAMS['use_inversion_params_for_run']` and `cfg.PARAMS['store_fl_diagnostics']`. 

I will add them for now, but in the long term it maybe would be a good idea to create a separate function (something like preprocess_flowline_run), as I am just copying code from the `flowline_model_run` function and so upcoming changes (or other things I have forgotten in the dynamic spinup) only need to be done at one place in the code. Although this new function would look exactly the same as the `flowline_model_run` one up to the actual evolution_model run.

**Comment by fmaussion** [comment]
This can be closed now? Reopen if needed @pat-schmitt
