### ISSUE TITLE
Can oggm output future glacier area or volume changes in the form of raster data?

### ISSUE THREAD

**Issue by zhaocaicai252** [OGGM/oggm#1391]
Hello, When I followed the Run OGGM with GCM data tutorial to simulate the future changes of the glacier, I found that the simulation results of the changes in the area and volume of the glacier in different climate models in the future could not visually reflect the changes in the glacier. I would like to know if oggm can output the future glacier area or volume change in the form of raster data?
As shown in the figure, it is the area change of Ngojumba Glacier output from the model_diagnostics_CCSM4_rcp26.nc file.
![QQ截图20220308161209](https://user-images.githubusercontent.com/75459436/157195209-31284b88-3ddf-435e-9dc5-538410a97e9f.png)

**Comment by fmaussion** [comment]
I'm sorry but this is currently not possible (see https://github.com/OGGM/oggm/issues/1192 for a discussion about possible solution). OGGM is not a distributed model, and any solution would have to be some kind of statistical trick. Help welcome!

If you use the multiple flowlines data model, you can make plots such as these here though: https://oggm.org/tutorials/master/notebooks/getting_started.html#simulations
