### ISSUE TITLE
what are "fpath_temp","fpath_precc", and "fpath_precl" represent in process_cesm_data( ) ? 

### ISSUE THREAD

**Issue by yangmin27** [OGGM/oggm#1393]
1. I want to use the function of process_cesm_data( ), not sure what are these mean?
2.  when I go here, lon = gdir.cenlon , it throw me error:  'list' object has no attribute 'cenlon'.  my gdir type is still the list? what should I do about it ?

**Comment by yangmin27** [comment]
oh, so in GCM the prc is precc here. I want prepare my own GCM which I downloaded for run the oggm model, can u give me some advise? I asked similar question before, then I understand that I should maybe use process_cesm_data and process_gcm_data function to process GCM, it is like a downscale process... but still no idea how to prepare...

**Comment by anoukvlug** [comment]
I think you're referring to your question in #1221 

I don't know what type of data you have, but if it isn't cesm or cmip data, you will need use the `process_gcm_function` and to do some coding to prepare your data to the required format. You could have a look at the `process_cesm_data`,  `process_cmip_data` and `process_lmr_data` functions as examples, as they also prepare climate data for the `process_gcm_data` function.

I'm not sure if this answers you're question. If not, it would be helpful if you describe your issue more precisely.

**Comment by yangmin27** [comment]
yes yes  . thank you. I am working on it .. little bit tricky.
