### ISSUE TITLE
About 'compute_velocities'

### ISSUE THREAD

**Issue by nova321** [OGGM/oggm#1394]
About OGGM velocity simulation part of the model, I have some questions：
1.How to open and visualize display flowline velocity simulation results? (Surface velocities along the flowlines from inverted ice thickness.)
2.How to simulate the velocities for the entire glacier, and convert the results to TIF format?

**Comment by fmaussion** [comment]
About 1: this tutorial might be useful? https://oggm.org/tutorials/master/notebooks/ingest_gridded_data_on_flowlines.html?highlight=velocity

About 2: unfortunately this is not possible. OGGM is a flowline model, we do not use gridded format internally. See:
- https://github.com/OGGM/oggm/issues/1391
- https://github.com/OGGM/oggm/issues/1192

**Comment by fmaussion** [comment]
Feel free to reopen id your question is still valid
