### ISSUE TITLE
possible divide by zero in dynamical spinup

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1397]
@pat-schmitt this line here might create a divide by zero:

https://github.com/OGGM/oggm/blob/08a1b1a303d648f190603dcb38840c5bfaa90229/oggm/core/flowline.py#L4032-L4033

It would be good to add a check and be explicit about the consequences when this happens

**Comment by pat-schmitt** [comment]
Yes this is included in the function:
Here is the handling/raising the error message: https://github.com/OGGM/oggm/blob/master/oggm/core/flowline.py#L4120
And here it is also included in the tests: https://github.com/OGGM/oggm/blob/master/oggm/tests/test_models.py#L3410

**Comment by fmaussion** [comment]
OK weird because the tests still raise a divide by zero warning

**Comment by pat-schmitt** [comment]
Ah ok, yes the division through zero is executed and only afterwards it is checked if the result is INF. But I could change this, so that it is checked if it is zero before the calculation is executed.

**Comment by fmaussion** [comment]
yes that's better - or silence the warning locally (I do it sometimes as well)

**Comment by pat-schmitt** [comment]
ok, I will include this in the open PR https://github.com/OGGM/oggm/pull/1392
