### ISSUE TITLE
Millan et al. 2022 in OGGM-shop

### ISSUE THREAD

**Issue by bearecinos** [OGGM/oggm#1401]
cc. @nchampollion @JordiBolibar @fmaussion 

Hello ... 

So I started playing with this data but like I explained before I did not manage to do the automatic download of the data and the paring of each glacier to a tif from Millan et. al 2022.

How to process the data in the same style as the itslive data can be found here (probably needs improvement):
https://gist.github.com/bearecinos/26a828f8b0e1d0b4bff19bd5192deb54

The relevant function is in here:
https://github.com/bearecinos/k_calibration_greenland_jog/blob/k_new_oggm/k_tools/utils_thick.py#L215-L282

next week I am on leave .. but I will try to come up with a table like @fmaussion suggested. 
I personally think having this in the oggm shop will be very useful! Happy to help with coding this too.

**Comment by JordiBolibar** [comment]
Hi @bearecinos and @fmaussion! What is the current situation of this? With ODINN we've hit a point where having this dataset available is pretty much necessary. 

I've seen it is included for the next release. Is there an approximate timeline for this? I'm not sure if I could be of any help with my limited knowledge of OGGM, but I'd be willing to help/test things if you need me to. 

Thanks again in advance, really looking forward to this! 😄

**Comment by fmaussion** [comment]
There is actually very little that is OGGM specific in this. 95% of the code is already there in itslive (https://github.com/OGGM/oggm/blob/master/oggm/shop/its_live.py) and can be reused, the only thing left to do is to have a lookup table between the several Millan files and the glaciers ID (i.e. we need to know which file to fetch for which glacier).

I can take care of the rest but I would be glad if someone could work on this lookup file (either between RGI IDs or RGI regions and the respective file to fetch)

**Comment by nchampollion** [comment]
I made a lookup table for RGI regions and Millan's velocity and thickness data ([https://github.com/nchampollion/Millan_data](https://github.com/nchampollion/Millan_data)).

I have few questions:
	- which format do you prefer, csv ?
	- there is usally few geotiff of Millan's data for one region, is that an issue ?
	- for regions 13, 14 and 15, geotiff Millan's data are combined, is that an issue ?
	
Finally, where do you want I upload the data ?

**Comment by JordiBolibar** [comment]
Wow, that was fast! Thanks so much for working on this @nchampollion. I can volunteer to test the code with the look-up table and see if everything works smoothly, and report on this. I can also help with documentation if that can be helpful.

**Comment by fmaussion** [comment]
Thanks a lot @nchampollion ! Answers inline:

> - which format do you prefer, csv ?

Yes

> - there is usally few geotiff of Millan's data for one region, is that an issue ?

Yes. The need for a lookup table arises because for a given glacier I need to know which file(s) to use in Millan's data. As it is now, for 1 single glacier in region 13 I would need to download 14 geotiffs and test them all

> - for regions 13, 14 and 15, geotiff Millan's data are combined, is that an issue ?

No that's not an issue, once we have a proper lookup table.

Now that I think of it, the simplest probably is that I download ALL files on cluster and create a shapefile of each geotiff's boundary. This can then be used to test for each glacier which geotiffs are needed. Will start the download

**Comment by fmaussion** [comment]
Ah OK I checked the [data download on Theia](https://www.sedoo.fr/theia-publication-products/?uuid=55acbdd5-3982-4eac-89b2-46703557938c) and they prevent automated download anyways. OGGM can't fetch these files automatically from this server.

So there are two ways to deal with the issue:
1. we don't do anything automatically in OGGM, i.e. the users are responsible of downloading the data they need and feed it to a function in OGGM
2. we mirror the data in Bremen. Someone would have to download all the data files and put them on cluster in Bremen.

From a user perspective, option 2 is better by far. I don't think we would violate any license in doing so.

@nchampollion , do you have all data available somewhere? Can we copy all files to cluster?

**Comment by fmaussion** [comment]
OK I had a closer look at RGI13-15 in particular and I see how this will be some more work. I created a [very short script](https://nbviewer.ipython.org/urls/cluster.klima.uni-bremen.de/~oggm/velocities/millan22/lookup_millan.ipynb) that does what we need: a lookup shapefile of the tiles (which is what we need if we want this to be automated): 

![image](https://user-images.githubusercontent.com/10050469/165274940-757fafde-d75f-4705-a889-2123f0af87ec.png)

The problem, as you can see, is that they overlap. And if you look at the data there is indeed an overlap, with some glaciers having data from more than one geotiff and others having only one. Where there are more than one, the values are not strictly the same:

![image](https://user-images.githubusercontent.com/10050469/165275550-f81d480a-f3f7-4ff5-8196-e316ef0d0b03.png)

I think we will need more guidance from Romain on how to deal with these data the same way he did.

**Comment by millanr1** [comment]
Hi everyone, 

First thing I wanted to ask is when was the last time that you have downloaded the data ? Bea knows this already, but we have tried to rapidly correct these overlapping regions (we had similar issues in Greenland). If you downloaded the dataset very early at the publication time, then you may want to download it again (specifically for Asia). Let me know if you still have issues then.

Best would be to have one single geotiff file,  but at a 50 m resolution, it will just be huge. I will need to figure out something to deal with this, and specifically for large regions such as Greenland or Asia.

**Comment by fmaussion** [comment]
Thanks @millanr1 !

This is the RGI13-15 file I downloaded yesterday. 

>Best would be to have one single geotiff file, but at a 50 m resolution, it will just be huge. 

I completely understand the challenges here

> I will need to figure out something to deal with this, and specifically for large regions such as Greenland or Asia.

We are here to help! I don't think the current format is an issue, I could create the lookup shapefile quite easily. Happy to let OGGM do the "glacier per glacier" processing for example (we are already doing that for RGI anyway)

Right now, I need to know what to do when there are two or more datasets for one glacier (like on the image above): what's the way to use the data then?

**Comment by millanr1** [comment]
So I looked at the layer you had on QGIS with Region 15.12 and 15.6. And if you go to the geotiff properties and set the zeros to be transparent, then there is no overlap. I think it might be because of a masked_array thing that QGIS may not recognize or something. Let me know if that fixes the issue.

Otherwise you can send me a shapefile with overlapping layers and I will fix the issue and update the file online.

**Comment by fmaussion** [comment]
@millanr1 OK I didn't check for strict overlap, I just saw that red and green pixels were found in the same glacier. I'm curious about how this could happen? But maybe this can be explained another time. 

So, to summarize, the workflow for one glacier would be:

1. Find which tiffs are needed for a specific glacier
2. *without reprojecting*, subset all the files for the glacier extent and then add all the files ignoring NaNs (this is probably the least easy to do in pure python, I'll have to think about a way to do that...)
3. reproject if needed

**Comment by fmaussion** [comment]
Ah now I think I see another thing: the value "0" means nodata right?

**Comment by millanr1** [comment]
I think that the faster way to do is within step 2, you should ignore pixels with NaN or zeros. Doing this you should not find any overlap. But if you do please send me a list of the glaciers that are overlapping.

See the screenshot below when zeros values are set as no data in QGIS, 
![Screen Shot 2022-04-26 at 1 34 22 PM](https://user-images.githubusercontent.com/104430112/165291301-1c07d909-f961-4bc4-be2e-43264cf195f4.png)

**Comment by millanr1** [comment]
The student that Nico and I supervised wrote a couple of python script to browse through our dataset and extract velocity or thicknesses. Would that be of any use ? I remember that we talked about it few weeks ago. Nico did you had time to look into this ?

**Comment by fmaussion** [comment]
Thanks for your help! I'll have a look.

I think that eventually what would be super useful is a shapefile like this: 

![image](https://user-images.githubusercontent.com/10050469/165294578-7a16ddab-44d7-4879-8a11-6d5f7c5a5e46.png)

This would allow any icebody to know unambiguously which file to open or ignore. I'm still amazed about how you managed to to these files without such a shapefile :sweat_smile:

**Comment by millanr1** [comment]
We have such shapefiles in our database, and we could consider releasing them as a mask, along with the surface DEM (which is something I got asked many times). I am taking note of it !

**Comment by fmaussion** [comment]
Thanks a lot! OK then I'll put this on hold until I have access to this shapefile

**Comment by millanr1** [comment]
I am not sure how long it will take since we need to exchange with the people at CNES and THEIA on how to set up things if we need to regularly add external datasets to the present repository. I think that going with the "ignore NaN and Zeros values" should do the job. I guess you have many other projects at the same time, so if you prefer waiting I'll keep you up to date.

**Comment by fmaussion** [comment]
OK, I understand. If you have the shapefile at hand I'm happy to also receive it via "unofficial" channels ;-)

**Comment by JordiBolibar** [comment]
Thanks for the comments @millanr1! Regarding the surface DEMs, I second that those would be extremely interesting! From a modelling perspective, having the surface altimetry that goes with the surface velocity is key to correctly reconstructing the bedrock 🙂

**Comment by fmaussion** [comment]
> having the surface altimetry that goes with the surface velocity

Why is this relevant? Does the DEM influence the velocity? 

We have practically all DEMs available in OGGM already (https://rgitools.readthedocs.io/en/latest/dems.html), but I'd be curious about why this is important in your case. (I would for example always favor the temporality of all datasets)

**Comment by JordiBolibar** [comment]
When working with the SIA, it's the surface elevation gradient that drives the diffusivity:
<img width="174" alt="image" src="https://user-images.githubusercontent.com/2025815/165357568-c650d460-2b7d-4d36-8c83-0040d909a0ff.png">

And the surface velocities also depend on the surface elevation (code in Julia, too lazy to rewrite in latex hehe):
```julia
Vx = - D .* avg_y(dSdx)
Vy = - D .* avg_x(dSdy)
```

Therefore, having a DEM (i.e. `S` in the equation) that matches the surface velocities is important. With that, I suppose that the DEM Romain is talking about matches the surface velocity product (not 100% though). Of course the ice thickness also influences the surface velocities, and the date in Glathida will definitely be different than the 2017-2018 period from Millan et al. (2022), but at least by having those DEMs we make sure that 2 out of 3 datasets are aligned temporally.

**Comment by JordiBolibar** [comment]
Ah yes, I see what you mean. Indeed, not sure if those are directly used in the processing of the surface velocities, but from a user/modeller's perspective, I think that is important (if there is a temporal match between those two datasets).

**Comment by bearecinos** [comment]
Thanks everyone for the efforts on adding this to OGGM ... indeed the DEM's will make a great addition specially for tidewater glaciers when the velocities indicate a terminus position that OGGM can't reproduce I have examples of just that, even using different DEM's..(@JordiBolibar thanks for enlightening me on this).
Happy to help review/test any set up .. I also have a notebook more or less made about the thickness data so once things are implemented I am happy to expand the current oggm-shop notebook or write a new one just for this! Cheers guys
