### ISSUE TITLE
the function "mu_star_calibration_from_geodetic_mb" write to json error

### ISSUE THREAD

**Issue by aierfulz** [OGGM/oggm#1422]
Dear OGGM development team:
       The line 1495 of climate.py ` gdir.add_to_diagnostics('ref_hgt_calib_diff', sel_steps[0] - start)` need to modify as ` gdir.add_to_diagnostics('ref_hgt_calib_diff', int(sel_steps[0] - start))
` to avoid write to json error.

**Comment by fmaussion** [comment]
Thanks for the report! you can try to make the change yourself if you want! 

Edit the file online at: https://github.com/OGGM/oggm/blob/master/oggm/core/climate.py

**Comment by fmaussion** [comment]
I see no open pull-request? You would need to send us a request change.

**Comment by aierfulz** [comment]
Dear Maussion: I had revised it again. this time may be right.
