### ISSUE TITLE
Should we change a line in climate.py?

### ISSUE THREAD

**Issue by bowenbelongstonature** [OGGM/oggm#1424]
I think this [line](https://github.com/OGGM/oggm/blob/master/oggm/core/climate.py#L1613) just send the start year and the end year to `mb_years` for subsequent calculations.

**Comment by fmaussion** [comment]
@lilianschuster can you have a look?

**Comment by lilianschuster** [comment]
Thanks Bowen for looking into the code in these details!

In OGGM/massbalance-sandbox, I always predefine mb_years (as an array) when using `apparent_mb_from_any_mb` (see: 
https://github.com/OGGM/massbalance-sandbox/blob/b2208c1028fb0d47b520f47cfd8f3f98a0ed8e13/MBsandbox/help_func.py#L2241 ). 

So, I am also confused from where the [y0,y1-1] comes from. I did some "research": The mentioned line was included in this pull request (https://github.com/OGGM/oggm/pull/1286), also see https://github.com/OGGM/oggm/commit/9e433f4c3044e27c09b18949bd8c7b44f67c12f7 line 1567  . According to the documentation, `mb_years` should be an array, and not just two years. **So after debugging and looking into my own code, I totally agree with @bowenbelongstonature , that  [line](https://github.com/OGGM/oggm/blob/master/oggm/core/climate.py#L1613) should be changed to  `np.arange(y0, y1,1)`** 

In the tests, also just two values are applied on this line https://github.com/OGGM/oggm/blob/1fca0cbd3564c33ff82ab3c4c41307055e7c7b85/oggm/tests/test_models.py#L4359 . 
Either I don't understand the concept here, or it should also there be an array? 

In any case, if we change this, it has consequences for some preprocessed gdirs! I don't know, however if they are important. 

What do you think, @fmaussion ?

**Comment by fmaussion** [comment]
Yes this is a bug, thanks for catching this. I think @drounce might be affected in his own code, depending how he calls `apparent_mb_from_any_mb`.

I think we should:
- change the line as suggested
- raise an error when the number of years given to `apparent_mb_from_any_mb` is smaller than 10.

Can someone take care of this?

**Comment by bowenbelongstonature** [comment]
I've made a PR.

Will some preprocessed  data in Shop be affected by this? @fmaussion

**Comment by bowenbelongstonature** [comment]
![Screenshot from 2022-07-01 14-42-09](https://user-images.githubusercontent.com/69409026/176839169-17f6bdf5-f42f-4bb3-b59a-d02a8e6a3acc.png)

I add a straightforward example how this change affects `apparent_mb_from_any_mb_residual`. This may affect the following thickness inversion.
