### ISSUE TITLE
When using user-defiend glacier shpfile, how can I produce model_flowlines.pkl file

### ISSUE THREAD

**Issue by 510781109** [OGGM/oggm#1427]

**Comment by bowenbelongstonature** [comment]
I think [this tutorial](https://oggm.org/tutorials/master/notebooks/use_your_own_inventory.html#finally-the-oggm-run) will help you.

**Comment by 510781109** [comment]
> I think [this tutorial](https://oggm.org/tutorials/master/notebooks/use_your_own_inventory.html#finally-the-oggm-run) will help you.

I have passed the following commands:
workflow.gis_prepro_tasks(gdirs)
workflow.download_ref_tstars('https://cluster.klima.unibremen.de/~oggm/ref_mb_params/oggm_v1.4/RGIV62/CRU/centerlines/qc3/pcp2.5')
workflow.climate_tasks(gdirs)
workflow.inversion_tasks(gdirs)
utils.compile_glacier_statistics(gdirs)
>>> print(os.listdir(gdir.dir))
['catchments_intersects.tar.gz', 'centerlines.pkl', 'climate_historical.nc', 'climate_info.json', 'dem.tif', 'dem_source.txt', 'diagnostics.json', 'downstream_line.pkl', 'flowline_catchments.tar.gz', 'geometries.pkl', 'glacier_grid.json', 'gridded_data.nc', 'intersects.tar.gz', 'inversion_flowlines.pkl', 'inversion_input.pkl', 'inversion_output.pkl', 'local_mustar.json', 'log.txt', 'outlines.tar.gz']
However, I have not yet seen the model_flowlines.pkl.  Is there anything wrong?

**Comment by bowenbelongstonature** [comment]
try [`init_present_time_glacier`](https://github.com/OGGM/oggm/blob/92ad564760bddc0d9967139f436917260bb75378/oggm/core/flowline.py#L2693)

**Comment by 510781109** [comment]
> try [`init_present_time_glacier`](https://github.com/OGGM/oggm/blob/92ad564760bddc0d9967139f436917260bb75378/oggm/core/flowline.py#L2693)

Great！It works. Thanks for a lot.
