### ISSUE TITLE
How to work with our own climate data sets as well as change parameters as per requirement

### ISSUE THREAD

**Issue by Sayantan-1996** [OGGM/oggm#1433]
Hi,

I wanted to know if we can manipulate the `params.cfg` and use different climate datasets or use a different value of creep parameter. 
Also, I understand that if I want to use my own climate datasets as well as Climate projections from CMIP6, they need to be in the format as per  `HISTALP_oetztal.nc`. But where specifically (directory) I place them. I was not able to understand this from the docs. 

Thank You.

**Comment by Sayantan-1996** [comment]
Thank you for your replies @bowenbelongstonature  & @anoukvlug. It will probably take some time for me to work out the tutorials. I will keep you posted here.

**Comment by Jinneedayu** [comment]
Hi@Sayantan-1996. I also want to replace the original climate data with the downloaded and downscaled cmip6 data. May I ask if your problem has been resolved？

**Comment by anoukvlug** [comment]
Hi @Jinneedayu, did you already checkout the [10 minutes to… a glacier change projection with GCM data](https://oggm.org/tutorials/stable/notebooks/10minutes/run_with_gcm.html) tutorial? I think it explains what you're trying to do.

**Comment by anoukvlug** [comment]
@Sayantan-1996 no worries and thanks for closing the issue! (I was about to ask if it could be closed.)
