### ISSUE TITLE
do_calving=True for non-tidewater glaciers

### ISSUE THREAD

**Issue by juliaeis** [OGGM/oggm#1449]
When reading the modeloutput of an non-tidewater glacier, the attribute `do_calving` becomes `True`. 

![grafik](https://user-images.githubusercontent.com/22957789/185604144-d591d160-bbc3-46a2-923e-7691257ff352.png)

This seems to happen here: https://github.com/OGGM/oggm/blob/5aa684bcdcf2c8c74ad3943369d677bbb3d44999/oggm/core/flowline.py#L2126, as the dataset contains` calving_m3.values`, even if they are zero. 

This should be changed, as it causes an error in e.g. graphics.plot_modeloutput_section(model=fmod):
![grafik](https://user-images.githubusercontent.com/22957789/185604610-29f125c7-5c8f-42ac-8ac6-11501b3a69c9.png)

**Comment by anoukvlug** [comment]
Thank you for reporting this issue @juliaeis! Would you be up for making a PR to correct this? If not, I wouldn't mind solving the issue.

**Comment by juliaeis** [comment]
The error above actually wasn't only related to the do_calving issue, but to the fact that the graphics.plot_modeloutput_section function wasn't well working with a FileModel. The PR #1450 add the water_level attribute to the FileModel. 
Unfortuanelty, the do_calving issue still remains and isn't that easy to solve...

**Comment by fmaussion** [comment]
yes indeed - FileModel and calving was not trivial I'm sure there was a reason I needed to solve it that way - the proposed fix is ok for me and we might need to investigate further later
