### ISSUE TITLE
Change ice density in dynamic mu star calibration

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/oggm#1474]
It just came to my mind that I used the oggm ice density (900 kg m-3) when I calculate the modelled geodetic mass balance in the dynamic mu star calibration, but actually, I should use the same ice density as was used when the geodetic mass balance was created (e.g. 850 kg m-3). With this in the end we match actually the volume change instead of the mass change.

My plan is to include a new kwarg `geodetic_mb_ice_density` into the dynamic mu star calibration, so if someone is using a geodetic mass balance which was derived using a different ice density assumption this could be changed.

**Comment by fmaussion** [comment]
This has been a decision made at a meeting involving @drounce and others
two years ago. To discuss at the workshop

**Comment by pat-schmitt** [comment]
Yes, let's discuss this at the workshop!

**Comment by pat-schmitt** [comment]
We should stay with the default OGGM density of 900 kg m-3 for the conversion of volume change to mass change because OGGM only simulates ice and no snow/firn.
