### ISSUE TITLE
Thesis topic: "Interpretation and simulation of glacier mass-balance with machine learning"

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1483]
### Context

Recently, an new [global dataset of glacier mass change](https://www.nature.com/articles/s41586-021-03436-z) has been released. It provides a map of glacier elevation change over nearly all of the world's glaciers. These data are now used to calibrate the OGGM model. However, we make very little use of them for other purposes, such as to predict future mass-balance or to help interpret the high spatio-temporal variability of mass balance between neighboring glaciers. There is a lot to learn from this dataset, and machine learning should be a suitable tool for this

![image](https://user-images.githubusercontent.com/10050469/191497026-b22fd68e-8b3f-4eab-921c-c92666b7ddf2.png)
Examples of the elevation maps product. Source: [Hugonnet et al, 2021](https://www.nature.com/articles/s41586-021-03436-z)

### Objectives 

The student will use classification and prediction algorithms on the dataset to help disentangle the very important question of controls of mass-balance: why can neighboring glaciers have  very different mass-balance values? This tool can be used to predict certain glacier characteristics such as surges, avalanches, calving, or debris cover.

### Profile of the candidate

Interest in machine learning, glacier modelling, and programming!

**Comment by fmaussion** [comment]
@JordiBolibar @facusapienza21 to discuss tomorrow

**Comment by JordiBolibar** [comment]
[This repo](https://github.com/Machine-Learning-in-Glaciology-Workshop/Project_MB_Regression/tree/main) from the ML workshop project can be a good baseline, since we already used OGGM and Hugonnet et al. (2021) applied in Scandinavia.

**Comment by fmaussion** [comment]
Closing this for now - This has been done before and is likely to be inconclusive unless better specified, i.e. let's reassess in a few months.
