### ISSUE TITLE
Preprocessed gdirs for getting_started missing from cluster

### ISSUE THREAD

**Issue by ehultee** [OGGM/oggm#1487]
Using OGGM v1.5, the `getting_started` notebook gives the following RuntimeError on attempting data import:
`
RuntimeError: Could not find file at https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.4/L3-L5_files/CRU/centerlines/qc3/pcp2.5/no_match/RGI62/b_080/L3/RGI60-11/RGI60-11.01.tar
`

I suspect this problem is already known because of the ongoing migration of old gdirs.  I assume that the best thing to do right now is wait for v1.6 release, then update the tutorial notebooks afterward.  But if the v1.6 release might take a while, let me know and I can submit a PR to directly modify the `base_url` in the tutorials.

**Comment by fmaussion** [comment]
I'm really sorry about that - please set `PARAMS['dl_verify'] = False` and try again. I'll ask Timo to recompute the hashes

**Comment by ehultee** [comment]
With that option I get `NameError: name 'salem' is not defined`.  Clearly a problem in import because the environment does have salem (on both computers I've tried).  I haven't dug into what's going on but FYI.

This is also not urgent - it's a research setup, not a class.  No stress.

**Comment by fmaussion** [comment]
> With that option I get NameError: name 'salem' is not defined. Clearly a problem in import because the environment does have salem (on both computers I've tried). I haven't dug into what's going on but FYI.

That hints at an install problem though, because it means that the file was downloaded but some problem happens later. Do the OGGM tests run properly in that env?

**Comment by ehultee** [comment]
Hah okay sorry I'm testing on two different computers.

On my laptop with v1.5.0, yes, I get `No module named 'descartes'` which seems like an install problem.  I can deal with that.

On Linux desktop with OGGM v 1.5.3, and `PARAMS['dl_verify'] = False`, the gdirs are located correctly and the tutorial finishes. :tada: 

I can open a PR to add that command to the tutorials unless you prefer not to have the clutter.  Will plan to do so in a bit unless I hear from you.

**Comment by fmaussion** [comment]
> On my laptop with v1.5.0, yes, on import salem I get No module named 'descartes' which seems like an install problem. I can deal with that.

Yes its probably an old install - I recommend to update OGGM and salem, we lost the descartes dependency a while ago

> I can open a PR to add that command to the tutorials unless you prefer not to have the clutter. Will plan to do so in a bit unless I hear from you.

No, the problem is on our data server side. We need to update a file so that the download can be verified again. @TimoRoth is the person able to do that
