### ISSUE TITLE
Issues related to importing glacier boundaries from non-public sources for simulation.

### ISSUE THREAD

**Issue by KReeves092** [OGGM/oggm#1492]
Hi Mr. Developer, can I use one or more glacier boundaries extracted by myself or other non-public sources for OGGM simulation and prediction? If yes, is there a specific tutorial?

**Comment by pat-schmitt** [comment]
Hi, you can have a look at this tutorial https://oggm.org/tutorials/stable/notebooks/use_your_own_inventory.html. There it is explained how you can use your own glacier outlines within OGGM.

**Comment by KReeves092** [comment]
> Hi, you can have a look at this tutorial https://oggm.org/tutorials/stable/notebooks/use_your_own_inventory.html. There it is explained how you can use your own glacier outlines within OGGM.

Thank you for your reply and I will try it again!
