### ISSUE TITLE
Reference Run OGGM with GCM data encountered a problem when running oggm.

### ISSUE THREAD

**Issue by KReeves092** [OGGM/oggm#1493]
In the [Run OGGM with GCM data](https://oggm.org/tutorials/stable/notebooks/run_with_gcm.html#run-oggm-with-gcm-data) tutorial, an error occurs while running the line from oggm.core import gcm_climate. 
The error is: 
`ImportError: cannot import name 'gcm_climate' from 'oggm.core' (/home/cc/anaconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/ core/__init__.py)`. 
I'm wondering if it's a python version issue. I hope I can get an answer, thanks a lot!

**Comment by fmaussion** [comment]
My guess is that you are using oggm latest, not stable. Replace `from oggm.core import gcm_climate` with `from oggm.shop import gcm_climate`

We need to update the tutorial as well

**Comment by KReeves092** [comment]
> 

Thank you very much for your reply, I updated oggm to the latest version not long ago and I will try again！

**Comment by KReeves092** [comment]
> My guess is that you are using oggm latest, not stable. Replace `from oggm.core import gcm_climate` with `from oggm.shop import gcm_climate`
> 
> We need to update the tutorial as well

Thank you very much for your reply, I updated oggm to the latest version not long ago and I will try again. Thanks again for your reply!
