### ISSUE TITLE
Problems encountered when using code to obtain the data needed for glacier simulation.

### ISSUE THREAD

**Issue by KReeves092** [OGGM/oggm#1494]
Recently, I encountered the following problem when using OGGM to perform simulations of future changes in glaciers.
When I ran the code `gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=5)` to get the relevant data, I got the following error `Starting with v1.6, users now have to explicitly indicate the url they want to start from`.
I'm wondering if this is because the version needs to be updated, but I already updated oggm to the latest version a while ago. Would very much appreciate an answer, thanks!

**Comment by pat-schmitt** [comment]
Hi, starting with the upcoming v1.6, OGGM forces the user to specify which data and calibration option should be used. This can be done by defining the `prepro_base_url`. You can read about the different options in the documentation https://docs.oggm.org/en/latest/input-data.html#pre-processed-directories. The reason for this is that there are many different options for how you can run OGGM (e.g. different climate datasets, different representations of the flowlines, different calibration strategies,...), and the user should actively decide which option to use for the specific research question.

But if you are just running the tutorials (which need to be updated to run with the newest OGGM version) here is one option: 
`gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=5, prepro_base_url='https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/L3-L5_files/elev_bands/w5e5/qc0/pcpwin/match_geod_pergla/', prepro_border=80)`

**Comment by fmaussion** [comment]
@KReeves092 in addition to what @pat-schmitt said: if you are learning OGGM I recommend to install the stable version, not latest master. We are making quite some changes in preparation for 1.6, and the tutorials do not yet reflect these changes.

**Comment by KReeves092** [comment]
> Hi, starting with the upcoming v1.6, OGGM forces the user to specify which data and calibration option should be used. This can be done by defining the `prepro_base_url`. You can read about the different options in the documentation https://docs.oggm.org/en/latest/input-data.html#pre-processed-directories. The reason for this is that there are many different options for how you can run OGGM (e.g. different climate datasets, different representations of the flowlines, different calibration strategies,...), and the user should actively decide which option to use for the specific research question.
> 
> But if you are just running the tutorials (which need to be updated to run with the newest OGGM version) here is one option: `gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=5, prepro_base_url='https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/L3-L5_files/elev_bands/w5e5/qc0/pcpwin/match_geod_pergla/', prepro_border=80)`

Thank you very much for your reply! I have reinstalled the stable version of oggm, and my intention is to use oggm to simulate the climate-influenced variability of glaciers.
After reinstalling oggm, I wanted to follow the Run OGGM with GCM data tutorial to see if it would simulate the results in the tutorial successfully so that I could use the CMIP6 dataset again later in my work, but a new error occurred: when I went to Download and process GCM data and Projection runs, the oggm model gave me the following message: 
**_2022-10-12 12:15:25: oggm.workflow: Execute entity tasks [process_cmip_data] on 1 glaciers
[None]
2022-10-12 12:15:26: oggm.workflow: Execute entity tasks [process_cmip_data] on 1 glaciers
[None]
2022-10-12 12:15:27: oggm.workflow: Execute entity tasks [process_cmip_data] on 1 glaciers
[None]
2022-10-12 12:15:27: oggm.workflow: Execute entity tasks [process_cmip_data] on 1 glaciers
[None]_**
and
_**2022-10-12 12:17:59: oggm.workflow: Execute entity tasks [run_from_climate_data] on 1 glaciers
[<oggm.core.flowline.FluxBasedModel object at 0x7fb49dbcb850>]
2022-10-12 12:18:00: oggm.workflow: Execute entity tasks [run_from_climate_data] on 1 glaciers
[<oggm.core.flowline.FluxBasedModel object at 0x7fb49dbb03d0>]
2022-10-12 12:18:00: oggm.workflow: Execute entity tasks [run_from_climate_data] on 1 glaciers
[<oggm.core.flowline.FluxBasedModel object at 0x7fb49dc8bd00>]
2022-10-12 12:18:01: oggm.workflow: Execute entity tasks [run_from_climate_data] on 1 glaciers
[<oggm.core.flowline.FluxBasedModel object at 0x7fb49db17d30>]**_
. 
What is confusing is that I checked the results folder I set up and found that the folder only contains the historical results of the glacier runs and is missing the results of future simulations.

**Comment by fmaussion** [comment]
I'm sorry but you are not giving us enough information to help you out. A [mre](https://stackoverflow.com/help/minimal-reproducible-example) would help! Also you main consider joining our slack space: https://oggm.org/2022/10/11/Welcome-to-the-OGGM-Slack/
