### ISSUE TITLE
Download rgi data in a very slow speed

### ISSUE THREAD

**Issue by YNULuke** [OGGM/oggm#1499]
![image](https://user-images.githubusercontent.com/103492001/197925623-6fd373b8-a2a6-4699-98bb-c6e1562b0904.png)
I can run the file in binder, the speed is OK！ But when I try to download the file in my own linux system, the speed is very low.

**Comment by fmaussion** [comment]
yes our servers were very slow yesterday (its better today I think). sorry about that! Hopefully this will be resolved soon.

**Comment by fmaussion** [comment]
feel free to reopen if it happens again
