### ISSUE TITLE
Unexpected Test failers with master

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/oggm#1503]
Hi,

I was just about to try to fix the test failers of this recent PR https://github.com/OGGM/oggm/pull/1502 and their many tests are failing. There are that many that I now tried to run a few failing tests with the current master and they are still failing with the same error message as in the PR.

For example these tests:
https://github.com/OGGM/oggm/blob/master/oggm/tests/test_models.py#L2911
https://github.com/OGGM/oggm/blob/master/oggm/tests/test_models.py#L4499

 Can someone please try if it is only a problem on my side?
And if not has someone an idea what is going wrong? (Maybe something changed with the test data?)

**Comment by pat-schmitt** [comment]
Seems to be an error on my side. Thanks

**Comment by pat-schmitt** [comment]
I think I figured out what caused the problem on master for me.

If you are running the tests a folder is created in your `OGGM_data_directory/tests/`, where the glacier directory used by the tests is created. And I think the directory created with my new `filter_inversion_output` function was used later when I switched back to master and caused the tests to fail. (Probably a problem of using git stash when switching back to master).

The solution is to delete all folders in `OGGM_data_directory/tests/` before running the tests. This forces a rebuild of the test glacier directory.

**Comment by fmaussion** [comment]
There are some safeguards against this problem here : https://github.com/OGGM/oggm/blob/fd6ce6c745ec883a14c61f2de8ceb813cf7c99f4/oggm/tests/funcs.py#L306-L326 

But it will never be perfect...

**Comment by pat-schmitt** [comment]
Thanks, I see.

So each combination for `s` should be unique and create a new directory. And all the old directories are removed.
I have two questions: 

- how is the `get_git_ident()` getting its value for `ident_str` here https://github.com/OGGM/oggm/blob/master/oggm/utils/_workflow.py#L198
- maybe to avoid an error if the resulting `s` is not unique and was used previously (as I suspect it was the case for me) we could set `mkdir(out, reset=True)`. This would reset the directory for sure each time a new set of tests is started. Or would this have other unwanted side effects?
