### ISSUE TITLE
Unable to convert the flowlines to a "glacier" for the ice dynamics module

### ISSUE THREAD

**Issue by av-manoj** [OGGM/oggm#1537]
With climate data and an estimate of the ice thickness, I was trying to do transient simulations for the Chotta Shigri glacier by following the OGGM tutorial but an error **"KeyError: 'bedshapes"** occurred after running these code **"workflow.execute_entity_task(tasks.init_present_time_glacier, gdirs);"**
I am a beginner and just started using OGGM, so currently I am unable to understand this error. Can anyone help me with this?

**Comment by av-manoj** [comment]
> With climate data and an estimate of the ice thickness, I was trying to do transient simulations for the Chotta Shigri glacier by following the OGGM tutorial but an error **"KeyError: 'bedshapes"** occurred after running these code **"workflow.execute_entity_task(tasks.init_present_time_glacier, gdirs);"** I am a beginner and just started using OGGM, so currently I am unable to understand this error. Can anyone help me with this?

These are the errors occurred

KeyError                                  Traceback (most recent call last)
Cell In[213], line 2
      1 # Convert the flowlines to a "glacier" for the ice dynamics module
----> 2 workflow.execute_entity_task(tasks.init_present_time_glacier, gdirs);

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/workflow.py:191, in execute_entity_task(task, gdirs, **kwargs)
    187     if ng > 3:
    188         log.workflow('WARNING: you are trying to run an entity task on '
    189                      '%d glaciers with multiprocessing turned off. OGGM '
    190                      'will run faster with multiprocessing turned on.', ng)
--> 191     out = [pc(gdir) for gdir in gdirs]
    193 return out

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/workflow.py:191, in <listcomp>(.0)
    187     if ng > 3:
    188         log.workflow('WARNING: you are trying to run an entity task on '
    189                      '%d glaciers with multiprocessing turned off. OGGM '
    190                      'will run faster with multiprocessing turned on.', ng)
--> 191     out = [pc(gdir) for gdir in gdirs]
    193 return out

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/workflow.py:108, in _pickle_copier.__call__(self, arg)
    106 for func in self.call_func:
    107     func, kwargs = func
--> 108     res = self._call_internal(func, arg, kwargs)
    109 return res

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/workflow.py:102, in _pickle_copier._call_internal(self, call_func, gdir, kwargs)
     99     gdir, gdir_kwargs = gdir
    100     kwargs.update(gdir_kwargs)
--> 102 return call_func(gdir, **kwargs)

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/utils/_workflow.py:491, in entity_task.__call__.<locals>._entity_task(gdir, reset, print_log, return_value, continue_on_error, add_to_log_file, **kwargs)
    489     signal.alarm(cfg.PARAMS['task_timeout'])
    490 ex_t = time.time()
--> 491 out = task_func(gdir, **kwargs)
    492 ex_t = time.time() - ex_t
    493 if cfg.PARAMS['task_timeout'] > 0:

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/core/flowline.py:2739, in init_present_time_glacier(gdir)
   2736 if not gdir.is_tidewater and inv['is_last']:
   2737     # for valley glaciers, simply add the downstream line
   2738     dic_ds = gdir.read_pickle('downstream_line')
-> 2739     bed_shape = np.append(bed_shape, dic_ds['bedshapes'])
   2740     lambdas = np.append(lambdas, dic_ds['bedshapes'] * np.NaN)
   2741     section = np.append(section, dic_ds['bedshapes'] * 0.)

KeyError: 'bedshapes'

**Comment by pat-schmitt** [comment]
Hi,
the error tells you that 'bedshapes' of the downstream line have not been computed. This 'bedshapes' are calculated in `tasks.compute_downstream_bedshape`.

But for in-depth help, it would be interesting which OGGM Tutorial exactly you are using, and how your whole workflow looks like..

**Comment by av-manoj** [comment]
Thanks for replying. As you said but I failed to compute the bedshape.
Ok. I am writing the issues in detail during the entire run in OGGM.
I have been following this tutorial "https://oggm.org/tutorials/stable/notebooks/getting_started.html".
I tried following the given codes in this tutorial for my glacier (chotta shigri) RGI60-14.155990.
During this entire run, two errors occurred.

1. Running Task
list_talks = [
         tasks.compute_centerlines,
         tasks.initialize_flowlines,
         tasks.compute_downstream_line,
         ]
for task in list_talks:
    # The order matters!
    workflow.execute_entity_task(task, gdirs)

_Error:_
2023-03-03 12:13:16: oggm.workflow: Execute entity tasks [compute_centerlines] on 1 glaciers
2023-03-03 12:13:16: oggm.core.centerlines: TypeError occurred during task compute_centerlines on RGI60-14.15990: No matching signature found
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[312], line 8
      1 list_talks = [
      2          tasks.compute_centerlines,
      3          tasks.initialize_flowlines,
      4          tasks.compute_downstream_line,
      5          ]
      6 for task in list_talks:
      7     # The order matters!
----> 8     workflow.execute_entity_task(task, gdirs)

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/workflow.py:191, in execute_entity_task(task, gdirs, **kwargs)
    187     if ng > 3:
    188         log.workflow('WARNING: you are trying to run an entity task on '
    189                      '%d glaciers with multiprocessing turned off. OGGM '
    190                      'will run faster with multiprocessing turned on.', ng)
--> 191     out = [pc(gdir) for gdir in gdirs]
    193 return out

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/workflow.py:191, in <listcomp>(.0)
    187     if ng > 3:
    188         log.workflow('WARNING: you are trying to run an entity task on '
    189                      '%d glaciers with multiprocessing turned off. OGGM '
    190                      'will run faster with multiprocessing turned on.', ng)
--> 191     out = [pc(gdir) for gdir in gdirs]
    193 return out

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/workflow.py:108, in _pickle_copier.__call__(self, arg)
    106 for func in self.call_func:
    107     func, kwargs = func
--> 108     res = self._call_internal(func, arg, kwargs)
    109 return res

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/workflow.py:102, in _pickle_copier._call_internal(self, call_func, gdir, kwargs)
     99     gdir, gdir_kwargs = gdir
    100     kwargs.update(gdir_kwargs)
--> 102 return call_func(gdir, **kwargs)

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/utils/_workflow.py:491, in entity_task.__call__.<locals>._entity_task(gdir, reset, print_log, return_value, continue_on_error, add_to_log_file, **kwargs)
    489     signal.alarm(cfg.PARAMS['task_timeout'])
    490 ex_t = time.time()
--> 491 out = task_func(gdir, **kwargs)
    492 ex_t = time.time() - ex_t
    493 if cfg.PARAMS['task_timeout'] > 0:

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/core/centerlines.py:916, in compute_centerlines(gdir, heads)
    914 # Filter the lines which are going up instead of down
    915 if do_filter_slope:
--> 916     olines, oheads = _filter_lines_slope(olines, oheads, topo,
    917                                          gdir, min_slope)
    918     log.debug('(%s) number of heads after slope filter: %d',
    919               gdir.rgi_id, len(olines))
    921 # And rejoin the cut tails

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/core/centerlines.py:512, in _filter_lines_slope(lines, heads, topo, gdir, min_slope)
    510 # Interpolate heights
    511 x, y = new_line.xy
--> 512 hgts = interpolator((y, x))
    514 # If smoothing, this is the moment
    515 hgts = gaussian_filter1d(hgts, sw)

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/scipy/interpolate/_rgi.py:336, in RegularGridInterpolator.__call__(self, xi, method)
    332 if (ndim == 2 and hasattr(self.values, 'dtype') and
    333         self.values.ndim == 2):
    334     # a fast path
    335     out = np.empty(indices.shape[1], dtype=self.values.dtype)
--> 336     result = evaluate_linear_2d(self.values,
    337                                 indices,
    338                                 norm_distances,
    339                                 self.grid,
    340                                 out)
    341 else:
    342     result = self._evaluate_linear(indices, norm_distances)

File _rgi_cython.pyx:19, in scipy.interpolate._rgi_cython.__pyx_fused_cpdef()

TypeError: No matching signature found

​2. I tried to compute the bedshape using this function
oggm.tasks.compute_downstream_bedshape(gdir)

_Error:_
2023-03-03 12:12:26: oggm.core.centerlines: TypeError occurred during task compute_downstream_bedshape on RGI60-14.15990: No matching signature found
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[310], line 1
----> 1 oggm.tasks.compute_downstream_bedshape(gdir)

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/utils/_workflow.py:491, in entity_task.__call__.<locals>._entity_task(gdir, reset, print_log, return_value, continue_on_error, add_to_log_file, **kwargs)
    489     signal.alarm(cfg.PARAMS['task_timeout'])
    490 ex_t = time.time()
--> 491 out = task_func(gdir, **kwargs)
    492 ex_t = time.time() - ex_t
    493 if cfg.PARAMS['task_timeout'] > 0:

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/core/centerlines.py:1213, in compute_downstream_bedshape(gdir)
   1210 xy = (np.arange(0, len(y)-0.1, 1), np.arange(0, len(x)-0.1, 1))
   1211 interpolator = RegularGridInterpolator(xy, topo)
-> 1213 bs = _parabolic_bed_from_topo(gdir, cl, interpolator)
   1214 assert len(bs) == cl.nx, 'len(bs) == cl.nx'
   1215 assert np.all(np.isfinite(bs)), 'np.all(np.isfinite(bs))'

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/oggm/core/centerlines.py:1115, in _parabolic_bed_from_topo(gdir, idl, interpolator)
   1113 ro = []
   1114 for i in cc:
-> 1115     z.append(interpolator((i[0].y, i[0].x)))
   1116     ro.append(i[1])
   1117 aso = np.argsort(ro)

File ~/miniconda3/envs/oggm_env1/lib/python3.10/site-packages/scipy/interpolate/_rgi.py:336, in RegularGridInterpolator.__call__(self, xi, method)
    332 if (ndim == 2 and hasattr(self.values, 'dtype') and
    333         self.values.ndim == 2):
    334     # a fast path
    335     out = np.empty(indices.shape[1], dtype=self.values.dtype)
--> 336     result = evaluate_linear_2d(self.values,
    337                                 indices,
    338                                 norm_distances,
    339                                 self.grid,
    340                                 out)
    341 else:
    342     result = self._evaluate_linear(indices, norm_distances)

File _rgi_cython.pyx:19, in scipy.interpolate._rgi_cython.__pyx_fused_cpdef()

TypeError: No matching signature found

**Comment by av-manoj** [comment]
Thanks for answering. The RGI-ID that I mentioned earlier was by mistake.  Currently, I'm using the latest one (OGGM version 1.5.3). Let me try all the steps from the beginning again. If I get any problem, I will post the issue. Thank you so much!

**Comment by av-manoj** [comment]
Hi,
I again tried from the beginning steps, and no errors in computing till the "Climate task".  
But it got stuck computing the "mass balance" for this glacier. 
**I run these codes:**

rom oggm.core.massbalance import MultipleFlowlineMassBalance
gdir_hef = gdirs[1]
mbmod = MultipleFlowlineMassBalance(gdir_hef, use_inversion_flowlines=True)

**got error:** 

IndexError                                Traceback (most recent call last)
Cell In[38], line 2
      1 from oggm.core.massbalance import MultipleFlowlineMassBalance
----> 2 gdir_hef = gdirs[1]
      3 mbmod = MultipleFlowlineMassBalance(gdir_hef, use_inversion_flowlines=True)

IndexError: list index out of range


Is it due to "gdirs[1]", as in tutorial 2 glaciers were considered for computation and I have used only 1 glacier, i.e. for Chotta Shigri glacier?

**Comment by av-manoj** [comment]
Correction in the above lines due to a typing mistake.

from oggm.core.massbalance import MultipleFlowlineMassBalance
gdir_hef = gdirs[1]
mbmod = MultipleFlowlineMassBalance(gdir_hef, use_inversion_flowlines=True)

**Comment by pat-schmitt** [comment]
Hi,
yes, you are right. The error is because you only use one glacier in your example. You should use `gdirs[0]` everywhere in the tutorial.

**Comment by av-manoj** [comment]
> Hi, yes, you are right. The error is because you only use one glacier in your example. You should use `gdirs[0]` everywhere in the tutorial.

Thanks!
It run successfully.

**Comment by fmaussion** [comment]
Yes this is due to changes in numpy - you need to downgrade numpy, I'm sorry! See discussion here: https://github.com/OGGM/oggm/issues/1538

**Comment by av-manoj** [comment]
> Yes this is due to changes in numpy - you need to downgrade numpy, I'm sorry! See discussion here: #1538

Okk.. Thanks!! Let me see thoroughly.
