### ISSUE TITLE
Problems with installing OGGM using pyenv

### ISSUE THREAD

**Issue by zhanzexin** [OGGM/oggm#1538]
I installed oggm using pyenv and had trouble testing it.
Here are my test results
[test_result.txt](https://github.com/OGGM/oggm/files/10870895/test_result.txt)
in test_benchmarks.py
line 54  TypeError: object of type 'float' has no len()
line 111 TypeError: object of type 'float' has no len()
line 161 TypeError: object of type 'float' has no len()
line 211TypeError: object of type 'float' has no len()
in test_models.py
line316  AttributeError: module 'numpy' has no attribute 'warnings'
line 429 AttributeError: module 'numpy' has no attribute 'warnings'
line 545 AttributeError: module 'numpy' has no attribute 'warnings'
line 676 AttributeError: module 'numpy' has no attribute 'warnings'
in test_prepro.py
line  765  TypeError: object of type 'numpy.float64' has no len()
line 870  AttributeError: module 'numpy' has no attribute 'warnings'
in test_utils.py
line 1010 AttributeError: module 'numpy' has no attribute 'warnings'
line 1136 AttributeError: module 'numpy' has no attribute 'warnings'
line 1255  RuntimeError: Found no valid glaciers!
I wonder how to solve these problems.

**Comment by fmaussion** [comment]
Yes, these are errors related to upstream package updates. Latest OGGM has solved these, but not OGGM 1.5.3 

If you can wait a few days, we will soon release OGGM 1.6. Otherwise, I suggest to try to use older versions of scipy and numpy (maybe only a few mnths old)

**Comment by zhanzexin** [comment]
Thank you for your instructions and help.I will try it again.

**Comment by zhanzexin** [comment]
@fmaussion I try to use older versions of scipy 1.9.2 and numpy1.23.0 to install OGGM1.5.3，but there are still some questions.
in in test_benchmarks.py ,four problems remain. in test_prepro.py,line 765 TypeError: object of type 'numpy.float64' has no len(),this problem still remains.How to deal with them

**Comment by fmaussion** [comment]
Yes this is another package update - but I don't know which one :sob: 

can you try to downgrade geopandas, shapely and fiona?

**Comment by fmaussion** [comment]
oggm v1.6 will solve all this and will be release early next week

**Comment by zhanzexin** [comment]
Thank you for your advice and help.I'm looking forward to the upcoming v1.6 OGGM,and I am also very confident that these problems can be solved.
