### ISSUE TITLE
mu_star_calibration_from_geodetic_mb

### ISSUE THREAD

**Issue by jwzs** [OGGM/oggm#1546]
When calibrating the mass balance model, could I use multi- mass balance values (e.g.，mass balance time series of a certain glacier/ region) to calibrate it with mu_star_calibration_from_geodetic_mb? We may calibrate the model wrongly use only an mean value if there was a sudden change in the glacier during the calibration period.

**Comment by fmaussion** [comment]
I'm sorry but your question is not clear to me!

**Comment by jwzs** [comment]
If I have four or five mass balance values for a certain glacier, how can I use all of them to calibrate the mass balance model with mu_star_calibration_from_geodetic_mb or other functions? For example, during 2000-2003, the mass balance of the glacier is mb1; during 2003-2006, the mass balance of the glacier is mb2; ...  and during 2015-2018, the mass balance of the glacier is mb6. Is it possible for me to use all these values to calibrate the model？

**Comment by fmaussion** [comment]
OGGM currently does not support parameters that vary with time. However these data could be used to inform other parameters. I would recommend to have a look at:
- This new tutorial: https://oggm.org/tutorials/stable/notebooks/advanced/massbalance_calibration.html (requires OGGM 1.6)
- This preprint: https://doi.org/10.31223/X5C65S (in review)
