### ISSUE TITLE
Error: 'MixedBedFlowline' object has no attribute 'mu_star'

### ISSUE THREAD

**Issue by yanglinlin668** [OGGM/oggm#1553]
Dear sirs,
I am trying running the following codes with OGGM (1.5.3), but raise errors.

# RGI glaciers: Hintereisferner and Kesselwandferner
rgi_ids = utils.get_rgi_glacier_entities(['RGI60-11.00897', 'RGI60-11.00787'])

# Go - get the pre-processed glacier directories
base_url = ('https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/'
            'L3-L5_files/2023.1/elev_bands/W5E5/')
gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=3, prepro_base_url=base_url)

# Run
workflow.execute_entity_task(tasks.run_from_climate_data, gdirs, 
                             output_filesuffix='_spinup',  # to use the files as input later on
                             );

The last code raising the error "oggm.core.flowline: AttributeError occurred during task run_from_climate_data_spinup on RGI60-11.00787: 'MixedBedFlowline' object has no attribute 'mu_star' "

Hope to help me！

**Comment by fmaussion** [comment]
Thank you for your interest!

> base_url = ('https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/L3-L5_files/2023.1/elev_bands/W5E5/')

If you are running 1.5.3 you cannot use 1.6 directories (`oggm_v1.6` in the url). If you prefer to continue using 1.5.3 you should follow the 1.5.3 tutorials: https://oggm.org/tutorials/v1.5.3

**Comment by yanglinlin668** [comment]
Thanks for you valuable suggestions! Good luck to you!
