### ISSUE TITLE
a problem when test OGGM

### ISSUE THREAD

**Issue by Jinneedayu** [OGGM/oggm#1559]
There is a proble when I test the OGGM and run the code : _pytest.oggm_
It run too fast and found few items.
How to solve this problem? Thanks.

![image](https://user-images.githubusercontent.com/90368320/229325706-59e3b754-86ae-40da-88a4-7256deeb7382.png)

**Comment by pat-schmitt** [comment]
Hi @Jinneedayu,

have you solved this issue? I think so because of your comment here https://github.com/OGGM/oggm/issues/1409.

**Comment by Jinneedayu** [comment]
Hi @pat-schmitt , I solved the problem. Thank you for your kind reply.
