### ISSUE TITLE
How to calculate future mass balance data

### ISSUE THREAD

**Issue by yanglinlin668** [OGGM/oggm#1560]
Dear sirs,

Recently, I run the OGGM model with CMIP6 climate data. However, the final simulation variables do not contain "mass balance"  in the simulation. So how to get the mass balance changes with the model?

**Comment by pat-schmitt** [comment]
Hi,

here in this tutorial, it is explained how to calculate the specific mass balance using the volume and area output of the model: https://oggm.org/tutorials/stable/notebooks/beginner/plot_mass_balance.html#specific-mass-balance-from-volume-change-time-series

Is this what you are looking for?
