### ISSUE TITLE
error in process_cmip_data

### ISSUE THREAD

**Issue by yanglinlin668** [OGGM/oggm#1565]
bp = 'https://cluster.klima.uni-bremen.de/~oggm/cmip6/GCM/CESM2/CESM2_{}_r1i1p1f1_pr.nc'
bt = 'https://cluster.klima.uni-bremen.de/~oggm/cmip6/GCM/CESM2/CESM2_{}_r1i1p1f1_tas.nc'
for ssp in ['ssp126', 'ssp585']:  # Removed 'ssp245', 'ssp370' because the files are large!
    # Download the files
    ft = utils.file_downloader(bt.format(ssp))
    fp = utils.file_downloader(bp.format(ssp))
    # bias correct them
    workflow.execute_entity_task(gcm_climate.process_cmip_data, gdirs, 
                                 filesuffix='_CMIP6_CESM2_{}'.format(ssp),  # recognize the climate file for later
                                 fpath_temp=ft,  # temperature projections
                                 fpath_precip=fp,  # precip projections
                                 );

When I run the code, raised an error:
oggm.shop.gcm_climate: InvalidParamsError occurred during task process_gcm_data_CMIP6_CESM2_ssp126 on RGI60-13.45335: The reference climate period and the GCM period after window selection do not match.

How can I solve this error?Please help me.

**Comment by lilianschuster** [comment]
Hi,
It always helps us to understand your problem if you tell us how you came to that error: 
I guess you refer to this notebook https://oggm.org/tutorials/stable/notebooks/10minutes/run_with_gcm.html and you tried to rerun it with another glacier (i.e., `RGI60-13.45335`)? 
- The error tells you that the climate that you used to calibrate the MB model parameters (default is `GSWP3_W5E5` in OGGM v16) has no data in the default common time period with the GCM (default for `process_cmip_data` is 1961-1990).  Thus, the bias correction can not be done. 

 I tried to reproduce your error by running this notebook https://oggm.org/tutorials/stable/notebooks/10minutes/run_with_gcm.html with your glacier, and it worked for me without errors. I see two possibilities for how you came to that error:
- you use an OGGM version that is below 1.6 -> solution: update to OGGM v16
- you used your own climate data for calibration, which does not have data between 1961-1990? -> solution: Use another `year_range` for which the bias correction is applied. Normally it should be the common time period between GCM and the climate data used for calibration. For example, if your climate data goes from 2000-2019, do the following for the bias correction:
`workflow.execute_entity_task(gcm_climate.process_cmip_data, gdirs,
                                                       year_range=('2000','2019'), 
    filesuffix='CMIP6_CESM2{}'.format(ssp),   fpath_temp=ft, fpath_precip=fp)`
    
  The `year_range=('2000','2019')` key-word argument is then used within the `process_gcm_data` function   (https://github.com/OGGM/oggm/blob/master/oggm/shop/gcm_climate.py#L24) to bias-correct the GCMs to the applied calibration climate during the period 2000-2019.  `process_gcm_data` is called inside of `process_cmip_data`. 

Does one of these solutions work for you? If not, please tell us more about **when** your error occurs. 

If you are in the OGGM slack, you can also ask questions there in the #support channel. If not, you can ask to get into slack by writing an email to info@oggm.org.

Cheers,
Lilian
