### ISSUE TITLE
How to use own glacier boundary shapefile in OGGM

### ISSUE THREAD

**Issue by av-manoj** [OGGM/oggm#1566]
Hello,
I am working on the Chhota Shigri glacier (RGI ID - RGI60-14.15990). The RGI v6 boundary outline is not that much accurate. Therefore, I want to use my own glacier shapefile. For this, I already followed your tutorial "Using your our own glacier inventory with OGGM" - "Case 3: Start from a completely independent inventory (https://oggm.org/tutorials/stable/notebooks/advanced/use_your_own_inventory.html)". I followed the steps given in the tutorial 
("Case 3: Start from a completely independent inventory")  But I could not understand how to implement my own shapefile into the OGGM module for computing MB. Can you please guide me on this issue?

**Comment by fmaussion** [comment]
I'm sorry but your question is not precise enough for us to help you, as you don't express a specific problem. [Here](https://stackoverflow.com/help/how-to-ask) is some guidance about how to ask questions for better guidance. Thanks!

Closing this now - feel free to reopen if needed.
