### ISSUE TITLE
Error in calibrating direct glaciological in-situ MB observations

### ISSUE THREAD

**Issue by av-manoj** [OGGM/oggm#1568]
_Hello,_
_An error occurred while computing in calibration using direct glaciological in-situ MB observations. I could not understand the error._

_I type these codes:_

mbdf_in_situ = gdir_hef.get_ref_mb_data()
mbdf_in_situ['ref_mb'] = mbdf_in_situ['ANNUAL_BALANCE']
#check that every year between the beginning and the end has MB observations
assert len(mbdf_in_situ.index) == (mbdf_in_situ.index[-1] - mbdf_in_situ.index[0] + 1)
ref_mb = mbdf_in_situ.ref_mb.mean()

_and error occurred:_ 

AssertionError                            Traceback (most recent call last)
Cell In[47], line 4
      2 mbdf_in_situ['ref_mb'] = mbdf_in_situ['ANNUAL_BALANCE']
      3 # check that every year between the beginning and the end has MB observations 
----> 4 assert len(mbdf_in_situ.index) == (mbdf_in_situ.index[-1] - mbdf_in_situ.index[0] + 1)
      5 ref_mb = mbdf_in_situ.ref_mb.mean()

AssertionError: 

_can anyone help me in dealing with this error?_

**Comment by lilianschuster** [comment]
Hi,
I guess you used the notebook https://oggm.org/tutorials/stable/notebooks/advanced/massbalance_calibration.html to try to calibrate OGGM with your own direct glaciological in-situ MB on a specific glacier (is your question related to issue https://github.com/OGGM/oggm/issues/1567 using `RGI60-14.15990`)? Please try to write down this kind of information, as it helps us answer your question faster! 

I rerun the notebook with your glacier. The error just tells you that the period where you have in-situ observations is not continuous (for your glacier, I guess  `RGI60-14.15990` ???, there are continuous observations from 2003 onwards, but there are also two observations in the years 1987 and 1988). If the remaining workflow looks fine, you can just comment out that "assert" line and ignore it, or you use instead just the data from 2003 onwards.  I might remove that assert line from the notebook. 

Does that work out for you? 

If you are in the OGGM Slack, you can also ask questions there in the #support channel. If not, you can ask to get into Slack by writing an email to [info@oggm.org](mailto:info@oggm.org).

**Comment by fmaussion** [comment]
Closing this now - feel free to reopen if needed.
