### ISSUE TITLE
When is the climate data used to calculate the mass balance when inversing the thickness？

### ISSUE THREAD

**Issue by WSXCZ** [OGGM/oggm#1577]
Hi, I would like to ask you a question, I don't quite understand  which year is the climate data used to calculate the mass balance and ice flux in OGGM when it is finally used to invese the thickness? Or is it a 31 year average centered on u(t)? I must state that we are using OGGM version 1.5.3，thank you very much!

**Comment by fmaussion** [comment]
Are you using `apparent_mb_from_any_mb`? or are you using the default as in OGGM 1.5.3?

**Comment by WSXCZ** [comment]
> Are you using `apparent_mb_from_any_mb`? or are you using the default as in OGGM 1.5.3?

I use the default  as in OGGM 1.5.3.

**Comment by WSXCZ** [comment]
> If you are using the calibration without geodetic data ("old" calibration) then OGGM uses the mass balance of 31 years centered at the date t* , which is different for each glacier: https://docs.oggm.org/en/v1.5.3/inversion.html#ice-flux https://docs.oggm.org/en/v1.5.3/mass-balance-2012.html
> 
> Of you are using the calibration on geodetic data (glacier per glacier) then it is the 2000-2020 period + a bias so that MB=0

I got it, thanks a lot!
