### ISSUE TITLE
Failed test_graphics

### ISSUE THREAD

**Issue by qikai-sun** [OGGM/oggm#1598]
pytest.oggm
================================================ test session starts =================================================
platform linux -- Python 3.8.8, pytest-7.3.2, pluggy-0.13.1
Matplotlib: 3.3.4
Freetype: 2.10.4
rootdir: /public/home/sunqk
plugins: anyio-2.2.0, mpl-0.160.1
collected 352 items                                                                                                  

anaconda3/lib/python3.8/site-packages/oggm/tests/test_benchmarks.py ...s.ss                                    [  1%]
anaconda3/lib/python3.8/site-packages/oggm/tests/test_graphics.py .ss.....F.s...s...x.sss                      [  8%]
anaconda3/lib/python3.8/site-packages/oggm/tests/test_minimal.py ...                                           [  9%]
anaconda3/lib/python3.8/site-packages/oggm/tests/test_models.py ..............................ssss.....ss....s [ 22%]
ssssssss..sssssssssssssssssssssssssssssssssssss.sssss                                                          [ 37%]
anaconda3/lib/python3.8/site-packages/oggm/tests/test_numerics.py sssss.ss.ssssss.s.sssss.sss.sss.s            [ 46%]
anaconda3/lib/python3.8/site-packages/oggm/tests/test_prepro.py .................s.................s...s.....s [ 59%]
ssssssss....s.......                                                                                           [ 65%]
anaconda3/lib/python3.8/site-packages/oggm/tests/test_shop.py sss...........                                   [ 69%]
anaconda3/lib/python3.8/site-packages/oggm/tests/test_utils.py .........................sss.....ssss...s...... [ 82%]
..............ss.s..ssss.ssssss..sss...s.ss.ss.ss....                                                          [ 98%]
anaconda3/lib/python3.8/site-packages/oggm/tests/test_workflow.py ssssss.                                      [100%]

====================================================== FAILURES ======================================================
________________________________________________ test_width_corrected ________________________________________________

args = (), kwargs = {}

    def wrapper(*args, **kwargs):
>       store.return_value[test_name] = obj(*args, **kwargs)

anaconda3/lib/python3.8/site-packages/pytest_mpl/plugin.py:135: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
anaconda3/lib/python3.8/site-packages/oggm/tests/conftest.py:93: in test_wrapper
    return test(*args, **kwargs)
anaconda3/lib/python3.8/site-packages/oggm/tests/test_graphics.py:145: in test_width_corrected
    graphics.plot_catchment_width(gdir, ax=ax, corrected=True,
anaconda3/lib/python3.8/site-packages/oggm/graphics.py:230: in newplotfunc
    out = plotfunc(gdirs, ax=ax, smap=mp, **kwargs)
anaconda3/lib/python3.8/site-packages/oggm/graphics.py:578: in plot_catchment_width
    xi, yi = ogrid.transform(np.asarray(xi)[pok],
anaconda3/lib/python3.8/site-packages/salem/gis.py:706: in transform
    x, y = _crs.ij_to_crs(x, y, crs=self.proj)
anaconda3/lib/python3.8/site-packages/salem/gis.py:667: in ij_to_crs
    ret = transform_proj(self.proj, _crs, x, y)
anaconda3/lib/python3.8/site-packages/salem/gis.py:1312: in transform_proj
    return _transform_internal(p1, p2, x, y, always_xy=True)
anaconda3/lib/python3.8/site-packages/salem/gis.py:1282: in _transform_internal
    return trf.transform(x, y)
anaconda3/lib/python3.8/site-packages/pyproj/transformer.py:812: in transform
    return self._transformer._transform_point(
pyproj/_transformer.pyx:756: in pyproj._transformer._Transformer._transform_point
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = masked_array(data=[],
             mask=False,
       fill_value=1e+20,
            dtype=float64)

    def __float__(self):
        """
        Convert to float.
    
        """
        if self.size > 1:
            raise TypeError("Only length-1 arrays can be converted "
                            "to Python scalars")
        elif self._mask:
            warnings.warn("Warning: converting a masked element to nan.", stacklevel=2)
            return np.nan
>       return float(self.item())
E       ValueError: can only convert an array of size 1 to a Python scalar

anaconda3/lib/python3.8/site-packages/numpy/ma/core.py:4375: ValueError
------------------------------------------------ Captured stderr call ------------------------------------------------
2023-06-20 09:23:01: oggm.cfg: Reading default parameters from the OGGM `params.cfg` configuration file.
2023-06-20 09:23:01: oggm.cfg: Multiprocessing switched OFF according to the parameter file.
2023-06-20 09:23:01: oggm.cfg: Multiprocessing: using all available processors (N=24)
2023-06-20 09:23:01: oggm.cfg: PARAMS['baseline_climate'] changed from `GSWP3_W5E5` to ``.
2023-06-20 09:23:01: oggm.cfg: PARAMS['trapezoid_lambdas'] changed from `2.0` to `1`.
2023-06-20 09:23:01: oggm.cfg: PARAMS['border'] changed from `80` to `40`.
2023-06-20 09:23:01: oggm.cfg: PARAMS['use_winter_prcp_fac'] changed from `True` to `False`.
2023-06-20 09:23:01: oggm.cfg: PARAMS['use_temp_bias_from_file'] changed from `True` to `False`.
2023-06-20 09:23:01: oggm.cfg: PARAMS['evolution_model'] changed from `SemiImplicit` to `FluxBased`.
2023-06-20 09:23:01: oggm.cfg: PARAMS['downstream_line_shape'] changed from `trapezoidal` to `parabola`.
2023-06-20 09:23:01: oggm.cfg: PARAMS['temp_bias_min'] changed from `-15.0` to `-10`.
2023-06-20 09:23:01: oggm.cfg: PARAMS['temp_bias_max'] changed from `15.0` to `10`.
================================================== warnings summary ==================================================
anaconda3/lib/python3.8/site-packages/oggm/tests/test_models.py: 10 warnings
  /public/home/sunqk/anaconda3/lib/python3.8/site-packages/pandas/core/nanops.py:1606: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
  Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
    return np.percentile(values, q, interpolation=interpolation)

anaconda3/lib/python3.8/site-packages/oggm/tests/test_models.py: 120 warnings
anaconda3/lib/python3.8/site-packages/oggm/tests/test_shop.py: 21 warnings
  /public/home/sunqk/anaconda3/lib/python3.8/site-packages/pandas/core/nanops.py:1673: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
  Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
    return np.percentile(values, q, axis=axis, interpolation=interpolation)

anaconda3/lib/python3.8/site-packages/oggm/tests/test_numerics.py::TestIdealisedCases::test_run_until
anaconda3/lib/python3.8/site-packages/oggm/tests/test_numerics.py::TestIdealisedCases::test_run_until
anaconda3/lib/python3.8/site-packages/oggm/tests/test_numerics.py::TestFluxGate::test_find_flux_from_thickness
  <__array_function__ internals>:180: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================== short test summary info ===============================================
FAILED anaconda3/lib/python3.8/site-packages/oggm/tests/test_graphics.py::test_width_corrected - ValueError: can only convert an array of size 1 to a Python scalar
================== 1 failed, 204 passed, 146 skipped, 1 xfailed, 154 warnings in 476.03s (0:07:56) =============

**Comment by pat-schmitt** [comment]
Hi, can you provide a little more context (how did you install oggm, what do you want to do with oggm, ...)?

**Comment by pat-schmitt** [comment]
How did you install oggm (stable version or dev version, see here https://docs.oggm.org/en/stable/installing-oggm.html for explanations)?
Are you doing research or teaching or just want to try out oggm?

In general, the error you see in the tests is not very severe as the tests for the main oggm functionalities have passed. However, the error is an indication that some packages in your environment are not installed correctly.

Probably you can ignore this error and move on. But you can also try to do the installation and the building of the environment again from scratch following the explanations here https://docs.oggm.org/en/stable/installing-oggm.html.

**Comment by qikai-sun** [comment]
Thank you @pat-schmitt.  I want to simulate glacier runoff. and I will try the oggm.
