### ISSUE TITLE
Add new dynamic spinup functionality to tutorials

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/oggm#1601]
I will add the new dynamic spinup functionality from PR https://github.com/OGGM/oggm/pull/1600 to the tutorials for documentation.

**Comment by fmaussion** [comment]
Closed via https://github.com/OGGM/tutorials/pull/87 - still needs review by others, e.g. @anoukvlug

**Comment by pat-schmitt** [comment]
Unfortunately, I have not added the changes of PR https://github.com/OGGM/oggm/pull/1600 (`target_yr` and `target_value`) in https://github.com/OGGM/tutorials/pull/87. This is still on my todo list and therefore I am reopening this issue
