### ISSUE TITLE
Global task: Difficulties in plotting the mass balance of multiple glaciers

### ISSUE THREAD

**Issue by av-manoj** [OGGM/oggm#1605]
Hello OGGM team,

I have been following your tutorials and they are very helpful. I am currently trying to calculate the mass balance of all the glaciers in the Western Himalayas (a total of 9830 glaciers) from 2000 to 2020 in OGGM. And I am using RGI v6.0 - Region:14-03 (first-order region 14, second-order region 03). 

Would you please help me (or guide me to the resources) on how to compile and plot the mass balance of all the 9830 glaciers as a whole. The following are the codes that I have done yet.

from oggm import cfg, utils
cfg.initialize(logging_level='WARNING')

_2023-07-04 10:21:52: oggm.cfg: Reading default parameters from the OGGM `params.cfg` configuration file.
2023-07-04 10:21:52: oggm.cfg: Multiprocessing switched OFF according to the parameter file.
2023-07-04 10:21:52: oggm.cfg: Multiprocessing: using all available processors (N=12)_

cfg.PARAMS['melt_f'], cfg.PARAMS['ice_density'], cfg.PARAMS['continue_on_error']

_(5.0, 900.0, False)_

cfg.PARAMS['use_multiprocessing'] = True

_2023-07-04 10:21:53: oggm.cfg: Multiprocessing switched ON after user settings._

from oggm import workflow

cfg.PATHS['working_dir'] = utils.mkdir('/home/oem/Environments/env01/Results_env01', reset=True)
cfg.PATHS['working_dir']

_'/home/oem/Environments/env01/Results_env01'_

fr = utils.get_rgi_region_file(14, version='62')  # South Area west - W Himalaya

import geopandas as gpd
gdf = gpd.read_file(fr)

gdf_sel = gdf.loc[gdf.O2Region == '3']

'Glacier area in the Pyrenees: {} km2'.format(gdf_sel.Area.sum())

_'Glacier area in the Pyrenees: 7767.598 km2'_

import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
import numpy as np
import os

import oggm
from oggm import cfg, utils, workflow, tasks, graphics
from oggm.core import massbalance
from oggm.core.massbalance import mb_calibration_from_scalar_mb, mb_calibration_from_geodetic_mb, mb_calibration_from_wgms_mb

cfg.initialize(logging_level='WARNING')
cfg.PATHS['working_dir'] = utils.gettempdir(dirname='OGGM-calib-mb', reset=True)
cfg.PARAMS['border'] = 10
cfg.PARAMS['use_multiprocessing'] = True

_2023-07-04 10:22:03: oggm.cfg: Reading default parameters from the OGGM `params.cfg` configuration file.
2023-07-04 10:22:03: oggm.cfg: Multiprocessing switched OFF according to the parameter file.
2023-07-04 10:22:03: oggm.cfg: Multiprocessing: using all available processors (N=12)
2023-07-04 10:22:03: oggm.cfg: PARAMS['border'] changed from `80` to `10`.
2023-07-04 10:22:03: oggm.cfg: Multiprocessing switched ON after user settings._

base_url = 'https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/L3-L5_files/2023.1/elev_bands/W5E5/'
gdirs = workflow.init_glacier_directories(gdf_sel, prepro_base_url=base_url, from_prepro_level=3)

_2023-07-04 10:22:05: oggm.workflow: init_glacier_directories from prepro level 3 on 9830 glaciers.
2023-07-04 10:22:05: oggm.workflow: Execute entity tasks [gdir_from_prepro] on 9830 glaciers_

for gdir in gdirs:
    mbmod = massbalance.MonthlyTIModel(gdir)
    mean_mb = mbmod.get_specific_mb(fls=gdir.read_pickle('inversion_flowlines'),
                                               year=np.arange(2000,2020,1)).mean()
    print(gdir.rgi_id, f': average MB 2000-2020 = {mean_mb:.1f} kg m-2, ',
          f"prcp_fac: {gdir.read_json('mb_calib')['prcp_fac']:.2f}")

_RGI60-14.11362 : average MB 2000-2020 = -524.0 kg m-2,  prcp_fac: 3.08
RGI60-14.11363 : average MB 2000-2020 = -625.7 kg m-2,  prcp_fac: 3.62
RGI60-14.11370 : average MB 2000-2020 = -212.9 kg m-2,  prcp_fac: 4.66
RGI60-14.11371 : average MB 2000-2020 = 277.3 kg m-2,  prcp_fac: 6.99
RGI60-14.11372 : average MB 2000-2020 = -112.7 kg m-2,  prcp_fac: 5.45
RGI60-14.11373 : average MB 2000-2020 = -273.6 kg m-2,  prcp_fac: 3.14
RGI60-14.11374 : average MB 2000-2020 = -268.7 kg m-2,  prcp_fac: 4.64
RGI60-14.11375 : average MB 2000-2020 = -434.5 kg m-2,  prcp_fac: 4.34
RGI60-14.11376 : average MB 2000-2020 = -376.7 kg m-2,  prcp_fac: 3.93
RGI60-14.11377 : average MB 2000-2020 = -212.5 kg m-2,  prcp_fac: 4.01
RGI60-14.11378 : average MB 2000-2020 = -26.8 kg m-2,  prcp_fac: 4.57
RGI60-14.11379 : average MB 2000-2020 = -373.3 kg m-2,  prcp_fac: 3.14
RGI60-14.11380 : average MB 2000-2020 = -119.1 kg m-2,  prcp_fac: 3.25
RGI60-14.11381 : average MB 2000-2020 = -381.6 kg m-2,  prcp_fac: 3.47
RGI60-14.11382 : average MB 2000-2020 = -449.1 kg m-2,  prcp_fac: 2.42
RGI60-14.11383 : average MB 2000-2020 = -301.1 kg m-2,  prcp_fac: 2.42
RGI60-14.11384 : average MB 2000-2020 = -271.9 kg m-2,  prcp_fac: 3.03
RGI60-14.11385 : average MB 2000-2020 = -158.6 kg m-2,  prcp_fac: 3.14
RGI60-14.11386 : average MB 2000-2020 = -283.0 kg m-2,  prcp_fac: 3.70_
so on......

The following error also occurred during the run.
and I am unable to understand this line " AttributeError: 'list' object has no attribute 'read_json' " and " AttributeError: 'list' object has no attribute 'get_inversion_flowline_wh' "

gdirs.read_json('mb_calib')['mb_global_params']

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[23], line 1
----> 1 gdirs.read_json('mb_calib')['mb_global_params']

AttributeError: 'list' object has no attribute 'read_json'
---------------------------------------------------------------------------

wh = gdirs.get_inversion_flowline_wh()
mb_geod = massbalance.MonthlyTIModel(gdirs)
mbdf['mod_mb'] = mb_geod.get_specific_mb(wh, year=mbdf.index)
mbdf.mean()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[25], line 1
----> 1 wh = gdirs.get_inversion_flowline_wh()
      2 mb_geod = massbalance.MonthlyTIModel(gdirs)
      4 mbdf['mod_mb'] = mb_geod.get_specific_mb(wh, year=mbdf.index)

AttributeError: 'list' object has no attribute 'get_inversion_flowline_wh'
---------------------------------------------------------------------------

I am facing difficulties in finding the mass balance (2000-2020) for 9830 glaciers but want to do this for all the glaciers as a whole.

Your help will be appreciated! 
I am new to OGGM so sorry for my novice Python abilities.
let me know if any other information is needed to solve this issue.

**Comment by pat-schmitt** [comment]
The error you are seeing is because you try to open attributes off the list of gdirs. For clarification `gdirs = [gdir1, gdir2, ...]` and for example you can only call `gdir1.read_json('mb_calib')` but not `gdirs.read_json('mb_calib')`, because gdirs is a list and not a real GlacierDirectory. This is also the reason why their are for-loops in the code you posted (e.g. `for gdir in gdirs:`).

So probably you also need to use a for-loop and decide by yourself how to aggregate the information of the individual gdirs.

If you plan to use oggm for longer you should consider joining the Slack channel for more support (https://oggm.org/community/, just write an email to info@oggm.org telling shortly who you are and that you would like to join Slack).
GitHub is meant to be used more or less only for bugs in the code, typos in the documentation or errors in the tutorials and not so much for questions about the usage of oggm (at least I understand it this way ;)). On Slack, there is also a larger community who can help with your questions :)

**Comment by av-manoj** [comment]
Thanks for answering this!! I'll try this way to do it. If I find any issue further then I'll ask it on Slack.
