### ISSUE TITLE
A question about 'tasks.apparent_mb_from_linear_mb'.

### ISSUE THREAD

**Issue by WSXCZ** [OGGM/oggm#1618]
Hi, I am a beginner of OGGM and have recently been modeling glacier thickness using OGGM. I would like to know how this function _**'tasks.apparent_mb_from_linear_mb'**_ is similar and different from[ Farinotti2009](https://www.cambridge.org/core/journals/journal-of-glaciology/article/method-to-estimate-the-ice-volume-and-icethickness-distribution-of-alpine-glaciers/40D2B92744F6512E8DEC142DE6BEA471), can we implement Farinotti2009's method in OGGM?

**Comment by fmaussion** [comment]
Hi, yes its very easy to implement this method. If I remember well they use two gradients for the apparent MB, so the better task to use would be https://docs.oggm.org/en/stable/generated/oggm.tasks.apparent_mb_from_any_mb.html 

But to be honest I think that OGGM's standard inversion is quite equivalent (and superior where climate data is good and parameters are well constrained)

**Comment by WSXCZ** [comment]
Thanks for your reply!
