### ISSUE TITLE
how to update?

### ISSUE THREAD

**Issue by Aixiaoli123456789** [OGGM/oggm#1620]
Dear OGGM,
    I currently have OGGM model version 1.5.3 installed on my computer, how do I update to 1.6?
                                                                                                                                                                            Thank  you  very  much!

**Comment by pat-schmitt** [comment]
Hi,
here in the documentation it is explained how to update your version https://docs.oggm.org/en/stable/installing-oggm.html#install-oggm-itself.
Depending on how old your oggm environment is, it maybe could be a good idea to create a new conda environment with all updated package versions...

**Comment by chen0954** [comment]
Excuse me, have you solved this problem now? Seeing that you are also conducting related experiments on OGGM, I would like to exchange related questions with you.

**Comment by Aixiaoli123456789** [comment]
> Excuse me, have you solved this problem now? Seeing that you are also conducting related experiments on OGGM, I would like to exchange related questions with you.

Sorry，I was recreating an environment, then installing the corresponding python package on it, and then installing the model.
Do you also do some related work? I'm glad to communicate with you.
