### ISSUE TITLE
PytestReturnNotNoneWarning

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1625]
Happening on latest versions - @TimoRoth this is for pytest-mpl I think

**Comment by TimoRoth** [comment]
Do you have a bit more detail on this?
Is it happening in our tests on github here?
Our pytest-mpl fork is pretty much up to date with upstream, minus one irrelevant change.

**Comment by fmaussion** [comment]
In a very recent environment (fresh from yesterday) the graphics tests produce a lot of these warnings:

```
oggm/tests/test_graphics.py::test_catch_areas
  /home/mowglie/.miniconda3/envs/oggm_env_latest/lib/python3.11/site-packages/_pytest/python.py:198: PytestReturnNotNoneWarning: Expected None, but oggm/tests/test_graphics.py::test_catch_areas returned <Figure size 640x480 with 1 Axes>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

I agree its not something we can deal with, probably pytest-mpl are thinking about how to deal with that already (via a fixture? no clue)

**Comment by fmaussion** [comment]
https://github.com/matplotlib/pytest-mpl/issues/183 ?

**Comment by fmaussion** [comment]
OK that's on me then. People need to have pytest-mpl installed otherwise a bunch of tests will do warnings.

**Comment by fmaussion** [comment]
Closed in https://github.com/OGGM/oggm/pull/1629
