### ISSUE TITLE
cannot import name 'DEFAULT_BASE_URL' from 'oggm'

### ISSUE THREAD

**Issue by chen0954** [OGGM/oggm#1637]
Dear OGGM, I'm a code newbie. My package version is as follows：
`# OGGM environment: 
## System info:
    python: 3.11.4.final.0
    python-bits: 64
    OS: Linux
    OS-release: 5.15.90.1-microsoft-standard-WSL2
    machine: x86_64
    processor: x86_64
## Packages info:
    oggm: 1.6.0
    numpy: 1.25.2
    scipy: 1.11.2
    pandas: 2.0.3
    geopandas: 0.13.2
    netCDF4: 1.6.4
    matplotlib: 3.7.2
    rasterio: 1.3.8
    fiona: 1.9.4
    pyproj: 3.6.0
    shapely: 2.0.1
    xarray: 2023.8.0
    dask: 2023.8.1
    salem: 0.0.0
    OGGM git identifier: dd5c520ce73e0fe40e9d06757952320cb5a779f0`

When I run this line of code on jupyter notebook, 
`from oggm import workflow
from oggm import DEFAULT_BASE_URL
DEFAULT_BASE_URL`

I get the following error. 
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 2
      1 from oggm import workflow
----> 2 from oggm import DEFAULT_BASE_URL
      3 DEFAULT_BASE_URL

ImportError: cannot import name 'DEFAULT_BASE_URL' from 'oggm' (/home/cyq/mambaforge/envs/oggm_env/lib/python3.11/site-packages/oggm/__init__.py)`
How should I solve it?

**Comment by pat-schmitt** [comment]
Hi,

you need to update oggm to version 1.6.1. So either you create a new environment with the newest oggm version or you use `pip install --upgrade git+https://github.com/OGGM/oggm.git` to install the latest development version.

You can find all the info how to install oggm here https://docs.oggm.org/en/stable/installing-oggm.html
