### ISSUE TITLE
Can't get the glacier file by following the tutorial in version 1.6.1

### ISSUE THREAD

**Issue by YangCan-nmm** [OGGM/oggm#1639]
I was followed the tutorial(https://oggm.org/tutorials/stable/notebooks/10minutes/preprocessed_directories.html), and I find out the code in the page can't work normal. it showed the glacier file place is wrong, but I have downloaded the file based on the DEFAULT_BASE_URL (https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/L3-L5_files/2023.3/elev_bands/W5E5_spinup). I find out the glacieral file is there. I don't know why the code can't find the file. my oggm version is 1.6.1.  the code and the error information is as following:
<img width="573" alt="微信截图_20230903222115" src="https://github.com/OGGM/oggm/assets/56429004/a2f64b20-fef1-4472-a008-e126b15713d7">
<img width="937" alt="微信截图_20230903222205" src="https://github.com/OGGM/oggm/assets/56429004/0a1780c0-c2c9-42b2-9d19-738ea04a41d4">
![图片1](https://github.com/OGGM/oggm/assets/56429004/15917b2d-bcd3-4c27-bfc6-1cd3110db0d5)

**Comment by pat-schmitt** [comment]
Hi,

when looking at your file path it seems like you are working on Windows. If so, make sure to use the Windows Subsystem for Linux as explained in the documentation ('Warning'- box here https://docs.oggm.org/en/stable/installing-oggm.html#installing-oggm).

Besides, I would recommend you delete all files and redownload them again.

**Comment by anoukvlug** [comment]
Depending on your use case, you might like to use the [OGGM-hub](https://docs.oggm.org/en/stable/cloud.html#oggm-hub) instead of running OGGM locally.
