### ISSUE TITLE
Mass-balance question

### ISSUE THREAD

**Issue by Aixiaoli123456789** [OGGM/oggm#1642]
Hello,
   I know that oggm uses the weight average method to calculate the mass balance of the whole glacier, the weight is the streamline width of each point, how should I obtain the streamline width, and then how to call the function to achieve it.
                                                                                                                                                                          Thank you very much.

**Comment by fmaussion** [comment]
This notebook should help: https://oggm.org/tutorials/stable/notebooks/beginner/plot_mass_balance.html

**Comment by anoukvlug** [comment]
@Aixiaoli123456789, you might consider joining the OGGM slack, our internal communication platform (https://oggm.org/2022/10/11/Welcome-to-the-OGGM-Slack/). There we have a support channel, which is a good place to ask these type of questions :)
