### ISSUE TITLE
Failed test

### ISSUE THREAD

**Issue by Suther11LBU** [OGGM/oggm#1643]
Hi I've installed the stable version of OGGM on Linux. When I run the tests (not the entire test suite), I get the following:

FAILED ../mambaforge/envs/oggm_env/lib/python3.11/site-packages/oggm/tests/test_prepro.py::TestGIS::test_define_region - FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_... 
================================================= 1 failed, 202 passed, 133 skipped, 100 warnings in 298.41s (0:04:58) =================================================

Is this a problem?

**Comment by fmaussion** [comment]
No you should be fine, as long as OGGM runs!

**Comment by Suther11LBU** [comment]
Thank you! It runs fine, was just checking
