### ISSUE TITLE
Using own glacier inventory

### ISSUE THREAD

**Issue by Suther11LBU** [OGGM/oggm#1649]
I am using my own glacier inventory in OGGM, using the exact structure of the RGI file (the only thing that differs are my glacier area values). I run the following lines of code just to check it plots all ok before I move on to other tasks but I get the following error message which I don't understand:
oggm.exceptions.InvalidWorkflowError: This glacier directory seems to have lost its glacier_grid.json file.Use .grid_from_params(), but make surethat the PARAMS are the ones you want.

`from oggm import utils, cfg, workflow, graphics`
`import geopandas as gpd`
`cgidf = gpd.read_file('LIA_outlines_forOGGM.shp')`
`cgidf`
`rgidf_simple = utils.cook_rgidf(cgidf, o1_region='08')`
`rgidf_simple`
`cfg.initialize(logging_level='WARNING')`
`cfg.PARAMS['use_multiprocessing'] = True`
`cfg.PARAMS['use_rgi_area'] = False`
`cfg.PARAMS['use_intersects'] = False`
`cfg.PATHS['working_dir'] = 'OGGM_outputs'`
`
gdirs = workflow.init_glacier_directories(rgidf_simple)
`
`utils.compile_glacier_statistics(gdirs)`
`graphics.plot_domain(gdirs, figsize=(6, 5))
`

How can I solve this? Thanks!

**Comment by anoukvlug** [comment]
It looks like you skipped some steps. In the following [section](https://oggm.org/tutorials/stable/notebooks/advanced/use_your_own_inventory.html#run-oggm-with-this-new-glacier) of the tutorial you will find the steps you need to do first, before you can plot the domain. Good luck with the plot :)

**Comment by Suther11LBU** [comment]
Great, thank you very much for getting back to me so quickly! Successfully plotted now :)

**Comment by anoukvlug** [comment]
I'm happy to hear that! Just in case you aren't aware, we have an internal communication platform, the OGGM slack, where among others model support is being offered (see the following [blog post](https://oggm.org/2022/10/11/Welcome-to-the-OGGM-Slack/) for details).
