### ISSUE TITLE
Implement and document a way to combine external thickness data with dynamic spinup

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1655]
This request comes often enough and is reasonable.

@pat-schmitt , I think we can reasonably get this to work without too much work. What do you think? Something for OGGM 1.6.2?

**Comment by pat-schmitt** [comment]
Do you mean defining the glacier bed with thickness observations and doing the dynamic calibration (dynamic melt_f and dynamic spinup) without an inversion? If yes, this is already possible and I can document it somewhere in the tutorials.

However, in such a case the user must decide on the value for A, by default it is defined during the inversion to match the volume. For a clean solution, it probably would need a function to calibrate A. I have two possibilities in mind:

1.  Could be an extra loop in the dynamic calibration procedure: still have one consistent calibration/initialisation modelling chain and no equilibrium assumption incorporated, but probably more work (compared to 2.) and not computationally very efficient (for small regions not so much of a deal...)
2. We can use the existing inversion function (just do an inversion matching the volume to find an A value, but do not use the inverted glacier bed later on): would only need little adaptation to the existing code and no extra computation time, use of equilibrium assumption and needed to be tested if this is good enough
