### ISSUE TITLE
How to use my own glacier dataset?

### ISSUE THREAD

**Issue by Nicole1150** [OGGM/oggm#1670]
How to use my own glacier dataset instead of the RGI6.0 data?

**Comment by pat-schmitt** [comment]
Hi @Nicole1150, if you plan to use oggm and have questions about the usage you should consider joining slack, here's a short introduction https://oggm.org/2022/10/11/Welcome-to-the-OGGM-Slack/.
And here is a blog post on how to proceed if you get stuck using oggm https://oggm.org/2023/11/02/error-guide/.
