### ISSUE TITLE
workflow.init_glacier_directories:file not found

### ISSUE THREAD

**Issue by maluma013** [OGGM/oggm#1672]
hello! I tried to work in OGGM with glacier shape file in OGGM. I followed the tutorial but got an error.I tried many times, including redefining the url, changing the oggm version, but always the same error.
Here is my code:

`from oggm import cfg, workflow, tasks,utils
import geopandas as gpd

cfg.initialize(logging_level='WARNING')
cfg.PARAMS['continue_on_error'] = True
cfg.PARAMS['use_multiprocessing'] = True
cfg.PARAMS['border'] = 80
cfg.PATHS['working_dir'] = 'I:\\flood risk in snowmelt\\data\\OGGM_output'
cfg.PARAMS['rgi_version'] = 62

rgi_ids = ['RGI60-11.01328','RGI60-11.00897']

gdirs = workflow.init_glacier_directories(
    rgi_ids,  
    prepro_base_url=DEFAULT_BASE_URL, 
    from_prepro_level=4, 
    prepro_border=80
)`

The output thrown out is:

`2024-01-11 19:48:50: oggm.cfg: Reading default parameters from the OGGM `params.cfg` configuration file.
2024-01-11 19:48:50: oggm.cfg: Multiprocessing switched OFF according to the parameter file.
2024-01-11 19:48:50: oggm.cfg: Multiprocessing: using all available processors (N=8)
2024-01-11 19:48:52: oggm.cfg: PARAMS['continue_on_error'] changed from `False` to `True`.
2024-01-11 19:48:52: oggm.cfg: Multiprocessing switched ON after user settings.
2024-01-11 19:48:52: oggm.cfg: PARAMS['rgi_version'] changed from `62` to `62`.
2024-01-11 19:48:54: oggm.workflow: init_glacier_directories from prepro level 4 on 2 glaciers.
2024-01-11 19:48:55: oggm.workflow: Execute entity tasks [gdir_from_prepro] on 2 glaciers

{
	"name": "KeyError",
	"message": "\"filename 'RGI60-11.00\\\\\\\\RGI60-11.00897.tar.gz' not found\"",
	"stack": "---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
\"\"\"
Traceback (most recent call last):
  File \"d:\\mambaforge\\envs\\oggm_env\\Lib\\multiprocessing\\pool.py\", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File \"d:\\mambaforge\\envs\\oggm_env\\Lib\\multiprocessing\\pool.py\", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File \"d:\\mambaforge\\envs\\oggm_env\\Lib\\site-packages\\oggm\\workflow.py\", line 108, in __call__
    res = self._call_internal(func, arg, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"d:\\mambaforge\\envs\\oggm_env\\Lib\\site-packages\\oggm\\workflow.py\", line 102, in _call_internal
    return call_func(gdir, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"d:\\mambaforge\\envs\\oggm_env\\Lib\\site-packages\\oggm\\workflow.py\", line 251, in gdir_from_prepro
    return oggm.GlacierDirectory(entity, from_tar=from_tar)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"d:\\mambaforge\\envs\\oggm_env\\Lib\\site-packages\\oggm\\utils\\_workflow.py\", line 2494, in __init__
    robust_tar_extract(from_tar, _dir, delete_tar=delete_tar)
  File \"d:\\mambaforge\\envs\\oggm_env\\Lib\\site-packages\\oggm\\utils\\_workflow.py\", line 2379, in robust_tar_extract
    _back_up_retry(func, RuntimeError)
  File \"d:\\mambaforge\\envs\\oggm_env\\Lib\\site-packages\\oggm\\utils\\_workflow.py\", line 2334, in _back_up_retry
    return func()
           ^^^^^^
  File \"d:\\mambaforge\\envs\\oggm_env\\Lib\\site-packages\\oggm\\utils\\_workflow.py\", line 2375, in func
    i_from_tar = tf.getmember(os.path.join(dirbname, bname))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"d:\\mambaforge\\envs\\oggm_env\\Lib\\tarfile.py\", line 1984, in getmember
    raise KeyError(\"filename %r not found\" % name)
KeyError: \"filename 'RGI60-11.00\\\\\\\\RGI60-11.00897.tar.gz' not found\"
\"\"\"
`
it was always showing:"KeyError: \"filename 'RGI60-11.00\\\\\\\\RGI60-11.00897.tar.gz' not found\"

**Comment by fmaussion** [comment]
@maluma013 - you seem to be using windows. OGGM does not work on windows unfortunately: https://docs.oggm.org/en/stable/installing-oggm.html

**Comment by maluma013** [comment]
> @maluma013 - you seem to be using windows. OGGM does not work on windows unfortunately: https://docs.oggm.org/en/stable/installing-oggm.html

I do use windows system，it was a big mistake tt. I will try another system later. Thank you for your reply!
