### ISSUE TITLE
docs issues with preprocessing directories, addition of a clear workflow between levels 

### ISSUE THREAD

**Issue by bearecinos** [OGGM/oggm#1675]
This issue is related to those posted on [tutorials](https://github.com/OGGM/tutorials/issues/112). 

> We (@ehultee, @bearecinos and @suther11LBU) are adding other thoughts related to the docs here.

**General comments**
Flag **when you CAN’T use pre-processing directories** and from which level you should start if you are introducing different input data (e.g. different DEM, Climate, outlines). I think this is obvious of us and is already written in the docs, but is often missed by new users! probably a big headline should be added here: https://docs.oggm.org/en/latest/shop.html#pre-processed-directories
On that section we also need to link to a full workflow of how to reproduce the different levels and how to pick up from each level into the next...

@suther11LBU: 
I know we don’t really want to propose new tutorials but I do think one is needed for people who want to start from scratch and redo the pre-processing steps for their runs. There is a nice flowchart in the [Glacier Flowlines page](https://docs.oggm.org/en/latest/flowlines.html#compatibility-within-the-oggm-framework) which was super helpful for me to understand the workflow but I think it might be a little lost for people who don’t trawl through documentation as much as I do. 

**Action**
- Documenting a clear/template workflow would be a good idea.
The aim of this should be documenting the connectivity between pre-processing tasks done with different input data and how to continue to other parts of the model workflow from there.

**Comment by pat-schmitt** [comment]
Yes, a notebook showing the complete workflow for deriving the preprocessed directories, with explicitly setting all data used during the process would be very helpful. This is often requested. Including links in this notebook to more advanced notebooks along the workflow could give a good overview, especially for new users.

Probably we would need two notebooks, one for elevation bands and one for centerlines as they differ quite a bit, as illustrated in the flowchart linked above. (to propose one more new notebook ;))

I am happy to help, as I have already some drafts for this lying around.

**Comment by pat-schmitt** [comment]
Hi, I just added the first version for such a tutorial (including both elevation bands and centerlines) https://github.com/OGGM/tutorials/pull/120.

If anyone finds the time, I would appreciate any feedback :)

**Comment by bearecinos** [comment]
@pat-schmitt I will run them and let you know next week during the workshop meeting ... on them already!

**Comment by fmaussion** [comment]
Let's move this discussion to the tutorials if necessary.
