### ISSUE TITLE
Unable to access CERA20C data

### ISSUE THREAD

**Issue by tamnnm** [OGGM/oggm#1680]
Dear all, 
I'm currently working on an analysis based on reanalysis datasets which includes CERA20C daily (temperature + precipitation). I've encountered extremely informative tutorials and resources. However, I could not access the CERA20C through the provided link or the public data web or any got resources on CERA20C monthly. Is there any other way or access link that I can retrieve this dataset since on the public port, I would only see the ERA5 provided?

Thank you and wish you all a good day.

**Comment by anoukvlug** [comment]
Dear @tamnnm,
Thank you for the notification. Currently I can't reach the [website](https://cluster.klima.uni-bremen.de/~oggm/) either. I will get back to you once I know what is going on.

**Comment by anoukvlug** [comment]
@tamnnm, I'm not sure what precisely was going on, but in the mean time I can reach the website again. Could you check if your issue is solved now? 
Just in case, here is the [link](https://cluster.klima.uni-bremen.de/~oggm/climate/cera-20c/monthly/v1.0/) to the CERA20C data.

**Comment by tamnnm** [comment]
@anoukvlug  Thank you for your prompt response. I was accessing the dataset through this [link](https://cluster.klima.uni-bremen.de/~fmaussion/climate/) which comes in the tutorial pointing to ~fmaussion branch. However, I have now been able to access to the data thanks to your help. Thank you very much again.

**Comment by anoukvlug** [comment]
@tamnnm, I'm happy to hear your issue has been solved. Which tutorial uses that link? It seems like it deserves some updating. I only in my quick search couldn't find the tutorial you referred to.

**Comment by tamnnm** [comment]
The tutorial I have followed was from [fmaussion](https://gist.github.com/fmaussion/3f31bdf90fdccd86692c73f0ef095c4e), which might not directly related to OGGM but was in the same directory. Hence, I was able to trace back to OGGM github. Thank you for your time and consideration.

**Comment by anoukvlug** [comment]
Thank you for the information @tamnnm.
