### ISSUE TITLE
How did we calibrate the default ’mb_calib.json‘ file in the pre-processed directories with the three-step process?

### ISSUE THREAD

**Issue by Nicole1150** [OGGM/oggm#1681]
What is the parameter calibration order? ('melt_f', 'temp_bias', 'prcp_fac')

**Comment by anoukvlug** [comment]
Hi @Nicole1150, you can find the details about the mass balance calibration in the following [tutorial](https://oggm.org/tutorials/stable/notebooks/advanced/massbalance_calibration.html?highlight=mb+calibration#).  

As a side note, questions about OGGM usage can best be asked in the [OGGM slack](https://oggm.org/2022/10/11/Welcome-to-the-OGGM-Slack/) support channel. In addition I would recommend you to read the [blog post](https://oggm.org/2023/11/02/error-guide/) on how to proceed if you get stuck using OGGM.

**Comment by fmaussion** [comment]
Feel free to reopen if there is something we should do in OGGM.
