### ISSUE TITLE
The annual runoff components

### ISSUE THREAD

**Issue by Nicole1150** [OGGM/oggm#1695]
Could someone please explain if these four components of the runoff ’melt_off_glacier‘, 'melt_on_glacier', 'liq_prcp_off_glacier', 'liq_prcp_on_glacier' can represent the surface water resources of the basin?

<img width="389" alt="1710208883619" src="https://github.com/OGGM/oggm/assets/103488171/73bb90a7-0408-4a5d-b48e-e774a29233f6">

**Comment by lilianschuster** [comment]
Hi Jingyao Sun @Nicole1150,
Please look into the OGGM-edu tutorials https://oggm.org/oggm-edu-notebooks/oggm-edu/glacier_water_resources.html and https://oggm.org/oggm-edu-notebooks/oggm-edu/glacier_water_resources_projections.html.  
The four components describe the runoff from the previously glaciated area (here in this example that you show, the sum of the four runoff component describe the runoff from the glaciated area as modelled in 1980!). It does not represent the surface water resources of the entire basin, only from the selected glacier areas!!! 
These studies using the runoff components might help you to understand it further: https://doi.org/10.5194/egusphere-2023-2325 , https://egusphere.copernicus.org/preprints/2024/egusphere-2023-2562/ , https://doi.org/10.1017/aog.2023.57 . 
Please write further questions into the OGGM slack #support channel .

**Comment by Nicole1150** [comment]
Thank you. This means that the runoff simulated by the model can only represent all the runoff in the selected glacier area, including precipitation, melt and snow runoff.
