### ISSUE TITLE
Mass balance calibration using `mb_calibration_from_scalar_mb'

### ISSUE THREAD

**Issue by Nicole1150** [OGGM/oggm#1696]
Why is the mean value of `mod_mb` for each glacier from 2000 to 2020, obtained by using `mb_calibration_from_scalar_mb` for mass balance calibration, exactly equal to the reference value `ref_mb`? I think these two values should not be exactly equal.
code:
```
mb_df = pd.DataFrame(index=np.arange(2000, 2020, 1))
# reference MB
for gdir in gdirs:
    ref_mb_df = utils.get_geodetic_mb_dataframe().loc[gdir.rgi_id]
    ref_mb_df = ref_mb_df.loc[ref_mb_df['period'] == cfg.PARAMS['geodetic_mb_period']].iloc[0]
    # kg m-2 yr-1
    ref_mb = ref_mb_df['dmdtda'] * 1000
    
    # mass_balance
    mb_calibration_from_scalar_mb(gdir,
                                  ref_mb = ref_mb,
                                  calibrate_param1='melt_f',
                                  calibrate_param2='prcp_fac',
                                  calibrate_param3='temp_bias',
                                  ref_period = cfg.PARAMS['geodetic_mb_period'],
                                  overwrite_gdir=True)   
   
    mb_melt_f = massbalance.MonthlyTIModel(gdir)
    mb_df['mod_mb_melt_f'] = mb_melt_f.get_specific_mb(h, w, year=mb_df.index)
```
Example results：
![1710211154908](https://github.com/OGGM/oggm/assets/103488171/06128fa0-c1e5-4827-9a91-ef3926ce438c)

**Comment by lilianschuster** [comment]
Hi @Nicole1150 ,
I am not sure if I understand your question. By doing `mb_calibration_from_scalar_mb` we calibrate the glacier model parameters to match the average observed mass-balance (here from year 2000-2019). We do not have observations for every year, but just the average over the 2000-2019, that is the reason why the mean value (your `mod_mb`) matches the  `ref_mb`. 
More information about this calibration procedure is in https://oggm.org/tutorials/stable/notebooks/advanced/massbalance_calibration.html. 
Please ask further questions in the OGGM #support channel!

**Comment by Nicole1150** [comment]
Hi @lilianschuster , I have another question that puzzles me. My glacier has no in-situ MB data. If all parameter combinations obtained under different calibration orders satisfy that the values of 'mod_mb' and 'ref_mb' are equal, how should I choose the optimal parameters and evaluate the calibration performance of the model?

**Comment by anoukvlug** [comment]
@Nicole1150, questions regarding model use are better suited for the [OGGM slack](https://oggm.org/2022/10/11/Welcome-to-the-OGGM-Slack/) #support channel. The github is meant for model development related issues and bugs, not general model support. The following blog post, [Help, an error! A short guide on what to do when you get stuck or have a question](https://oggm.org/2023/11/02/error-guide/), serves as a guidance for how to deal with questions and where best to ask them.
