### ISSUE TITLE
How do I use my own data in Ice thickness inversion?

### ISSUE THREAD

**Issue by KReeves092** [OGGM/oggm#1699]
I want to use my own data in [Ice thickness inversion](https://oggm.org/tutorials/stable/notebooks/beginner/inversion.html), such as glacier boundary and DEM data. I have already read the tutorial on changing glacier boundary ([Using your our own glacier inventory with OGGM](https://oggm.org/tutorials/stable/notebooks/advanced/use_your_own_inventory.html)), but how to change the DEM and use elevation data?

**Comment by anoukvlug** [comment]
@KReeves092, please have a look at the [Create local topography maps from different DEM sources with OGGM](https://oggm.org/tutorials/stable/notebooks/advanced/dem_sources.html#) tutorial. It explains how different DEMs can be used.

As a general remark, questions regarding model use are better suited for the [OGGM slack](https://oggm.org/2022/10/11/Welcome-to-the-OGGM-Slack/) #support channel. The OGGM github issues are meant for model development related issues and bugs, not general model support. The following blog post, [Help, an error! A short guide on what to do when you get stuck or have a question](https://oggm.org/2023/11/02/error-guide/), serves as a guidance for how to deal with questions and where best to ask them.

**Comment by fmaussion** [comment]
We also have a tutorial for this now: https://tutorials.oggm.org/master/notebooks/tutorials/observed_thickness_with_dynamic_spinup.html 

Feel free to open this issue if needed.
