### ISSUE TITLE
Error with testGIS when testing my OGGM installation

### ISSUE THREAD

**Issue by millie-spencer** [OGGM/oggm#1704]
I got one error when trying to test my OGGM installation per the directions [here](https://docs.oggm.org/en/stable/installing-oggm.html#test-oggm): TestGIS.test_gridded_data_var_to_geotiff. 
Any ideas as to what could have caused this error and how I can resolve it? 
Attaching screenshot of the error code
Thanks!
<img width="1342" alt="ss1" src="https://github.com/OGGM/oggm/assets/127904183/d7ad6aef-0987-4888-8f17-2cbaa04012f7">
<img width="1448" alt="ss2" src="https://github.com/OGGM/oggm/assets/127904183/5e33a6b2-b409-4f15-8041-3ecb80f9ab88">

**Comment by fmaussion** [comment]
Thanks for the report - you can safely ignore this error, it was a bug in salem (these tests have been updated in OGGM latest, and will be published with an OGGM update later this month)

**Comment by millie-spencer** [comment]
Thanks for the quick reply!
