### ISSUE TITLE
pytest.oggm takes too long and has a failed

### ISSUE THREAD

**Issue by hou312** [OGGM/oggm#1707]
Using conda's latest oggm installation, my pytest took about 40 minutes, mostly stuck at test_utils.py. 
Failed is of type anaconda3 / envs/oggm/lib/python3.11 / site - packages/oggm/tests/test_prepro. Py: 506: AssertionError.
I have attached the complete test report, hoping to get some help.
[pytest.txt](https://github.com/OGGM/oggm/files/15137359/pytest.txt)

**Comment by anoukvlug** [comment]
@hou312, the problem you describe looks the same as the one raised, and resolved in the mean time, in issue #1704. I would advise you to have a look at it :)

**Comment by hou312** [comment]
> ，您描述的问题看起来与问题 #1704 中提出的问题相同，并同时得到解决。我建议你看一看:)

I also found that this problem had little impact in subsequent applications, so I did not pay attention to the reply in time. Thank you very much for your message.

**Comment by anoukvlug** [comment]
You're welcome :) I will close this issue, but feel free to re-open it if needed.
