### ISSUE TITLE
level 5 data for glacier is not available 

### ISSUE THREAD

**Issue by shahidusmaninfo** [OGGM/oggm#1708]
I am working on shiger vally glacier
but level 5 data of ogmm is not downloading properly it says remote error , what to do

**Comment by anoukvlug** [comment]
@shahidusmaninfo, without the code you used and error log, I'm not sure what is going on. Having said that, questions regarding model use are better suited for the [OGGM slack](https://oggm.org/2022/10/11/Welcome-to-the-OGGM-Slack/) #support channel. The github is meant for model development related issues and bugs, not general model support. The following blog post, [Help, an error! A short guide on what to do when you get stuck or have a question](https://oggm.org/2023/11/02/error-guide/), serves as a guidance for how to deal with questions and where best to ask them. :)
