### ISSUE TITLE
Shutdown of OGGM servers from July 18 to July 22

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1716]
Dear OGGM users,

The OGGM servers, serving all OGGM related data and infrastructure (oggm-edu apps, the two jupyter hubs, etc) will be shut down for maintenance from Thursday, the 18th of July at around 20:00 CEST, until at least the following Monday at 8:00 CEST.

None of the OGGM downloads will be available during that time.

**Comment by Morlocke** [comment]
Still seems unavailable at 09:30 CEST on July 23rd?

**Comment by lilianschuster** [comment]
Yes, the cluster and servers are still unavailable. @TimoRoth  wrote in the OGGM Slack that the cluster's central switch did not boot back up. As he is currently not in Bremen, where the cluster is located, he has to wait for the response of some local people to manually power-cycle the switch. That means,  he can not yet say when the cluster/servers will work again.

**Comment by Morlocke** [comment]
OK, thanks for the clarification!

**Comment by lilianschuster** [comment]
just wanted to repeat the update from @TimoRoth in case someone has no access to OGGM slack: 
- For now, the cluster remains down for running jobs on it, but you can log in again and access your data, and the data files for OGGM are also reachable again!
