### ISSUE TITLE
Wrong version when downloaded

### ISSUE THREAD

**Issue by Adokan11** [OGGM/oggm#1728]
I've installed oggm, and I'm super confused as even though I've installed 1.6.1, at least one of the files in it seem to be the same as version 1.6.0 (core.gis.py). I even found this was the case when I downloaded oggm as a zip directly from here. This has given me a huge amount of errors in all the tests (mostly related to the deprecated np.NaN). I was just checking here to see if I've done something wrong.

**Comment by fmaussion** [comment]
I'm not sure what you mean with "wrong version" but we recommend to install OGGM via pip (not downloading the zip). 

OGGM is currently not compatible with numpy 2.0 which came out recently - please try to downgrade numpy or create a new environment using this file and report again. 

Note that we are in the process of release a new OGGM version within a few days - it still wont be numpy 2 compatible but we are working on it.

```
name: oggm_env
channels:
  - conda-forge
dependencies:
  - python<3.12
  - numpy<2.0
  - scipy
  - pandas
  - shapely
  - matplotlib
  - Pillow
  - netcdf4
  - scikit-image
  - configobj
  - xarray
  - pytest
  - dask
  - bottleneck
  - pyproj
  - cartopy
  - geopandas
  - rasterio
  - rioxarray
  - seaborn
  - pytables
  - salem
  - motionless
  - pip
  - pip:
    - joblib
    - progressbar2
    - git+https://github.com/OGGM/pytest-mpl
    - oggm
```

**Comment by Adokan11** [comment]
Ah ok, thank you, it is all working now. I had not realised there was an incompatibility with numpy 2.0.
