### ISSUE TITLE
oggm installation issues

### ISSUE THREAD

**Issue by vcollavini** [OGGM/oggm#1752]
Hello! I am currently having some issues when testing oggm (installation phase) with `pytest.oggm  --disable-warnings`.
Firstly, I downloaded oggm as reported [here](https://docs.oggm.org/en/v1.6.1/installing-oggm.html#install-oggm-itself), run the command `pip install oggm`, created the environment through `conda env create -f environment.yml` and activated it with `conda activate oggm_env`.

However, when I run the system for testing, I get two errors. Below you find some of the output from anaconda prompt.

Thanks, and looking forward for your feedback!

(oggm_env) C:\Users\valen>pytest.oggm
=========================== test session starts ===========================
platform win32 -- Python 3.11.10, pytest-8.3.3, pluggy-1.5.0
Matplotlib: 3.9.2
Freetype: 2.12.1
rootdir: C:\Users\valen
plugins: mpl-0.170.1, typeguard-4.3.0
collected 369 items

anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\test_benchmarks.py . [  0%]
..s.ss                                                               [  1%]
anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\test_graphics.py . [  2%]
s........s...s...x.sss                                               [  8%]
anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\test_minimal.py . [  8%]
..                                                                   [  8%]
anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\test_models.py . [  9%]
..............................ssss.....ss....sssssssss..ssssssssssss [ 27%]
sssssssssssssssssssssssssFsssssss                                    [ 36%]
anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\test_numerics.py s [ 36%]
ssss.ssFssssss.s.sssss.sss.ssss.s                                    [ 45%]
anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\test_prepro.py . [ 46%]
.........F.......s.................s...s.....sssssssss....s........  [ 64%]
anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\test_sandbox.py s [ 64%]
sss                                                                  [ 65%]
anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\test_shop.py ss [ 65%]
ssFF.....FFE...Es                                                    [ 69%]
anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\test_utils.py . [ 70%]
..........................sss.FFFFssss.FFs.....FF............Fss.s.. [ 88%]
ssss.ssssss..sss...s.ss.ss.ss....                                    [ 97%]
anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\test_workflow.py s [ 97%]
ssssss..                                                             [100%]

================================= ERRORS ==================================
___________ ERROR at teardown of Test_ecmwf.test_ecmwf_workflow ___________

request = <SubRequest 'class_case_dir' for <Function test_ecmwf_historical_delta_method>>
test_dir = 'C:\\Users\\valen\\OGGM\\tests\\90abb9b5a6e9e9252fb3e136c30627b5'

    @pytest.fixture(scope='class')
    def class_case_dir(request, test_dir):
        """ Provides a unique directory for the current test class, a child of
            the session test directory (test_dir > class_case_dir). Named after
            the current test class.
            As a class-scoped fixture, a class directory is created once for
            the current class and used by each test inside it. It is cleaned
            up when the all the cases in the class complete.
        """
        cd = _setup_case_dir(request.cls, test_dir)
        yield cd
>       _teardown_case_dir(cd)

anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\conftest.py:270:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\conftest.py:242: in _teardown_case_dir
    shutil.rmtree(casedir)
anaconda3\envs\oggm_env\Lib\shutil.py:787: in rmtree
    return _rmtree_unsafe(path, onerror)
anaconda3\envs\oggm_env\Lib\shutil.py:629: in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
anaconda3\envs\oggm_env\Lib\shutil.py:629: in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
anaconda3\envs\oggm_env\Lib\shutil.py:629: in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
anaconda3\envs\oggm_env\Lib\shutil.py:629: in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
anaconda3\envs\oggm_env\Lib\shutil.py:634: in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = 'C:\\Users\\valen\\OGGM\\tests\\90abb9b5a6e9e9252fb3e136c30627b5\\Test_ecmwf\\per_glacier\\RGI50-11\\RGI50-11.00\\RGI50-11.00897'
onerror = <function rmtree.<locals>.onerror at 0x000002BDB8369DA0>

    def _rmtree_unsafe(path, onerror):
        try:
            with os.scandir(path) as scandir_it:
                entries = list(scandir_it)
        except OSError:
            onerror(os.scandir, path, sys.exc_info())
            entries = []
        for entry in entries:
            fullname = entry.path
            if _rmtree_isdir(entry):
                try:
                    if entry.is_symlink():
                        # This can only happen if someone replaces
                        # a directory with a symlink after the call to
                        # os.scandir or entry.is_dir above.
                        raise OSError("Cannot call rmtree on a symbolic link")
                except OSError:
                    onerror(os.path.islink, fullname, sys.exc_info())
                    continue
                _rmtree_unsafe(fullname, onerror)
            else:
                try:
>                   os.unlink(fullname)
E                   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\valen\\OGGM\\tests\\90abb9b5a6e9e9252fb3e136c30627b5\\Test_ecmwf\\per_glacier\\RGI50-11\\RGI50-11.00\\RGI50-11.00897\\climate_historicalCERA.nc'

anaconda3\envs\oggm_env\Lib\shutil.py:632: PermissionError
-------------------------- Captured stderr call ---------------------------
2024-11-10 10:43:35: oggm.cfg: Reading default parameters from the OGGM `params.cfg` configuration file.
2024-11-10 10:43:35: oggm.cfg: Multiprocessing switched OFF according to the parameter file.
2024-11-10 10:43:35: oggm.cfg: Multiprocessing: using all available processors (N=12)
2024-11-10 10:43:35: oggm.cfg: PARAMS['use_intersects'] changed from `True` to `False`.
2024-11-10 10:43:35: oggm.workflow: Execute entity tasks [GlacierDirectory] on 1 glaciers
2024-11-10 10:43:35: pyogrio._io: Created 1 records
2024-11-10 10:43:35: oggm.cfg: PARAMS['baseline_climate'] changed from `GSWP3_W5E5` to `CERA+ERA5L`.
2024-11-10 10:43:35: oggm.core.climate: (RGI50-11.00897) process_climate_data
2024-11-10 10:43:35: oggm.shop.ecmwf: (RGI50-11.00897) process_ecmwf_datatmp_CERA
2024-11-10 10:43:35: oggm.shop.ecmwf: (RGI50-11.00897) process_ecmwf_datatmp_ERA5L
2024-11-10 10:43:35: oggm.core.climate: (RGI50-11.00897) historical_delta_method
2024-11-10 10:43:35: oggm.core.climate: PermissionError occurred during task historical_delta_method on RGI50-11.00897: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\valen\\OGGM\\tests\\90abb9b5a6e9e9252fb3e136c30627b5\\Test_ecmwf\\per_glacier\\RGI50-11\\RGI50-11.00\\RGI50-11.00897\\climate_historicaltmp_ERA5L.nc'
2024-11-10 10:43:35: oggm.core.climate: PermissionError occurred during task process_climate_data on RGI50-11.00897: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\valen\\OGGM\\tests\\90abb9b5a6e9e9252fb3e136c30627b5\\Test_ecmwf\\per_glacier\\RGI50-11\\RGI50-11.00\\RGI50-11.00897\\climate_historicaltmp_ERA5L.nc'
__________ ERROR at teardown of Test_bedtopo.test_add_consensus ___________

request = <SubRequest 'class_case_dir' for <Function test_add_consensus>>
test_dir = 'C:\\Users\\valen\\OGGM\\tests\\90abb9b5a6e9e9252fb3e136c30627b5'

    @pytest.fixture(scope='class')
    def class_case_dir(request, test_dir):
        """ Provides a unique directory for the current test class, a child of
            the session test directory (test_dir > class_case_dir). Named after
            the current test class.
            As a class-scoped fixture, a class directory is created once for
            the current class and used by each test inside it. It is cleaned
            up when the all the cases in the class complete.
        """
        cd = _setup_case_dir(request.cls, test_dir)
        yield cd
>       _teardown_case_dir(cd)

anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\conftest.py:270:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
anaconda3\envs\oggm_env\Lib\site-packages\oggm\tests\conftest.py:242: in _teardown_case_dir
    shutil.rmtree(casedir)
anaconda3\envs\oggm_env\Lib\shutil.py:787: in rmtree
    return _rmtree_unsafe(path, onerror)
anaconda3\envs\oggm_env\Lib\shutil.py:629: in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
anaconda3\envs\oggm_env\Lib\shutil.py:629: in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
anaconda3\envs\oggm_env\Lib\shutil.py:629: in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
anaconda3\envs\oggm_env\Lib\shutil.py:629: in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
anaconda3\envs\oggm_env\Lib\shutil.py:634: in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = 'C:\\Users\\valen\\OGGM\\tests\\90abb9b5a6e9e9252fb3e136c30627b5\\Test_bedtopo\\per_glacier\\RGI60-11\\RGI60-11.00\\RGI60-11.00897'
onerror = <function rmtree.<locals>.onerror at 0x000002BDB8368180>

    def _rmtree_unsafe(path, onerror):
        try:
            with os.scandir(path) as scandir_it:
                entries = list(scandir_it)
        except OSError:
            onerror(os.scandir, path, sys.exc_info())
            entries = []
        for entry in entries:
            fullname = entry.path
            if _rmtree_isdir(entry):
                try:
                    if entry.is_symlink():
                        # This can only happen if someone replaces
                        # a directory with a symlink after the call to
                        # os.scandir or entry.is_dir above.
                        raise OSError("Cannot call rmtree on a symbolic link")
                except OSError:
                    onerror(os.path.islink, fullname, sys.exc_info())
                    continue
                _rmtree_unsafe(fullname, onerror)
            else:
                try:
>                   os.unlink(fullname)
E                   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\valen\\OGGM\\tests\\90abb9b5a6e9e9252fb3e136c30627b5\\Test_bedtopo\\per_glacier\\RGI60-11\\RGI60-11.00\\RGI60-11.00897\\consensus.tif'

anaconda3\envs\oggm_env\Lib\shutil.py:632: PermissionError

============================ warnings summary =============================
anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_numerics.py::TestIdealisedCases::test_mass_redistribution_retreat
  C:\Users\valen\anaconda3\envs\oggm_env\Lib\site-packages\oggm\core\flowline.py:904: RuntimeWarning: overflow encountered in scalar multiply
    t = (y - self.y0) * SEC_IN_YEAR

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= short test summary info =========================
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_models.py::TestMassRedis::test_hef_retreat - AssertionError:
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_numerics.py::TestIdealisedCases::test_mass_redistribution_retreat - assert 68.0 == 69
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_prepro.py::TestGIS::test_gridded_data_var_to_geotiff - PermissionError: [WinError 32] The process cannot access the file becau...
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_shop.py::Test_rgitopo::test_from_dem - KeyError: "filename 'RGI60-09.01\\\\RGI60-09.01004.tar.gz' not found"
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_shop.py::Test_rgitopo::test_qc - KeyError: "filename 'RGI60-09.01\\\\RGI60-09.01004.tar.gz' not found"
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_shop.py::Test_ecmwf::test_ecmwf_historical_delta_method - PermissionError: [WinError 32] The process cannot access the file becau...
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_shop.py::Test_ecmwf::test_ecmwf_workflow - PermissionError: [WinError 32] The process cannot access the file becau...
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_utils.py::TestDLVerify::test_corrupted_file - KeyError: "filename 'RGI60-11.00\\\\RGI60-11.00787.tar.gz' not found"
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_utils.py::TestStartFromV14::test_start_from_level_1 - KeyError: "filename 'RGI60-15.13\\\\RGI60-15.13005.tar.gz' not found"
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_utils.py::TestStartFromV14::test_start_from_level_2 - KeyError: "filename 'RGI60-15.13\\\\RGI60-15.13005.tar.gz' not found"
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_utils.py::TestStartFromV14::test_start_from_level_3 - KeyError: "filename 'RGI60-15.13\\\\RGI60-15.13005.tar.gz' not found"
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_utils.py::TestPreproCLI::test_source_run - KeyError: "filename 'RGI60-11.00\\\\RGI60-11.00648.tar.gz' not found"
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_utils.py::TestPreproCLI::test_start_from_prepro - KeyError: "filename 'RGI60-11.00\\\\RGI60-11.00663.tar.gz' not found"
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_copdem30 - KeyError: "filename 'Copernicus_DSM_10_N46_00_E010_00\\\\DEM\\\\Coperni...
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_copdem90 - KeyError: "filename 'Copernicus_DSM_30_N46_00_E010_00\\\\DEM\\\\Coperni...
FAILED anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_utils.py::TestFakeDownloads::test_tandem_invalid - AssertionError: 'http[51 chars]W140/TDM1_DEM__30_N60W144.zip' != 'http[...
ERROR anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_shop.py::Test_ecmwf::test_ecmwf_workflow - PermissionError: [WinError 32] The process cannot access the file becau...
ERROR anaconda3/envs/oggm_env/Lib/site-packages/oggm/tests/test_shop.py::Test_bedtopo::test_add_consensus - PermissionError: [WinError 32] The process cannot access the file becau...
= 16 failed, 197 passed, 155 skipped, 1 xfailed, 1 warning, 2 errors in 526.09s (0:08:46) =

**Comment by anoukvlug** [comment]
@vcollavini, it looks to me like you're trying to install OGGM on windows. However OGGM doesn't work on windows. For a workaround see the following [documentation](https://docs.oggm.org/en/stable/installing-oggm-windows.html). I would recommend you to check if you really need to install oggm, or if the [OGGM hub](https://docs.oggm.org/en/stable/cloud.html) might be sufficient for your needs.

Having said that, questions regarding model use are better suited for the [OGGM slack](https://community.oggm.org/guides/slack-intro.html) #support channel. The github is meant for model development related issues and bugs, not general model support. Therefore I will hereby close the issue. For future reference the [Help, an error! ](https://community.oggm.org/guides/error-guide.html) guide, can serve as a guidance for how to deal with OGGM related questions and where best to ask them.
