### ISSUE TITLE
Consider licencing the next release under LGPL

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#210]
https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License

@jlandmann for example would benefit from this change

**Comment by jlandmann** [comment]
I tried hard to understand what the implications of the "Lesser" are and if I'm correct this makes using OGGM as I have to do it more "supported" by law. So, of course, I'm for it! Nice idea, thank you very much for your will to support!

**Comment by fmaussion** [comment]
Yes, what I told you last time is wrong: it is not possible to do "import oggm" in a closed source base.

LGPL would allow this: "The license allows developers and companies to use and integrate software released under the LGPL into their own (even proprietary) software without being required by the terms of a strong copyleft license to release the source code of their own components."

**Comment by jlandmann** [comment]
Ah okay!!!
This always confused me and gave me reason to a write an e-mail again. Okay, and after being happy again to hear it's possible, I'm definitely for LGPL - not wanting to imagine the opposite...

**Comment by fmaussion** [comment]
I think I don't want to change this in the end, and keep it under the regular GPL. I think we have now clarified what GPL means, and users are allowed to use OGGM for his own cuisine, as long as they doesn't redistribute his cuisine to others under a closed license. Would that be OK Johannes? If not I'm opened to discussion

**Comment by jlandmann** [comment]
Well, I guess as you say it now it solves the application in my case, so I'd be fine if you close this issue. Thanks, however, for considering and your patience!
