### ISSUE TITLE
Appveyor fails due to some lockfile issue

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#212]
```PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\.oggm\\oggm_data_download.lock'```

https://ci.appveyor.com/project/fmaussion/oggm/build/1.0.581

This happens since a while, no clue if this is due to one of my changes or not...

CC @TimoRoth

**Comment by TimoRoth** [comment]
The FileLock is causing all kind of weird issues, and it's not working properly at all.
Replacing it is part of my plans to overhaul the downloads.
