### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#222]
Error prone numerical operations can lead to such an obscure error.

This would be OK in single threaded mode, but I have the feeling this signal is not received by the multiprocessing pool, which hangs indefinitely... 

:-(

**Comment by TimoRoth** [comment]
SIGSEGV is a hard crash of the process do to an invalid memory access in native code, it has no chance to signal that to the multiprocessing host.
The pool should notice the crashed process on its own though, and throw an exception on its own, is that not happening?

**Comment by fmaussion** [comment]
Unfortunately not. Python doesn't raise anything:

```
/home/mowglie/.virtualenvs/py3/bin/python /home/mowglie/disk/Dropbox/HomeDocs/git/oggm-fork/oggm/sandbox/run_reference_glaciers_dx.py
2017-04-20 12:48:52: oggm.cfg: Parameter file: /home/mowglie/disk/Dropbox/HomeDocs/git/oggm-fork/oggm/params.cfg
Number of glaciers: 1
2017-04-20 12:48:54: oggm.core.preprocessing.centerlines: RGI50-05.16072: compute_centerlines, divide 1
2017-04-20 12:48:54: oggm.core.preprocessing.geometry: RGI50-05.16072: catchment_area, divide 1
/home/mowglie/disk/Dropbox/HomeDocs/git/oggm-fork/oggm/core/preprocessing/geometry.py:362: RuntimeWarning: invalid value encountered in multiply
  costgrid[y, x] *= cost_factor

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by fmaussion** [comment]
I can solve the upstream problem (in that case an undesired behavior), but this won't prevent this from happening again.

**Comment by anoukvlug** [comment]
I think I run into a similar error as you were discussing here.
```
2017-05-09 12:19:14: oggm.core.preprocessing.geometry: RGI50-03.01686: catchment_area, divide 1
/home/avlug/Programs/oggm-anoukvlug/oggm/core/preprocessing/geometry.py:357: RuntimeWarning: invalid value encountered in multiply
  costgrid[y, x] *= cost_factor

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
Continue on error doesn't work for this case. 
When I use multiprocessing, it looks like the model gets stuck, but it doesn't give an error message.

**Comment by fmaussion** [comment]
Yes! So sorry about that. The fix is in master already: simply replace ``costgrid[y, x] *= cost_factor`` with ``costgrid[y, x] = cost_factor``
