### ISSUE TITLE
Make use of the ``has_internet`` option

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#228]
I added this option in the config file with clusters and issues like https://github.com/OGGM/oggm/issues/171 in mind, but currently this option is simply ignored.

**Comment by TimoRoth** [comment]
It would be easy to just throw an error on downloads when this is set, but do we want that kind of behavior?

**Comment by fmaussion** [comment]
Yes, I think we should do two things with either the ``has_internet`` or the ``dl_cache_readonly`` options (or both):
- what we really want to avoid is the check for a new sample-data checksum on poor internet connections (reported by @juliaeis after her train ride to innsbruck: https://github.com/OGGM/oggm/issues/171). Because afaik this is the only moment OGGM will try to go online without the user's approval
- all other things should throw an error. If you need CRU data but don't have internet, this is not going to work. Without internet everything should be in cache.

What do you think?

**Comment by TimoRoth** [comment]
Yes, that sounds reasonable.
I'm just gonna make the cached_download_helper throw an error if no_internet is set when it reaches the actual download functions.
In addition, I'll modify the sample date function to not try for a new version if one is already available locally.
