### ISSUE TITLE
Delete temporary on Travis and RTD?

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#230]
Currently, the OGGM test suite and doc builds on RTD leave a bunch of data behind (test running directories, etc.).

Should we delete them? Does it even matter?  @TimoRoth what do you think?

(deleting should be quite a simple task since https://github.com/OGGM/oggm/pulls)

**Comment by TimoRoth** [comment]
There's not really a point, the VM that builds stuff is destroyed the 
moment the build finishes.

Am 07.05.2017 um 16:06 schrieb Fabien Maussion:

**Comment by fmaussion** [comment]
Good to know!
