### ISSUE TITLE
Make tarballs

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#235]
An OGGM run writes A LOT of small files (several hundreds of thousands). I've seen no issue with this in general since OGGM will never *look* for a file, it always knows where it is, but it makes copying quite slow (especially with ``scp``).

I wonder if a ``working_directory_to_tarball`` and ``working_directory_from_tarball`` would be the way to go. I originally even considered doing everything in tarballs from the scratch, but it looks like its a bad idea to use tarballs as alternative for databases.

The current directory structure is following:
```
   per_glacier
       /RGI_REGION
            / RGI_ID_FIRST_TWO_DIGITS
                   /RGI_ID
                         /FILES
```

With this structure there should always be less than 1000 files/folders per folder. Tarballs could be created at basically any level in this directory structure.

@TimoRoth thoughts?

**Comment by TimoRoth** [comment]
Using tarballs for storing and using them from them at runtime seems redundant to me, and will most likely have a performance impact.
For transferring the working dir over scp or some other protocol making a tar archive would be beneficial. But I don't see why OGGM would need functions to create them, one can easily do that manually before copying.

**Comment by fmaussion** [comment]
> Using tarballs for storing and using them from them at runtime seems redundant to me, and will most likely have a performance impact.

Yes this is what I thought too

> But I don't see why OGGM would need functions to create them, one can easily do that manually before copying.

Yes OK, the only reason to use OGGM for this is for users less savy with the command line, OR if it is somehow advantageous to know the file structure before ``tar``?  For example, making tarballs of the ``/RGI_ID_FIRST_TWO_DIGITS`` or ``RGI_ID`` only with the structure above. Not sure if this is much better than doing a tarball of the entire directory though, maybe you're right.
