### ISSUE TITLE
HTTP Error 300, for glacier RGI50-03.00691

### ISSUE THREAD

**Issue by anoukvlug** [OGGM/oggm#237]
When I increase the border parameter to 250 or higher, I get the following error for glacier RGI50-03.00691:

`define_glacier_region: HTTPError: HTTP Error 300: Multiple Choicesglacier_masks: AttributeError: 'NoneType' object has no attribute 'ReadAsArray'compute_downstream_lines: OSError: No such file or directorycatchment_width_correction: FileNotFoundError: [Errno 2] No such file or directory: '/mnt/raid1/home/avlug/Workspace/A03ERRORtest/per_glacier/RGI50-03/RGI50-03.00691/glacier_grid.json'mu_candidates: ValueError: zero-size array to reduction operation maximum which has no identity`

**Comment by fmaussion** [comment]
Thanks for the report! As you say I think the original bug happens very early (when downloading the topo files), the other messages are irrelevant:

```define_glacier_region: HTTPError: HTTP Error 300: Multiple Choices``` is probably something happening at the ```download_dem3``` level and should be a relatively easy fix. Will look into this later.

**Comment by anoukvlug** [comment]
I just noticed that this error has been solved :)
