### ISSUE TITLE
Upcoming chages in Travis

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#244]
https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2

@TimoRoth woukd you have time to look at this?

**Comment by TimoRoth** [comment]
I wouldn't expect there to be any issues, as we are running in our own Docker-Container anyway.

**Comment by fmaussion** [comment]
ok. maybe we could still add group: edge to get rid of the warning
