### ISSUE TITLE
Add more diagnostic variables

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#298]
- [ ] Specific MB
- [ ] (Total MB)
- [x] ELA

**Comment by fmaussion** [comment]
Added ELA, but not MB values. MB and SMB can be computed from volume changes, but we have to be careful that this is not *really* the surface mass-balance as given by the MB model

**Comment by anoukvlug** [comment]
How do you mean that it is not really the surface mass balance as given by the MB model? What would be the difference?

**Comment by fmaussion** [comment]
Yes, it's the result of the surface mass-balance and of the dynamic model (in the real world its called the *geodetic* mass-balance).

A trivial example happens at the tongue: let's say there is 4 meters of ice, and the MB model says 8 m melt per year: the model cannot melt more than 4 meters.

For our purposes I would say that we are good with storing the ELA only: total volume change is the only things that matters for sea level rise studies, and the "geodetic" and "surface" mass-balance should be very close anyway (as long as our model is mass-conservative ;-) ).

**Comment by fmaussion** [comment]
For "past" studies of the mass-balance, we can always go back and use the mass-balance model btw: if this is something you need we could add a task for this actually.

**Comment by anoukvlug** [comment]
Thanks you for the explanation. I didn't think of that. At the moment don't think I will need the MB or SMB to be a part of the diagnostics file.
I was just calculating the specific mass balance, by dividing the volume change by the area. To get maybe an insight what is going in the rare cases that a nan occurs in the ELA :)

**Comment by fmaussion** [comment]
here is the code I used to compute the SMB for the recent [OGGM blog post](http://oggm.org/2017/10/01/specmb-ela/): https://github.com/OGGM/oggm/blob/master/docs/notebooks/specmb_vs_ela.ipynb

**Comment by fmaussion** [comment]
Closing this, as it seems we may not need it for now
