### ISSUE TITLE
Reset multiprocessing pool

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#327]
The fact that the runs params are stored for multiprocessing and not changeable any more hit me again while I was working on the last PR. I think this is quite unintuitive and dangerous. I see two solutions:
- we patch the `cfg.PARAMS` and `cfg.PATHS` dicts so that  the multiprocessing pool is reset each time a parameter is changed
- we reset the multiprocessing pool each time we call `run_entity_task`

What do you think @TimoRoth ? Do you have another idea?

**Comment by fmaussion** [comment]
I think I tend for option 2 above, will look into it

**Comment by TimoRoth** [comment]
Option two would lead to quite some inefficiency, I'd definitely prefer option 1, and it should not be too hard to implement.

**Comment by fmaussion** [comment]
Is reset_multiprocessing so slow? Because the cfg.PATHS dict is updated *a lot* at each cfg.initialize() (which happens at least once at startup), while the `execute_entity_task` is typically called a dozen of times in a standard script

**Comment by TimoRoth** [comment]
reset_multiprocessing is not, but spinning it up back again on the next execute_entity_task is.
It kills the entire multiprocessing pool, so it gets re-created on next run with the updated parameters.

**Comment by fmaussion** [comment]
OK. I'm open for suggestions here, I just think it shouldn't be user's responsibility to call reset_multiproc

**Comment by fmaussion** [comment]
After thinking a bit more, option 1 indeed should work fine -- since at initialization time there is no pool anyway.
