### ISSUE TITLE
The OGGM "time format" should be clearer

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#348]
Because of the infamous pandas [time limitation](https://github.com/pandas-dev/pandas/issues/7307) there are several time "formats" in OGGM:
- when working with CRU, we use the default pandas/xarray functionalities 
- with CESM data we have to do more tricks in between but still store the data in a CF compliant format (in "units since ..."). This implies that we assume that CESM actually uses a real calendar (i.e. with leap years and stuff) although I'm not sure if this is the case
- for the runs, we then get rid of these calendar formats because they are annoying and use a "float year" format. (https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L1085-L1113)

At the very least I will rename this "year" format to the more explicit "float year" name. 

Better would be to document all these things somewhere

**Comment by anoukvlug** [comment]
The CESM-LME uses a noleap calendar, but both calendars with leap and no leap years can be used by CESM: http://www.cesm.ucar.edu/models/cesm1.2/cesm/doc/usersguide/x1923.html
