### ISSUE TITLE
Re-download sample data when updated 

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#37]
OGGM will download some data files automatically from the oggm-sample-data repository:

https://github.com/OGGM/oggm-sample-data/archive/master.zip

The relevant code is [here](https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L37) and [here](https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L54). 

Currently there's no check to see of the server file has changed: this is bad but I don't know how to ask github if the file has changed.

Any idea on how to do this within python, @TimoRoth , @fso42 ? Any interest in submitting a PR? ;-)

**Comment by BtbN** [comment]
I'll be back in my office on Tuesday, should be no problem to add a check for the github commit sha.

**Comment by TimoRoth** [comment]
I'll be back in my office on Tuesday, should be no problem to add a check for the github commit sha.

**Comment by fmaussion** [comment]
Perfect, thanks! That's not very urgent, you can take your time
