### ISSUE TITLE
matplotlib._cntr not found

### ISSUE THREAD

**Issue by MartinLuethi** [OGGM/oggm#418]
Hi

matplotlib does *not* contain a module called _cntr. 
Please stick to standard modules that are easily installed.

This is matplotlib git version (pre 2.2)
version '2.2.0rc1+282.g3f3065d3a.dirty'

**Comment by fmaussion** [comment]
OK, after doing some research: we should indeed find another way to compute the contours of our masks. I will dig into this, but the easiest for now would be to stick to mpl version 2.1

(mpl 2.2 is going to be officially released today or tomorrow, sigh...)

**Comment by MartinLuethi** [comment]
Hi Fabien

Fabien Maussion <notifications@github.com> writes:

> Thanks for the report! The probably changed in the lastest Matpotlib
> version (2.2). Your installed package is still a release candidate and
> therefore has not been tested yet. I will try to implement a fix for
> this later today.

Yes, with stock matplotlib it works. It seems that ._cntr was not an
official part of the library (the underscore naming warns about that).

I'm considering using OGGM in our glacier modeling class, so I'll test
it somewhat more in the coming days.

Best, Martin

-- 
Dr. Martin Lüthi
Department of Geography, 3G
University of Zurich
Winterthurerstrasse 190
CH-8057 Zurich, Switzerland
Phone: +41-44-635-5146
Fax:   +41-44-635-6841
Email: martin.luethi@geo.uzh.ch

**Comment by fmaussion** [comment]
Thanks a lot for the heads up! It's always unfortunate to start with an error. 

Thanks for considering OGGM for your class! If you are interested in idealized examples, a good way to start could be to have a look at the [flowline](https://github.com/OGGM/oggm/blob/master/docs/notebooks/flowline_model.ipynb) example. This [blog post](http://oggm.org/2017/10/01/specmb-ela/) is another example.

I think that one of the hardest bit is (as you've noticed) to get all the necessary python packages installed for all your students. I discussed a possible solution with Horst last time he came to visit, but if you are interested you can contact me offline or on the phone to discuss the deployment solution we have opted for our classes in Innsbruck.

**Comment by MartinLuethi** [comment]
Fabien Maussion <notifications@github.com> writes:

> OK, after doing some research: we should indeed find another way to compute the contours of our masks. I will dig into this, but the easiest for now would be to stick to mpl version 2.1

Or you add the code from ._cntr to your repository under "src/contrib"
including the original license file. Many codes do that.

Best, Martin

**Comment by MartinLuethi** [comment]
Hi Fabien

Thanks for your rapid answers.

Fabien Maussion <notifications@github.com> writes:
> Thanks for considering OGGM for your class! If you are interested in idealized examples, a good way to start could be to have a look at the [flowline](https://github.com/OGGM/oggm/blob/master/docs/notebooks/flowline_model.ipynb) example. This [blog post](http://oggm.org/2017/10/01/specmb-ela/) is another example.

That's what I did. 

I haven't worked further yet, but maybe you could give me a hint how to
do a flowline calculation on a known bedrock topography. Maybe I'll rip
just that out of the library, but I'll have to experiment some more.

I consider using Jupyter notebooks for the class, running on a Jupyterhub
instance. This worked nicely for other stuff.

Best, Martin

-- 
Dr. Martin Lüthi
Department of Geography, 3G
University of Zurich
Winterthurerstrasse 190
CH-8057 Zurich, Switzerland
Phone: +41-44-635-5146
Fax:   +41-44-635-6841
Email: martin.luethi@geo.uzh.ch

**Comment by fmaussion** [comment]
> I haven't worked further yet, but maybe you could give me a hint how to do a flowline calculation on a known bedrock topography

I will work out an example for this (including known mass-balance). It should be quite easy to do

> I consider using Jupyter notebooks for the class, running on a Jupyterhub instance. This worked nicely for other stuff.

Yes! If you have full control on the packages installed in the background (ideally with conda) then this would work fine.

**Comment by fmaussion** [comment]
This should now be fixed (https://github.com/OGGM/oggm/pull/421). 

See also https://github.com/OGGM/oggm/issues/420 for a discussion about making some dependencies optional.

**Comment by fmaussion** [comment]
Martin, I just added another example to the notebooks folder (https://github.com/OGGM/oggm/blob/master/docs/notebooks/flowline_with_known_bedrock.ipynb)

Let me know if something is unclear, and good luck with your lectures!

**Comment by MartinLuethi** [comment]
Salut Fabien

Fabien Maussion <notifications@github.com> writes:
> Martin, I just added another example to the notebooks folder
> (https://github.com/OGGM/oggm/blob/master/docs/notebooks/flowline_with_known_bedrock.ipynb)

Great, thanks a lot for this excellent support.

Best, Martin
