### ISSUE TITLE
Glacier centerlines - 'Invalid CRS' error for some glaciers

### ISSUE THREAD

**Issue by iliyanadobreva** [OGGM/oggm#450]
Howdy,

Thank you for developing and sharing OGGM, this work in invaluable!

I derived the centerlines for over 80 glaciers in the Karakoram Himalaya, but there is an error for another 10 glaciers. I use RGI60 outlines as input. You could find a Jupyter Notebook showing the error for one glacier, and also a compressed file of that glacier outline here:

https://github.com/iliyanadobreva/OGGM

Here is the list of glaciers for which there is the error:
RGI60-14.03405
RGI60-14.03439
RGI60-14.03869
RGI60-14.04068
RGI60-14.04477
RGI60-14.00032
RGI60-14.04531
RGI60-14.04638
RGI60-14.04872
RGI60-14.04945

Also, I have set 'use_intersects' to False, is there documentation of how to use this parameter when set to True?

Thank you

**Comment by fmaussion** [comment]
Thanks a lot for trying OGGM and reporting back!

Let's start with the second question:

> I have set 'use_intersects' to False, is there documentation of how to use this parameter when set to True?

I have shown you how to do this in the example code below. However, if you are interested in the centerlines only (and not the rest of the OGGM workflow), there is no need to set them and setting this option to ``False`` is no problem.

Now, to your problem: the ``'Invalid CRS' error``. Unfortunately I don't have this error myself when running the code below (which does the same as yours). Looking at your error it seems to be a problem in your rasterio/GDAL installation :-(. I'm not sure what to do here... Did you try to reinstall/update your packages? Maybe @TimoRoth has an idea? 

Here is the code:

```python
import os
import geopandas as gpd
import matplotlib.pyplot as plt
import oggm
from oggm import cfg, tasks, graphics
from oggm import utils, workflow

# Initialize OGGM and set up the default run parameters
cfg.initialize()
rgi_version = '6'
rgi_region = '14' 

# Local working directory (where OGGM will write its output)
WORKING_DIR = os.path.join(os.path.expanduser('~'), 'tmp', 'test_center')
utils.mkdir(WORKING_DIR, reset=True)
cfg.PATHS['working_dir'] = WORKING_DIR

# We use intersects
path = utils.get_rgi_intersects_region_file(rgi_region, version=rgi_version)
cfg.set_intersects_db(path)

# RGI file
path = utils.get_rgi_region_file(rgi_region, version=rgi_version)
rgidf = gpd.read_file(path)

# Selection of IDs
namepart = ['RGI60-14.03439']
rgidf = rgidf.loc[rgidf.RGIId.isin(namepart)]

# Go - initialize working directories
gdirs = workflow.init_glacier_regions(rgidf)

# Preprocessing tasks
task_list = [
    tasks.glacier_masks,
    tasks.compute_centerlines,
    tasks.initialize_flowlines,
]
for task in task_list:
    workflow.execute_entity_task(task, gdirs)

graphics.plot_centerlines(gdirs)
plt.show()
```

**Comment by fmaussion** [comment]
Not that your bug report inspired a further bug report from me here ;-) 
https://github.com/OGGM/oggm/issues/451

Please let me know ow things work out for you

**Comment by fmaussion** [comment]
Great, thanks! Don't hesitate to ask here if you have other questions

**Comment by iliyanadobreva** [comment]
May I create center lines with a DEM that I provide? I set the cfg.PATHS to
the DEM file, but the center line function is not using it.

cfg.PATHS['dem_file'] = 'C:\workspace\dem.tif'

Iliyana

On Fri, Apr 13, 2018 at 9:43 AM, Fabien Maussion <notifications@github.com>
wrote:

> Great, thanks! Don't hesitate to ask here if you have other questions
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OGGM_oggm_issues_450-23issuecomment-2D381157835&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=scvXvHDVNTbNHir-wzeA58gIkeRLVNJd5Ns0zPkHJFE&m=LKZ9XwU_mYr9BnlmXfbI6qOUAXWMMi0Z0xPrz3Lu9Ho&s=TgdAnuNaxPL44DxWwRxpJrk_2KM6RasfOLD0BrvXkQ8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AVkz2fqZUSATGkUr3pUbvoGhOuP4EZNtks5toLmXgaJpZM4TM7ro&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=scvXvHDVNTbNHir-wzeA58gIkeRLVNJd5Ns0zPkHJFE&m=LKZ9XwU_mYr9BnlmXfbI6qOUAXWMMi0Z0xPrz3Lu9Ho&s=czdWJKoFeAYeISOvxgq-p9RXWr8xUrc3RygIKxo6ot4&e=>
> .
>



-- 

*Iliyana Dobreva*
*Research Associate at the Department of Soil & Crop Sciences*
*Ph.D. Candidate at the **Department of Geography*
*Texas A&M University, **College Station TX*

**Comment by fmaussion** [comment]
Hi @iliyanadobreva , are you sure it is not used? A good way to check is to go in the glacier directory and have a look at the DEM source file. For example, if I do ``print(gdir.dir)`` it gives me the path to the path to the directory. In the directory there should be a ``dem_source.txt`` file, and if OGGM used your DEM it should be written "USER" in it. 

If not, then there is a problem. In this case:
- did you set ``cfg.PATHS['dem_file'] = 'C:\workspace\dem.tif'`` **right after** the call to ``cfg.initialize()``?
- did you reset your directories? (either by deleting them or by setting ``workflow.init_glacier_regions(rgidf, reset=True, force=True)``). Resetting is important because if there was already a DEM available before, OGGM won't rewrite it.

**Comment by fmaussion** [comment]
Note that if you want more control on the resolution of the local glacier DEM resolution, you can set some parameters for this too. Let me know if you'd like to do so.
