### ISSUE TITLE
copy_to_basedir 

### ISSUE THREAD

**Issue by anoukvlug** [OGGM/oggm#467]
@fmaussion, like we discussed during the oggm workshop, I would like to make a pull request for adding ''cesm_data'' to the options 'run' and 'inversion' of the copy_to_basedir function.

While playing around with this function, I didn't find an entity task that can be used to use this function. I just wrote one. Shall I add it to the pull request?  Or is there already a more suitable way to use this function?

**Comment by fmaussion** [comment]
Hi Anouk, until now the ``copy_to_basedir`` is a method available from the gdir object. I never considered making an entity task out of it, although maybe it would make sense for paralelizing the copy/paste. 

Yes, open a PR and we can discuss the details there

**Comment by fmaussion** [comment]
Just to claridfy: until now I did:

```
for gdir in gdirs:
    gdir.copy_to_basedir()
```

But maybe this could be done in parallel yes

**Comment by anoukvlug** [comment]
It make a sense to do it like that. Somehow the first thing that came to my mind was making an entity task for it. Anyway I will make a pull request to discuss this further.
