### ISSUE TITLE
Allow different mu's for different flowlines

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#478]
This is something I've been considering for a while now. Recent works by @matthiasdusch made it more urgent.

### Problem

The major issue with the way we compute mu currently (one mu per glacier) is that sometimes, a single mu cannot explain the existence of all the branches in a glacier. Some lower lying tributaries have a negative mass-balance and therefore a negative mass-flux for the inversion. 

### Current workarounds 

This problem lead to two waves of "improvements" in the model:
- the first solution (now deprecated but still available as option in the config file) is to correct for these negative fluxes *for the inversion only* and ignore them the rest of the time. This was later discussed as being not good because not physically consistent and leading to issues of mass conservation in the t* experiments (see GMD paper)
- the second solution (current default) is to *suppress* these unphysical tributaries. This seemed like a good idea at the time and surely is more mass-conservative, but it is clunky and leads to several other problems I don't want to list here (mostly related to the OGGM workflow itself)

### A better solution?

A solution which would take the best out of the two workarounds above it to allow for different mus for each flowline. With this mechanism, a tributary which cannot be explained by the glacier-wide mu would get a different climate sensitivity. This mu would then be used for the inversion **and** for the ice-dynamics runs, therefore ensuring consistency. 

This is I think the better solution of all three. The only problem with it is: how to choose mu? The simplest way would by to treat this lonesome tributary as a single glacier and define mu so that its tributary-wide mass-balance is equal to zero. This would lead to a zero mass-flux into the underlying main branch (which is clearly wrong) but would be extendable to better solutions in the future.

### Consequences

The consequences for the model internals will be consequent, but manageable. The default behavior of one mu per glacier should still remain available, internally it will be handled as a multiple mu case though.

A positive consequence will be that it is going to be relatively straightforward to allow the dynamical model to merge glacier complexes before runtime, i.e. by merging all glaciers in a single valley together.

### When?

I am quite keen on starting this ASAP, but this might take more time than expected. Let's see...

**Comment by fmaussion** [comment]
Closed via https://github.com/OGGM/oggm/pull/539

**Comment by bearecinos** [comment]
Hi, 
I spent sometime yesterday updating OGGM and my frontal ablation code. There is no error per say but when I assign the new calving rate to the MB model there seems to be not change in Volume at all after the inversion happens. That is really odd, I will like to ask where is my mistake on using this functions?

```
gdir.inversion_calving_rate = F_calving

                # Recompute mu with calving
                tasks.local_t_star(gdir)
                tasks.mu_star_calibration(gdir)

                # Inversion with calving, inv optimization is not iterative
                tasks.prepare_for_inversion(gdir, add_debug_var=True)
                tasks.mass_conservation_inversion(gdir)
```
1. Maybe I am forgetting something in the mu_star_calibration() such as this first_call variable? .... `_recursive_mu_star_calibration(gdir, fls, t_star, first_call=True):`

**Comment by fmaussion** [comment]
Yes it's possible that the calving is not treated properly - I don't think we even test for this.

Will have a look.
