### ISSUE TITLE
What's the deal with NetCDF 1.4

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#482]
Just because I've seen this in https://github.com/OGGM/oggm/pull/481

What is the issue with NetCDF 1.4? Did we find out where the problem lies?

**Comment by fmaussion** [comment]
At least we should put a big warning in the installation docs warning about it.

**Comment by TimoRoth** [comment]
I have no idea what the issue is. In general, everything still works fine, but it takes insanely long.
Running the tests with netCDF 1.4 compared to <1.4 increases the time from 5-10 minutes to over 2 hours for me.

**Comment by fmaussion** [comment]
See https://github.com/Unidata/netcdf4-python/issues/809
