### ISSUE TITLE
Use pytest.mark.slow instead of homegrown @is_slow decorator

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#495]
https://docs.pytest.org/en/latest/example/simple.html

**Comment by fmaussion** [comment]
While we are at it we should run the slow tests on appveyor as well: I mistakenly ran the slow tests on appveyor in https://github.com/OGGM/oggm/pull/509 and it discovered a couple of usual windows file related bugs.

**Comment by fmaussion** [comment]
@TimoRoth if you feel like giving it a go and have time for it this would be much appreciated!

**Comment by TimoRoth** [comment]
I can do that, but won't we run out of time on appveyor?
At least I recall explicitly disabling slow tests there because all the 
runs kept timing out.
