### ISSUE TITLE
Readthedocs builds

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#497]
We have frequent build fails on RTD, mostly timeouts.

Recently, the build failed with a GDAL dependency problem:

```
Fetching package metadata ...............
Solving package specifications: 

ResolvePackageNotFound: 
  - gdal 2.2.3*
  - libgdal 2.2.3
```

(https://readthedocs.org/projects/oggm/builds/7431611/) 

Right now I am always pinning the conda packages to a certain version, which used to work OK but obviously not always (https://github.com/OGGM/oggm/blob/master/docs/environment.yml)

@TimoRoth , do you think that there is a way to use docker and/or the oggm conda channels for easier installation on RTD? Would you have time to have a look? The "docs" branch on master can be used to test RTD...

**Comment by TimoRoth** [comment]
The build script for RTD seem fairly limited, and hardcoded to use conda from their end. So I don't think using anything else is possible.

**Comment by fmaussion** [comment]
We are now constantly exeeding the 900s build time allowance on RTD: https://readthedocs.org/projects/oggm/builds/7443730/

I have the same problem with Salem, no clue how to make the build faster. @TimoRoth would you have time to look into this? On the [oggm/docs](https://github.com/OGGM/oggm/compare/docs) branch I have tried to use conda oggm-deps but this is what takes ages at installation. I wonder if pip would now be faster since they use wheels?

**Comment by TimoRoth** [comment]
pip would fail horribly, primarily because of gdal, fiona, rasterio, pandas and a bunch of other stuff that can't be pre-compiled in a generic way.
Isn't it possible to push docs to them externally? We could just generate and push them at the end of the travis tests we run anyway.

**Comment by fmaussion** [comment]
This is certainly one possibility, but I wonder if it's worth the trouble. 

Plus sides:
- full control
- possibility to document processes which take longer to run (i.e. some hard-coded examples)
- easy hosting under github pages with oggm.org/docs

Minus sides:
- maintenance burden
- A feature which might be difficult to keep is the possibility to access docs for tagged versions (http://oggm.readthedocs.io/en/latest/)
- the RTD address is already in many places, if we can't make a redirect its a bit sad

**Comment by TimoRoth** [comment]
I can't find any API to upload docs to them. Which seems weird, that should be a basic feature.
Do we even need all/any dependencies just for building the docs? It's just a bunch of richtext, and compiling that shouldn't need any of the normal dependencies.

**Comment by fmaussion** [comment]
We need the dependencies because OGGM code is executed at build. You should try to build the docs locally to have an idea of how it works. (http://oggm.readthedocs.io/en/latest/contributing.html#contributing-to-the-documentation)

Sphinx builds the html code and, where python examples are found, executes the code. Readthedocs simply uses sphinx to build the html site.

**Comment by fmaussion** [comment]
this page for example executes oggm code: http://oggm.readthedocs.io/en/latest/flowlines.html

and this page doesn't (although it could) because of time constraints: http://oggm.readthedocs.io/en/latest/run_examples/run_from_calibrated.html

**Comment by TimoRoth** [comment]
Using just pip is out of the question. There is no gdal or other binary dependencies in their Docker images, so conda is the only option there. And conda takes more than 15 minutes just for installing all the dependencies, which is probably because their build systems are massively overloaded.

Not really sure what to do about this. Since there does not appear to be a way to manually upload docs, I'm pretty much out of ideas other than using something completely different.

**Comment by TimoRoth** [comment]
I got our time limit on readthedocs builds bumped to 1 hour, and was nicely asked to not abuse it. So we should be good from now on.
Reason for the random failures/success was that they cache the conda installations, but only for a certain while. So a lot of successive builds will eventually succeed, once the conda cache is built up. But builds after a while of silence will run into timeouts again.

With 1h of time we should be good from now on out though.
