### ISSUE TITLE
Deploy: ebs storage name

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#51]
If one user creates two instances at the same time (which he should not do, but this happens ;-) ), then two storages with the same name are created. Her the output of `cloud_list`: 
```
py2)mowglie@flappi ~/Documents/deploy $ fab cloud_list

-------CURRENT RUNNING-----------
       REGION: us-east-1

Instances:


Volumes:


-------CURRENT RUNNING-----------
       REGION: eu-west-1

Instances:


Volumes:

vol-2da855df 	 available 	 50 	Lifetime: perm	Uservolume Name: ebs_fabi
vol-1e44baec 	 available 	 50 	Lifetime: perm	Uservolume Name: ebs_work_volume
vol-49bac88b 	 available 	 50 	Lifetime: perm	Uservolume Name: ebs_fabi

Done.
```
This does not seem to be a problem for AWS, but when you open a new machine you can't be sure about the one you get. I guess that it is handled here, where simply the first of the list is taken:
https://github.com/OGGM/oggm/blob/master/deployment/fabfile.py#L435

**Comment by TimoRoth** [comment]
EBS volumes are only unique inside of their availability zone, as you can only mount them on instances in the same zone.

I added the AVZ to the list output with one of the latest fabfile pull requests. spot instances are always created in the cheapest AVZ, so it's possible that instances are created in different zones, which results in another user-volume being created for that zone if none exists so far.

**Comment by TimoRoth** [comment]
It's possible to manually select the AVZ, so you get your desired user-volume all the time, by directly calling instance_start with a defined avz parameter:

`fab instance_start:avz=eu-west-1a`

**Comment by fmaussion** [comment]
Aha ok now I get this. What do you think about adding the possibility to select the region in `fabfile.py`, as an optional parameter? 

It seems important to me, because setting a run and downloading the appropriate data can take a long time.

**Comment by TimoRoth** [comment]
For ondemand nodes it's already possible to select a precise region in the config hears, the idea with the spot instances is to always select the cheapest region automatically.
But as the EBS volume has to be in the same avz, some option has to be added/reused for this.

**Comment by TimoRoth** [comment]
Just noticed, calling instance_start instead of cloud_make already behaves like that, it uses the avz from def_default_avz.
Will update the docs to inform about that.

**Comment by fmaussion** [comment]
Addressed by https://github.com/OGGM/oggm/pull/71
