### ISSUE TITLE
Notebook "Glacier dynamics and length changes" 

### ISSUE THREAD

**Issue by nchampollion** [OGGM/oggm#535]
Why in the run_from_climate_data function I need to set up the parameter 'ys' to 1902 whereas HISTALP climate data starts earlier ?

Here is the error: 2018-09-24 16:52:49: oggm.core.flowline: ValueError occurred during task run_from_climate_data hist_from_current on RGI50-11.00897: year 1855.0 out of the valid time bounds: [1902, 2016]

**Comment by matthiasdusch** [comment]
Add `cfg.PARAMS['baseline_climate']= 'HISTALP'`  somewhere before `workflow.climate_tasks([gdir])`.

This is related to the recent introduction of `cfg.PARAMS['baseline_climate']` and `process_histalp_data`.

**Comment by nchampollion** [comment]
Ok, thanks. And what should I do with an other commit I have which is the same as you (switching from `cfg.A` to `cfg.PARAMS['glen_a']`) ?
