### ISSUE TITLE
run_output.nc file error

### ISSUE THREAD

**Issue by sumnonpuella** [OGGM/oggm#537]
I've run a series of 10 Iceland glaciers for 1000 years with GCM data through `run_constant_climate`, and compiled the output with `utils.glacier_characteristics` and `utils.compile_run_output`. When I go to look at the data as an xarray dataframe in python, it looks fine. But, when I look at at the output file (`run_output.nc`) with external software (Ferret in my case), it throws this error a few times:

` *** NOTE: Internal err: unknown data type`

Is this a known issue with the way OGGM writes model run data to netCDF? Are there other methods people use to look at model output?

**Comment by matthiasdusch** [comment]
`run_output.nc` stores time series of different model output values (area, length, ela and volume) for each modeled glacier. Dimensions in your case would be (10, 1000) [glaciers, time].

Ferret apparently expects and requires gridded, georeferenced data with the dimensions (time, latitude, longitude). See: https://www.johnny-lin.com/cdat_tips/tips_fileio/ncdf_ferret.html
Ferret might be the wrong tool to look at these time series.

If you are looking for a way to visualize model output in a 2D way, there are several functions within the oggm.graphics module. For example `plot_modeloutput_map`.

**Comment by fmaussion** [comment]
We should really set up some tutorials to plot these run_ouptut files with xarray online. 

For a start you can have a look at this example: https://docs.oggm.org/en/latest/run_examples/run_from_calibrated.html which has some graphics in the end
