### ISSUE TITLE
SimpleRandomMassBalance lacks `fl_id` in Notebook `flowline_with_known_bedrock`

### ISSUE THREAD

**Issue by phigre** [OGGM/oggm#572]
When running the notebook `flowline_with_known_bedrock`, following error is raised.

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-11-040dc36f89df> in <module>
          8 # Loop
          9 for i, yr in enumerate(yrs):
    ---> 10     model.run_until(yr)
         11     length[i] = model.length_m
         12     vol[i] = model.volume_km3
    
    ~/oggm/oggm/core/flowline.py in run_until(self, y1)
        602         t = (y1-self.y0) * SEC_IN_YEAR
        603         while self.t < t:
    --> 604             self.step(t-self.t)
        605 
        606         # Check for domain bounds
    
    ~/oggm/oggm/core/flowline.py in step(self, dt)
        954             # Mass balance
        955             widths = fl.widths_m
    --> 956             mb = self.get_mb(fl.surface_h, self.yr, fl_id=i)
        957             # Allow parabolic beds to grow
        958             widths = np.where((mb > 0.) & (widths == 0), 10., widths)
    
    ~/oggm/oggm/core/flowline.py in get_mb(self, heights, year, fl_id)
        564             self._mb_current_out = dict()
        565             self._mb_current_out[fl_id] = self._mb_call(heights, year,
    --> 566                                                         fl_id=fl_id)
        567 
        568         return self._mb_current_out[fl_id]
    
    TypeError: get_annual_mb() got an unexpected keyword argument 'fl_id'

Should be easily fixed by adding an optional argument to `get_annual_mb` of `SimpleRandomMassBalance` in the Notebook.

**Comment by fmaussion** [comment]
Thanks! Solved in https://github.com/OGGM/oggm/pull/573
