### ISSUE TITLE
To what OGGM version does conda install -c oggm oggm points to?

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#578]
I think it should point to the latest PyPi version, but currently it seems to point to the dev version. Is this true or did I make a mistake somewhere?

**Comment by TimoRoth** [comment]
It semi-automatically follows master.

**Comment by fmaussion** [comment]
OK, thanks. I think it should point to the PyPI version. If people want a dev version they should go for git+pip (or, alternatively, we add an oggmdev conda package following master)

Thoughts?

**Comment by TimoRoth** [comment]
I can trivially do that with the next OGGM release. Or I'll have to nuke everything thats's already there on conda, because the version numbers are ahead of the released versions, to replace it with the current release.

**Comment by fmaussion** [comment]
OK - next release is planned for beginning of November

**Comment by TimoRoth** [comment]
It's 1.0.0 right now, and will follow any new tags made.

**Comment by fmaussion** [comment]
Perfect! Thanks
