### ISSUE TITLE
Improve data download

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#58]
Since ITMIX, OGGM can theoretically work everywhere on the globe without effort. 

Some of the data (e.g. WGMS, GlaThiDa, CRU Clim) is stored on the [oggm-data](https://github.com/OGGM/oggm-sample-data) repository. This is downloaded at run time, and this is fast.

Some larger files are downloaded from their original repo, when public:
- [CRU](https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L677)
- [SRTM](https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L131)
- [RGI](https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L635)

Some large files are not really public (ASTER -- TODO: what is their data policy by the way?) and are stored on S3:
- [ASTER](https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L173)
- [alternate topo files](https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L208): some files I got from http://viewfinderpanoramas.org/dem3.html, but which I had to pre process with GIS (mosaics + convert to geotiff) 

Note that SRTM and ASTER tiles are downloaded only if necessary, i.e. just for the region of interest.

It would be great to formalize all this logic in a separate module (maybe `download.py`?). When a file needs to be downloaded (eg CRU, SRTM...), it can take a long time. It would be good to inform the user with a log message that the download is happening.

I also have the feeling that S3 download is faster than the other repos. A possible (but clumpsy) solution would be to download SRTM from the public server once and only once, and make a local copy on S3 for faster download for the next run. 

For the very long term, we should find a solution so that external users can get access to our S3 drive.

**Comment by TimoRoth** [comment]
The s3 drive can be configured to be public, so anyone can download from it via http or boto s3 api calls.
I'm just unsure if this is acceptable for the data on there, as we would be redistributing it which might not be ok with the owners.

**Comment by fmaussion** [comment]
Yes, exactly. I'll ask Ben about that

**Comment by fmaussion** [comment]
But it doesnt have to be entirely public: would it be possible to have guest read-only credentials?

**Comment by TimoRoth** [comment]
Yes, it's possible to craft credentials to behave like that.
Only Ben can do so via the S3 Webinterface.

**Comment by fmaussion** [comment]
OK, perfect. For now, it is not very important, but good to know that its possible

**Comment by fmaussion** [comment]
Download log now addressed by: https://github.com/OGGM/oggm/pull/83
