### ISSUE TITLE
Idea: start to freeze package versions on oggm-deps

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#590]
@TimoRoth I would like to discuss a possibility here. It's just an idea, but the more I think of it the more sense it makes: I think we should start to freeze (e.g: pin) the oggm-deps (and, per analogy, the docker container and cluster) to a set of package versions that works. 

This freeze wouldn't be a "hard one", meaning that OGGM will still work with other package versions. (However, it might issue a warning or similar when not, although I'm not sure this is necessary).

We will then update the package versions when deemed necessary, i.e. for major OGGM tags or when required by a new feature.

The advantages are:
- avoid the install chaos we have right now
- less work for you
- more reproducibility - we ensure that everybody works with the same package versions

The disadvantage is that we might oversee important updates, but this can be avoided if we test on two streams: "frozen" and "latest".

What do you think?

**Comment by fmaussion** [comment]
@OGGM/oggm-devs if you want to chime in, please do ;-)

**Comment by TimoRoth** [comment]
I can try setting it up, but it seems like a massive hassle. From my experience, hard-pinnen dependencies cause more headaches down the road when trying to combine versions. Specially with gdal, which depends on the library version present on the system.

**Comment by fmaussion** [comment]
> Specially with gdal, which depends on the library version present on the system.

True. The alternative is to use conda binaries (or wheels) everywhere, in order not to rely on system versions at all.

**Comment by fmaussion** [comment]
Other alternative: we use two frozen versions:
- cluster version
- conda version

and we make sure that the results are in-line together. Correct me if I'm wrong, but pinning conda's oggm-deps would be of a great help right?

**Comment by TimoRoth** [comment]
I would kind of expect a full freeze of the deps on the oggm-deps package to make it break even more often, as not all deps have fully frozen deps on their own, and over time this grows into a mess.
The only way to avoid this would be to put absolutely everything in there, which would be over 100 packages in total.

**Comment by fmaussion** [comment]
> I would kind of expect a full freeze of the deps on the oggm-deps package to make it break even more often, as not all deps have fully frozen deps on their own, and over time this grows into a mess

I don't understand this. If we have a list of dependencies defined as such:

```
channels:
  - conda-forge
dependencies:
  - python=3.6
  - rasterio=1.1
  - numpy=1.3
  - ...
```

With all packages pinned to a version, then this setup will work for as long as the packages are available in this version in conda-forge channel. Which is, I hope, going to be a long time.

**Comment by fmaussion** [comment]
Note that I have two main motivations here, that might or might not be compatible:
1. reduce the install pain of our users, which is currently extremely high for some reason that only you can understand
2. ensure reproducibility of scientific results by making sure everybody has the same results when running OGGM

For 2, the easiest is surely to use docker or [singularity](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0188511) containers, but I'm unsure how this can be achieved for all our (prospective) users. This is why I came up with the freeze idea to combine 1. and 2.

**Comment by fmaussion** [comment]
OK, now I understand. But while we cannot force the users to not update all the time, we could at least encourage them *not* to update.

Anyways - I'm open to solutions or ideas for both objectives above, and in the short term I hope that these conda problems will be solved upstream...

**Comment by TimoRoth** [comment]
Unfortunately, from what I gather the Interest in Windows from all the anaconda/python people is very small, if not nonexistent. It's almost at a point where I'd say right now Windows is barely a supported platform.

Another issue I just realized is that package versions sometimes differ vastly between Platforms, cause on Windows they include stuff like the Visual Studio runtime version used to build the packages, which would mean we'd need a different package per OS, which seems like a big mess to maintain.

What we can do instead is put a per-platform conda-requirements.txt (output of `conda list --export`) into the OGGM repository, or maybe in a separate repo. Then you can just do `conda create -n oggm_env --file conda-requirements-win64.txt`.
That file could be auto-generated by the Anaconda CI jobs even, as they run tests before uploading a new package, that would ensure that file contains an up to date but known working configuration of packages.

**Comment by alexjarosch** [comment]
Hi Guys,
I think we should provide a singularity as well as docker container (one can convert the one to the other). That really solves the issue in the long run. 
People can get used to run things in containers easily and I know for certain, singularity containers don't have any performance issues whatsoever.

Any suggestions as to why we should NOT use containers?

**Comment by fmaussion** [comment]
Thanks for jumping in Alex

> Any suggestions as to why we should NOT use containers?

I don't think that there are arguments against containers, they are the way to go on the long run. My main concern here is that some of our users are not very tech savvy, and it's going to be hard to make them use them, especially when they want to develop in it.

**Comment by alexjarosch** [comment]
Right. Developing in an container is somewhat harder, true.
I personally don't mind developing in a docker container, singularity less so....
The downside with docker is that it is only natively available for Linux and Windows, MacOS only on top of a linux virtual machine.
Do we have many MacOS users? 
But, maybe vagrant (https://www.vagrantup.com/) is our way forward. It creates a virtual machine based development environment and in supports a large set of OSs and distributions (https://www.vagrantup.com/downloads.html)
The advantages are outlined here (https://www.vagrantup.com/intro/index.html)
Looks like something to think about.
My argument would be that we have to unify the development environment setup approach if the users are not very tech savvy and it seems conda is not cutting the deal.

**Comment by TimoRoth** [comment]
So, something like https://hub.docker.com/r/oggm/oggm/ ?
That's around for quite a while, but too much of a hassle to use for everything but playing around, due to all the stuff you do being in a container and not easily accesible outside of it.

**Comment by fmaussion** [comment]
Yes, on medium term I would also go for docker and also a singularity container.  Singularity seems to gain momentum as "the solution to install problems" for multi-user clusters, and is what the uin Innsbruck uses.

I registered for a singularity workshop at UIBK in two weeks, then I'll know a little more.

**Comment by TimoRoth** [comment]
Singularity should already be able to run our Docker containers without any modifications to them, and seems like a great tool to use them for development purposes.
