### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#598]
@TimoRoth is coverage still running corectly since the recent updates?

Previously we had something like:

```
    pytest oggm $MPL --cov-config .coveragerc --cov=oggm --cov-report term-missing
    coverage combine
```

**Comment by TimoRoth** [comment]
https://travis-ci.org/OGGM/oggm/jobs/454100495#L546 looks good to me on our end

**Comment by fmaussion** [comment]
:cry: https://coveralls.io/github/OGGM/oggm?branch=master

I don't know what's going on again...

**Comment by fmaussion** [comment]
It looks like completely broken currently, not covering anything...

**Comment by TimoRoth** [comment]
I have no idea what's going on with them, but it really looks like an issue on their end to me.
Job #1432.4 on our end, showing 32% coverage and a successful upload: https://travis-ci.org/OGGM/oggm/jobs/454100494#L549
On their end, 0%: https://coveralls.io/jobs/42157087

**Comment by TimoRoth** [comment]
Quick google suggests that we're not alone with this. Seems to be ongoing since 2015 somehow: https://github.com/lemurheavy/coveralls-public/issues/281

**Comment by fmaussion** [comment]
I think we need to look for alternatives...

**Comment by fmaussion** [comment]
Maybe codecov: https://docs.codecov.io/docs/testing-with-docker

**Comment by fmaussion** [comment]
I'll try to delete the webhook and restart the service again to see if that helps

**Comment by fmaussion** [comment]
Closed by recent changes. Thanks @TimoRoth !
