### ISSUE TITLE
how to transfer the centerlines.pkl into csv or shp files

### ISSUE THREAD

**Issue by egalistmir** [OGGM/oggm#601]
When applying OGGM to work on the centerlines of several glaciers, I failed to read the centerlines.pkl
I use Python3.6 picker package to load the pkl file, but only see something below.

In [7]: f = gzip.open('centerlines.pkl')

In [8]: info = pickle.load(f)

In [9]: info
Out[9]: 
[<oggm.core.centerlines.Centerline at 0x7f89dbdc8ba8>,
 <oggm.core.centerlines.Centerline at 0x7f89acfc6208>,
 <oggm.core.centerlines.Centerline at 0x7f89acfa0f98>]
``

**Comment by fmaussion** [comment]
Hi @egalistmir , did you have a look at this example: https://docs.oggm.org/en/latest/run_examples/run_rgi_region.html ?

At the end we call `utils.write_centerlines_to_shape(gdirs)`, which seems to do what you want.

**Comment by fmaussion** [comment]
With `path='yourfile.shp'` you can decide where to store it.

**Comment by fmaussion** [comment]
> Why do you use pkl files to store the centerlines? Is it easier to process in the model run?

Yes: not only processing, but because centerlines are more than just "a line". The pickle files store the entire python objects, which have several other model related attributes. However, I agree that shapefiles are easier to work with.
