### ISSUE TITLE
about ：RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by liyaojun** [OGGM/oggm#602]
However, today , when I import oggm as well as geopandas, the terminal reminds "RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility." 
 I have tried to reinstall numpy(elder version) but still reminds me as above. Does this influence model running or not? And How to fix it?
Moreover, which IDE is better to run and develop oggm model in Ubuntu? Or just in the linux terminal?
So sorry that I am freshman in coding and Linux.
![n jhwe0xvlx srh gkc21a9](https://user-images.githubusercontent.com/19677300/48561028-12e9a380-e92a-11e8-8291-c3f09838bd9a.png)

**Comment by fmaussion** [comment]
Dear @liyaojun , this has nothing to do with OGGM: https://github.com/numpy/numpy/issues/11788

You can get rid of the message by updating to more recent numpy, but it's not necessary (the warning is not important)

> Moreover, which IDE is better to run and develop oggm model in Ubuntu? Or just in the linux terminal?

I personally use PyCharm, other use Spyder or Atom or Jupyter-notebooks. It's a matter of choice!

> So sorry that I am freshman in coding and Linux.

OGGM is not (yet) so advanced that one can use it without coding experience. I suggest you slowly learn the basics first, then OGGM will be a bit easier.
