### ISSUE TITLE
Cluster: singularity start from virtualenv fails

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#652]
It's not directly OGGM related but we don't have an issue tracker for the cluster (idea: we could / should have one).

On cluster: if you start a singularity run from a terminal where virtualenv is on, the run fails with a very obscure numpy error. Arguably starting from a virtualenv is a user error (i.e. mine), but I wonder if this indicates deeper issues with the encapsulation of the container.

ping @TimoRoth

**Comment by TimoRoth** [comment]
singularity passes through most, but not all, of the outside 
environment. So it can easily get confused like this.
