### ISSUE TITLE
Add SHA checksum on pre-processed dirs

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#666]
OGGM is going to rely on the successful download of the glacier directories from our servers.

it would be great to have a checksum on the download. These are going to be many files, if needed we can consider bundle the glacier directories in groups - and download bundles only.

cc @TimoRoth I wonder if you have an opinion on how to do this - maybe you can help me out as well?

**Comment by TimoRoth** [comment]
I could easily put a checksum file next to all the files stored on our cluster. OGGM would then download it alongside the actual file, and verify the checksum after download.

**Comment by fmaussion** [comment]
yeah I have to see if this is really worth it - it's just that with my tests I saw that sometimes the downloads didn't proceed well and the run might mail unexpectedly

**Comment by fmaussion** [comment]
The very nice part is that we could use the checksums to deal with changes in data

**Comment by TimoRoth** [comment]
The checksums normally wouldn't be stored in oggm itself, but next to the file on the server, to verify the integrity of what was just downloaded.

I could in thory also generate one large checksum file of all the files stores on the cluster, which should be pretty much everything OGGM could potentially ever download. OGGM could then use that file to verify what it just downloaded for correctness and silent changes.
