### ISSUE TITLE
Add more alternate DEM files

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#69]
ASTER data can be crap, and people did the valuable effort to correct them for many regions of the globe: http://viewfinderpanoramas.org/dem3.html

OGGM already has three region specific DEMs here: https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L756

It would be cool to have more! @JohannesUIBK , if you still have a few hours left on your contract this would be a possible very useful task.

**Comment by JohannesUIBK** [comment]
Sure, I can have a look at it!
Thanks to your efforts there will enough time over the next weeks!

**Comment by fmaussion** [comment]
> there will enough time over the next weeks!

Cool! then maybe it will be worth it ti have a look at the always growing list of [issues](https://github.com/OGGM/oggm/issues) ;-)

**Comment by fmaussion** [comment]
Partly addressed by https://github.com/OGGM/oggm/pull/79 but there is still a bug so I had to revert part of it here: https://github.com/OGGM/oggm/pull/96

I should get back to this soon

**Comment by fmaussion** [comment]
@all : this task is still not finished. The relevant code is here: https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L1133-L1155 (commented because not working...)

**Comment by fmaussion** [comment]
closed via https://github.com/OGGM/oggm/pull/146
