### ISSUE TITLE
Usage: Missing Topography File

### ISSUE THREAD

**Issue by sumnonpuella** [OGGM/oggm#694]
This might be a silly question, but i'm genuinely stuck here. I'm redoing the preprocessing on some RGI regions, but but when I try to initialize a new RGI directory with the following code, 

`cfg.set_intersects_db(utils.get_rgi_intersects_region_file('15', version='5'))`
`path = utils.get_rgi_region_file('15', version='5')`
`rgidf = gpd.read_file(path)`
`gdirs = oggm.workflow.init_glacier_regions(rgidf, reset=True)`

I get the following error message:

`oggm.core.gis: (RGI50-15.00011) define_glacier_region`
`oggm.utils: Downloading http://srtm.csi.cgiar.org/SRT-ZIP/SRTM_V41/SRTM_Data_GeoTiff/srtm_57_07.zip to /home/david/OGGM/download_cache/srtm.csi.cgiar.org/SRT-ZIP/SRTM_V41/SRTM_Data_GeoTiff/srtm_57_07.zip...`
`oggm.core.gis: RuntimeError occurred during task define_glacier_region on RGI50-15.00011: No topography file available for extent lat:(29.916310670920453, 29.979849253756075),lon:(101.99613058463694, 102.0669526041314)!`

I've tried re-downloading the RGI files and walking through the `init_glacier_regions` code, but I can't find what i'm missing. Any pointers would be greatly appreciated. Thank you all in advance for your time!

**Comment by fmaussion** [comment]
Thanks for the report! I'm not sure either, although we can't expect every single glacier to run properly, so it depends how many times this happens. I see you are still using an old RGI version, we really recommend to use RGI6 obtained from OGGM directly.

I'll try to write some documentation today about all this and I'll let you know.

**Comment by fmaussion** [comment]
@sumnonpuella  I've finally managed to get this into the docs. Please have a look at these links: 

https://docs.oggm.org/en/latest/input-data.html#pre-processed-directories

https://docs.oggm.org/en/latest/run.html

It is now the recommend way to initialize OGGM runs. You'll need to update OGGM to the latest repository version for this to run. 

The documentation might still be unclear at times. I'm happy with any feedback you might have!
