### ISSUE TITLE
Download Verification Failed Exception

### ISSUE THREAD

**Issue by peltoglacier** [OGGM/oggm#696]
I'm new to OGGM, and after playing with the getting started tutorial a few times, and running through the Set-up and OGGM Run with the default Rofental region, I am trying to run through these steps with a subset of glaciers I am studing in British Columbia. However, during the pre-processing a subset phase, I am throwing the following error:

2019-02-12 09:39:52: oggm.core.gis: DownloadVerificationFailedException occurred during task define_glacier_region on RGI60-02.07780: /home/pelto/OGGM/download_cache/srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_13_02.zip failed to verify!
is: 69080116 d60e3f58
expected: 42210356 1f0dbe8d

I have tried to pinpoint the cause of this error, but am at a loss!

**Comment by TimoRoth** [comment]
The file in question was downloaded incompletely on the machine used as source of the hashes.
So the hash served its purpose, however the other way around than intended.

That specific file is fixed now, there might be more, given the sheer amount of files there are.

**Comment by peltoglacier** [comment]
Thanks much Timo. That allowed almost all of my glaciers to properly verify the SRTM, however a few are in srtm_13_03, which appears to have the same incomplete download issue:

/home/pelto/OGGM/download_cache/srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_13_03.zip failed to verify!
is: 83973605 b6a34104
expected: 43667597 080d5fea2019-02-12 12:35:38: oggm.core.gis: (RGI60-02.07003) define_glacier_region

**Comment by TimoRoth** [comment]
I will need to find a way to evaluate all the srtm files we have stored. For now you can just turn off the dl_verify param and it will run.

**Comment by fmaussion** [comment]
Note that I will release a new way to initialize glacier directories very shortly, which won't require to download topo data anymore - I'll let you know

**Comment by fmaussion** [comment]
@peltoglacier I've finally managed to get this into the docs. Please have a look at these links: 

https://docs.oggm.org/en/latest/input-data.html#pre-processed-directories

https://docs.oggm.org/en/latest/run.html

It is now the recommend way to initialize OGGM runs. You'll need to update OGGM to the latest repository version for this to run. 

The documentation might still be unclear at times. I'm happy with any feedback you might have!
