### ISSUE TITLE
Can't run the example script

### ISSUE THREAD

**Issue by Keeptg** [OGGM/oggm#702]
The document on OGGM's web seems get update recently. I meet the following Error when I run the new example script(http://docs.oggm.org/en/latest/run_examples/run_rgi_region.html):
    Could not find file at https://cluster.klima.uni-bremen.de/data/gdirs/oggm_v1.1/RGI61/b_080/L4/RGI60-11/RGI60-11.00/RGI60-11.00897.tar.gz
How do I fix this?

**Comment by matthiasdusch** [comment]
The `could not find file` error should be a matter of an older OGGM version. The example script update on the documentation came along with a model update. Please update to the newest OGGM version.

**Comment by Keeptg** [comment]
Thanks for your rapid answer very much. Today, I tried update oggm with "conda update oggm", but it seems not work. The version I got is also "1.0.0". So, I reinstalled the dev/stable version following the steps showing in [http://docs.oggm.org/en/latest/installing-oggm.html](url). The stable version is "1.0.0" and the dev version is "1.0.3+153.g435ef21".
For the dev version, it shows the following Error when I run the script mentioned above:
`DownloadVerificationFailedException: /home/lifei/OGGM/download_cache/cluster.klima.uni-bremen.de/~fmaussion/gdirs/oggm_v1.1/RGI61/b_080/L4/RGI60-11/RGI60-11.00.tar failed to verify!
is: 4587520 f4cc6bda
expected: 21606400 a6b463d4`
Did I miss the right update way?

**Comment by fmaussion** [comment]
> Did I miss the right update way?

No, I think you are OK now. Can you go in your OGGM input directory (`/home/lifei/OGGM/download_cache`) and delete the entire  `cluster.klima.uni-bremen.de` directory?

**Comment by Keeptg** [comment]
@fmaussion Yes, I can delete that directory.

**Comment by fmaussion** [comment]
@Keeptg we might have to make some changes for this to work properly with multi-processing: https://github.com/OGGM/oggm/pull/704 you should still delete the directory, but please await a little before going on, we'll stay in touch

**Comment by Keeptg** [comment]
> @Keeptg we might have to make some changes for this to work properly with multi-processing: #704 you should still delete the directory, but please await a little before going on, we'll stay in touch

OK. Thanks for your hard work.

**Comment by fmaussion** [comment]
Hopefully this should be solved now and the example should work. Let us know if that's not the case

**Comment by fmaussion** [comment]
I also added a line to the documentation explaining how to update from master: https://docs.oggm.org/en/latest/installing-oggm.html#install-oggm-itself

**Comment by Keeptg** [comment]
@fmaussion Nice! It can work now. Thanks again.
