### ISSUE TITLE
importing error when testing

### ISSUE THREAD

**Issue by larry-lu** [OGGM/oggm#709]
Trying to install `oggm` on a Mac Machine using `conda`, following the [installation instruction](http://docs.oggm.org/en/v1.1/installing-oggm.html).

The installation went smooth. However, when I ran `pytest --pyargs oggm`, it shows the following message:

============================= test session starts ==============================
platform darwin -- Python 3.6.7, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
rootdir: /Users/Larry/anaconda3/envs/oggm, inifile:
collected 0 items / 7 errors                                                   

==================================== ERRORS ====================================
__ ERROR collecting lib/python3.6/site-packages/oggm/tests/test_benchmarks.py __
ImportError while importing test module '/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/oggm/tests/test_benchmarks.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
lib/python3.6/site-packages/oggm/__init__.py:34: in <module>
    from oggm.utils import GlacierDirectory, entity_task, global_task
lib/python3.6/site-packages/oggm/utils.py:29: in <module>
    import geopandas as gpd
lib/python3.6/site-packages/geopandas/__init__.py:4: in <module>
    from geopandas.io.file import read_file
lib/python3.6/site-packages/geopandas/io/file.py:3: in <module>
    import fiona
lib/python3.6/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
lib/python3.6/site-packages/fiona/collection.py:9: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: dlopen(/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.71.dylib
E     Referenced from: /Users/Larry/anaconda3/envs/oggm/lib/libgdal.20.dylib
E     Reason: image not found
___ ERROR collecting lib/python3.6/site-packages/oggm/tests/test_graphics.py ___
ImportError while importing test module '/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/oggm/tests/test_graphics.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
lib/python3.6/site-packages/oggm/__init__.py:34: in <module>
    from oggm.utils import GlacierDirectory, entity_task, global_task
lib/python3.6/site-packages/oggm/utils.py:29: in <module>
    import geopandas as gpd
lib/python3.6/site-packages/geopandas/__init__.py:4: in <module>
    from geopandas.io.file import read_file
lib/python3.6/site-packages/geopandas/io/file.py:3: in <module>
    import fiona
lib/python3.6/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
lib/python3.6/site-packages/fiona/collection.py:9: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: dlopen(/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.71.dylib
E     Referenced from: /Users/Larry/anaconda3/envs/oggm/lib/libgdal.20.dylib
E     Reason: image not found
____ ERROR collecting lib/python3.6/site-packages/oggm/tests/test_models.py ____
ImportError while importing test module '/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/oggm/tests/test_models.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
lib/python3.6/site-packages/oggm/__init__.py:34: in <module>
    from oggm.utils import GlacierDirectory, entity_task, global_task
lib/python3.6/site-packages/oggm/utils.py:29: in <module>
    import geopandas as gpd
lib/python3.6/site-packages/geopandas/__init__.py:4: in <module>
    from geopandas.io.file import read_file
lib/python3.6/site-packages/geopandas/io/file.py:3: in <module>
    import fiona
lib/python3.6/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
lib/python3.6/site-packages/fiona/collection.py:9: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: dlopen(/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.71.dylib
E     Referenced from: /Users/Larry/anaconda3/envs/oggm/lib/libgdal.20.dylib
E     Reason: image not found
___ ERROR collecting lib/python3.6/site-packages/oggm/tests/test_numerics.py ___
ImportError while importing test module '/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/oggm/tests/test_numerics.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
lib/python3.6/site-packages/oggm/__init__.py:34: in <module>
    from oggm.utils import GlacierDirectory, entity_task, global_task
lib/python3.6/site-packages/oggm/utils.py:29: in <module>
    import geopandas as gpd
lib/python3.6/site-packages/geopandas/__init__.py:4: in <module>
    from geopandas.io.file import read_file
lib/python3.6/site-packages/geopandas/io/file.py:3: in <module>
    import fiona
lib/python3.6/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
lib/python3.6/site-packages/fiona/collection.py:9: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: dlopen(/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.71.dylib
E     Referenced from: /Users/Larry/anaconda3/envs/oggm/lib/libgdal.20.dylib
E     Reason: image not found
____ ERROR collecting lib/python3.6/site-packages/oggm/tests/test_prepro.py ____
ImportError while importing test module '/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/oggm/tests/test_prepro.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
lib/python3.6/site-packages/oggm/__init__.py:34: in <module>
    from oggm.utils import GlacierDirectory, entity_task, global_task
lib/python3.6/site-packages/oggm/utils.py:29: in <module>
    import geopandas as gpd
lib/python3.6/site-packages/geopandas/__init__.py:4: in <module>
    from geopandas.io.file import read_file
lib/python3.6/site-packages/geopandas/io/file.py:3: in <module>
    import fiona
lib/python3.6/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
lib/python3.6/site-packages/fiona/collection.py:9: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: dlopen(/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.71.dylib
E     Referenced from: /Users/Larry/anaconda3/envs/oggm/lib/libgdal.20.dylib
E     Reason: image not found
____ ERROR collecting lib/python3.6/site-packages/oggm/tests/test_utils.py _____
ImportError while importing test module '/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/oggm/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
lib/python3.6/site-packages/oggm/__init__.py:34: in <module>
    from oggm.utils import GlacierDirectory, entity_task, global_task
lib/python3.6/site-packages/oggm/utils.py:29: in <module>
    import geopandas as gpd
lib/python3.6/site-packages/geopandas/__init__.py:4: in <module>
    from geopandas.io.file import read_file
lib/python3.6/site-packages/geopandas/io/file.py:3: in <module>
    import fiona
lib/python3.6/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
lib/python3.6/site-packages/fiona/collection.py:9: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: dlopen(/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.71.dylib
E     Referenced from: /Users/Larry/anaconda3/envs/oggm/lib/libgdal.20.dylib
E     Reason: image not found
___ ERROR collecting lib/python3.6/site-packages/oggm/tests/test_workflow.py ___
ImportError while importing test module '/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/oggm/tests/test_workflow.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
lib/python3.6/site-packages/oggm/__init__.py:34: in <module>
    from oggm.utils import GlacierDirectory, entity_task, global_task
lib/python3.6/site-packages/oggm/utils.py:29: in <module>
    import geopandas as gpd
lib/python3.6/site-packages/geopandas/__init__.py:4: in <module>
    from geopandas.io.file import read_file
lib/python3.6/site-packages/geopandas/io/file.py:3: in <module>
    import fiona
lib/python3.6/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
lib/python3.6/site-packages/fiona/collection.py:9: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: dlopen(/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.71.dylib
E     Referenced from: /Users/Larry/anaconda3/envs/oggm/lib/libgdal.20.dylib
E     Reason: image not found
!!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 7 error in 1.42 seconds ============================

**Comment by fmaussion** [comment]
Hi @larry-lu , unfortunately this is not an OGGM problem but an installation issue. The important bit is:

```
import geopandas as gpd
lib/python3.6/site-packages/geopandas/init.py:4: in
from geopandas.io.file import read_file
lib/python3.6/site-packages/geopandas/io/file.py:3: in
import fiona
lib/python3.6/site-packages/fiona/init.py:69: in
from fiona.collection import Collection, BytesCollection, vsi_path
lib/python3.6/site-packages/fiona/collection.py:9: in
from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E ImportError: dlopen(/Users/Larry/anaconda3/envs/oggm/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.71.dylib
E Referenced from: /Users/Larry/anaconda3/envs/oggm/lib/libgdal.20.dylib
E Reason: image not found
```

So I think that `import geopandas` should be enough to show the problem. I'm not sure how to help here as I have no mac.  A quick google for the error message shows that you are not the only one with this problem...

**Comment by larry-lu** [comment]
Thanks for the response, @fmaussion .

It's `import fiona` that was causing the problem. Although I could not resolve the problem, I tried to install `oggm` in a differennt environment where `geopandas` and `fiona` are already installed and can be used without problem.

During installation, it gave me the following message:

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib-base
  - oggm -> matplotlib[version='2.1|2.1.*'] -> freetype==2.7
Use "conda info <package>" to see the dependencies for each package.
```

It seems to me that oggm has a version conflict with `Basemap`?

**Comment by fmaussion** [comment]
Another thing you could try is to start from a fresh environment and install all the packages from hand with conda-forge, e.g.:

`conda install -c conda-forge fiona geopandas numpy scipy ...` 

And then install OGGM via pip as explained in the instructions.

cc @TimoRoth who is maintaining the oggm conda channel

**Comment by TimoRoth** [comment]
I am, but I haven't been able to get it to work properly on over a month now, it just keeps crashing without any obvious reason, or produces installations with missing libraries.

**Comment by fmaussion** [comment]
@TimoRoth for these cases it might be good to document the alternative install without the oggm channel maybe. I.e install all packages in one or two commands and just leave the problems upstream to conda or conda forge, not us...

**Comment by TimoRoth** [comment]
The oggm channel has salem and motionless, which are required for oggm. But there are numerous issues with conda lately and they are appearing faster than I am able to keep up fixing them.

I'll see if I can at least generate a working environment with older known good packages to run oggm-1.1

**Comment by TimoRoth** [comment]
I managed to build some environment again that pass the tests at least:
https://github.com/OGGM/OGGM-dependency-list/tree/master/linux-64

For installation to work, your conda root environment needs to be up to date. So run conda update conda and conda update --all before trying to install those environments.
You then also might need to enforce strict channel ordering, because otherwise it will download some of the packages from the default channel instead of conda-forge, which will result in random crashes.

The oggm-1.1 environments come with oggm-1.1 installed. The oggmdev ones do not contain oggm itself, but only all of the dependencies tested to be working at the date the environment was generated. So you need to pip install -e your clone of oggm into them.

**Comment by larry-lu** [comment]
@TimoRoth I appreciate your time. 

I just tried on my Mac, and both the `pytest` part and using OGGM seem to be functional again.
