### ISSUE TITLE
Different results for `run_until` and `run_until_and_store`

### ISSUE THREAD

**Issue by matthiasdusch** [OGGM/oggm#710]
Results for `FluxBasedModel.run_until_and_store(y1)` and `FluxBasedModel.run_until(y1)`  can vary significantly.

More precisely the title should be _"Different results if `run_until` is called with different time steps"_ but I think the most relevant appearance of this phenomena is when comparing results between `run_until` and `run_until_and_store`.

`run_until_and_store` internally calls `run_until` for every year of `y1-y0`. This is identical to  
`for y in range(y1-y0): run_until(y)`.
Therefor `run_until` always starts at the beginning of one year and stops at the end of it.

If `run_until` is called with a time span `> 1yr` it just uses the maximal possible time steps (as determined with a CFL condition) until `y1` is reached. But these time steps can also begin in year y and end in y+1. And then the mass balance and/or elevation_feedback is off.

For many (probably most) glaciers this does not make a huge difference, but for others it can be significant . E.g this is Gepatschferner ('RGI60-11.00746'), run from from_prepro_level=4 with a  temperature bias of -0.45, run for 320yr (on the x axis). y-Axis shows length change in meters. 
![run_until_differences](https://user-images.githubusercontent.com/37663627/54125168-8c8b2d00-4404-11e9-9a2d-285d52d3bb4e.png)

This problem can either be tackled in `FluxBasedModel.step` or probably better in `FluxBasedModel.run_until`. But should we? It would be more accurate but also slower for longer simulations while the effect on many glaciers would be marginal.

I did not want to touch those core functions without discussion first. Possible fixes:
- Prevent run_until from 'crossing' years
- Make it optional e.g by introducing a `dt` parameter
- Make a fast and a slow function
- Don't touch it, but document it (here and in the docs)

**Comment by fmaussion** [comment]
Thanks for the nice post!

I think it's reasonable to make run_until (or, maybe even better: the flowline model) stop at each MB year. On top of the reason you mention, another argument is the mass-balance: indeed, if we significantly exceed the first MB month with the last time step of the preceding year we are making a big difference.

So actually I have the feeling that the flowline model should have an option to force some steps, and the default should be to follow the updates of the mass-balance model.

This is again a very quick though from Reading class-room, but it sounds sensible to me.

cc @juliaeis who might be affected by this change as well.

**Comment by juliaeis** [comment]
Hey, 
Thank you very much for the post! For my runs I use the run_until_and_store() function. A change in run_until() (as you suggested) would hence not affect my running times. In general, I think we should make sure that the two functions behave the same way. So an optional parameter in both functions would be the way I would prefer to. If I understand it correctly, this would then perhaps also speed-up my reconstruction method, as until know, I have used dt=1 ?! 
If we would force the run_until function to stop at each MB year, why do we than have the CFL-condition? Would it not be better to also use this condition for the run_until_and_store() function or would this lead to an problem, because then our time steps, where we save some data would be irregular or to large?

**Comment by juliaeis** [comment]
@matthiasdusch : Do you also have measured the times? So how large is the difference between the running times at your examples?

**Comment by fmaussion** [comment]
> In general, I think we should make sure that the two functions behave the same way. 

Yes, this is why I actually suggest to implement it in `step()`, not any of the `run_until*` functions. The only drawback is that it will become harder to keep the other numerical implementations in line, but I don't think it's a real problem.

> So an optional parameter in both functions would be the way I would prefer to. If I understand it correctly, this would then perhaps also speed-up my reconstruction method, as until know, I have used dt=1 ?!

No, it should be exact same. (and for the older default `run_until`, make it slightly slower)

> If we would force the run_until function to stop at each MB year, why do we than have the CFL-condition? Would it not be better to also use this condition for the run_until_and_store() function or would this lead to an problem, because then our time steps, where we save some data would be irregular or to large?

I don't understand what you mean. But the CFL will only very rarely lead to steps larger than weeks or months, very often much shorter. We still need it for numerical stability, but the new check will just make sure that the step meets each new MB year's start.

> No matter how we change this, an optional parameter would be really good! Because then, I could also use the old way, if I need.

if you used `dt=1` before, this shouldn't change anything for you! (I hope ;-)

**Comment by matthiasdusch** [comment]
`run_until_and_store` is just a wrapper which calls `run_until` year-by-year and stores the intermediate results. If we force the flowline model to "stop" after every MB year this will therefor not affect runs done with `run_until_and_store`.

The CFL condition is to determine the actual time step within the flowline model: Even if you run your model for 1 year (`run_until(1)`) this will be done in multiple time steps which are usually in the order of days.

As for the timing: Some very basic and non significant tests gave me around ~5% difference between `run_until(yr)` and `for y in range(yr): run_until(y)`.  So I think with a smart implementation in the flowline model the runtime differences will be way smaller than I initially thought. 

`run_until_and_store` is a bit slower of course, as it also writes the data. If you are using this function (which you are and probably have to, as you are also interested in the intermediate results) these changes will probably not affect you. Neither positive nor negative :-)

**Comment by juliaeis** [comment]
Then, I'm fine with the changes.

**Comment by matthiasdusch** [comment]
So I tried to tackle this issue and I came to a couple of conclusions. The first being: Gepatschferner, the glacier shown in the example above is just a really really weird glacier!
This plot shows the relative volume change for the same settings as above. I am really not sure what's happening there...
![gep_vol1](https://user-images.githubusercontent.com/37663627/55947039-0efa4d00-5c4e-11e9-917f-f58c589ddd6c.png)

Second conclusion: The difference might not be as big as I initially thought. The main reason being that OGGM's flowline model default timestepping  sets an upper limit of 10 days. And even the 'ambitious' timestepping only uses 15 days as upper limit. So yes this can and does cause a difference, but it should be small for not so weird glaciers...

I implemented a limiting scheme (PR #...) and here are the length and volume differences between the current and my implementation for Hintereisferner :
![len_diff](https://user-images.githubusercontent.com/37663627/55948238-600b4080-5c50-11e9-99e7-74928f20ca6c.png)
![vol_diff](https://user-images.githubusercontent.com/37663627/55948243-61d50400-5c50-11e9-9886-61e245cde3e0.png)
Length differences are within 1 grid point. Volume differences look weird again, but are in the order of 1e5 - 1e6 while the total volume is in the order of 1e9.

As HEF always works well, I randomly picked Oberer Grindelwald glacier and there the differences are basically none existing:
![len_diff_ogr](https://user-images.githubusercontent.com/37663627/55948439-dc058880-5c50-11e9-8a48-39c0ffb0d8f6.png)
![vol_diff_ogr](https://user-images.githubusercontent.com/37663627/55948445-ddcf4c00-5c50-11e9-8b81-fe9fa7a057a1.png)
Length difference is again one grid point, and volume difference is in the order of 10(!) m^3.

If we would proceed from here this for sure needs some more testing, but to be honest I am not even sure if it is necessary. Problems with glaciers like Gepatschferner will not be solved by this.

**Comment by fmaussion** [comment]
Thanks for the great write-up!

> to be honest I am not even sure if it is necessary. 

I would still like to proceed with the change as discussed. Regarding Gepatsch, it would be nice to find out what's going on indeed ;-)

**Comment by fmaussion** [comment]
@matthiasdusch wasn't this solved by https://github.com/OGGM/oggm/pull/743 ?

**Comment by matthiasdusch** [comment]
Yes.

Gepatsch still does wired things. But at least there is no more difference between the timesteps now:
![neu_len_gep](https://user-images.githubusercontent.com/37663627/57838969-06091800-77c6-11e9-96e7-36a8715d5e4f.png)
![neu_vol_gep](https://user-images.githubusercontent.com/37663627/57838980-099c9f00-77c6-11e9-9166-7f273de1d347.png)

**Comment by fmaussion** [comment]
Haha how weird is that!
