### ISSUE TITLE
One question about thickness calculation

### ISSUE THREAD

**Issue by Keeptg** [OGGM/oggm#714]
Hi,
I try using OGGM calculate ice thickness recently. And I compared my result with the data showing in paper"A consensus estimate for the ice thickness distribution of all glaciers on Earth". I find my maximum value is far more than the paper's data. For example, for the glacier RGI-13.53249, my maximum is 543.3 m, however it is only about 179 m in the paper's data. Also, my thickness distribution seems unreasonable(see My result VS. Paper data in RGI60-14.15990). So where is my problem? The following is my script the paper's thickness data and comparing plot:
[thickness_RGI60-13.53249.zip](https://github.com/OGGM/oggm/files/2976195/thickness_RGI60-13.53249.zip)
![My result(RGI60-14 15990)](https://user-images.githubusercontent.com/42733729/54504568-20ae4480-496f-11e9-8ec8-a06c973b546e.png)
![Paper data(RGI60-14 15990)](https://user-images.githubusercontent.com/42733729/54504576-2f94f700-496f-11e9-9e50-1bb3cc959df3.png)

```
import os
from os.path import join
import sys
import oggm.cfg as cfg
from oggm import utils, workflow, tasks

cfg.initialize(logging_level='WORKFLOW')
rgi_version = '61'

WORKING_DIR = join(os.path.split(sys.argv[0])[0], 'Working_dir')
utils.mkdir(WORKING_DIR, reset=True)
cfg.PATHS['working_dir'] = WORKING_DIR

rgiid = 'RGI60-13.53249'

rgidf = utils.get_rgi_glacier_entities([rgiid], version='61')

gdirs = workflow.init_glacier_regions(rgidf, from_prepro_level=3,
                                      prepro_border=10)
gdir = gdirs[0]
tasks.mass_conservation_inversion(gdir)
tasks.filter_inversion_output(gdir)
tasks.distribute_thickness_interp(gdir)
```

**Comment by fmaussion** [comment]
Haha, good question, and *very* good example ;-).

You've picked one of the best examples:
- here the RGI glacier entity is completely wrong (these are at least two glaciers, not one)
- the default DEM (SRTM) is very noisy and has artifacts

Now, OGGM used the same data to compute the thickness, so we should understand what's going on. Are you comparing to the composite estimate from Farinotti et al? Because the composite is an average of all model results. To compare to mine, use "model 3" data. Second, I used "optimized" parameters for the run, see: https://oggm.org/2018/05/21/g2ti/ (the most important being that I used A=1.5 times the default).

Now, if you want to make the best estimate for this one glacier, my recommendation is to start by separating the glaciers into two entities, then use an alternative DEM. I'll try to write a tutorial about this later this week. (for the alternate DEM we already have a tutorial, see OGGM Edu: http://edu.oggm.org/en/latest/oggm_tuto.html )

**Comment by Keeptg** [comment]
> Are you comparing to the composite estimate from Farinotti et al?
I choose the model 3 result to comparing. Following your advise, I change another glacier `RGI-17.14016` and reset glen_a with `glen_a = cfg.PARAMS['glen_a'] * 1.5`. But there still exist a large difference. I put the results in there for your convenience. The first picture is my result, and the second is model 3.
![My results(RGI-17 14016)](https://user-images.githubusercontent.com/42733729/54524960-24ad8700-49ae-11e9-91b6-4194065a3702.png)
![Farinotti et al_model3(RGI-17 14016)](https://user-images.githubusercontent.com/42733729/54525007-3abb4780-49ae-11e9-8988-3210d500aea8.png)

**Comment by fmaussion** [comment]
Yyou are right! I just tried it myself and on latest OGGM I get thicker values as well. I will investigate, but not before tomorrow -> right now I tend to think that there is an issue with the data online OR in the interpolation algorithm, but I can't be sure.

This is my code (slight modifs to yours):

```python
%matplotlib inline
import xarray as xr
import os
from os.path import join
import sys
import oggm.cfg as cfg
from oggm import utils, workflow, tasks

cfg.initialize(logging_level='WORKFLOW')
rgi_version = '61'

# Update Glen A
cfg.PARAMS['inversion_glen_a'] = cfg.PARAMS['glen_a'] * 1.5

WORKING_DIR = join(os.path.split(sys.argv[0])[0], 'Working_dir')
utils.mkdir(WORKING_DIR, reset=True)
cfg.PATHS['working_dir'] = WORKING_DIR

rgiid = 'RGI60-17.14016'

rgidf = utils.get_rgi_glacier_entities([rgiid], version='61')

gdirs = workflow.init_glacier_regions(rgidf, from_prepro_level=3,
                                      prepro_border=10)
gdir = gdirs[0]
tasks.prepare_for_inversion(gdir)
tasks.mass_conservation_inversion(gdir)
tasks.filter_inversion_output(gdir)
data = tasks.distribute_thickness_interp(gdir)
summary = utils.compile_glacier_statistics(gdirs)

summary.T
```

which gives:

```
inv_volume_km3                                 0.207004
inv_thickness_m                                  50.761
vas_volume_km3                                 0.234879
vas_thickness_m                                 57.5966
```

"VAS" means volume area scaling so we are not making an error of factor 3 on the total volume at least ;)

**Comment by Keeptg** [comment]
> right now I tend to think that there is an issue with the data online OR in the interpolation algorithm, but I can't be sure.

The online data seems more accurate. But everything depends on your investigation results finally.

**Comment by fmaussion** [comment]
@Keeptg I see now: you need to interpolate the flowline glacier with `distribute_thickness_per_altitude`, not `distribute_thickness_interp`. Then you'll have results very similar to Farinotti et al. (note that it's not exactly equivalent because of differences in DEMs and some changes in the mass-balance model since then). But much closer now ;-)

**Comment by Keeptg** [comment]
@fmaussion 
Yes，you are right! Thanks very much~

**Comment by fmaussion** [comment]
If you feel like improving the interpolation methods please give it a go ;-)

**Comment by Keeptg** [comment]
> If you feel like improving the interpolation methods please give it a go ;-)

OK, I will have a try about this.

**Comment by Keeptg** [comment]
> Now, if you want to make the best estimate for this one glacier, my recommendation is to start by separating the glaciers into two entities, then use an alternative DEM. I'll try to write a tutorial about this later this week.

Can OGGM use other glacier inventory now? Due RGI lack many glacier outlines in the southeastern part of Tibet, I want to use Sencond Glacier Inventory China(CGI) instead of RGI to calculate the glacier thickness and volumns.
The first method I thought is faking a RGI by changing CGI's geodataframe columns list. But there seem some special column names that can't be represented with CGI's item. (e.g: "O1Region")
So if there any official method to replace rgi to other Glacier Invertory or any information which list the  indispensable item and the removable item?

**Comment by fmaussion** [comment]
> The first method I thought is faking a RGI by changing CGI's geodataframe columns list

yes! This is the best way to go. You can use dummy values for most of the columns, they are not used quantitatively by OGGM. The only ones that really matter somewhere in the OGGM process are:
- RGIId: some unique ID
- lon, lat
- geometry (should be in lon, lat space I think)
- area: if you don't have the area pre-computed, then you should set `use_rgi_area` to False (https://github.com/OGGM/oggm/blob/master/oggm/params.cfg#L91) and OGGM will compute it for you.
- glacier type (water terminating or not)
