### ISSUE TITLE
local OGGM version number is not updated

### ISSUE THREAD

**Issue by matthiasdusch** [OGGM/oggm#716]
Even though I am using the latest version from github my local OGGM version says `oggm.__version__ = 1.0.3+162.g64245a4` instead of `1.1+3.g64245a4`. The commit-id is correct, but the release number wasn't updated.

I could look into this myself but I guess @TimoRoth you will be much quicker about this.

**Comment by TimoRoth** [comment]
Make sure your local git clone has the 1.1 tag.
Try git fetch --tags to make sure.

**Comment by matthiasdusch** [comment]
Thanks. I thought this would be handled internally and fetch/pull would be enough.
