### ISSUE TITLE
error in download.py

### ISSUE THREAD

**Issue by innopat** [OGGM/oggm#718]
I am studying how to use OGGMv1.1.

Following the guideline, an error occured when dowloading the glacier outlines as shown below.

>>> utils.get_rgi_dir()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yanq/soft/miniconda3/envs/oggm_env/lib/python3.7/site-packages/oggm/utils/_downloads.py", line 1105, in get_rgi_dir
    return _get_rgi_dir_unlocked(version=version, reset=reset)
  File "/home/yanq/soft/miniconda3/envs/oggm_env/lib/python3.7/site-packages/oggm/utils/_downloads.py", line 1112, in _get_rgi_dir_unlocked
    version = cfg.PARAMS['rgi_version']
KeyError: 'rgi_version'
>>> exit()

Although it is also easy to download the data mannually and then upload it, i am wondering if it is possible to fix it?

Thanks

Qing

**Comment by fmaussion** [comment]
Hi Qing, very likely you forgot to run `cfg.initialize()` before calling `get_rgi_dir`.

Are you aware of our online tutorials? 

http://edu.oggm.org/en/latest/oggm_tuto.html

**Comment by innopat** [comment]
Dear Fabien,

Thank you very much for the quick reply and sorry for the stupid question.

I am now studying online tutorials

Thanks

Sincerely

Qing



 
From: Fabien Maussion
Date: 2019-03-19 14:15
To: OGGM/oggm
CC: innopat; Author
Subject: Re: [OGGM/oggm] error in download.py (#718)
Hi Qing, very likely you forgot to run cfg.initialize() before calling get_rgi_dir.
Are you aware of our online tutorials?
http://edu.oggm.org/en/latest/oggm_tuto.html

**Comment by fmaussion** [comment]
Hi Qing, no worries. Great that you are trying OGGM!
