### ISSUE TITLE
Typo RGIv6 region 4 folder name

### ISSUE THREAD

**Issue by anoukvlug** [OGGM/oggm#723]
I just noticed that the folder names of RGI region 4 are `RGI_V61_Intersects/04_rgi61_ArcticCanadaNorth`, `RGIV60/04_rgi60_ArcticCanadaNorth` and `RGIV61/04_rgi61_ArcticCanadaNorth`, while region 4 is the ArcticCanadaSouth.

**Comment by fmaussion** [comment]
Hi @anoukvlug , thanks! Yes, I've noticed as well (or rather, OGGM noticed). It is an RGI problem, and is listed here: 

https://rgitools.readthedocs.io/en/latest/known-issues.html

Not much we can do, let's hope it's going to be solved in RGI7...

**Comment by anoukvlug** [comment]
That is good to know. I didn't realize that is was already on the docs page. Shall I close this issue as there is not much we can do about it or leave it open?

**Comment by fmaussion** [comment]
Let's close this for now. thanks!
