### ISSUE TITLE
Add flexibility to BASENAMES

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#731]
I'd like users like @bearecinos to add stuff to basenames from outside OGGM. This should be quite easy to implement (or document).

**Comment by bearecinos** [comment]
well .. I have re-write a function for pickle in my own utils thing.. I might think about it and add it later... 

`def write_pickle_file(gdir, var, filename, filesuffix=''):
    """ Writes a variable to a pickle on disk.

    Parameters
    ----------
    var : object
        the variable to write to disk
    filename : str
        file name
    filesuffix : str
        append a suffix to the filename (useful for experiments).
    """
    if filesuffix:
        filename = filename.split('.')
        assert len(filename) == 2
        filename = filename[0] + filesuffix + '.' + filename[1]

    fp = os.path.join(gdir.dir, filename)

    with open(fp, 'wb') as f:
        pickle.dump(var, f, protocol=-1)`
