### ISSUE TITLE
Version numbers in OGGM

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#732]
We are going towards more frequent releases now. Currently [we have](https://github.com/OGGM/oggm/releases):
- v1.1
- v1.0.3
- v1.0.2
- v1.0.1
- v1.0.0
- v0.1.1

We need to clarify what we meant by version numbers. Ideally they would mean something according to [semantic versioning](https://semver.org/), i.e. in short:
- MAJOR version when you make incompatible API changes
- MINOR version when you add functionality in a backwards-compatible manner, and
- PATCH version when you make backwards-compatible bug fixes.

To be honest I'm not sure we can ever apply this kind of versioning to OGGM. It might imply delaying certain PRs, or maintain so-called "maintenance" branches. Major changes would happen all the time, OR we have to define "major changes" as the one really affecting the ouptut in a significant way. 

I would really love to follow these rules, but I wonder how much we can comply to it, and at what cost. 

@OGGM/oggm-devs , thoughts?

**Comment by fmaussion** [comment]
(note: alternative calendar versioning is also a thing: https://calver.org/)

**Comment by TimoRoth** [comment]
With how it is right now, we could use the stable branch for OGGM v1.1, and only backport fully compatible patches there, like fixing the download verification and tests on recent Conda versions. To eventually release v1.1.1 from it.
While master is 1.2-dev, which at some point in the future v1.2 will be release from, which will then become the new stable branch, and receive micro updates in there, with 1.1 being retired from support.

**Comment by fmaussion** [comment]
> backport fully compatible patches there

If we do this, we have to follow the lead of larger projects: don't allow direct commits to master (I'm in favor of this anyway), in order to label PRs ideally at the time they are merged with a milestone, like ipython does: https://github.com/ipython/ipython/milestones . Then, we can do a backport action before release. 

We'd have to be careful for each PR to be selected for backport or not. Looking at the [current list of commits](https://github.com/OGGM/oggm/commits/master), we have to classify them then backport them.

The real question is: do we want that? What changes define a new minor version, a new major version?

**Comment by fmaussion** [comment]
OK, after more thoughts: I think we should forget about micro release numbers and backports, and simply release minor versions more often. E.g. v1.2 soon when @bearecinos submits her paper, and so (v1.3, ... , v1.11, v1.12, etc) until a "big change" impedes a new major version. This would allow quick development and less burden.

Reproducibility is ensured by the docker container tag which is used for testing at a specific release date, i.e. we don't have to care about backporting tests or whatever. OGGM v1.1 is guaranteed to work with docker tag BLAH, v1.2 with docker tag BLOH, etc.

**Comment by TimoRoth** [comment]
Yes, that would make things a lot easier.
Docker automatically tags containers for every tag that's made on this repository.
The only problem with them is that they will forever rely on downloads, that for example in the case of srtm breaking some of their files, have already stopped working. Which at the moment makes the 1.1 Docker container, and 1.1 in itself, pretty much unusable. Which makes me think we should release 1.1.1 from the current stable branch, with just the patches to fix the Download Verification and Test-Data added.
Or we can release it from master as it is now, but that would confuse the version scheme, since it would jump from 1.2-dev to 1.1.2-dev then. Also, master had a few additions already that go beyond just fixing bugs.

**Comment by fmaussion** [comment]
> The only problem with them is that they will forever rely on downloads

yes, ok. But in this case, it is straightforward to switch to v1.2 without changes in the model output. Also, we now provided pre-processed directories which will always work (as long as the cluster is online). We can't solve all problems...

On the long term, it is a pity that we rely on external downloads that might brake, but I really don't see any reasonable solution to this other than hosting the data ourselves, which cannot be done for all datasets anyway...

**Comment by fmaussion** [comment]
OK, I'v kind of written down our intent in the docs: https://docs.oggm.org/en/latest/practicalities.html#source-code-and-version-control
