### ISSUE TITLE
Pre-processed dirs should have model flowlines in them

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#736]
I wrote in the documentation:
- Level 1: the lowest level, with directories containing the glacier topography and glacier outlines only.
- Level 2, adding the baseline climate timeseries (CRU, see below) to this folder.
- Level 3, adding the output of all necessary pre-processing tasks for a dynamical run, including the bed inversion using the default parameters.
- Level 4, same as level 3 but with all intermediate ouptut files removed. The strong advantage of level 4 files is that their size is considerably reduced, at the cost that certain operations (like plotting on maps or running the bed inversion algorithm again) are not possible.

This is currently wrong, as the level 3 files don't have the output of `init_present_time_glacier` in them. Here the documentation is better than the code :roll_eyes:

**Comment by matthiasdusch** [comment]
I think I have to reopen that issue as I still don't get `model_flowlines` with level 3 prepro dirs. I think the code is implemented but the prepro dirs have not been rebuild with it?

Or can someone _not_ reproduce that error:
```
import oggm.cfg as cfg
from oggm import utils, workflow, tasks, graphics
import matplotlib.pyplot as plt

WORKING_DIR = utils.gettempdir('eklutna')
utils.mkdir(WORKING_DIR, reset=True)
cfg.initialize(logging_level='WORKFLOW')
cfg.PATHS['working_dir'] = WORKING_DIR

eklutna = 'RGI60-01.08989'
rgidf = utils.get_rgi_glacier_entities([eklutna])

gdir = workflow.init_glacier_regions(rgidf, from_prepro_level=3, prepro_border=10)[0]
gdir.read_pickle('model_flowlines')
```
`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/OGGM/eklutna/per_glacier/RGI60-01/RGI60-01.08/RGI60-01.08989/model_flowlines.pkl'`

**Comment by fmaussion** [comment]
Yes, that is correct: I corrected the code but the pre-processed gdirs are
still the old ones - there is a long overdue update of these dirs, but now
I'd like to wait until we have settled on a topo data...

**Comment by matthiasdusch** [comment]
Yes, I agree to wait. I just was a bit confused as I thought this was fixed _and_ deployed.
