### ISSUE TITLE
Pytest unrecognized arguments --mpl

### ISSUE THREAD

**Issue by phigre** [OGGM/oggm#757]
When reinstalling oggm and trying the entire test suite as described by the manual:
`pytest --pyargs oggm --run-slow --mpl`

I encountered the error:

`ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]`
`pytest: error: unrecognized arguments: --mpl`

It seems like this should be easy to fix (maybe only documentation?), but I am not too deep into pytest and don't have time to do it myself at the moment. Not top priority but maybe desirable to fix to make a good impression to new users.

**Comment by fmaussion** [comment]
I've noticed the same recently. @TimoRoth ?

**Comment by TimoRoth** [comment]
That just means that you didn't install pytest-mpl.
It's part of every way we provide for setting up an environment, since OGGM needs our modified version of it: https://github.com/OGGM/pytest-mpl
Not sure how it would be possible to end up without it, unless you setup your environment via pip/conda manually, and simply didn't install it.

**Comment by fmaussion** [comment]
Our pip install instructions are missing this part. Especially that one needs to install our flavor of it...

https://docs.oggm.org/en/v1.1/installing-oggm.html

**Comment by phigre** [comment]
Thanks a lot for the reply.
Interestingly, I did install oggm-deps via conda, so I guess it should have been installed?

**Comment by TimoRoth** [comment]
oggm-deps only includes runtime dependencies, not test-dependencies.
They are included in the pre-tested environments though: https://github.com/OGGM/OGGM-dependency-list/blob/master/linux-64/oggmdev-latest_py37.yml

**Comment by phigre** [comment]
Ok, I see. Thank you very much!
