### ISSUE TITLE
Add a picture test

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#758]
In #725 we added a graphic test but I marked it as ``xfail`` because I don't have a machine with the right truetype version at hand.

If someone (@TimoRoth ?) has time it would be good to add it to the sample directory.

Here is the test:  

https://github.com/OGGM/oggm/blob/734936916b961498fae32afc40ec2d1b4aedf5a2/oggm/tests/test_graphics.py#L75-L84

**Comment by TimoRoth** [comment]
You mean just generate the baseline image? That should be easy enough to do.
Is the old Truetype still a problem? I'm not aware of anything still using it.

**Comment by fmaussion** [comment]
> You mean just generate the baseline image? That should be easy enough to do.

Yes, and marking the test as not xfail. Thanks!

> Is the old Truetype still a problem? I'm not aware of anything still using it.

Yeah, my local linux mint is getting old... Still on python 3.5 for example
