### ISSUE TITLE
Error Raised on task gridded_mb_attributes

### ISSUE THREAD

**Issue by MatCast** [OGGM/oggm#764]
When running the task `gridded_mb_attributes` several alp glaciers raise the following error:
`RuntimeError('Spec mass-balance should be zero.')`

This error means that the sum of the mass balance over the whole glacier area is not zero, even though the Mass Balance was initialized with a `LinearMassBalance` model.

Following glaciers raise the error:

- RGI60-11.00846
- RGI60-11.00106
- RGI60-11.00415
I only tried this task for the glaciers in the alp having thickness measurements entries in GlaThiDa hence i don't know whether more glaciers would raise this error.
The error could be caused by scipy.optimize.minimize() not minimizing correctly the equilibrium line altitude.

**Comment by fmaussion** [comment]
Thanks! Will have a look

**Comment by fmaussion** [comment]
In these lines:

https://github.com/OGGM/oggm/blob/25ccc5c82e01a99461e3e1f9e6c530e6c742033c/oggm/core/gis.py#L1062-L1063

and 

https://github.com/OGGM/oggm/blob/25ccc5c82e01a99461e3e1f9e6c530e6c742033c/oggm/core/gis.py#L1079-L1080,

could you replace the error message with 

```python
raise RuntimeError('Spec mass-balance should be zero but is: {}'.format(np.sum(oggm_mb_on_z)))
```

and try again? I think it's just that the test is a bit too strict and we might need to increase the tolerance a little bit

**Comment by MatCast** [comment]
So i just checked for RGI60-11.00846: the sum is in fact -1.01 which i think can be tolerated as we are taking about 1kg per year.

**Comment by fmaussion** [comment]
yes, just increase the tolerance to 10, and update the error message to print the sum if failed.

Can you make a PR?

**Comment by MatCast** [comment]
Sure i will do it right now.

**Comment by MatCast** [comment]
Now it works for all the alpine glaciers the GlaThiDa
