### ISSUE TITLE
Readthedocs builds broken again

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#766]
@TimoRoth any idea? I think that conda is to blame...

**Comment by TimoRoth** [comment]
One Idea I'd have is replacing https://github.com/OGGM/oggm/blob/master/docs/environment.yml with https://github.com/OGGM/OGGM-dependency-list/blob/master/linux-64/oggmdev-latest_py37.yml.
Not sure how scriptable the build process is to download that file on its own.

**Comment by fmaussion** [comment]
> Not sure how scriptable the build process is to download that file on its own.

This is very improbable. But if we have a pinned file that works, it should work for a long time anyways (unless we rely on a later version, which doesn't happen often)
