### ISSUE TITLE
Glacier volume using OGGM

### ISSUE THREAD

**Issue by aniketgupta2009** [OGGM/oggm#772]
Dear All,
Greetings!

I am very new to OGGM and stuck in one initial problem. I have selected the glacier and able to plot the distributed ice thickness of selected glacier. However, while calculating the volume we are not able to get the suitable volume.

We are doing [summation of (90m*90m*thickness in each pixel in meter)]. We are excluding the NaN values in our calculation through replacing them by zero.

Kindly, guide me on how to calculate the proper ice volume of glacier.

Thanking You.

**Comment by MatCast** [comment]
Hi Aniketggupta,
what do you mean by suitable volume? You don't get a reasonable value or you don't get a value at all?
To get the volume of any glacier, provided that you already run all the `oggm.task` necessary to get the thickness value of you glacier, you can simply run the following commands:
```
import xarray as xr
ds = xr.open_dataset(gdir.get_filepath('gridded_data'))
np.nansum(ds.thickness.values * gdir.grid.dx**2) 
```
If this is not what you were looking for just please write you code to better understand the problem.

**Comment by aniketgupta2009** [comment]
Dear Sir,

Thank you very much your reply.

Yes, the code works for me. I have applied it to the gangotri glacier[RGI60-15.06881] and calculated the volume as 17.79 Km3.

But, I still have one confusion. If we are using the SRTM 90 meter resolution data, why I am getting the [dx,dy] as [165,165] meter. When printing the gdir, I am getting the, gdir.grid.dx = 165.

Kindly, clear my doubt.



Thanking You.

Best Regards
Aniket Gupta



________________________________

**Comment by fmaussion** [comment]
> But, I still have one confusion. If we are using the SRTM 90 meter resolution data, why I am getting the [dx,dy] as [165,165] meter. When printing the gdir, I am getting the, gdir.grid.dx = 165.

The reason for this is explained in section 3.1 of the [OGGM paper](https://www.geosci-model-dev.net/12/909/2019/gmd-12-909-2019.pdf). 

Please also bear in mind that SRTM actually doesn't have a resolution of 90m, but is defined in a lat/lon grid, i.e. the actual resolution of SRTM depends on the latitude. For OGGM (and global ITMIX), we are working on map projections (in meters).
