### ISSUE TITLE
OGGM tutorial error

### ISSUE THREAD

**Issue by peltoglacier** [OGGM/oggm#796]
I'm playing around with the tutorials to better figure out how to compare my mass balance measurements and ice thickness observations to the modeled MB and ice thickness.

Using thickness_model.ipynb I am throwing a few errors, which may all be related to the first.

First error is thrown when running:
`# Tested tasks
task_list = [
    tasks.gridded_attributes,
    tasks.gridded_mb_attributes,
]
for task in task_list:
    workflow.execute_entity_task(task, gdirs)`

OSError: [Errno -101] NetCDF: HDF error: b'/tmp/OGGM/OGGM_Toy_Thickness_Model/per_glacier/RGI60-01/RGI60-01.16/RGI60-01.16195/gridded_data.nc'

Second error when plotting the aspect and oggm_mb_above_z variables:
AttributeError: 'Proj' object has no attribute 'is_latlong'

Third error when using cross-validation to select the regularization parameter:
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by fmaussion** [comment]
Hi! The first two are new to me, the second one has made my day much worse than many other days ;-).

It is solved on salem/master, so if you are working locally I'd recommend to upgrade salem with

`pip install git+https://github.com/fmaussion/salem.git`

I'll investigate the other ones very soon

**Comment by peltoglacier** [comment]
Thanks Fabien! I was using the tutorial on binder when I had the errors. I will test out a similar run with one of my study sites locally shortly.

**Comment by fmaussion** [comment]
> Thanks Fabien! I was using the tutorial on binder when I had the errors

That's awesome! I've been changing things behind the scene today, and new links will come up soon.

Try [this world premiere link](https://mybinder.org/v2/gh/OGGM/oggm-edu-r2d/master?urlpath=git-pull?repo=https://github.com/OGGM/oggm-edu%26amp%3Bbranch=master%26amp%3Burlpath=lab/tree/oggm-edu/notebooks/oggm-tuto/welcome.ipynb%3Fautodecode) instead, it should run without errors now ;-)

**Comment by fmaussion** [comment]
(I think that error 1 and 3 are very strange and might come from a corrupt download or something - never seen this before...)

**Comment by jsignell** [comment]
I came across this while chasing a similar error on hvplot. I think the is_latlong error is real for pyproj>2.2. See https://github.com/pytroll/pycoast/issues/27

**Comment by fmaussion** [comment]
thanks @jsignell ! Yes, pyproj has created quite some problems for us recently...

**Comment by AndreasLuckert** [comment]
Hey guys,

I'd love if I didn't have to carry out `pip install git+https://github.com/fmaussion/salem.git` after every global update of all my pip-packages to the latest versions.
The problem seems to be that the latest pip-version of salem still contains the error causing `AttributeError: 'Proj' object has no attribute 'is_latlong'`.
I just had the issue again, executed `pip install git+https://github.com/fmaussion/salem.git` to solve it once again.

Thanks in advance for implementing this fix in the latest version of salem available and distributed via pip.

**Comment by fmaussion** [comment]
@AndreasLuckert  thanks for the report. This is more an issue for https://github.com/fmaussion/salem , but I agree. I will do a release shortly.

**Comment by fmaussion** [comment]
OK, a new release is on PyPi: https://pypi.org/project/salem/
