### ISSUE TITLE
assert in `flows_to_indice` is called on undefined variable `ind`

### ISSUE THREAD

**Issue by matthiasdusch** [OGGM/oggm#820]
https://github.com/OGGM/oggm/blob/13ca306fbfe1ce103697120bd2c0d88b2af11714/oggm/core/centerlines.py#L144-L152

I'll fix that myself

**Comment by fmaussion** [comment]
> I'll fix that myself

That made my day ;-)

**Comment by matthiasdusch** [comment]
by #834
