### ISSUE TITLE
File is not a zip file

### ISSUE THREAD

**Issue by Keeptg** [OGGM/oggm#826]
Hello,
I want to use another glacier inventory instead of RGI. So, I can't download the gdir data such as `centerlines`, `inversion_flowlines` et. al. from OGGM's official pre-processed pool, only calculate them. The following code is used to test the workflow of glacier region initializing:
```
import geopandas as gpd
from oggm import utils, tasks, workflow, cfg
from oggm.workflow import execute_entity_task

cfg.initialize()
cfg.PATHS['working_dir'] = './working_dir'
cfg.PARAMS['mp_processes'] = 65
cfg.PARAMS['dl_verify'] = False

rgi_version = '61'
rgi_region = '13'
path = utils.get_rgi_region_file(rgi_region, version=rgi_version)
rgidf = gpd.read_file(path)
gdirs = workflow.init_glacier_regions(rgidf[:10])

task_list = [
        tasks.glacier_masks, 
        tasks.compute_centerlines,
        tasks.initialize_flowlines,
        tasks.compute_downstream_line,
        tasks.compute_downstream_bedshape,
        tasks.catchment_area,
        tasks.catchment_intersections,
        tasks.catchment_width_geom,
        tasks.catchment_width_correction,
        tasks.process_cru_data,
        tasks.local_t_star,
        tasks.mu_star_calibration]

for task in task_list:
    execute_entity_task(task, gdirs)
```
While, I meet the following Error:
![1563355103(1)](https://user-images.githubusercontent.com/42733729/61363895-57618080-a8b7-11e9-8e9f-d210646e5fe8.png)
It seem's that the SRTM data was uncompressed automatically. I lookd at  `params.cfg` file and  `oggm.core.gis.py` module, hoping to find relevant parameters to set up. But I failed. Can you please give me any ideas to solve this problem?

**Comment by matthiasdusch** [comment]
I am confused: Have you at this stage already implemented your own glacier inventory? Something like edited the RGI files?

If not and the code above is pure clean OGGM code, I don't really see a reason why it should fail except for file system or file corruption problems. Which file exactly raises this BadZipFile Error? Can you delete it and let OGGM redownload it? Do you have enough disc space, etc..

**Comment by Keeptg** [comment]
@matthiasdusch Thanks for your prompt reply
> Have you at this stage already implemented your own glacier inventory? 

I'm not use my own glacier inventory in the upper code, but I do tried it. The result shows the same Error. I've tried delete the directory `~/OGGM/tem` and `./working_dir` but the result had no improvement.

> Do you have enough disc space

My disk should have enough space

> Which file exactly raises this BadZipFile Error? 

The DEM data OGGM own download is like this:
![image](https://user-images.githubusercontent.com/42733729/61377764-73c0e580-a8d6-11e9-9a6c-2dde28462731.png)
It is not a zip file. I guess this Error caused by DEM data, but I'm not sure. Is there any other data that I can delete? 

Did those code work well in your environment?

**Comment by matthiasdusch** [comment]
OK, so first of all I just realised: You should set `cfg.PARAMS['dl_verify'] = True`. 
Any particular reason you set this to False?

Second: `~/OGGM/tmp` just contains the latest used unziped files. The zipfiles are stored at `~/OGGM/download_cache`. If the error comes from a corrupt dem zipfile it should be located there. 

But like I said, please rerun your script with the download verification set to true, this should point to a broke file.

Yes, your code worked for me without problems.

**Comment by Keeptg** [comment]
> OK, so first of all I just realised: You should set cfg.PARAMS['dl_verify'] = True.
Any particular reason you set this to False?

#694 and #696 is the reason I set cfg.PARAMS['dl_verify'] = False 

`~/OGGM/download_cache` DEM data is zip file, that's OK. :(

**Comment by Keeptg** [comment]
@matthiasdusch Thanks your reply very much!
Despite I still don't figure out which file cause the BadZipFile Error, the code do work after I update OGGM to the newest dev version. Thanks again!
