### ISSUE TITLE
deployment folder

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#849]
@TimoRoth is anything in this folder still needed? 

https://github.com/OGGM/oggm/tree/master/deployment

The fabfile clearly not, but what about  the /docker folder?

**Comment by TimoRoth** [comment]
The docker directory is where the Dockerfile is that's used for the oggm/oggm Docker image.

**Comment by fmaussion** [comment]
OK, then we should keep them ;-) 

I will delete the fabric scripts, though
