### ISSUE TITLE
Add test for downloads?

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#86]
Most of the tests which require a download of large files have a `test_download` decorator which is defined here: https://github.com/OGGM/oggm/blob/master/oggm/tests/__init__.py#L55

This was done so that one can tests the downloads locally (by setting the `RUN_DOWNLOAD_TESTS` variable to True, or with an environment variable). The tests are not run on travis, because downloads are unstable and because I didn't want to overwhelm the data providers with countless requests from Travis.

Maybe some tests could be run from time to time, maybe at random times or something. Thoughts?

**Comment by fmaussion** [comment]
After https://github.com/OGGM/oggm/pull/146, there is plenty of room for improvement:
- a lot of code is duplicated
- the download logic could be tested by making the methods return a www path instead of actually downloading the file
- the downloads are still not 100% robust. A ``robust_download`` function taking care of this logic would be extremely useful (see for example: https://github.com/OGGM/oggm/blob/master/oggm/utils.py#L312-L339)

@TimoRoth let me know if you have interest and time to have a look at these in the upcoming weeks

**Comment by TimoRoth** [comment]
The downloaded data could just be cached on Travis, if it's not too large, that should also make it fairly reliable.
Will look into it.

**Comment by fmaussion** [comment]
Thanks a lot, this is very helpful! But again, I still think that all get_* routines should return a www path, and that one function should take care of the actual download, to improve the testing and to avoid duplicated code.

If you have time it would be very cool to add also this option that all data downloaded externally could be stored on Amazon S3 for later use.  (that is, we download SRTM data, CRU data, and DEM3 data once and only once from their - slower - servers )

**Comment by fmaussion** [comment]
This has been partly addressed by https://github.com/OGGM/oggm/pull/284
