### ISSUE TITLE
Thesis topic: estimation of ice thickness using inverse methods

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#868]
## Motivation

OGGM is able to compute the volume of glaciers using only surface properties. See [this paper](https://www.the-cryosphere.net/11/949/2017/) for a good overview of ice thickness estimation methods, and [this paper](https://www.nature.com/articles/s41561-019-0300-3) for a global application.

That said, OGGM's way of doing things is quite simple and has several caveats: it doesn't work well for large ice fields (ice caps), and rely on a very strong assumption: that glaciers are in steady state. Therefore, we started to explore better ways to deal with the problem. In 2018, we started a new project which is computing ice thickness with a completely new approach: [COMBINE](https://github.com/OGGM/COMBINE), written by @phigre and documented in [his thesis](http://diglib.uibk.ac.at/ulbtirolhs/content/titleinfo/3086935).

In this new thesis topic, I propose to build upon and extend this work in two possible ways (all listed below).

## Specific goals

I suggest to address one of these goals, which are largely independant:

1. **Apply COMBINE to real world ice caps**. In his thesis, Philipp used a theoretical, idealized environment to develop and test the method. The next natural step would be to try it out in the wild! This will come with a bunch of new challenges ;-)

2. **Release the steady state assumption in COMBINE**. While there is no steady state assumption hard coded in COMBINE, in practice we are still using steady state cases. It would be a great step forward to actually test if COMBINE can work in non-steady-state. This will imply the development of a "1D version" of COMBINE in order to be able to create simplified flowline experiments first, then define idealized retreating / advancing cases and see if COMBINE can deal with them. 

1 is more practical, 2 is more theoretical, both require quite a big investment in inverse theory, machine learning and its algorithms.

## Profile of the student

- high maths and programming skills
- willingness to deal with new concepts hardly taught at ACINN  
- interested in glaciology and machine learning
- demonstrated good to very good grades in the climate / glaciology / programming lectures

### Fabien's assessment of the topic

Highly rewarding, high profile topic, only suitable for very motivated students able to work / develop on their own. An excellent entry point in the world of machine learning.

**Comment by fmaussion** [comment]
@pat-schmitt will start to work on topic 2! Welcome Patrick!

**Comment by phigre** [comment]
Great! Welcome Patrick. I think, we should get in touch for all the details. And of course I am also highly interested in your work.

**Comment by pat-schmitt** [comment]
@phigre, thank you for you offer. This week I start with the work and i will come back to you when the first questions arise.
