### ISSUE TITLE
coveralls issue again

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#874]
The last two PRs (https://github.com/OGGM/oggm/pull/873, https://github.com/OGGM/oggm/pull/872) show a coverage reduction for no reason. @TimoRoth , do you have time to have a look?

**Comment by TimoRoth** [comment]
Hm, on first glance I can't spot any obvious issues, like missed jobs or anything. I'll have a closer look tomorrow. Are you sure the reduction in coverage is inaccurate?

**Comment by matthiasdusch** [comment]
Yes, my PR #811 (merged today) only touched docu and docstrings and also showed -15% coverage.
