### ISSUE TITLE
missing DEM tile might go without error

### ISSUE THREAD

**Issue by matthiasdusch** [OGGM/oggm#887]
I discussed this yesterday with @fmaussion and we came to the conclusion that a missing DEM tile will go unnoticed by `define_glacier_region` but should be detected during `glacier_masks` as the DEM is smoothed and interpolated.

But now I think it still might go undetected as areas where the DEM is missing are not loaded as NaNs or nodata values but 0. 

After `define_glacier_region`:
![define_glacier_region](https://user-images.githubusercontent.com/37663627/67094871-f21e7380-f1b4-11e9-8303-99df010b6cfe.png)

After `glacier_masks`, slightly interpolated:
![glacier_mask](https://user-images.githubusercontent.com/37663627/67094780-c3080200-f1b4-11e9-91b3-44dc0ae4d356.png)

Notebook:
https://nbviewer.jupyter.org/gist/matthiasdusch/f8cb20222d3c974aa37bd928c489e561

There is still the possibility that this will raise an error in a later processing step. I'll investigate this next week with a fresh brain...

Oh, and the reason why this tile is missing in the first place there: A bug in my ASTER implementation. Who would have thought glaciers can span more than two degree in longitude or latitude...

**Comment by fmaussion** [comment]
Nice catch! I'm still worried that the merge_raster tool is actually filling with zeros instead of NaNs. Will have a closer look.
