### ISSUE TITLE
ASTER lat/lon extend bug

### ISSUE THREAD

**Issue by matthiasdusch** [OGGM/oggm#888]
as mentioned here #887 , the below solution does not work if e.g. lat_ex is [70.1, 72.2] as 71 would be missing.

https://github.com/OGGM/oggm/blob/9db846e26f8f762b82b39fbff68e7d6d51c7e6db/oggm/utils/_downloads.py#L1253-L1254

easy to fix with something like `np.arange`

will do next week if nobody takes care of that first ;-)

**Comment by fmaussion** [comment]
Removed the tag as it might attract bots? See recent spurious PR :thinking:
