### ISSUE TITLE
Nonexistent TanDEM-X files are "downloadable" without credentials

### ISSUE THREAD

**Issue by matthiasdusch** [OGGM/oggm#893]
If a nonexistent TanDEM-X tile url is given to `requests` without credentials (which we do in OGGM to check the download cache first) it returns a valid status_code and a local file gets created. Beside the hash-warning this local file is now treated as valid.

Minimal example:
https://nbviewer.jupyter.org/gist/matthiasdusch/0b0444ee0b0ec743c466f73cb7f526ec

A first serious error is raised when trying to unpack this file and the respective glacier will fail, even if this particular tile is not necessary. A glacier where this happens is `RGI60-01.12886` and the reason why the tile is not necessary is that at this latitude there are two lons/lats in one tile. So W144 and W146 are required but we also try to download W145 which does not exist.

Possible ways to fix:
- Be more precise at the zone selection and do not select W145 in the first place: Quite error prone as we would rather download 1-2 unnecessary tiles than skipping existing ones.
- Test files for size or valid zip format in the TanDEMx download function and return None in that case.
- Catch this in `_requests_urlretrieve` and raise a HttpDownloadError. I'd say the best solution but not really sure how to do this without breaking other downloads. Maybe @TimoRoth can help here.

https://github.com/OGGM/oggm/blob/91b878b7119248787a2e1bede481b9fce510ab22/oggm/utils/_downloads.py#L356-L384

Line 368: The fallback to `size=-1` if no content-length is given is necessary I guess?

**Comment by TimoRoth** [comment]
There's a lot of files which do not give a proper content-length. Without setting it to -1, downloading them would fail.
I'm not sure how to properly catch this in the download function. If the server returns a 200 status code, and some data, really everything is OK for what it's concerned.
It's primarily an issue of the server to behave like this in this case.

As a workaround I'd say checking the file for an obviously too small size for that specific dataset is the cleanest way.

**Comment by fmaussion** [comment]
> Test files for size or valid zip format in the TanDEMx download function and return None in that case.

if this is possible yes -> maybe we should do this for all other datasets as well if this is somehow at the same location in code? (I don't have the overview right now)

**Comment by TimoRoth** [comment]
On 05.11.2019 17:39, Fabien Maussion wrote:
>     Test files for size or valid zip format in the TanDEMx download
>     function and return None in that case.
> 
> if this is possible yes -> maybe we should do this for all other 
> datasets as well if this is somehow at the same location in code? (I 
> don't have the overview right now)

This appear to be a specialty of their server, so introducing special 
cases for other datasets seems like a needless hack.
Most servers should give you a 404 if you request nonexistent files.

**Comment by matthiasdusch** [comment]
Yes, I agree that is a rather annoying behavior of the DLR server. And while a general check for e.g filesize would be sensible, there are also some quite small but valid files...

So if I can't come up with a more general solution to catch this in `_requests_urlretrieve` I'll take care of this in the tandem downloader.
