### ISSUE TITLE
Timestepping misconceptions and flaws in OGGM

### ISSUE THREAD

**Issue by alexjarosch** [OGGM/oggm#909]
Dear OGGM developers,

as OGGM gains momentum and is/will be used widely it is paramount to have basic yet vital numerical details correctly implemented. Else OGGM risks its own reputation, the plausibility of scientific results produced with OGGM and might in an extreme scenario (cf. climate-gate) negatively influence the reputation of glacier simulations as a whole.

Thus I urge the developers to seriously consider my suggestions below:

The basic idea of a CFL criteria for advection type problems (this is how OGGM views ice-flow) https://github.com/OGGM/oggm/blob/1dc07f57cf8f7d7708585a6f7ab972890924892e/oggm/core/flowline.py#L935 is correctly implemented: https://github.com/OGGM/oggm/blob/1dc07f57cf8f7d7708585a6f7ab972890924892e/oggm/core/flowline.py#L1113

Nevertheless how this criteria is subsequently treated raises some problems:

1. The concept of counter-limiting a time step calculated from a given CFL conditions is numerically not justifiable, nor sane. In case of OGGM this is the current argument https://github.com/OGGM/oggm/blob/1dc07f57cf8f7d7708585a6f7ab972890924892e/oggm/core/flowline.py#L939-L942
However this leaves the OGGM model on "very thin ice", so to say. Numerically such a strategy is worse than just setting a fixed, rather small time step as it deludes the user to think that OGGM applies a CFL to avoid instabilities and mass conservation issues.

2. Looking at the current choices of time stepping strategies https://github.com/OGGM/oggm/blob/1dc07f57cf8f7d7708585a6f7ab972890924892e/oggm/core/flowline.py#L965-L983 results in the realization that none of them can be justified from even the most basic time stepping stability theory. This is pure numerical engineering and would **at least** require some numerical test cases to prove that any of those choices make sense. Just to be clear, the existence and values of the variable "min_dt" **are** the issue.

3. The concept of a CFL condition in general and more so the possibility of deriving a generally applicable value for a given type of partial differential equation in combination with an applied numerical time stepping scheme seems to have escaped the attention of the OGGM developers:
https://github.com/OGGM/oggm/blob/1dc07f57cf8f7d7708585a6f7ab972890924892e/oggm/core/flowline.py#L936-L938
The statement that _There is no "best" CFL number:_ is plain wrong. See [Hindmarsh, 2001](https://doi.org/10.1007/978-3-662-04439-1_13) for a very good example on how to derive general CFL stability values for diffusion type SIA flow models in glaciology.

In summary all three above stated issues will lead to complications and stability issues as OGGM is applied. Especially as spatial resolutions will inevitably increase to smaller scales, mass conservation issues are on the horizon.

To mitigate the anticipated issues allow me to make two suggestions:

a) remove the "min_dt" parameter as there is no physical/numerical justification for its existence whatsoever. The argument that the "model will run slow": https://github.com/OGGM/oggm/blob/1dc07f57cf8f7d7708585a6f7ab972890924892e/oggm/core/flowline.py#L940-L941
is not even scientific.

b) if run time really is an issue in a flowline SIA model, I suggest to switch the time stepping strategy. It's my understanding that OGGM uses a simple forward Euler time step stabilized with a CFL condition which unfortunately can not work in its current implementation. Again [Hindmarsh, 2001](https://doi.org/10.1007/978-3-662-04439-1_13) discussed already 18 years ago very useful time stepping schemes for glaciology which allow models to run fast without scarifying numerical stability and accuracy. Especially semi-implicit and fully implicit schemes should be of interest if computational time is really an issue.

I hope that these remarks are useful to OGGM and it's development.

Regards,
Alex

**Comment by fmaussion** [comment]
Thanks a lot for bringing this up! I am aware of these issues (see e.g. https://github.com/OGGM/oggm/issues/860), although not as worried as you are, as I've always said. The argument for loose rules about numerics are following:
- we test against MUSCLSuperbee in a number of scenarios in our test-suite
- in light of all other uncertainties, numerical instabilities (especially in glacier shrinking scenarios) are small (not proven, I know)
- production code for >200k glaciers needs compromise
- we are not hiding these approximations, and we document them (in the docs and in the paper)

That being said, I agree with all your points of course. Here are my suggestions to move forward:

**a) remove the "min_dt" parameter**

Yes, agreed. But then we need some kind of "timeout" for a model run, because we simply can't afford the model to run indefinitely with infinitely small time steps in production. The difficulty in finding an appropriate timeout time is what motivated me to introduce the min_dt parameter in the first place, because empirical and selected tests showed that my simulations were still running stable. But yet again, I can see how this is an issue and would also like to get rid of it.

**b) Define and fix a  "best" CFL number** or **better time stepping strategy**

Could you help us here? What would be the best way forward in our case? Fixing the CFL to a reasonable value would be a good first step. I could lead the implementation but a suggestion about what to choose would help me a lot.

**c) make a global (or regional) run in idealized settings comparing current OGGM with MUSCLSuperbee to estimate the scale of the error we are making.**

This is relatively easy to do, as we just need to switch off the multiple flowline in OGGM and make all beds rectangular. I'll try to find some time quickly to do such a run.

**Comment by alexjarosch** [comment]
> Thanks a lot for bringing this up! I am aware of these issues (see e.g. #860), although not as worried as you are, as I've always said.

It is not about being worried, and I am not. The issue is about being mathematically, numerically and physically correct and consistent. However good to see you have related issues already open and think about this.
> The argument for loose rules about numerics are following:
> 
>     we test against MUSCLSuperbee in a number of scenarios in our test-suite

How valid this argument is depends on the test scenarios. Nevertheless it is good to test against certain more stable schemes and some available analytical exact solutions.
 
>     in light of all other uncertainties, numerical instabilities (especially in glacier shrinking scenarios) are small (not proven, I know)

As you say, this is not proven and hence no argument. Numerical instabilities are not really dependent on the mass balance forcing in the sense that you can expect (or argue with) them being small in a shrinking glacier scenario. As instabilities do, they suddenly grow fast and create unexpected errors.

>     production code for >200k glaciers needs compromise

I do not agree with this argument either. It's not scientific. The fact that you want to simulate many glaciers does not justify compromises on the numerics and physics. On the contrary, as you model "all" the glaciers in the world and as these estimates will have hopefully a significant impact on the scientific understanding of glaciers and climate, you **do** want to have the best numerics there are and do not want to make compromises. Thinking that any compromise is required in this case most likely stems from limited computational resources (as so often). Say you would use LEO4 with its 1344 cores you would only have to run less than 200 glaciers on each core in sequence. No need to compromise then.
 
>     we are not hiding these approximations, and we document them (in the docs and in the paper)

This is good, however they remain misconceptions about numerical stability.
 
> That being said, I agree with all your points of course. Here are my suggestions to move forward:
> 
> **a) remove the "min_dt" parameter**
> 
> Yes, agreed. But then we need some kind of "timeout" for a model run, because we simply can't afford the model to run indefinitely with infinitely small time steps in production.

No you do not. If time steps become really small due to a CFL condition, you will require these small time steps to correctly solve the projection step in time. If this does not suit your needs/constrains, you need to switch time stepping scheme. You can't _bend_ mathematical facts.
 
> **b) Define and fix a "best" CFL number** or **better time stepping strategy**
> 
> Could you help us here? What would be the best way forward in our case? Fixing the CFL to a reasonable value would be a good first step. I could lead the implementation but a suggestion about what to choose would help me a lot.

I would love to help, however as you formulate your flow dynamics as an "advection" type problem, all knowledge on glacier model time stepping stability does not apply. They almost all have been developed for diffusion type problems. Analysing the stability regime for your type of flow problem would require a substantial amount of time which I do not have to spare at the moment, even though I would like to help.
 
> **c) make a global (or regional) run in idealized settings comparing current OGGM with MUSCLSuperbee to estimate the scale of the error we are making.**

That might be the first step towards assessing the error.

**Comment by fmaussion** [comment]
>     a) remove the "min_dt" parameter
>    Yes, agreed. But then we need some kind of "timeout" for a model run, because we simply can't afford the model to run indefinitely with infinitely small time steps in production.

>> No you do not. If time steps become really small due to a CFL condition, you will require these small time steps to correctly solve the projection step in time. If this does not suit your needs/constrains, you need to switch time stepping scheme. You can't bend mathematical facts.

Haha no I don't want to bend mathematical facts ;-). With a timeout, OGGM simply won't run for expensive glaciers, like it currently fails with NaNs when numerical instabilities are too large.

Thanks a lot for your help anyways! As it is now, we can't move away from an advection scheme and we can only hope that future contributions will go in this direction. I would rather continue to work towards testing mass conservation in operational mode.

**Comment by alexjarosch** [comment]
> With a timeout, OGGM simply won't run for expensive glaciers, like it currently fails with NaNs when numerical instabilities are too large.

Aren't the NaNs OGGM is producing in some cases exactly the point for utilizing a CFL. The min_dt most likely causes the NaNs in the end as the CFL is not allowed to do it's business.

> Thanks a lot for your help anyways! As it is now, we can't move away from an advection scheme and we can only hope that future contributions will go in this direction. I would rather continue to work towards testing mass conservation in operational mode.

Sure.

**Comment by fmaussion** [comment]
> Aren't the NaNs OGGM is producing in some cases exactly the point for utilizing a CFL. The min_dt most likely causes the NaNs in the end as the CFL is not allowed to do it's business.

Yes, exactly, this is what I expected at first. As you point out, the main issue currently are the numerical shenanigan that are *not* erroring like in https://github.com/OGGM/oggm/issues/860 and are not clean at all.

Another way to avoid the timeout would be to do like WRF and exit with a CFL error when the necessary timestep is smaller than a predefined threshold.

**Comment by alexjarosch** [comment]
The WRF ideas sounds more logical to me. 

BTW for readers besides me and @fmaussion, there is also a related discussion happening in https://github.com/OGGM/oggm/pull/910#issuecomment-558515709

**Comment by alexjarosch** [comment]
Maybe an additional comment on the stability analysis which should be done. Here are the steps which would be required:

1. Write your whole ice dynamics evolution scheme ("flux based" model) as one partial differential equation (PDF).
2. Discretize the equation with finite differences, as you do, right?
3. Apply a [von Neumann stability analysis](https://en.wikipedia.org/wiki/Von_Neumann_stability_analysis), which will result in a stability criteria for you PDF.

The same way, CFL conditions are derived and this method works for linear PDFs.

Hope this helps.

**Comment by fmaussion** [comment]
@alexjarosch FYI there is a fix which will soon be merged in OGGM: https://github.com/OGGM/oggm/pull/931 

First of all, thanks a lot for pointing this out, the new scheme is so much better in all possible ways: better code, faster run time. If you are interested in the details, see https://oggm.org/2020/01/18/stability-analysis/ 

Fortunately, although the previous algorithms were horrible, the damage is limited. The errors are very small at the regional level, but we know that on some glaciers they were problematic. 

I don't think we are completely done with this though: Betka (a master student) is looking into a proper stability analysis now, and I will continue some more tests wrt mass conservation.
