### ISSUE TITLE
How to set CRS according to the research region instead of the default CRS in OGGM?

### ISSUE THREAD

**Issue by rylanlee** [OGGM/oggm#913]
Especially, in calculating the area as well as the length of glaciers.  For example, I want to use WGS 84 / North Pole LAEA Alaska(EPSG:3572）in Alaska. How to set it? Thank you!

**Comment by fmaussion** [comment]
Hi @rylanlee - what would be the use case here? In principle we could allow for this, but I see very little benefit from it. OGGM users can use OGGM-generated data and reprocess it afterwards, for example you can write the OGGM generated flowlines as shapefile and then convert them to the CRS of your choice. Why would you like OGGM to use another CRS than it's default one?

The choice of CRS in code happens here:

https://github.com/OGGM/oggm/blob/1dc07f57cf8f7d7708585a6f7ab972890924892e/oggm/core/gis.py#L287-L292

**Comment by rylanlee** [comment]
Thank you for your kindly reply@fmaussion .

As for Alaska in RGI 6.0, there is about 0.3% difference (86725 / 86432) betweent the area results from two CRS ({'init':'EPSG:3572'} and other Equal-area world map projections like Eckert VI).
I am using rgitools[https://rgitools.readthedocs.io/en/latest/](url) to compute glacier hypsometry. As far as I know, the results generated by  hypsometries from rgitool.func are dataframe rather than shapefile. So I try to change CRS in oggm to ensure areal calculation. 

ps: I have learned to export the glacier info as .csv (utils.compile_glacier_statistics()). How to export the flowlines as shapefile? Thank you.

**Comment by fmaussion** [comment]
> As for Alaska in RGI 6.0, there is about 0.3% difference (86725 / 86432) betweent the area results from two CRS ({'init':'EPSG:3572'} and other Equal-area world map projections like Eckert VI).

0.3% is way below the accuracy of the glacier area in the RGI! Furthermore, OGGM corrects its geometries to match the area provided by the RGI anyways. Are you **sure** this is of importance to you?

>  How to export the flowlines as shapefile?

There is a function helping you to do so: https://github.com/OGGM/oggm/blob/83bf62d678809cbbbd9d7a216264af4c8d6efeed/oggm/utils/_workflow.py#L502 

Hope that helps!

**Comment by rylanlee** [comment]
Thank you very much@fmaussion . Your answer helps me a lot. Maybe I should not do it. Thanks again.
