### ISSUE TITLE
The error of 'getting_started.ipynb'

### ISSUE THREAD

**Issue by zxl951128** [OGGM/oggm#924]
I install the stable version of OGGM on Windows 10 and python 3.7.
I run the code of 'getting_started.ipynb' on my computer.  When I run the part of 'Glacier directories', it come a error like that

   File "C:\Users\username\\.conda\envs\oggm_env\lib\site-packages\progressbar\bar.py", line 101, in update
    self.fd.write(line)
AttributeError: 'NoneType' object has no attribute 'write'

I just run your code and not change it. It works correctly online, but not on my computer. How do I deal with it?

**Comment by juliaeis** [comment]
You should check out the version of the progressbar package. 
```
 import progressbar
 print(progressbar.__version__) 
```
When the version online does not match the one of your computer, an update of the progressbar package should solve the problem.

**Comment by zxl951128** [comment]
> You should check out the version of the progressbar package.
> 
> ```
>  import progressbar
>  print(progressbar.__version__) 
> ```
> 
> When the version online does not match the one of your computer, an update of the progressbar package should solve the problem.

I check the version of my computer which is 3.47.0 and is the same to version online.
I had already install the OGGM correctly on my another computer which stystem is Linux.
I will try install again on Windows 10 and see whether this error occur.
Thanks a lot for your answer😀

**Comment by fmaussion** [comment]
> I will try install again on Windows 10 and see whether this error occur.

Note that because of installation issues we do not support Windows officially.

I've heard very good feedback about Windows subsytem for Linux, which would allow you to use linux within windows: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by fmaussion** [comment]
We should add this suggestion to the docs actually

**Comment by zxl951128** [comment]
> > I will try install again on Windows 10 and see whether this error occur.
> 
> Note that because of installation issues we do not support Windows officially.
> 
> I've heard very good feedback about Windows subsytem for Linux, which would allow you to use linux within windows: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by zxl951128** [comment]
> We should add this suggestion to the docs actually

**Comment by zxl951128** [comment]
> We should add this suggestion to the docs actually

Thanks your suggestion.

"Windows subsytem for Linux" is a way to solve the problem. But it may spend some time for people who just use Windows.

**Comment by fmaussion** [comment]
> "Windows subsytem for Linux" is a way to solve the problem. But it may spend some time for people who just use Windows.

I'm not sure, because Windows command line is a pain, so  Windows subsystem for Linux really is the best of both worlds: having Linux for python and the command line and windows for everything else.
