### ISSUE TITLE
init_glacier_regions error

### ISSUE THREAD

**Issue by psydiot** [OGGM/oggm#925]
I have tried some tests from test folder.All of them stop at init_glacier_regions string.I think there must be wrong path in the config file.Could you tell me how to fix glacier folder and manually download all data from the repository?

**Comment by fmaussion** [comment]
Thanks for the report!

Please be more specific in your request: 
- how can we reproduce this error?
- what is the error message?
- what is the output of: `import oggm; print(oggm.utils.show_versions())`?

**Comment by psydiot** [comment]
Hello fmaussion!
1.# System info:
python: 3.7.4.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
# Packages info:
oggm: 1.1.1
numpy: 1.16.5
scipy: 1.3.1
pandas: 0.25.1
geopandas: 0.6.1
netCDF4: 1.4.2
matplotlib: 3.1.1
rasterio: 1.0.21
fiona: 1.8.4
osgeo.gdal: None
pyproj: 1.9.6
shapely: 1.6.4.post1
xarray: 0.14.1
salem: 0.2.2.dev-781107a
# System info:
python: 3.7.4.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
# Packages info:
oggm: 1.1.1
numpy: 1.16.5
scipy: 1.3.1
pandas: 0.25.1
geopandas: 0.6.1
netCDF4: 1.4.2
matplotlib: 3.1.1
rasterio: 1.0.21
fiona: 1.8.4
osgeo.gdal: None
pyproj: 1.9.6
shapely: 1.6.4.post1
xarray: 0.14.1
salem: 0.2.2.dev-781107a

**Comment by psydiot** [comment]
I have tracked this error till geopandas.file.py.Python crashes at this string:  
crs = features.crs.to_dict()
with code ERROR 4: Unable to open EPSG support file gcs.csv. Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.

**Comment by fmaussion** [comment]
Yes, this looks like it's unrelated to OGGM, but rather (yet again) an installation problem on Windows.

Googling the error you mention gives a lot of results, maybe you'll find a solution... 

Note that we do not officially support windows (because of these recurring issues...)
