### ISSUE TITLE
Process ERA climate data 

### ISSUE THREAD

**Issue by anoukvlug** [OGGM/oggm#930]
I am currently working on a processing different ERA datasets (ERA40 and ERA5) in a way that I can force OGGM with those datasets. While downloading the data, I realized right away, that different ERA products have different data formats. For ERA40 the total precipitation exits of convective and large scale precipitation, while in ERA5 there is a variable total precipitation. In addition the ERA40 data can only be downloaded for each year individually, while for ERA5 it is easier to download the whole time series for temperature and precipitation, however not both in the same file. 

This made me wonder, if a PR for processing one or both of these dataset would in the end be useful, or if it gets to specific due to the different data formats... @fmaussion what do you think?

**Comment by nchampollion** [comment]
Hi Anouck, why not using ERA-20C instead of ERA-40 ? Anyway, I think it useful to have a tool in OGGM, i.e. a PR, to process these dataset.

**Comment by fmaussion** [comment]
> This made me wonder, if a PR for processing one or both of these dataset would in the end be useful, or if it gets to specific due to the different data formats

I don't have a strong opinion about this. ERA40 is very outdated, and I don't think we need it in OGGM. I would be keen in having support of ERA5 and CERA-20C  -> both datasets are prepared and donlowadable from here: https://cluster.klima.uni-bremen.de/~fmaussion/climate/ 

(ERA-20C is not good, use CERA-20C)

**Comment by anoukvlug** [comment]
@nchampollion: I was thinking about using ERA-40, because I would like to compare my simulations to the RACMO2.3 SMB (Noël et al., 2018). The first part of these RACMO simulations where forced with ERA-40, therefore it seemed at first sight a logical choice to use the same data.

@fmaussion: Thanks for preparing the data! That is really helpful :)

I will try to make a PR for processing the ERA5 and CERA-20C this week.

**Comment by anoukvlug** [comment]
@fmaussion: Do you have any thoughts on how the ERA data should be provided in the end? (e.g. by the user or should it for instance automatically downloaded from your folder on the cluster)

**Comment by fmaussion** [comment]
it will be automatically downloaded
