### ISSUE TITLE
scale stddev per default in process_gcm data

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#973]
This unfortunate (wrong) default option has done too much harm to be left to false per default:

https://github.com/OGGM/oggm/blob/5db5b37f6ea0836735a84043ef1661bd92c3c500/oggm/core/gcm_climate.py#L22-L24

Let's make it True per default.

I think that the users who might be interested by that are @nchampollion (although for the GlacierMIP runs we already had it to true), @anoukvlug and @DavidParkes (I don't know which option you chose, but for any revision you might make setting this to True also makes more sense)

**Comment by anoukvlug** [comment]
I agree, that setting the default to True is much better. I already used it for some time. Thanks for notifying me of this change :)
