### ISSUE TITLE
travis.org, travis.com

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#991]
Travis has done weird changes, and apparently this explains why the builds are not showing up properly. 

Currently I can't do anything OGGM related, because the "old" .org interface doesn't list the OGGM repositories in my dashboard, and I can't yet migrate them to the new .com service. 

Waiting...

**Comment by TimoRoth** [comment]
I also can't do anything, because Travis does not recognize me as part of the OGGM org anymore.

I was planning to migrate all the Travis-Things to Github Actions eventually. So might just go at that a bit sooner.
