### ISSUE TITLE
Problems changing DEM_SOURCE

### ISSUE THREAD

**Issue by matthiasdusch** [OGGM/oggm#992]
I am a bit late to the party, but #983 broke the prepro task.

I am working on a PR to fix right now. But I am confused about the following:
https://github.com/OGGM/oggm/blob/4436fa061d76b1b113412f220406fc89fdc93766/oggm/utils/_workflow.py#L1762-L1767

What is the reason to delete the DEM_SOURCE from the outlines?

Especially since it is later used to specify a custom DEM:

https://github.com/OGGM/oggm/blob/4436fa061d76b1b113412f220406fc89fdc93766/oggm/core/gis.py#L291-L293

**Comment by fmaussion** [comment]
ups - it is an oversight. The point of 983 was to now make most of the shape stuff happen at the gdir initialisation. Do you have an idea to get this to work?
